// TODO(merge): delete, use V8Sharp.Parsing's MessageTemplate.
// Temporary stand-in for the port of src/common/message-template.h, with the
// same namespace, type names, member names and signatures as the real port.
// Template texts are copied verbatim from message-template.h.
namespace V8Sharp.Common;

public enum MessageTemplate
{
    None,
    ConflictingPrivateName,
    CyclicProto,
    Debugger,
    DebuggerLoading,
    DefaultOptionsMissing,
    DeletePrivateField,
    PlaceholderOnly,
    UncaughtException,
    Unsupported,
    WrongServiceType,
    WrongValueType,
    IcuError,
    TargetNonFunction,
    ArgumentsDisallowedInInitializerAndStaticBlock,
    ArgumentIsNonObject,
    ArgumentIsNonString,
    ArrayBufferDetachKeyDoesntMatch,
    ArrayBufferTooShort,
    ArrayBufferSpeciesThis,
    AwaitNotInAsyncContext,
    AwaitNotInDebugEvaluate,
    AtomicsMutexNotOwnedByCurrentThread,
    AtomicsOperationNotAllowed,
    BadRoundingType,
    BadSortComparisonFunction,
    BigIntFromNumber,
    BigIntFromObject,
    BigIntMixedTypes,
    BigIntSerializeJSON,
    BigIntShr,
    BigIntToNumber,
    CalledNonCallable,
    CalledOnNonObject,
    CalledOnNullOrUndefined,
    CallShadowRealmEvaluateThrew,
    CallSiteExpectsFunction,
    CallSiteMethod,
    CallSiteMethodCrossedShadowRealmBoundary,
    CallWrappedFunctionThrew,
    CannotBeShared,
    CannotConvertToPrimitive,
    CannotPreventExt,
    CannotFreeze,
    CannotFreezeArrayBufferView,
    CannotSeal,
    CannotSealArrayBufferView,
    CannotWrap,
    CircularStructure,
    ConstructAbstractClass,
    ConstAssign,
    ConstructorClassField,
    ConstructorNonCallable,
    AnonymousConstructorNonCallable,
    ConstructorNotFunction,
    ConstructorNotReceiver,
    CurrencyCode,
    CyclicModuleDependency,
    DataViewNotArrayBuffer,
    DateType,
    DebuggerFrame,
    DebuggerType,
    DeclarationMissingInitializer,
    DefineDisallowed,
    DefineDisallowedFixedLayout,
    TypedArrayDetachedErrorOperation,
    TypedArrayOOBErrorOperation,
    TypedArrayValidateErrorOperation,
    TypedArrayValidateWriteErrorOperation,
    TypedArrayImmutableBufferErrorOperation,
    DoNotUse,
    DuplicateTemplateProperty,
    ExtendsValueNotConstructor,
    FirstArgumentNotRegExp,
    FunctionBind,
    GeneratorRunning,
    IllegalInvocation,
    ImmutablePrototypeSet,
    ImportAttributesDuplicateKey,
    ImportCallNotNewExpression,
    ImportOutsideModule,
    ImportMetaOutsideModule,
    ImportMissingSpecifier,
    ImportShadowRealmRejected,
    IncompatibleMethodReceiver,
    InstanceofNonobjectProto,
    InvalidArgument,
    InvalidArgumentForTemporal,
    InvalidOption,
    InvalidInOperatorUse,
    InvalidRawJsonValue,
    InvalidRegExpExecResult,
    InvalidUnit,
    IsNotNumber,
    IterableYieldedNonString,
    IteratorReduceNoInitial,
    IteratorResultNotAnObject,
    InvalidIteratorZipMode,
    IteratorZipStrictMismatch,
    SpreadIteratorSymbolNonCallable,
    FirstArgumentIteratorSymbolNonCallable,
    FirstArgumentAsyncIteratorSymbolNonCallable,
    IteratorValueNotAnObject,
    KeysMethodInvalid,
    LanguageID,
    LocaleNotEmpty,
    LocaleBadParameters,
    ListFormatBadParameters,
    MapperFunctionNonCallable,
    MethodInvokedOnWrongType,
    NoAccess,
    NonCallableInInstanceOfCheck,
    NonCoercible,
    NonCoercibleWithProperty,
    NonExtensibleProto,
    NonObjectAttributesOption,
    NonObjectInInstanceOfCheck,
    NonObjectPrivateNameAccess,
    NonObjectPropertyLoad,
    NonObjectPropertyLoadWithProperty,
    NonObjectPropertyStore,
    NonObjectPropertyStoreWithProperty,
    NonObjectImportArgument,
    NonStringImportAttributeValue,
    NoSetterInCallback,
    NotAnIterator,
    NotReadyForSyncExec,
    PromiseNewTargetUndefined,
    NotConstructor,
    NotDateObject,
    NotGeneric,
    NotCallable,
    NotCallableOrIterable,
    NotCallableOrAsyncIterable,
    NotFiniteNumber,
    NotIterable,
    NotIterableNoSymbolLoad,
    NotAsyncIterable,
    NotPropertyName,
    NotTypedArray,
    NotSuperConstructor,
    NotSuperConstructorAnonymousClass,
    NotIntegerTypedArray,
    NotInt32OrBigInt64TypedArray,
    NotSharedTypedArray,
    ObjectFixedLayout,
    ObjectGetterExpectingFunction,
    ObjectGetterCallable,
    ObjectNotExtensible,
    ObjectSetterExpectingFunction,
    ObjectSetterCallable,
    OrdinaryFunctionCalledAsConstructor,
    PromiseCyclic,
    PromiseExecutorAlreadyInvoked,
    PromiseNonCallable,
    PropertyDescObject,
    PropertyNotFunction,
    ProtoObjectOrNull,
    PrototypeParentNotAnObject,
    ProxyConstructNonObject,
    ProxyDefinePropertyNonConfigurable,
    ProxyDefinePropertyNonConfigurableWritable,
    ProxyDefinePropertyNonExtensible,
    ProxyDefinePropertyIncompatible,
    ProxyDeletePropertyNonConfigurable,
    ProxyDeletePropertyNonExtensible,
    ProxyGetNonConfigurableData,
    ProxyGetNonConfigurableAccessor,
    ProxyGetOwnPropertyDescriptorIncompatible,
    ProxyGetOwnPropertyDescriptorInvalid,
    ProxyGetOwnPropertyDescriptorNonConfigurable,
    ProxyGetOwnPropertyDescriptorNonConfigurableWritable,
    ProxyGetOwnPropertyDescriptorNonExtensible,
    ProxyGetOwnPropertyDescriptorUndefined,
    ProxyGetPrototypeOfInvalid,
    ProxyGetPrototypeOfNonExtensible,
    ProxyHasNonConfigurable,
    ProxyHasNonExtensible,
    ProxyIsExtensibleInconsistent,
    ProxyNonObject,
    ProxyOwnKeysMissing,
    ProxyOwnKeysNonExtensible,
    ProxyOwnKeysDuplicateEntries,
    ProxyPreventExtensionsExtensible,
    ProxyPrivate,
    ProxyRevoked,
    ProxySetFrozenData,
    ProxySetFrozenAccessor,
    ProxySetPrototypeOfNonExtensible,
    ProxyTrapReturnedFalsish,
    ProxyTrapReturnedFalsishFor,
    RedefineDisallowed,
    RedefineExternalArray,
    ReduceNoInitial,
    RegExpFlags,
    RegExpNonObject,
    RegExpNonRegExp,
    RegExpGlobalInvokedOnNonGlobal,
    RelativeDateTimeFormatterBadParameters,
    ResolverNotAFunction,
    ReturnMethodNotCallable,
    SizeIsNaN,
    ShadowRealmErrorStackNonString,
    ShadowRealmErrorStackThrows,
    SharedArrayBufferTooShort,
    SharedArrayBufferSpeciesThis,
    SharedStructTypeRegistryMismatch,
    StaticPrototype,
    StrictCannotCreateProperty,
    StrictCannotDeleteProperty,
    StrictCannotSetProperty,
    StrictPoisonPill,
    StrictReadOnlyProperty,
    StringMatchAllNullOrUndefinedFlags,
    SymbolIteratorInvalid,
    SymbolAsyncIteratorInvalid,
    SymbolKeyFor,
    SymbolToNumber,
    SymbolToString,
    Temporal,
    TemporalWithArg,
    ThrowMethodMissing,
    TopLevelAwaitStalled,
    UndefinedOrNullToObject,
    AwaitUsingAssign,
    UsingAssign,
    ValueAndAccessor,
    VarRedeclaration,
    VarNotAllowedInEvalScope,
    WrongArgs,
    NotDefined,
    SuperAlreadyCalled,
    AccessedUninitializedVariable,
    UnsupportedSuper,
    AccessedUnavailableVariable,
    DisposableStackIsDisposed,
    NotAnAsyncDisposableStack,
    BigIntDivZero,
    BigIntTooBig,
    CantSetOptionXWhenYIsUsed,
    DateRange,
    ExpectedLocation,
    InvalidArrayBufferLength,
    InvalidArrayBufferMaxLength,
    InvalidArrayBufferResizeLength,
    ArrayBufferAllocationFailed,
    Invalid,
    InvalidArrayLength,
    InvalidAtomicAccessIndex,
    InvalidCalendar,
    InvalidCodePoint,
    InvalidCountValue,
    InvalidDataViewAccessorOffset,
    InvalidDataViewLength,
    InvalidOffset,
    InvalidHint,
    InvalidIndex,
    InvalidLanguageTag,
    InvalidWeakMapKey,
    InvalidWeakSetValue,
    InvalidShadowRealmEvaluateSourceText,
    InvalidStringLength,
    InvalidTimeValue,
    InvalidTimeZone,
    InvalidTypedArrayAlignment,
    InvalidTypedArrayIndex,
    InvalidTypedArrayLength,
    LetInLexicalBinding,
    LocaleMatcher,
    MaximumFractionDigitsNotEqualMinimumFractionDigits,
    NormalizationForm,
    OutOfMemory,
    ZeroDigitNumericSeparator,
    NumberFormatRange,
    TrailingNumericSeparator,
    ContinuousNumericSeparator,
    PropertyValueOutOfRange,
    StackOverflow,
    ToPrecisionFormatRange,
    ToRadixFormatRange,
    SharedArraySizeOutOfRange,
    StructFieldCountOutOfRange,
    TypedArraySetOffsetOutOfBounds,
    TypedArraySetSourceTooLarge,
    TypedArrayTooLargeToSort,
    IterableTooLargeToSum,
    ValueOutOfRange,
    CollectionGrowFailed,
    MustBePositive,
    ArgumentIsNotUndefinedOrInteger,
    AmbiguousExport,
    BadGetterArity,
    BadSetterArity,
    Base64ExtraBits,
    Base64InputRemainder,
    BigIntInvalidString,
    ConstructorIsAccessor,
    ConstructorIsGenerator,
    ConstructorIsAsync,
    ConstructorIsPrivate,
    DerivedConstructorReturnedNonObject,
    DuplicateConstructor,
    DuplicateExport,
    DuplicateProto,
    ForInOfLoopInitializer,
    ForOfLet,
    ForOfAsync,
    ForInOfLoopMultiBindings,
    GeneratorInSingleStatementContext,
    AsyncFunctionInSingleStatementContext,
    IllegalBreak,
    ModuleExportNameWithoutFromClause,
    NoIterationStatement,
    IllegalContinue,
    IllegalLanguageModeDirective,
    IllegalReturn,
    IntrinsicWithSpread,
    InvalidBase64Character,
    InvalidRestBindingPattern,
    InvalidPropertyBindingPattern,
    InvalidRestAssignmentPattern,
    InvalidEscapedReservedWord,
    InvalidEscapedMetaProperty,
    InvalidLhsInAssignment,
    InvalidCoverInitializedName,
    InvalidDestructuringTarget,
    InvalidLhsInFor,
    InvalidLhsInPostfixOp,
    InvalidLhsInPrefixOp,
    InvalidHexString,
    InvalidModuleExportName,
    InvalidRegExpFlags,
    InvalidOrUnexpectedToken,
    InvalidPrivateBrandInstance,
    InvalidPrivateBrandStatic,
    InvalidPrivateBrandReinitialization,
    InvalidPrivateFieldReinitialization,
    InvalidPrivateFieldResolution,
    InvalidPrivateMemberRead,
    InvalidPrivateMemberWrite,
    InvalidPrivateMethodWrite,
    InvalidPrivateGetterAccess,
    InvalidPrivateSetterAccess,
    InvalidSizeValue,
    InvalidUnusedPrivateStaticMethodAccessedByDebugger,
    InvalidUsingInForInLoop,
    JsonParseUnexpectedEOS,
    JsonParseUnexpectedTokenNumber,
    JsonParseUnexpectedTokenString,
    JsonParseUnterminatedString,
    JsonParseExpectedPropNameOrRBrace,
    JsonParseExpectedCommaOrRBrack,
    JsonParseExpectedCommaOrRBrace,
    JsonParseExpectedDoubleQuotedPropertyName,
    JsonParseExponentPartMissingNumber,
    JsonParseExpectedColonAfterPropertyName,
    JsonParseUnterminatedFractionalNumber,
    JsonParseUnexpectedNonWhiteSpaceCharacter,
    JsonParseBadEscapedCharacter,
    JsonParseBadControlCharacter,
    JsonParseBadUnicodeEscape,
    JsonParseNoNumberAfterMinusSign,
    JsonParseShortString,
    JsonParseUnexpectedTokenShortString,
    JsonParseUnexpectedTokenSurroundStringWithContext,
    JsonParseUnexpectedTokenEndStringWithContext,
    JsonParseUnexpectedTokenStartStringWithContext,
    LabelRedeclaration,
    LabelledFunctionDeclaration,
    MalformedArrowFunParamList,
    MalformedRegExp,
    MalformedRegExpFlags,
    ModuleExportUndefined,
    MissingFunctionName,
    MismatchedCalendars,
    HtmlCommentInModule,
    MultipleDefaultsInSwitch,
    NewlineAfterThrow,
    NoCatchOrFinally,
    ParamAfterRest,
    FlattenPastSafeLength,
    PushPastSafeLength,
    ElementAfterRest,
    BadSetterRestParameter,
    ParamDupe,
    ArgStringTerminatesParametersEarly,
    UnexpectedEndOfArgString,
    RestDefaultInitializer,
    RuntimeWrongNumArgs,
    SuperNotCalled,
    SingleFunctionLiteral,
    SloppyFunction,
    SpeciesNotConstructor,
    StrictDelete,
    StrictEvalArguments,
    StrictFunction,
    StrictOctalLiteral,
    StrictDecimalWithLeadingZero,
    StrictOctalEscape,
    Strict8Or9Escape,
    StrictWith,
    TemplateOctalLiteral,
    Template8Or9Escape,
    ThisFormalParameter,
    AwaitBindingIdentifier,
    AwaitExpressionFormalParameter,
    TooManyArguments,
    TooManyParameters,
    TooManyProperties,
    TooManySpreads,
    TooManyVariables,
    TooManyEvals,
    TooManyElementsInPromiseCombinator,
    TypedArrayTooShort,
    UnexpectedEOS,
    UnexpectedPrivateField,
    UnexpectedReserved,
    UnexpectedStrictReserved,
    UnexpectedSuper,
    UnexpectedNewTarget,
    UnexpectedTemplateString,
    UnexpectedToken,
    UnexpectedTokenUnaryExponentiation,
    UnexpectedTokenIdentifier,
    UnexpectedTokenNumber,
    UnexpectedTokenString,
    UnexpectedTokenRegExp,
    UnexpectedLexicalDeclaration,
    UnknownLabel,
    UnresolvableExport,
    UnterminatedArgList,
    UnterminatedRegExp,
    UnterminatedTemplate,
    UnterminatedTemplateExpr,
    FoundNonCallableHasInstance,
    InvalidHexEscapeSequence,
    InvalidUnicodeEscapeSequence,
    UndefinedUnicodeCodePoint,
    YieldInParameter,
    CodeGenFromStrings,
    NoSideEffectDebugEvaluate,
    URIMalformed,
    WasmTrapUnreachable,
    WasmTrapMemOutOfBounds,
    WasmTrapUnalignedAccess,
    WasmTrapDivByZero,
    WasmTrapDivUnrepresentable,
    WasmTrapRemByZero,
    WasmTrapFloatUnrepresentable,
    WasmTrapTableOutOfBounds,
    WasmTrapNullFunc,
    WasmTrapFuncSigMismatch,
    WasmTrapMultiReturnLengthMismatch,
    WasmTrapJSTypeError,
    WasmTrapDataSegmentOutOfBounds,
    WasmTrapElementSegmentOutOfBounds,
    WasmTrapRethrowNull,
    WasmTrapNullDereference,
    WasmTrapIllegalCast,
    WasmTrapArrayOutOfBounds,
    WasmTrapArrayTooLarge,
    WasmTrapStringInvalidUtf8,
    WasmTrapStringInvalidWtf8,
    WasmTrapStringOffsetOutOfBounds,
    WasmTrapResume,
    WasmTrapSuspend,
    WasmTrapSwitch,
    WasmSuspendError,
    WasmFXSuspendError,
    WasmTrapStringIsolatedSurrogate,
    WasmSuspendJSFrames,
    WasmExceptionError,
    WasmObjectsAreOpaque,
    DataCloneError,
    DataCloneErrorOutOfMemory,
    DataCloneErrorDetachedArrayBuffer,
    DataCloneErrorNonDetachableArrayBuffer,
    DataCloneErrorSharedArrayBufferTransferred,
    DataCloneDeserializationError,
    DataCloneDeserializationVersionError,
    TraceEventCategoryError,
    TraceEventNameError,
    TraceEventNameLengthError,
    TraceEventPhaseError,
    TraceEventIDError,
    InvalidWeakRefsUnregisterToken,
    WeakRefsCleanupMustBeCallable,
    InvalidWeakRefsRegisterTarget,
    WeakRefsRegisterTargetAndHoldingsMustNotBeSame,
    InvalidWeakRefsWeakRefConstructorTarget,
    OptionalChainingNoNew,
    OptionalChainingNoSuper,
    OptionalChainingNoTemplate,
    AllPromisesRejected,
    CannotDeepFreezeObject,
    CannotDeepFreezeValue,
    SuppressedErrorDuringDisposal,
    ExpectAnObjectWithUsing,
}

public static class MessageFormatter
{
    /// <summary>The raw template text (V8's MessageFormatter::TemplateString).</summary>
    public static string TemplateString(MessageTemplate index) => index switch
    {
        MessageTemplate.None => "",
        MessageTemplate.ConflictingPrivateName => "Operation is ambiguous because there are more than one private name'%' on the object",
        MessageTemplate.CyclicProto => "Cyclic __proto__ value",
        MessageTemplate.Debugger => "Debugger: %",
        MessageTemplate.DebuggerLoading => "Error loading debugger",
        MessageTemplate.DefaultOptionsMissing => "Internal % error. Default options are missing.",
        MessageTemplate.DeletePrivateField => "Private fields can not be deleted",
        MessageTemplate.PlaceholderOnly => "%",
        MessageTemplate.UncaughtException => "Uncaught %",
        MessageTemplate.Unsupported => "Not supported",
        MessageTemplate.WrongServiceType => "Internal error, wrong service type: %",
        MessageTemplate.WrongValueType => "Internal error. Wrong value type.",
        MessageTemplate.IcuError => "Internal error. Icu error.",
        MessageTemplate.TargetNonFunction => "% was called on %, which is % and not a function",
        MessageTemplate.ArgumentsDisallowedInInitializerAndStaticBlock => "'arguments' is not allowed in class field initializer or static initialization block",
        MessageTemplate.ArgumentIsNonObject => "% argument must be an object",
        MessageTemplate.ArgumentIsNonString => "% argument must be a string",
        MessageTemplate.ArrayBufferDetachKeyDoesntMatch => "Provided key doesn't match [[ArrayBufferDetachKey]]",
        MessageTemplate.ArrayBufferTooShort => "Derived ArrayBuffer constructor created a buffer which was too small",
        MessageTemplate.ArrayBufferSpeciesThis => "ArrayBuffer subclass returned this from species constructor",
        MessageTemplate.AwaitNotInAsyncContext => "await is only valid in async functions and the top level bodies of modules",
        MessageTemplate.AwaitNotInDebugEvaluate => "await can not be used when evaluating code while paused in the debugger",
        MessageTemplate.AtomicsMutexNotOwnedByCurrentThread => "Atomics.Mutex is not owned by the current agent",
        MessageTemplate.AtomicsOperationNotAllowed => "% cannot be called in this context",
        MessageTemplate.BadRoundingType => "RoundingType is not fractionDigits",
        MessageTemplate.BadSortComparisonFunction => "The comparison function must be either a function or undefined: %",
        MessageTemplate.BigIntFromNumber => "The number % cannot be converted to a BigInt because it is not an integer",
        MessageTemplate.BigIntFromObject => "Cannot convert % to a BigInt",
        MessageTemplate.BigIntMixedTypes => "Cannot mix BigInt and other types, use explicit conversions",
        MessageTemplate.BigIntSerializeJSON => "Do not know how to serialize a BigInt",
        MessageTemplate.BigIntShr => "BigInts have no unsigned right shift, use >> instead",
        MessageTemplate.BigIntToNumber => "Cannot convert a BigInt value to a number",
        MessageTemplate.CalledNonCallable => "% is not a function",
        MessageTemplate.CalledOnNonObject => "% called on non-object",
        MessageTemplate.CalledOnNullOrUndefined => "% called on null or undefined",
        MessageTemplate.CallShadowRealmEvaluateThrew => "ShadowRealm evaluate threw (%)",
        MessageTemplate.CallSiteExpectsFunction => "CallSite expects wasm object as first or function as second argument, got <%, %>",
        MessageTemplate.CallSiteMethod => "CallSite method % expects CallSite as receiver",
        MessageTemplate.CallSiteMethodCrossedShadowRealmBoundary => "CallSite method % cannot access objects across ShadowRealm boundary",
        MessageTemplate.CallWrappedFunctionThrew => "WrappedFunction threw (%)",
        MessageTemplate.CannotBeShared => "% cannot be shared",
        MessageTemplate.CannotConvertToPrimitive => "Cannot convert object to primitive value",
        MessageTemplate.CannotPreventExt => "Cannot prevent extensions",
        MessageTemplate.CannotFreeze => "Cannot freeze",
        MessageTemplate.CannotFreezeArrayBufferView => "Cannot freeze array buffer views with elements",
        MessageTemplate.CannotSeal => "Cannot seal",
        MessageTemplate.CannotSealArrayBufferView => "Cannot seal array buffer views with elements",
        MessageTemplate.CannotWrap => "Cannot wrap target callable (%)",
        MessageTemplate.CircularStructure => "Converting circular structure to JSON%",
        MessageTemplate.ConstructAbstractClass => "Abstract class % not directly constructable",
        MessageTemplate.ConstAssign => "Assignment to constant variable.",
        MessageTemplate.ConstructorClassField => "Classes may not have a field named 'constructor'",
        MessageTemplate.ConstructorNonCallable => "Class constructor % cannot be invoked without 'new'",
        MessageTemplate.AnonymousConstructorNonCallable => "Class constructors cannot be invoked without 'new'",
        MessageTemplate.ConstructorNotFunction => "Constructor % requires 'new'",
        MessageTemplate.ConstructorNotReceiver => "The .constructor property is not an object",
        MessageTemplate.CurrencyCode => "Currency code is required with currency style.",
        MessageTemplate.CyclicModuleDependency => "Detected cycle while resolving name '%' in '%'",
        MessageTemplate.DataViewNotArrayBuffer => "First argument to DataView constructor must be an ArrayBuffer",
        MessageTemplate.DateType => "this is not a Date object.",
        MessageTemplate.DebuggerFrame => "Debugger: Invalid frame index.",
        MessageTemplate.DebuggerType => "Debugger: Parameters have wrong types.",
        MessageTemplate.DeclarationMissingInitializer => "Missing initializer in % declaration",
        MessageTemplate.DefineDisallowed => "Cannot define property %, object is not extensible",
        MessageTemplate.DefineDisallowedFixedLayout => "Cannot define property %, object has fixed layout",
        MessageTemplate.TypedArrayDetachedErrorOperation => "Cannot perform % on a detached ArrayBuffer",
        MessageTemplate.TypedArrayOOBErrorOperation => "Cannot perform % out-of-bounds of the ArrayBuffer",
        MessageTemplate.TypedArrayValidateErrorOperation => "Cannot perform % on a detached or out-of-bounds ArrayBuffer",
        MessageTemplate.TypedArrayValidateWriteErrorOperation => "Cannot perform % on a detached or out-of-bounds ArrayBuffer",
        MessageTemplate.TypedArrayImmutableBufferErrorOperation => "Cannot perform % on an immutable ArrayBuffer",
        MessageTemplate.DoNotUse => "Do not use %; %",
        MessageTemplate.DuplicateTemplateProperty => "Object template has duplicate property '%'",
        MessageTemplate.ExtendsValueNotConstructor => "Class extends value % is not a constructor or null",
        MessageTemplate.FirstArgumentNotRegExp => "First argument to % must not be a regular expression",
        MessageTemplate.FunctionBind => "Bind must be called on a function",
        MessageTemplate.GeneratorRunning => "Generator is already running",
        MessageTemplate.IllegalInvocation => "Illegal invocation",
        MessageTemplate.ImmutablePrototypeSet => "Immutable prototype object '%' cannot have their prototype set",
        MessageTemplate.ImportAttributesDuplicateKey => "Import attribute has duplicate key '%'",
        MessageTemplate.ImportCallNotNewExpression => "Cannot use new with import",
        MessageTemplate.ImportOutsideModule => "Cannot use import statement outside a module",
        MessageTemplate.ImportMetaOutsideModule => "Cannot use 'import.meta' outside a module",
        MessageTemplate.ImportMissingSpecifier => "import() requires a specifier",
        MessageTemplate.ImportShadowRealmRejected => "Cannot import in ShadowRealm (%)",
        MessageTemplate.IncompatibleMethodReceiver => "Method % called on incompatible receiver %",
        MessageTemplate.InstanceofNonobjectProto => "Function has non-object prototype '%' in instanceof check",
        MessageTemplate.InvalidArgument => "invalid_argument",
        MessageTemplate.InvalidArgumentForTemporal => "Invalid argument for Temporal %",
        MessageTemplate.InvalidOption => "invalid option %",
        MessageTemplate.InvalidInOperatorUse => "Cannot use 'in' operator to search for '%' in %",
        MessageTemplate.InvalidRawJsonValue => "Invalid value for JSON.rawJSON",
        MessageTemplate.InvalidRegExpExecResult => "RegExp exec method returned something other than an Object or null",
        MessageTemplate.InvalidUnit => "Invalid unit argument for %() '%'",
        MessageTemplate.IsNotNumber => "Type of '%' must be 'number', found '%'",
        MessageTemplate.IterableYieldedNonString => "Iterable yielded % which is not a string",
        MessageTemplate.IteratorReduceNoInitial => "Reduce of a done iterator with no initial value",
        MessageTemplate.IteratorResultNotAnObject => "Iterator result % is not an object",
        MessageTemplate.InvalidIteratorZipMode => "% mode must be 'shortest', 'longest', or 'strict'",
        MessageTemplate.IteratorZipStrictMismatch => "Iterators passed to % in 'strict' mode must have the same length",
        MessageTemplate.SpreadIteratorSymbolNonCallable => "Spread syntax requires ...iterable[Symbol.iterator] to be a function",
        MessageTemplate.FirstArgumentIteratorSymbolNonCallable => "% requires that the property of the first argument, items[Symbol.iterator], when exists, be a function",
        MessageTemplate.FirstArgumentAsyncIteratorSymbolNonCallable => "% requires that the property of the first argument, items[Symbol.asyncIterator], when exists, be a function",
        MessageTemplate.IteratorValueNotAnObject => "Iterator value % is not an entry object",
        MessageTemplate.KeysMethodInvalid => "Result of the keys method is not an object",
        MessageTemplate.LanguageID => "Language ID should be string or object.",
        MessageTemplate.LocaleNotEmpty => "First argument to Intl.Locale constructor can't be empty or missing",
        MessageTemplate.LocaleBadParameters => "Incorrect locale information provided",
        MessageTemplate.ListFormatBadParameters => "Incorrect ListFormat information provided",
        MessageTemplate.MapperFunctionNonCallable => "flatMap mapper function is not callable",
        MessageTemplate.MethodInvokedOnWrongType => "Method invoked on an object that is not %.",
        MessageTemplate.NoAccess => "no access",
        MessageTemplate.NonCallableInInstanceOfCheck => "Right-hand side of 'instanceof' is not callable",
        MessageTemplate.NonCoercible => "Cannot destructure '%' as it is %.",
        MessageTemplate.NonCoercibleWithProperty => "Cannot destructure property '%' of '%' as it is %.",
        MessageTemplate.NonExtensibleProto => "% is not extensible",
        MessageTemplate.NonObjectAttributesOption => "The 'with' option must be an object",
        MessageTemplate.NonObjectInInstanceOfCheck => "Right-hand side of 'instanceof' is not an object",
        MessageTemplate.NonObjectPrivateNameAccess => "Cannot access private name % from %",
        MessageTemplate.NonObjectPropertyLoad => "Cannot read properties of %",
        MessageTemplate.NonObjectPropertyLoadWithProperty => "Cannot read properties of % (reading '%')",
        MessageTemplate.NonObjectPropertyStore => "Cannot set properties of %",
        MessageTemplate.NonObjectPropertyStoreWithProperty => "Cannot set properties of % (setting '%')",
        MessageTemplate.NonObjectImportArgument => "The second argument to import() must be an object",
        MessageTemplate.NonStringImportAttributeValue => "Import attribute value must be a string",
        MessageTemplate.NoSetterInCallback => "Cannot set property % of % which has only a getter",
        MessageTemplate.NotAnIterator => "% is not an iterator",
        MessageTemplate.NotReadyForSyncExec => "Deferred module is not ready for sync execution",
        MessageTemplate.PromiseNewTargetUndefined => "Promise constructor cannot be invoked without 'new'",
        MessageTemplate.NotConstructor => "% is not a constructor",
        MessageTemplate.NotDateObject => "this is not a Date object.",
        MessageTemplate.NotGeneric => "% requires that 'this' be a %",
        MessageTemplate.NotCallable => "% is not a function",
        MessageTemplate.NotCallableOrIterable => "% is not a function or its return value is not iterable",
        MessageTemplate.NotCallableOrAsyncIterable => "% is not a function or its return value is not async iterable",
        MessageTemplate.NotFiniteNumber => "Value need to be finite number for %()",
        MessageTemplate.NotIterable => "% is not iterable",
        MessageTemplate.NotIterableNoSymbolLoad => "% is not iterable (cannot read property %)",
        MessageTemplate.NotAsyncIterable => "% is not async iterable",
        MessageTemplate.NotPropertyName => "% is not a valid property name",
        MessageTemplate.NotTypedArray => "this is not a typed array.",
        MessageTemplate.NotSuperConstructor => "Super constructor % of % is not a constructor",
        MessageTemplate.NotSuperConstructorAnonymousClass => "Super constructor % of anonymous class is not a constructor",
        MessageTemplate.NotIntegerTypedArray => "% is not an integer typed array.",
        MessageTemplate.NotInt32OrBigInt64TypedArray => "% is not an int32 or BigInt64 typed array.",
        MessageTemplate.NotSharedTypedArray => "% is not a shared typed array.",
        MessageTemplate.ObjectFixedLayout => "Cannot add property %, object has fixed layout",
        MessageTemplate.ObjectGetterExpectingFunction => "Object.prototype.__defineGetter__: Expecting function",
        MessageTemplate.ObjectGetterCallable => "Getter must be a function: %",
        MessageTemplate.ObjectNotExtensible => "Cannot add property %, object is not extensible",
        MessageTemplate.ObjectSetterExpectingFunction => "Object.prototype.__defineSetter__: Expecting function",
        MessageTemplate.ObjectSetterCallable => "Setter must be a function: %",
        MessageTemplate.OrdinaryFunctionCalledAsConstructor => "Function object that's not a constructor was created with new",
        MessageTemplate.PromiseCyclic => "Chaining cycle detected for promise %",
        MessageTemplate.PromiseExecutorAlreadyInvoked => "Promise executor has already been invoked with non-undefined arguments",
        MessageTemplate.PromiseNonCallable => "Promise resolve or reject function is not callable",
        MessageTemplate.PropertyDescObject => "Property description must be an object: %",
        MessageTemplate.PropertyNotFunction => "'%' returned for property '%' of object '%' is not a function",
        MessageTemplate.ProtoObjectOrNull => "Object prototype may only be an Object or null: %",
        MessageTemplate.PrototypeParentNotAnObject => "Class extends value does not have valid prototype property %",
        MessageTemplate.ProxyConstructNonObject => "'construct' on proxy: trap returned non-object ('%')",
        MessageTemplate.ProxyDefinePropertyNonConfigurable => "'defineProperty' on proxy: trap returned truish for defining non-configurable property '%' which is either non-existent or configurable in the proxy target",
        MessageTemplate.ProxyDefinePropertyNonConfigurableWritable => "'defineProperty' on proxy: trap returned truish for defining non-configurable property '%' which cannot be non-writable, unless there exists a corresponding non-configurable, non-writable own property of the target object.",
        MessageTemplate.ProxyDefinePropertyNonExtensible => "'defineProperty' on proxy: trap returned truish for adding property '%'  to the non-extensible proxy target",
        MessageTemplate.ProxyDefinePropertyIncompatible => "'defineProperty' on proxy: trap returned truish for adding property '%'  that is incompatible with the existing property in the proxy target",
        MessageTemplate.ProxyDeletePropertyNonConfigurable => "'deleteProperty' on proxy: trap returned truish for property '%' which is non-configurable in the proxy target",
        MessageTemplate.ProxyDeletePropertyNonExtensible => "'deleteProperty' on proxy: trap returned truish for property '%' but the proxy target is non-extensible",
        MessageTemplate.ProxyGetNonConfigurableData => "'get' on proxy: property '%' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '%' but got '%')",
        MessageTemplate.ProxyGetNonConfigurableAccessor => "'get' on proxy: property '%' is a non-configurable accessor property on the proxy target and does not have a getter function, but the trap did not return 'undefined' (got '%')",
        MessageTemplate.ProxyGetOwnPropertyDescriptorIncompatible => "'getOwnPropertyDescriptor' on proxy: trap returned descriptor for property '%' that is incompatible with the existing property in the proxy target",
        MessageTemplate.ProxyGetOwnPropertyDescriptorInvalid => "'getOwnPropertyDescriptor' on proxy: trap returned neither object nor undefined for property '%'",
        MessageTemplate.ProxyGetOwnPropertyDescriptorNonConfigurable => "'getOwnPropertyDescriptor' on proxy: trap reported non-configurability for property '%' which is either non-existent or configurable in the proxy target",
        MessageTemplate.ProxyGetOwnPropertyDescriptorNonConfigurableWritable => "'getOwnPropertyDescriptor' on proxy: trap reported non-configurable and non-writable for property '%' which is non-configurable, writable in the proxy target",
        MessageTemplate.ProxyGetOwnPropertyDescriptorNonExtensible => "'getOwnPropertyDescriptor' on proxy: trap returned undefined for property '%' which exists in the non-extensible proxy target",
        MessageTemplate.ProxyGetOwnPropertyDescriptorUndefined => "'getOwnPropertyDescriptor' on proxy: trap returned undefined for property '%' which is non-configurable in the proxy target",
        MessageTemplate.ProxyGetPrototypeOfInvalid => "'getPrototypeOf' on proxy: trap returned neither object nor null",
        MessageTemplate.ProxyGetPrototypeOfNonExtensible => "'getPrototypeOf' on proxy: proxy target is non-extensible but the trap did not return its actual prototype",
        MessageTemplate.ProxyHasNonConfigurable => "'has' on proxy: trap returned falsish for property '%' which exists in the proxy target as non-configurable",
        MessageTemplate.ProxyHasNonExtensible => "'has' on proxy: trap returned falsish for property '%' but the proxy target is not extensible",
        MessageTemplate.ProxyIsExtensibleInconsistent => "'isExtensible' on proxy: trap result does not reflect extensibility of proxy target (which is '%')",
        MessageTemplate.ProxyNonObject => "Cannot create proxy with a non-object as target or handler",
        MessageTemplate.ProxyOwnKeysMissing => "'ownKeys' on proxy: trap result did not include '%'",
        MessageTemplate.ProxyOwnKeysNonExtensible => "'ownKeys' on proxy: trap returned extra keys but proxy target is non-extensible",
        MessageTemplate.ProxyOwnKeysDuplicateEntries => "'ownKeys' on proxy: trap returned duplicate entries",
        MessageTemplate.ProxyPreventExtensionsExtensible => "'preventExtensions' on proxy: trap returned truish but the proxy target is extensible",
        MessageTemplate.ProxyPrivate => "Cannot pass private property name to proxy trap",
        MessageTemplate.ProxyRevoked => "Cannot perform '%' on a proxy that has been revoked",
        MessageTemplate.ProxySetFrozenData => "'set' on proxy: trap returned truish for property '%' which exists in the proxy target as a non-configurable and non-writable data property with a different value",
        MessageTemplate.ProxySetFrozenAccessor => "'set' on proxy: trap returned truish for property '%' which exists in the proxy target as a non-configurable and non-writable accessor property without a setter",
        MessageTemplate.ProxySetPrototypeOfNonExtensible => "'setPrototypeOf' on proxy: trap returned truish for setting a new prototype on the non-extensible proxy target",
        MessageTemplate.ProxyTrapReturnedFalsish => "'%' on proxy: trap returned falsish",
        MessageTemplate.ProxyTrapReturnedFalsishFor => "'%' on proxy: trap returned falsish for property '%'",
        MessageTemplate.RedefineDisallowed => "Cannot redefine property: %",
        MessageTemplate.RedefineExternalArray => "Cannot redefine a property of an object with external array elements",
        MessageTemplate.ReduceNoInitial => "Reduce of empty array with no initial value",
        MessageTemplate.RegExpFlags => "Cannot supply flags when constructing one RegExp from another",
        MessageTemplate.RegExpNonObject => "% getter called on non-object %",
        MessageTemplate.RegExpNonRegExp => "% getter called on non-RegExp object",
        MessageTemplate.RegExpGlobalInvokedOnNonGlobal => "% called with a non-global RegExp argument",
        MessageTemplate.RelativeDateTimeFormatterBadParameters => "Incorrect RelativeDateTimeFormatter provided",
        MessageTemplate.ResolverNotAFunction => "Promise resolver % is not a function",
        MessageTemplate.ReturnMethodNotCallable => "The iterator's 'return' method is not callable",
        MessageTemplate.SizeIsNaN => "The .size property is NaN",
        MessageTemplate.ShadowRealmErrorStackNonString => "Error stack is not a string in ShadowRealm (%)",
        MessageTemplate.ShadowRealmErrorStackThrows => "Error stack getter threw in ShadowRealm (%)",
        MessageTemplate.SharedArrayBufferTooShort => "Derived SharedArrayBuffer constructor created a buffer which was too small",
        MessageTemplate.SharedArrayBufferSpeciesThis => "SharedArrayBuffer subclass returned this from species constructor",
        MessageTemplate.SharedStructTypeRegistryMismatch => "SharedStructType registered as '%' does not match",
        MessageTemplate.StaticPrototype => "Classes may not have a static property named 'prototype'",
        MessageTemplate.StrictCannotCreateProperty => "Cannot create property '%' on % '%'",
        MessageTemplate.StrictCannotDeleteProperty => "Cannot delete property '%' of %",
        MessageTemplate.StrictCannotSetProperty => "Cannot assign to property '%' of %",
        MessageTemplate.StrictPoisonPill => "'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them",
        MessageTemplate.StrictReadOnlyProperty => "Cannot assign to read only property '%' of % '%'",
        MessageTemplate.StringMatchAllNullOrUndefinedFlags => "The .flags property of the argument to String.prototype.matchAll cannot be null or undefined",
        MessageTemplate.SymbolIteratorInvalid => "Result of the Symbol.iterator method is not an object",
        MessageTemplate.SymbolAsyncIteratorInvalid => "Result of the Symbol.asyncIterator method is not an object",
        MessageTemplate.SymbolKeyFor => "% is not a symbol",
        MessageTemplate.SymbolToNumber => "Cannot convert a Symbol value to a number",
        MessageTemplate.SymbolToString => "Cannot convert a Symbol value to a string",
        MessageTemplate.Temporal => "Temporal error: %",
        MessageTemplate.TemporalWithArg => "Temporal error: % %.",
        MessageTemplate.ThrowMethodMissing => "The iterator does not provide a 'throw' method.",
        MessageTemplate.TopLevelAwaitStalled => "Top-level await promise never resolved",
        MessageTemplate.UndefinedOrNullToObject => "Cannot convert undefined or null to object",
        MessageTemplate.AwaitUsingAssign => "Assignment to await using variable.",
        MessageTemplate.UsingAssign => "Assignment to using variable.",
        MessageTemplate.ValueAndAccessor => "Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, %",
        MessageTemplate.VarRedeclaration => "Identifier '%' has already been declared",
        MessageTemplate.VarNotAllowedInEvalScope => "Identifier '%' cannot be declared with 'var' in current evaluation scope, consider trying 'let' instead",
        MessageTemplate.WrongArgs => "%: Arguments list has wrong type",
        MessageTemplate.NotDefined => "% is not defined",
        MessageTemplate.SuperAlreadyCalled => "Super constructor may only be called once",
        MessageTemplate.AccessedUninitializedVariable => "Cannot access '%' before initialization",
        MessageTemplate.UnsupportedSuper => "Unsupported reference to 'super'",
        MessageTemplate.AccessedUnavailableVariable => "Cannot access '%' from debugger",
        MessageTemplate.DisposableStackIsDisposed => "Cannot call % on an already-disposed DisposableStack",
        MessageTemplate.NotAnAsyncDisposableStack => "Receiver is not an AsyncDisposableStack",
        MessageTemplate.BigIntDivZero => "Division by zero",
        MessageTemplate.BigIntTooBig => "Maximum BigInt size exceeded",
        MessageTemplate.CantSetOptionXWhenYIsUsed => "Can't set option % when % is used",
        MessageTemplate.DateRange => "Provided date is not in valid range.",
        MessageTemplate.ExpectedLocation => "Expected letters optionally connected with underscores or hyphens for a location, got %",
        MessageTemplate.InvalidArrayBufferLength => "Invalid array buffer length",
        MessageTemplate.InvalidArrayBufferMaxLength => "Invalid array buffer max length",
        MessageTemplate.InvalidArrayBufferResizeLength => "%: Invalid length parameter",
        MessageTemplate.ArrayBufferAllocationFailed => "Array buffer allocation failed",
        MessageTemplate.Invalid => "Invalid % : %",
        MessageTemplate.InvalidArrayLength => "Invalid array length",
        MessageTemplate.InvalidAtomicAccessIndex => "Invalid atomic access index",
        MessageTemplate.InvalidCalendar => "Invalid calendar specified: %",
        MessageTemplate.InvalidCodePoint => "Invalid code point %",
        MessageTemplate.InvalidCountValue => "Invalid count value: %",
        MessageTemplate.InvalidDataViewAccessorOffset => "Offset is outside the bounds of the DataView",
        MessageTemplate.InvalidDataViewLength => "Invalid DataView length %",
        MessageTemplate.InvalidOffset => "Start offset % is outside the bounds of the buffer",
        MessageTemplate.InvalidHint => "Invalid hint: %",
        MessageTemplate.InvalidIndex => "Invalid value: not (convertible to) a safe integer",
        MessageTemplate.InvalidLanguageTag => "Invalid language tag: %",
        MessageTemplate.InvalidWeakMapKey => "Invalid value used as weak map key",
        MessageTemplate.InvalidWeakSetValue => "Invalid value used in weak set",
        MessageTemplate.InvalidShadowRealmEvaluateSourceText => "Invalid value used as source text",
        MessageTemplate.InvalidStringLength => "Invalid string length",
        MessageTemplate.InvalidTimeValue => "Invalid time value",
        MessageTemplate.InvalidTimeZone => "Invalid time zone specified: %",
        MessageTemplate.InvalidTypedArrayAlignment => "% of % should be a multiple of %",
        MessageTemplate.InvalidTypedArrayIndex => "Invalid typed array index",
        MessageTemplate.InvalidTypedArrayLength => "Invalid typed array length: %",
        MessageTemplate.LetInLexicalBinding => "let is disallowed as a lexically bound name",
        MessageTemplate.LocaleMatcher => "Illegal value for localeMatcher:%",
        MessageTemplate.MaximumFractionDigitsNotEqualMinimumFractionDigits => "maximumFractionDigits not equal to minimumFractionDigits",
        MessageTemplate.NormalizationForm => "The normalization form should be one of %.",
        MessageTemplate.OutOfMemory => "%: Out of memory",
        MessageTemplate.ZeroDigitNumericSeparator => "Numeric separator can not be used after leading 0.",
        MessageTemplate.NumberFormatRange => "% argument must be between 0 and 100",
        MessageTemplate.TrailingNumericSeparator => "Numeric separators are not allowed at the end of numeric literals",
        MessageTemplate.ContinuousNumericSeparator => "Only one underscore is allowed as numeric separator",
        MessageTemplate.PropertyValueOutOfRange => "% value is out of range.",
        MessageTemplate.StackOverflow => "Maximum call stack size exceeded",
        MessageTemplate.ToPrecisionFormatRange => "toPrecision() argument must be between 1 and 100",
        MessageTemplate.ToRadixFormatRange => "toString() radix argument must be between 2 and 36",
        MessageTemplate.SharedArraySizeOutOfRange => "SharedArray length out of range",
        MessageTemplate.StructFieldCountOutOfRange => "Struct field count out of range (maximum of 999 allowed)",
        MessageTemplate.TypedArraySetOffsetOutOfBounds => "offset is out of bounds",
        MessageTemplate.TypedArraySetSourceTooLarge => "Source is too large",
        MessageTemplate.TypedArrayTooLargeToSort => "Custom comparefn not supported for huge TypedArrays",
        MessageTemplate.IterableTooLargeToSum => "Math.sumPrecise not supported for huge iterables",
        MessageTemplate.ValueOutOfRange => "Value % out of range for % options property %",
        MessageTemplate.CollectionGrowFailed => "% maximum size exceeded",
        MessageTemplate.MustBePositive => "% must be positive",
        MessageTemplate.ArgumentIsNotUndefinedOrInteger => "% argument must be undefined or an integer",
        MessageTemplate.AmbiguousExport => "The requested module '%' contains conflicting star exports for name '%'",
        MessageTemplate.BadGetterArity => "Getter must not have any formal parameters.",
        MessageTemplate.BadSetterArity => "Setter must have exactly one formal parameter.",
        MessageTemplate.Base64ExtraBits => "The base64 input terminates with non-zero padding bits.",
        MessageTemplate.Base64InputRemainder => "The base64 input terminates with a single character, excluding padding (=).",
        MessageTemplate.BigIntInvalidString => "Invalid BigInt string",
        MessageTemplate.ConstructorIsAccessor => "Class constructor may not be an accessor",
        MessageTemplate.ConstructorIsGenerator => "Class constructor may not be a generator",
        MessageTemplate.ConstructorIsAsync => "Class constructor may not be an async method",
        MessageTemplate.ConstructorIsPrivate => "Class constructor may not be a private method",
        MessageTemplate.DerivedConstructorReturnedNonObject => "Derived constructors may only return object or undefined",
        MessageTemplate.DuplicateConstructor => "A class may only have one constructor",
        MessageTemplate.DuplicateExport => "Duplicate export of '%'",
        MessageTemplate.DuplicateProto => "Duplicate __proto__ fields are not allowed in object literals",
        MessageTemplate.ForInOfLoopInitializer => "% loop variable declaration may not have an initializer.",
        MessageTemplate.ForOfLet => "The left-hand side of a for-of loop may not start with 'let'.",
        MessageTemplate.ForOfAsync => "The left-hand side of a for-of loop may not be 'async'.",
        MessageTemplate.ForInOfLoopMultiBindings => "Invalid left-hand side in % loop: Must have a single binding.",
        MessageTemplate.GeneratorInSingleStatementContext => "Generators can only be declared at the top level or inside a block.",
        MessageTemplate.AsyncFunctionInSingleStatementContext => "Async functions can only be declared at the top level or inside a block.",
        MessageTemplate.IllegalBreak => "Illegal break statement",
        MessageTemplate.ModuleExportNameWithoutFromClause => "String literal module export names must be followed by a 'from' clause",
        MessageTemplate.NoIterationStatement => "Illegal continue statement: no surrounding iteration statement",
        MessageTemplate.IllegalContinue => "Illegal continue statement: '%' does not denote an iteration statement",
        MessageTemplate.IllegalLanguageModeDirective => "Illegal '%' directive in function with non-simple parameter list",
        MessageTemplate.IllegalReturn => "Illegal return statement",
        MessageTemplate.IntrinsicWithSpread => "Intrinsic calls do not support spread arguments",
        MessageTemplate.InvalidBase64Character => "Found a character that cannot be part of a valid base64 string.",
        MessageTemplate.InvalidRestBindingPattern => "`...` must be followed by an identifier in declaration contexts",
        MessageTemplate.InvalidPropertyBindingPattern => "Illegal property in declaration context",
        MessageTemplate.InvalidRestAssignmentPattern => "`...` must be followed by an assignable reference in assignment contexts",
        MessageTemplate.InvalidEscapedReservedWord => "Keyword must not contain escaped characters",
        MessageTemplate.InvalidEscapedMetaProperty => "'%' must not contain escaped characters",
        MessageTemplate.InvalidLhsInAssignment => "Invalid left-hand side in assignment",
        MessageTemplate.InvalidCoverInitializedName => "Invalid shorthand property initializer",
        MessageTemplate.InvalidDestructuringTarget => "Invalid destructuring assignment target",
        MessageTemplate.InvalidLhsInFor => "Invalid left-hand side in for-loop",
        MessageTemplate.InvalidLhsInPostfixOp => "Invalid left-hand side expression in postfix operation",
        MessageTemplate.InvalidLhsInPrefixOp => "Invalid left-hand side expression in prefix operation",
        MessageTemplate.InvalidHexString => "Input string must contain hex characters in even length",
        MessageTemplate.InvalidModuleExportName => "Invalid module export name: contains unpaired surrogate",
        MessageTemplate.InvalidRegExpFlags => "Invalid flags supplied to RegExp constructor '%'",
        MessageTemplate.InvalidOrUnexpectedToken => "Invalid or unexpected token",
        MessageTemplate.InvalidPrivateBrandInstance => "Receiver must be an instance of class %",
        MessageTemplate.InvalidPrivateBrandStatic => "Receiver must be class %",
        MessageTemplate.InvalidPrivateBrandReinitialization => "Cannot initialize private methods of class % twice on the same object",
        MessageTemplate.InvalidPrivateFieldReinitialization => "Cannot initialize % twice on the same object",
        MessageTemplate.InvalidPrivateFieldResolution => "Private field '%' must be declared in an enclosing class",
        MessageTemplate.InvalidPrivateMemberRead => "Cannot read private member % from an object whose class did not declare it",
        MessageTemplate.InvalidPrivateMemberWrite => "Cannot write private member % to an object whose class did not declare it",
        MessageTemplate.InvalidPrivateMethodWrite => "Private method '%' is not writable",
        MessageTemplate.InvalidPrivateGetterAccess => "'%' was defined without a getter",
        MessageTemplate.InvalidPrivateSetterAccess => "'%' was defined without a setter",
        MessageTemplate.InvalidSizeValue => "'%' is an invalid size",
        MessageTemplate.InvalidUnusedPrivateStaticMethodAccessedByDebugger => "Unused static private method '%' cannot be accessed at debug time",
        MessageTemplate.InvalidUsingInForInLoop => "Invalid 'using' in for-in loop",
        MessageTemplate.JsonParseUnexpectedEOS => "Unexpected end of JSON input",
        MessageTemplate.JsonParseUnexpectedTokenNumber => "Unexpected number in JSON at position % (line % column %)",
        MessageTemplate.JsonParseUnexpectedTokenString => "Unexpected string in JSON at position % (line % column %)",
        MessageTemplate.JsonParseUnterminatedString => "Unterminated string in JSON at position % (line % column %)",
        MessageTemplate.JsonParseExpectedPropNameOrRBrace => "Expected property name or '}' in JSON at position % (line % column %)",
        MessageTemplate.JsonParseExpectedCommaOrRBrack => "Expected ',' or ']' after array element in JSON at position % (line % column %)",
        MessageTemplate.JsonParseExpectedCommaOrRBrace => "Expected ',' or '}' after property value in JSON at position % (line % column %)",
        MessageTemplate.JsonParseExpectedDoubleQuotedPropertyName => "Expected double-quoted property name in JSON at position % (line % column %)",
        MessageTemplate.JsonParseExponentPartMissingNumber => "Exponent part is missing a number in JSON at position % (line % column %)",
        MessageTemplate.JsonParseExpectedColonAfterPropertyName => "Expected ':' after property name in JSON at position % (line % column %)",
        MessageTemplate.JsonParseUnterminatedFractionalNumber => "Unterminated fractional number in JSON at position % (line % column %)",
        MessageTemplate.JsonParseUnexpectedNonWhiteSpaceCharacter => "Unexpected non-whitespace character after JSON at position % (line % column %)",
        MessageTemplate.JsonParseBadEscapedCharacter => "Bad escaped character in JSON at position % (line % column %)",
        MessageTemplate.JsonParseBadControlCharacter => "Bad control character in string literal in JSON at position % (line % column %)",
        MessageTemplate.JsonParseBadUnicodeEscape => "Bad Unicode escape in JSON at position % (line % column %)",
        MessageTemplate.JsonParseNoNumberAfterMinusSign => "No number after minus sign in JSON at position % (line % column %)",
        MessageTemplate.JsonParseShortString => "\"%\" is not valid JSON",
        MessageTemplate.JsonParseUnexpectedTokenShortString => "Unexpected token '%', \"%\" is not valid JSON",
        MessageTemplate.JsonParseUnexpectedTokenSurroundStringWithContext => "Unexpected token '%', ...\"%\"... is not valid JSON",
        MessageTemplate.JsonParseUnexpectedTokenEndStringWithContext => "Unexpected token '%', ...\"%\" is not valid JSON",
        MessageTemplate.JsonParseUnexpectedTokenStartStringWithContext => "Unexpected token '%', \"%\"... is not valid JSON",
        MessageTemplate.LabelRedeclaration => "Label '%' has already been declared",
        MessageTemplate.LabelledFunctionDeclaration => "Labelled function declaration not allowed as the body of a control flow structure",
        MessageTemplate.MalformedArrowFunParamList => "Malformed arrow function parameter list",
        MessageTemplate.MalformedRegExp => "Invalid regular expression: /%/%: %",
        MessageTemplate.MalformedRegExpFlags => "Invalid regular expression flags",
        MessageTemplate.ModuleExportUndefined => "Export '%' is not defined in module",
        MessageTemplate.MissingFunctionName => "Function statements require a function name",
        MessageTemplate.MismatchedCalendars => "Mismatched calendars.",
        MessageTemplate.HtmlCommentInModule => "HTML comments are not allowed in modules",
        MessageTemplate.MultipleDefaultsInSwitch => "More than one default clause in switch statement",
        MessageTemplate.NewlineAfterThrow => "Illegal newline after throw",
        MessageTemplate.NoCatchOrFinally => "Missing catch or finally after try",
        MessageTemplate.ParamAfterRest => "Rest parameter must be last formal parameter",
        MessageTemplate.FlattenPastSafeLength => "Flattening % elements on an array-like of length % is disallowed, as the total surpasses 2**53-1",
        MessageTemplate.PushPastSafeLength => "Pushing % elements on an array-like of length % is disallowed, as the total surpasses 2**53-1",
        MessageTemplate.ElementAfterRest => "Rest element must be last element",
        MessageTemplate.BadSetterRestParameter => "Setter function argument must not be a rest parameter",
        MessageTemplate.ParamDupe => "Duplicate parameter name not allowed in this context",
        MessageTemplate.ArgStringTerminatesParametersEarly => "Arg string terminates parameters early",
        MessageTemplate.UnexpectedEndOfArgString => "Unexpected end of arg string",
        MessageTemplate.RestDefaultInitializer => "Rest parameter may not have a default initializer",
        MessageTemplate.RuntimeWrongNumArgs => "Runtime function given wrong number of arguments",
        MessageTemplate.SuperNotCalled => "Must call super constructor in derived class before accessing 'this' or returning from derived constructor",
        MessageTemplate.SingleFunctionLiteral => "Single function literal required",
        MessageTemplate.SloppyFunction => "In non-strict mode code, functions can only be declared at top level, inside a block, or as the body of an if statement.",
        MessageTemplate.SpeciesNotConstructor => "object.constructor[Symbol.species] is not a constructor",
        MessageTemplate.StrictDelete => "Delete of an unqualified identifier in strict mode.",
        MessageTemplate.StrictEvalArguments => "Unexpected eval or arguments in strict mode",
        MessageTemplate.StrictFunction => "In strict mode code, functions can only be declared at top level or inside a block.",
        MessageTemplate.StrictOctalLiteral => "Octal literals are not allowed in strict mode.",
        MessageTemplate.StrictDecimalWithLeadingZero => "Decimals with leading zeros are not allowed in strict mode.",
        MessageTemplate.StrictOctalEscape => "Octal escape sequences are not allowed in strict mode.",
        MessageTemplate.Strict8Or9Escape => "\\8 and \\9 are not allowed in strict mode.",
        MessageTemplate.StrictWith => "Strict mode code may not include a with statement",
        MessageTemplate.TemplateOctalLiteral => "Octal escape sequences are not allowed in template strings.",
        MessageTemplate.Template8Or9Escape => "\\8 and \\9 are not allowed in template strings.",
        MessageTemplate.ThisFormalParameter => "'this' is not a valid formal parameter name",
        MessageTemplate.AwaitBindingIdentifier => "'await' is not a valid identifier name in an async function",
        MessageTemplate.AwaitExpressionFormalParameter => "Illegal await-expression in formal parameters of async function",
        MessageTemplate.TooManyArguments => "Too many arguments in function call (only 65525 allowed)",
        MessageTemplate.TooManyParameters => "Too many parameters in function definition (only 65534 allowed)",
        MessageTemplate.TooManyProperties => "Too many properties to enumerate",
        MessageTemplate.TooManySpreads => "Literal containing too many nested spreads (up to 65534 allowed)",
        MessageTemplate.TooManyVariables => "Too many variables declared (only 4194303 allowed)",
        MessageTemplate.TooManyEvals => "Too many eval calls in script",
        MessageTemplate.TooManyElementsInPromiseCombinator => "Too many elements passed to Promise.%",
        MessageTemplate.TypedArrayTooShort => "Derived TypedArray constructor created an array which was too small",
        MessageTemplate.UnexpectedEOS => "Unexpected end of input",
        MessageTemplate.UnexpectedPrivateField => "Unexpected private field",
        MessageTemplate.UnexpectedReserved => "Unexpected reserved word",
        MessageTemplate.UnexpectedStrictReserved => "Unexpected strict mode reserved word",
        MessageTemplate.UnexpectedSuper => "'super' keyword unexpected here",
        MessageTemplate.UnexpectedNewTarget => "new.target expression is not allowed here",
        MessageTemplate.UnexpectedTemplateString => "Unexpected template string",
        MessageTemplate.UnexpectedToken => "Unexpected token '%'",
        MessageTemplate.UnexpectedTokenUnaryExponentiation => "Unary operator used immediately before exponentiation expression. Parenthesis must be used to disambiguate operator precedence",
        MessageTemplate.UnexpectedTokenIdentifier => "Unexpected identifier '%'",
        MessageTemplate.UnexpectedTokenNumber => "Unexpected number",
        MessageTemplate.UnexpectedTokenString => "Unexpected string",
        MessageTemplate.UnexpectedTokenRegExp => "Unexpected regular expression",
        MessageTemplate.UnexpectedLexicalDeclaration => "Lexical declaration cannot appear in a single-statement context",
        MessageTemplate.UnknownLabel => "Undefined label '%'",
        MessageTemplate.UnresolvableExport => "The requested module '%' does not provide an export named '%'",
        MessageTemplate.UnterminatedArgList => "missing ) after argument list",
        MessageTemplate.UnterminatedRegExp => "Invalid regular expression: missing /",
        MessageTemplate.UnterminatedTemplate => "Unterminated template literal",
        MessageTemplate.UnterminatedTemplateExpr => "Missing } in template expression",
        MessageTemplate.FoundNonCallableHasInstance => "Found non-callable @@hasInstance",
        MessageTemplate.InvalidHexEscapeSequence => "Invalid hexadecimal escape sequence",
        MessageTemplate.InvalidUnicodeEscapeSequence => "Invalid Unicode escape sequence",
        MessageTemplate.UndefinedUnicodeCodePoint => "Undefined Unicode code-point",
        MessageTemplate.YieldInParameter => "Yield expression not allowed in formal parameter",
        MessageTemplate.CodeGenFromStrings => "%",
        MessageTemplate.NoSideEffectDebugEvaluate => "Possible side-effect in debug-evaluate",
        MessageTemplate.URIMalformed => "URI malformed",
        MessageTemplate.WasmTrapUnreachable => "unreachable",
        MessageTemplate.WasmTrapMemOutOfBounds => "memory access out of bounds",
        MessageTemplate.WasmTrapUnalignedAccess => "operation does not support unaligned accesses",
        MessageTemplate.WasmTrapDivByZero => "divide by zero",
        MessageTemplate.WasmTrapDivUnrepresentable => "divide result unrepresentable",
        MessageTemplate.WasmTrapRemByZero => "remainder by zero",
        MessageTemplate.WasmTrapFloatUnrepresentable => "float unrepresentable in integer range",
        MessageTemplate.WasmTrapTableOutOfBounds => "table index is out of bounds",
        MessageTemplate.WasmTrapNullFunc => "null function",
        MessageTemplate.WasmTrapFuncSigMismatch => "function signature mismatch",
        MessageTemplate.WasmTrapMultiReturnLengthMismatch => "multi-return length mismatch",
        MessageTemplate.WasmTrapJSTypeError => "type incompatibility when transforming from/to JS",
        MessageTemplate.WasmTrapDataSegmentOutOfBounds => "data segment out of bounds",
        MessageTemplate.WasmTrapElementSegmentOutOfBounds => "element segment out of bounds",
        MessageTemplate.WasmTrapRethrowNull => "rethrowing null value",
        MessageTemplate.WasmTrapNullDereference => "dereferencing a null pointer",
        MessageTemplate.WasmTrapIllegalCast => "illegal cast",
        MessageTemplate.WasmTrapArrayOutOfBounds => "array element access out of bounds",
        MessageTemplate.WasmTrapArrayTooLarge => "requested new array is too large",
        MessageTemplate.WasmTrapStringInvalidUtf8 => "invalid UTF-8 string",
        MessageTemplate.WasmTrapStringInvalidWtf8 => "invalid WTF-8 string",
        MessageTemplate.WasmTrapStringOffsetOutOfBounds => "string offset out of bounds",
        MessageTemplate.WasmTrapResume => "WasmFX: resuming an invalid continuation",
        MessageTemplate.WasmTrapSuspend => "WasmFX: unhandled suspend",
        MessageTemplate.WasmTrapSwitch => "WasmFX: switching from central stack",
        MessageTemplate.WasmSuspendError => "trying to suspend without WebAssembly.promising",
        MessageTemplate.WasmFXSuspendError => "WasmFX: unhandled suspend",
        MessageTemplate.WasmTrapStringIsolatedSurrogate => "Failed to encode string as UTF-8: contains unpaired surrogate",
        MessageTemplate.WasmSuspendJSFrames => "trying to suspend JS frames",
        MessageTemplate.WasmExceptionError => "wasm exception",
        MessageTemplate.WasmObjectsAreOpaque => "WebAssembly objects are opaque",
        MessageTemplate.DataCloneError => "% could not be cloned.",
        MessageTemplate.DataCloneErrorOutOfMemory => "Data cannot be cloned, out of memory.",
        MessageTemplate.DataCloneErrorDetachedArrayBuffer => "An ArrayBuffer is detached and could not be cloned.",
        MessageTemplate.DataCloneErrorNonDetachableArrayBuffer => "ArrayBuffer is not detachable and could not be cloned.",
        MessageTemplate.DataCloneErrorSharedArrayBufferTransferred => "A SharedArrayBuffer could not be cloned. SharedArrayBuffer must not be transferred.",
        MessageTemplate.DataCloneDeserializationError => "Unable to deserialize cloned data.",
        MessageTemplate.DataCloneDeserializationVersionError => "Unable to deserialize cloned data due to invalid or unsupported version.",
        MessageTemplate.TraceEventCategoryError => "Trace event category must be a string.",
        MessageTemplate.TraceEventNameError => "Trace event name must be a string.",
        MessageTemplate.TraceEventNameLengthError => "Trace event name must not be an empty string.",
        MessageTemplate.TraceEventPhaseError => "Trace event phase must be a number.",
        MessageTemplate.TraceEventIDError => "Trace event id must be a number.",
        MessageTemplate.InvalidWeakRefsUnregisterToken => "Invalid unregisterToken ('%')",
        MessageTemplate.WeakRefsCleanupMustBeCallable => "FinalizationRegistry: cleanup must be callable",
        MessageTemplate.InvalidWeakRefsRegisterTarget => "FinalizationRegistry.prototype.register: invalid target",
        MessageTemplate.WeakRefsRegisterTargetAndHoldingsMustNotBeSame => "FinalizationRegistry.prototype.register: target and holdings must not be same",
        MessageTemplate.InvalidWeakRefsWeakRefConstructorTarget => "WeakRef: invalid target",
        MessageTemplate.OptionalChainingNoNew => "Invalid optional chain from new expression",
        MessageTemplate.OptionalChainingNoSuper => "Invalid optional chain from super property",
        MessageTemplate.OptionalChainingNoTemplate => "Invalid tagged template on optional chain",
        MessageTemplate.AllPromisesRejected => "All promises were rejected",
        MessageTemplate.CannotDeepFreezeObject => "Cannot DeepFreeze object of type %",
        MessageTemplate.CannotDeepFreezeValue => "Cannot DeepFreeze non-const value %",
        MessageTemplate.SuppressedErrorDuringDisposal => "An error was suppressed during disposal",
        MessageTemplate.ExpectAnObjectWithUsing => "An object is expected with `using` declarations",
        _ => throw new ArgumentOutOfRangeException(nameof(index)),
    };

    /// <summary>
    /// Substitutes <paramref name="args"/> for the <c>%</c> placeholders in order;
    /// <c>%%</c> is a literal percent sign and a missing argument prints
    /// <c>undefined</c> (V8's MessageFormatter::TryFormat).
    /// </summary>
    public static string Format(MessageTemplate index, ReadOnlySpan<string> args)
    {
        string t = TemplateString(index);
        var sb = new System.Text.StringBuilder(t.Length + 16);
        int next = 0;
        for (int i = 0; i < t.Length; i++)
        {
            char c = t[i];
            if (c != '%') { sb.Append(c); continue; }
            if (i + 1 < t.Length && t[i + 1] == '%') { sb.Append('%'); i++; continue; }
            sb.Append(next < args.Length ? args[next++] : "undefined");
        }
        return sb.ToString();
    }
}
