// Port of src/base/numbers/fixed-dtoa.h and fixed-dtoa.cc.

namespace V8Sharp.Base.Numbers;

public static partial class DoubleConversion
{
    const int kDoubleSignificandSize = 53;  // Includes the hidden bit.

    static void FillDigits32FixedLength(uint number, int requestedLength, Span<char> buffer, ref int length)
    {
        for (int i = requestedLength - 1; i >= 0; --i)
        {
            buffer[length + i] = (char)('0' + number % 10);
            number /= 10;
        }
        length += requestedLength;
    }

    static void FillDigits32(uint number, Span<char> buffer, ref int length)
    {
        int numberLength = 0;
        // We fill the digits in reverse order and exchange them afterwards.
        while (number != 0)
        {
            uint d = number % 10;
            number /= 10;
            buffer[length + numberLength] = (char)('0' + d);
            numberLength++;
        }
        // Exchange the digits.
        int i = length;
        int j = length + numberLength - 1;
        while (i < j)
        {
            (buffer[i], buffer[j]) = (buffer[j], buffer[i]);
            i++;
            j--;
        }
        length += numberLength;
    }

    static void FillDigits64FixedLength(ulong number, Span<char> buffer, ref int length)
    {
        const uint kTen7 = 10000000;
        // For efficiency cut the number into 3 uint32_t parts, and print those.
        uint part2 = (uint)(number % kTen7);
        number /= kTen7;
        uint part1 = (uint)(number % kTen7);
        uint part0 = (uint)(number / kTen7);

        FillDigits32FixedLength(part0, 3, buffer, ref length);
        FillDigits32FixedLength(part1, 7, buffer, ref length);
        FillDigits32FixedLength(part2, 7, buffer, ref length);
    }

    static void FillDigits64(ulong number, Span<char> buffer, ref int length)
    {
        const uint kTen7 = 10000000;
        // For efficiency cut the number into 3 uint32_t parts, and print those.
        uint part2 = (uint)(number % kTen7);
        number /= kTen7;
        uint part1 = (uint)(number % kTen7);
        uint part0 = (uint)(number / kTen7);

        if (part0 != 0)
        {
            FillDigits32(part0, buffer, ref length);
            FillDigits32FixedLength(part1, 7, buffer, ref length);
            FillDigits32FixedLength(part2, 7, buffer, ref length);
        }
        else if (part1 != 0)
        {
            FillDigits32(part1, buffer, ref length);
            FillDigits32FixedLength(part2, 7, buffer, ref length);
        }
        else
        {
            FillDigits32(part2, buffer, ref length);
        }
    }

    static void DtoaRoundUp(Span<char> buffer, ref int length, ref int decimalPoint)
    {
        // An empty buffer represents 0.
        if (length == 0)
        {
            buffer[0] = '1';
            decimalPoint = 1;
            length = 1;
            return;
        }
        // Round the last digit until we either have a digit that was not '9' or until
        // we reached the first digit.
        buffer[length - 1]++;
        for (int i = length - 1; i > 0; --i)
        {
            if (buffer[i] != '0' + 10) return;
            buffer[i] = '0';
            buffer[i - 1]++;
        }
        // If the first digit is now '0' + 10, we would need to set it to '0' and add
        // a '1' in front. However we reach the first digit only if all following
        // digits had been '9' before rounding up. Now all trailing digits are '0' and
        // we simply switch the first digit to '1' and update the decimal-point
        // (indicating that the point is now one digit to the right).
        if (buffer[0] == '0' + 10)
        {
            buffer[0] = '1';
            decimalPoint++;
        }
    }

    // The given fractionals number represents a fixed-point number with binary
    // point at bit (-exponent).
    // Preconditions:
    //   -128 <= exponent <= 0.
    //   0 <= fractionals * 2^exponent < 1
    //   The buffer holds the result.
    // The function will round its result. During the rounding-process digits not
    // generated by this function might be updated, and the decimal-point variable
    // might be updated. If this function generates the digits 99 and the buffer
    // already contained "199" (thus yielding a buffer of "19999") then a
    // rounding-up will change the contents of the buffer to "20000".
    static void FillFractionals(ulong fractionals, int exponent, int fractionalCount,
                                Span<char> buffer, ref int length, ref int decimalPoint)
    {
        Debug.Assert(-128 <= exponent && exponent <= 0);
        // 'fractionals' is a fixed-point number, with binary point at bit
        // (-exponent). Inside the function the non-converted remainder of fractionals
        // is a fixed-point number, with binary point at bit 'point'.
        if (-exponent <= 64)
        {
            // One 64 bit number is sufficient.
            Debug.Assert(fractionals >> 56 == 0);
            int point = -exponent;
            for (int i = 0; i < fractionalCount; ++i)
            {
                if (fractionals == 0) break;
                // Instead of multiplying by 10 we multiply by 5 and adjust the point
                // location. This way the fractionals variable will not overflow.
                // Invariant at the beginning of the loop: fractionals < 2^point.
                // Initially we have: point <= 64 and fractionals < 2^56
                // After each iteration the point is decremented by one.
                // Note that 5^3 = 125 < 128 = 2^7.
                // Therefore three iterations of this loop will not overflow fractionals
                // (even without the subtraction at the end of the loop body). At this
                // time point will satisfy point <= 61 and therefore fractionals < 2^point
                // and any further multiplication of fractionals by 5 will not overflow.
                fractionals *= 5;
                point--;
                int d = (int)(fractionals >> point);
                buffer[length] = (char)('0' + d);
                length++;
                fractionals -= (ulong)d << point;
            }
            // If the first bit after the point is set we have to round up.
            if (point > 0 && ((fractionals >> (point - 1)) & 1) == 1)
            {
                DtoaRoundUp(buffer, ref length, ref decimalPoint);
            }
        }
        else
        {
            // We need 128 bits.
            Debug.Assert(64 < -exponent && -exponent <= 128);
            UInt128 fractionals128 = new(fractionals, 0);
            fractionals128 >>= -exponent - 64;
            int point = 128;
            for (int i = 0; i < fractionalCount; ++i)
            {
                if (fractionals128 == UInt128.Zero) break;
                // As before: instead of multiplying by 10 we multiply by 5 and adjust the
                // point location.
                // This multiplication will not overflow for the same reasons as before.
                fractionals128 *= 5;
                point--;
                // DivModPowerOf2(point)
                UInt128 q = fractionals128 >> point;
                fractionals128 -= q << point;
                int d = (int)(ulong)q;
                buffer[length] = (char)('0' + d);
                length++;
            }
            if (((ulong)(fractionals128 >> (point - 1)) & 1) == 1)
            {
                DtoaRoundUp(buffer, ref length, ref decimalPoint);
            }
        }
    }

    // Removes leading and trailing zeros.
    // If leading zeros are removed then the decimal point position is adjusted.
    static void TrimZeros(Span<char> buffer, ref int length, ref int decimalPoint)
    {
        while (length > 0 && buffer[length - 1] == '0') length--;
        int firstNonZero = 0;
        while (firstNonZero < length && buffer[firstNonZero] == '0') firstNonZero++;
        if (firstNonZero != 0)
        {
            for (int i = firstNonZero; i < length; ++i)
            {
                buffer[i - firstNonZero] = buffer[i];
            }
            length -= firstNonZero;
            decimalPoint -= firstNonZero;
        }
    }

    /// <summary>
    /// Produces digits necessary to print a given number with
    /// <paramref name="fractionalCount"/> digits after the decimal point. The
    /// buffer must be big enough to hold the result plus one terminating null
    /// character.
    /// The produced digits might be too short in which case the caller has to
    /// fill the gaps with '0's. Example: FastFixedDtoa(0.001, 5, ...) is
    /// allowed to return buffer = "1", and decimal_point = -2.
    /// Halfway cases are rounded towards +/-Infinity (away from 0). The call
    /// FastFixedDtoa(0.15, 2, ...) thus returns buffer = "2", decimal_point = 0.
    /// This method only works for some parameters. If it can't handle the
    /// input it returns false. The output is null-terminated when the function
    /// succeeds.
    /// </summary>
    public static bool FastFixedDtoa(double v, int fractionalCount, Span<char> buffer, out int length, out int decimalPoint)
    {
        const uint kMaxUInt32 = 0xFFFFFFFF;
        ulong significand = new Double(v).Significand;
        int exponent = new Double(v).Exponent;
        length = 0;
        decimalPoint = 0;
        // v = significand * 2^exponent (with significand a 53bit integer).
        // If the exponent is larger than 20 (i.e. we may have a 73bit number) then we
        // don't know how to compute the representation. 2^73 ~= 9.5*10^21.
        // If necessary this limit could probably be increased, but we don't need
        // more.
        if (exponent > 20) return false;
        if (fractionalCount > 20) return false;
        // At most kDoubleSignificandSize bits of the significand are non-zero.
        // Given a 64 bit integer we have 11 0s followed by 53 potentially non-zero
        // bits:  0..11*..0xxx..53*..xx
        if (exponent + kDoubleSignificandSize > 64)
        {
            // The exponent must be > 11.
            //
            // We know that v = significand * 2^exponent.
            // And the exponent > 11.
            // We simplify the task by dividing v by 10^17.
            // The quotient delivers the first digits, and the remainder fits into a 64
            // bit number.
            // Dividing by 10^17 is equivalent to dividing by 5^17*2^17.
            const ulong kFive17 = 0xB1_A2BC_2EC5;  // 5^17
            ulong divisor = kFive17;
            int divisorPower = 17;
            ulong dividend = significand;
            uint quotient;
            ulong remainder;
            // Let v = f * 2^e with f == significand and e == exponent.
            // Then need q (quotient) and r (remainder) as follows:
            //   v            = q * 10^17       + r
            //   f * 2^e      = q * 10^17       + r
            //   f * 2^e      = q * 5^17 * 2^17 + r
            // If e > 17 then
            //   f * 2^(e-17) = q * 5^17        + r/2^17
            // else
            //   f  = q * 5^17 * 2^(17-e) + r/2^e
            if (exponent > divisorPower)
            {
                // We only allow exponents of up to 20 and therefore (17 - e) <= 3
                dividend <<= exponent - divisorPower;
                quotient = (uint)(dividend / divisor);
                remainder = (dividend % divisor) << divisorPower;
            }
            else
            {
                divisor <<= divisorPower - exponent;
                quotient = (uint)(dividend / divisor);
                remainder = (dividend % divisor) << exponent;
            }
            FillDigits32(quotient, buffer, ref length);
            FillDigits64FixedLength(remainder, buffer, ref length);
            decimalPoint = length;
        }
        else if (exponent >= 0)
        {
            // 0 <= exponent <= 11
            significand <<= exponent;
            FillDigits64(significand, buffer, ref length);
            decimalPoint = length;
        }
        else if (exponent > -kDoubleSignificandSize)
        {
            // We have to cut the number.
            ulong integrals = significand >> -exponent;
            ulong fractionals = significand - (integrals << -exponent);
            if (integrals > kMaxUInt32)
            {
                FillDigits64(integrals, buffer, ref length);
            }
            else
            {
                FillDigits32((uint)integrals, buffer, ref length);
            }
            decimalPoint = length;
            FillFractionals(fractionals, exponent, fractionalCount, buffer, ref length, ref decimalPoint);
        }
        else if (exponent < -128)
        {
            // This configuration (with at most 20 digits) means that all digits must be
            // 0.
            Debug.Assert(fractionalCount <= 20);
            buffer[0] = '\0';
            length = 0;
            decimalPoint = -fractionalCount;
        }
        else
        {
            decimalPoint = 0;
            FillFractionals(significand, exponent, fractionalCount, buffer, ref length, ref decimalPoint);
        }
        TrimZeros(buffer, ref length, ref decimalPoint);
        buffer[length] = '\0';
        if (length == 0)
        {
            // The string is empty and the decimal_point thus has no importance. Mimick
            // Gay's dtoa and and set it to -fractional_count.
            decimalPoint = -fractionalCount;
        }
        return true;
    }
}
