// Port of src/interpreter/bytecode-node.h/.cc.
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;

namespace V8Sharp.Interpreter;

[InlineArray(Bytecodes.kMaxOperands)]
internal struct BytecodeOperandArray
{
    uint _element0;
}

/// <summary>A container for a generated bytecode, its operands, and source information.</summary>
/// <remarks>A mutable struct passed by <c>ref</c>, as V8 passes <c>BytecodeNode*</c>.</remarks>
public struct BytecodeNode : IEquatable<BytecodeNode>
{
    readonly Bytecode _bytecode;
    BytecodeOperandArray _operands;
    readonly int _operandCount;
    OperandScale _operandScale;
    BytecodeSourceInfo _sourceInfo;

    public BytecodeNode(Bytecode bytecode, BytecodeSourceInfo sourceInfo = default)
    {
        _bytecode = bytecode;
        _operandCount = 0;
        _operandScale = OperandScale.Single;
        _sourceInfo = sourceInfo;
        Debug.Assert(Bytecodes.NumberOfOperands(bytecode) == _operandCount);
    }

    public BytecodeNode(Bytecode bytecode, uint operand0, BytecodeSourceInfo sourceInfo = default)
    {
        _bytecode = bytecode;
        _operandCount = 1;
        _operandScale = OperandScale.Single;
        _sourceInfo = sourceInfo;
        Debug.Assert(Bytecodes.NumberOfOperands(bytecode) == _operandCount);
        SetOperand(0, operand0);
    }

    public BytecodeNode(Bytecode bytecode, uint operand0, uint operand1, BytecodeSourceInfo sourceInfo = default)
    {
        _bytecode = bytecode;
        _operandCount = 2;
        _operandScale = OperandScale.Single;
        _sourceInfo = sourceInfo;
        Debug.Assert(Bytecodes.NumberOfOperands(bytecode) == _operandCount);
        SetOperand(0, operand0);
        SetOperand(1, operand1);
    }

    public BytecodeNode(Bytecode bytecode, uint operand0, uint operand1, uint operand2,
                        BytecodeSourceInfo sourceInfo = default)
    {
        _bytecode = bytecode;
        _operandCount = 3;
        _operandScale = OperandScale.Single;
        _sourceInfo = sourceInfo;
        Debug.Assert(Bytecodes.NumberOfOperands(bytecode) == _operandCount);
        SetOperand(0, operand0);
        SetOperand(1, operand1);
        SetOperand(2, operand2);
    }

    public BytecodeNode(Bytecode bytecode, uint operand0, uint operand1, uint operand2, uint operand3,
                        BytecodeSourceInfo sourceInfo = default)
    {
        _bytecode = bytecode;
        _operandCount = 4;
        _operandScale = OperandScale.Single;
        _sourceInfo = sourceInfo;
        Debug.Assert(Bytecodes.NumberOfOperands(bytecode) == _operandCount);
        SetOperand(0, operand0);
        SetOperand(1, operand1);
        SetOperand(2, operand2);
        SetOperand(3, operand3);
    }

    public BytecodeNode(Bytecode bytecode, uint operand0, uint operand1, uint operand2, uint operand3,
                        uint operand4, BytecodeSourceInfo sourceInfo = default)
    {
        _bytecode = bytecode;
        _operandCount = 5;
        _operandScale = OperandScale.Single;
        _sourceInfo = sourceInfo;
        Debug.Assert(Bytecodes.NumberOfOperands(bytecode) == _operandCount);
        SetOperand(0, operand0);
        SetOperand(1, operand1);
        SetOperand(2, operand2);
        SetOperand(3, operand3);
        SetOperand(4, operand4);
    }

    /// <summary>
    /// The general form of V8's per-bytecode <c>BytecodeNode::Name(source_info, operands...)</c>
    /// creators (BytecodeNode::Create): the operand scale is the maximum scale
    /// any scalable operand needs.
    /// </summary>
    public static BytecodeNode Create(Bytecode bytecode, BytecodeSourceInfo sourceInfo, ReadOnlySpan<uint> operands)
    {
        Debug.Assert(operands.Length == Bytecodes.NumberOfOperands(bytecode));
        var node = new BytecodeNode(bytecode, operands.Length, sourceInfo);
        for (int i = 0; i < operands.Length; i++) node.SetOperand(i, operands[i]);
        return node;
    }

    BytecodeNode(Bytecode bytecode, int operandCount, BytecodeSourceInfo sourceInfo)
    {
        _bytecode = bytecode;
        _operandCount = operandCount;
        _operandScale = OperandScale.Single;
        _sourceInfo = sourceInfo;
    }

    public readonly Bytecode Bytecode
    {
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        get => _bytecode;
    }

    public readonly uint Operand(int i)
    {
        Debug.Assert(i < _operandCount);
        return _operands[i];
    }

    /// <summary>The operands, as V8's <c>operands()</c> pointer.</summary>
    [UnscopedRef]
    public readonly ReadOnlySpan<uint> Operands => ((ReadOnlySpan<uint>)_operands)[.._operandCount];

    public void UpdateOperand0(uint operand0) => SetOperand(0, operand0);

    public readonly int OperandCount => _operandCount;
    public readonly OperandScale OperandScale => _operandScale;

    public readonly BytecodeSourceInfo SourceInfo => _sourceInfo;
    public void SetSourceInfo(BytecodeSourceInfo sourceInfo) => _sourceInfo = sourceInfo;

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    void UpdateScaleForOperand(int operandIndex, uint operand)
    {
        if (Bytecodes.OperandIsScalableSignedByte(_bytecode, operandIndex))
        {
            OperandScale scale = Bytecodes.ScaleForSignedOperand((int)operand);
            if (scale > _operandScale) _operandScale = scale;
        }
        else if (Bytecodes.OperandIsScalableUnsignedByte(_bytecode, operandIndex))
        {
            OperandScale scale = Bytecodes.ScaleForUnsignedOperand(operand);
            if (scale > _operandScale) _operandScale = scale;
        }
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    void SetOperand(int operandIndex, uint operand)
    {
        _operands[operandIndex] = operand;
        UpdateScaleForOperand(operandIndex, operand);
    }

    public readonly bool Equals(BytecodeNode other)
    {
        if (_bytecode != other._bytecode || _sourceInfo != other._sourceInfo) return false;
        for (int i = 0; i < _operandCount; ++i)
        {
            if (Operand(i) != other.Operand(i)) return false;
        }
        return true;
    }

    public override readonly bool Equals(object? obj) => obj is BytecodeNode n && Equals(n);
    public override readonly int GetHashCode() => HashCode.Combine(_bytecode, _operandCount, _sourceInfo);
    public static bool operator ==(BytecodeNode a, BytecodeNode b) => a.Equals(b);
    public static bool operator !=(BytecodeNode a, BytecodeNode b) => !a.Equals(b);

    /// <summary>BytecodeNode::Print (the DEBUG format).</summary>
    public override readonly string ToString()
    {
        var sb = new StringBuilder(Bytecodes.ToString(_bytecode));
        for (int i = 0; i < _operandCount; ++i)
        {
            sb.Append(' ').Append(_operands[i].ToString("x8", CultureInfo.InvariantCulture));
        }
        if (_sourceInfo.IsValid()) sb.Append(' ').Append(_sourceInfo.ToString());
        sb.Append('\n');
        return sb.ToString();
    }
}
