// Port of the BYTECODE_LIST table of src/interpreter/bytecodes.h: the bytecodes in
// V8's exact order (so the numbering matches), with their implicit register use
// and operand types. Generated by expanding the V8 macro list; do not edit by hand.
namespace V8Sharp.Interpreter;

/// <summary>Enumeration of interpreter bytecodes (V8's <c>enum class Bytecode : uint8_t</c>).</summary>
public enum Bytecode : byte
{
    Wide,
    ExtraWide,
    DebugBreakWide,
    DebugBreakExtraWide,
    DebugBreak0,
    DebugBreak1,
    DebugBreak2,
    DebugBreak3,
    DebugBreak4,
    DebugBreak5,
    DebugBreak6,
    Ldar,
    LdaZero,
    LdaSmi,
    LdaUndefined,
    LdaNull,
    LdaTheHole,
    LdaTdzHole,
    LdaTrue,
    LdaFalse,
    LdaConstant,
    LdaContextSlotNoCell,
    LdaContextSlot,
    LdaImmutableContextSlot,
    LdaCurrentContextSlotNoCell,
    LdaCurrentContextSlot,
    LdaImmutableCurrentContextSlot,
    Star,
    Mov,
    PushContext,
    PopContext,
    TestReferenceEqual,
    TestUndetectable,
    TestNull,
    TestUndefined,
    TestTypeOf,
    LdaGlobal,
    LdaGlobalInsideTypeof,
    StaGlobal,
    StaContextSlotNoCell,
    StaCurrentContextSlotNoCell,
    StaContextSlot,
    StaCurrentContextSlot,
    LdaLookupSlot,
    LdaLookupContextSlotNoCell,
    LdaLookupContextSlot,
    LdaLookupGlobalSlot,
    LdaLookupSlotInsideTypeof,
    LdaLookupContextSlotNoCellInsideTypeof,
    LdaLookupContextSlotInsideTypeof,
    LdaLookupGlobalSlotInsideTypeof,
    StaLookupSlot,
    GetNamedProperty,
    GetNamedPropertyFromSuper,
    GetKeyedProperty,
    GetEnumeratedKeyedProperty,
    GetPrivateField,
    LdaModuleVariable,
    StaModuleVariable,
    SetNamedProperty,
    DefineNamedOwnProperty,
    SetKeyedProperty,
    DefineKeyedOwnProperty,
    StaInArrayLiteral,
    DefineKeyedOwnPropertyInLiteral,
    SetPrototypeProperties,
    SetPrivateField,
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Exp,
    BitwiseOr,
    BitwiseXor,
    BitwiseAnd,
    ShiftLeft,
    ShiftRight,
    ShiftRightLogical,
    Add_StringConstant_Internalize,
    AddSmi,
    SubSmi,
    MulSmi,
    DivSmi,
    ModSmi,
    ExpSmi,
    BitwiseOrSmi,
    BitwiseXorSmi,
    BitwiseAndSmi,
    ShiftLeftSmi,
    ShiftRightSmi,
    ShiftRightLogicalSmi,
    Inc,
    Dec,
    Negate,
    BitwiseNot,
    ToBooleanLogicalNot,
    LogicalNot,
    TypeOf,
    DeletePropertyStrict,
    DeletePropertySloppy,
    GetSuperConstructor,
    FindNonDefaultConstructorOrConstruct,
    CallAnyReceiver,
    CallProperty,
    CallProperty0,
    CallProperty1,
    CallProperty2,
    CallUndefinedReceiver,
    CallUndefinedReceiver0,
    CallUndefinedReceiver1,
    CallUndefinedReceiver2,
    CallWithSpread,
    CallRuntime,
    CallRuntimeForPair,
    CallJSRuntime,
    InvokeIntrinsic,
    Construct,
    ConstructWithSpread,
    ConstructForwardAllArgs,
    TestEqual,
    TestEqualStrict,
    TestLessThan,
    TestGreaterThan,
    TestLessThanOrEqual,
    TestGreaterThanOrEqual,
    TestInstanceOf,
    TestIn,
    ToName,
    ToNumber,
    ToNumeric,
    ToObject,
    ToString,
    ToBoolean,
    CreateRegExpLiteral,
    CreateArrayLiteral,
    CreateArrayFromIterable,
    CreateEmptyArrayLiteral,
    CreateObjectLiteral,
    CreateEmptyObjectLiteral,
    CloneObject,
    GetTemplateObject,
    CreateClosure,
    CreateBlockContext,
    CreateCatchContext,
    CreateFunctionContext,
    CreateFunctionContextWithCells,
    CreateEvalContext,
    CreateWithContext,
    CreateMappedArguments,
    CreateUnmappedArguments,
    CreateRestParameter,
    JumpLoop,
    Jump,
    JumpConstant,
    JumpIfNullConstant,
    JumpIfNotNullConstant,
    JumpIfUndefinedConstant,
    JumpIfNotUndefinedConstant,
    JumpIfUndefinedOrNullConstant,
    JumpIfTrueConstant,
    JumpIfFalseConstant,
    JumpIfJSReceiverConstant,
    JumpIfForInDoneConstant,
    JumpIfToBooleanTrueConstant,
    JumpIfToBooleanFalseConstant,
    JumpIfToBooleanTrue,
    JumpIfToBooleanFalse,
    JumpIfTrue,
    JumpIfFalse,
    JumpIfNull,
    JumpIfNotNull,
    JumpIfUndefined,
    JumpIfNotUndefined,
    JumpIfUndefinedOrNull,
    JumpIfJSReceiver,
    JumpIfForInDone,
    SwitchOnSmiNoFeedback,
    ForInEnumerate,
    ForInPrepare,
    ForInNext,
    ForInStep,
    ForOfNext,
    SetPendingMessage,
    Throw,
    ReThrow,
    Return,
    ThrowReferenceErrorIfTdzHole,
    ThrowSuperNotCalledIfTdzHole,
    ThrowSuperAlreadyCalledIfNotTdzHole,
    ThrowIfNotSuperConstructor,
    SwitchOnGeneratorState,
    SuspendGenerator,
    ResumeGenerator,
    GetIterator,
    ArrayDestructure,
    Debugger,
    IncBlockCounter,
    Abort,
    Star15,
    Star14,
    Star13,
    Star12,
    Star11,
    Star10,
    Star9,
    Star8,
    Star7,
    Star6,
    Star5,
    Star4,
    Star3,
    Star2,
    Star1,
    Star0,
    Illegal,
}

public static partial class Bytecodes
{
    /// <summary>Bytecode::kLast.</summary>
    public const Bytecode kLast = Bytecode.Illegal;
    public const Bytecode kFirstShortStar = Bytecode.Star15;
    public const Bytecode kLastShortStar = Bytecode.Star0;

    static readonly ImplicitRegisterUse[] s_implicitRegisterUse =
    [
        ImplicitRegisterUse.None, // Wide
        ImplicitRegisterUse.None, // ExtraWide
        ImplicitRegisterUse.ReadWriteAccumulator, // DebugBreakWide
        ImplicitRegisterUse.ReadWriteAccumulator, // DebugBreakExtraWide
        ImplicitRegisterUse.ReadWriteAccumulator, // DebugBreak0
        ImplicitRegisterUse.ReadWriteAccumulator, // DebugBreak1
        ImplicitRegisterUse.ReadWriteAccumulator, // DebugBreak2
        ImplicitRegisterUse.ReadWriteAccumulator, // DebugBreak3
        ImplicitRegisterUse.ReadWriteAccumulator, // DebugBreak4
        ImplicitRegisterUse.ReadWriteAccumulator, // DebugBreak5
        ImplicitRegisterUse.ReadWriteAccumulator, // DebugBreak6
        ImplicitRegisterUse.WriteAccumulator, // Ldar
        ImplicitRegisterUse.WriteAccumulator, // LdaZero
        ImplicitRegisterUse.WriteAccumulator, // LdaSmi
        ImplicitRegisterUse.WriteAccumulator, // LdaUndefined
        ImplicitRegisterUse.WriteAccumulator, // LdaNull
        ImplicitRegisterUse.WriteAccumulator, // LdaTheHole
        ImplicitRegisterUse.WriteAccumulator, // LdaTdzHole
        ImplicitRegisterUse.WriteAccumulator, // LdaTrue
        ImplicitRegisterUse.WriteAccumulator, // LdaFalse
        ImplicitRegisterUse.WriteAccumulator, // LdaConstant
        ImplicitRegisterUse.WriteAccumulator, // LdaContextSlotNoCell
        ImplicitRegisterUse.WriteAccumulator, // LdaContextSlot
        ImplicitRegisterUse.WriteAccumulator, // LdaImmutableContextSlot
        ImplicitRegisterUse.WriteAccumulator, // LdaCurrentContextSlotNoCell
        ImplicitRegisterUse.WriteAccumulator, // LdaCurrentContextSlot
        ImplicitRegisterUse.WriteAccumulator, // LdaImmutableCurrentContextSlot
        ImplicitRegisterUse.ReadAccumulator, // Star
        ImplicitRegisterUse.None, // Mov
        ImplicitRegisterUse.ReadAccumulator, // PushContext
        ImplicitRegisterUse.None, // PopContext
        ImplicitRegisterUse.ReadWriteAccumulator, // TestReferenceEqual
        ImplicitRegisterUse.ReadWriteAccumulator, // TestUndetectable
        ImplicitRegisterUse.ReadWriteAccumulator, // TestNull
        ImplicitRegisterUse.ReadWriteAccumulator, // TestUndefined
        ImplicitRegisterUse.ReadWriteAccumulator, // TestTypeOf
        ImplicitRegisterUse.WriteAccumulator, // LdaGlobal
        ImplicitRegisterUse.WriteAccumulator, // LdaGlobalInsideTypeof
        ImplicitRegisterUse.ReadAndClobberAccumulator, // StaGlobal
        ImplicitRegisterUse.ReadAccumulator, // StaContextSlotNoCell
        ImplicitRegisterUse.ReadAccumulator, // StaCurrentContextSlotNoCell
        ImplicitRegisterUse.ReadAccumulator, // StaContextSlot
        ImplicitRegisterUse.ReadAccumulator, // StaCurrentContextSlot
        ImplicitRegisterUse.WriteAccumulator, // LdaLookupSlot
        ImplicitRegisterUse.WriteAccumulator, // LdaLookupContextSlotNoCell
        ImplicitRegisterUse.WriteAccumulator, // LdaLookupContextSlot
        ImplicitRegisterUse.WriteAccumulator, // LdaLookupGlobalSlot
        ImplicitRegisterUse.WriteAccumulator, // LdaLookupSlotInsideTypeof
        ImplicitRegisterUse.WriteAccumulator, // LdaLookupContextSlotNoCellInsideTypeof
        ImplicitRegisterUse.WriteAccumulator, // LdaLookupContextSlotInsideTypeof
        ImplicitRegisterUse.WriteAccumulator, // LdaLookupGlobalSlotInsideTypeof
        ImplicitRegisterUse.ReadWriteAccumulator, // StaLookupSlot
        ImplicitRegisterUse.WriteAccumulator, // GetNamedProperty
        ImplicitRegisterUse.ReadWriteAccumulator, // GetNamedPropertyFromSuper
        ImplicitRegisterUse.ReadWriteAccumulator, // GetKeyedProperty
        ImplicitRegisterUse.ReadWriteAccumulator, // GetEnumeratedKeyedProperty
        ImplicitRegisterUse.WriteAccumulator, // GetPrivateField
        ImplicitRegisterUse.WriteAccumulator, // LdaModuleVariable
        ImplicitRegisterUse.ReadAccumulator, // StaModuleVariable
        ImplicitRegisterUse.ReadAndClobberAccumulator, // SetNamedProperty
        ImplicitRegisterUse.ReadAndClobberAccumulator, // DefineNamedOwnProperty
        ImplicitRegisterUse.ReadAndClobberAccumulator, // SetKeyedProperty
        ImplicitRegisterUse.ReadAndClobberAccumulator, // DefineKeyedOwnProperty
        ImplicitRegisterUse.ReadAndClobberAccumulator, // StaInArrayLiteral
        ImplicitRegisterUse.ReadAccumulator, // DefineKeyedOwnPropertyInLiteral
        ImplicitRegisterUse.ReadAndClobberAccumulator, // SetPrototypeProperties
        ImplicitRegisterUse.ReadAndClobberAccumulator, // SetPrivateField
        ImplicitRegisterUse.ReadWriteAccumulator, // Add
        ImplicitRegisterUse.ReadWriteAccumulator, // Sub
        ImplicitRegisterUse.ReadWriteAccumulator, // Mul
        ImplicitRegisterUse.ReadWriteAccumulator, // Div
        ImplicitRegisterUse.ReadWriteAccumulator, // Mod
        ImplicitRegisterUse.ReadWriteAccumulator, // Exp
        ImplicitRegisterUse.ReadWriteAccumulator, // BitwiseOr
        ImplicitRegisterUse.ReadWriteAccumulator, // BitwiseXor
        ImplicitRegisterUse.ReadWriteAccumulator, // BitwiseAnd
        ImplicitRegisterUse.ReadWriteAccumulator, // ShiftLeft
        ImplicitRegisterUse.ReadWriteAccumulator, // ShiftRight
        ImplicitRegisterUse.ReadWriteAccumulator, // ShiftRightLogical
        ImplicitRegisterUse.ReadWriteAccumulator, // Add_StringConstant_Internalize
        ImplicitRegisterUse.ReadWriteAccumulator, // AddSmi
        ImplicitRegisterUse.ReadWriteAccumulator, // SubSmi
        ImplicitRegisterUse.ReadWriteAccumulator, // MulSmi
        ImplicitRegisterUse.ReadWriteAccumulator, // DivSmi
        ImplicitRegisterUse.ReadWriteAccumulator, // ModSmi
        ImplicitRegisterUse.ReadWriteAccumulator, // ExpSmi
        ImplicitRegisterUse.ReadWriteAccumulator, // BitwiseOrSmi
        ImplicitRegisterUse.ReadWriteAccumulator, // BitwiseXorSmi
        ImplicitRegisterUse.ReadWriteAccumulator, // BitwiseAndSmi
        ImplicitRegisterUse.ReadWriteAccumulator, // ShiftLeftSmi
        ImplicitRegisterUse.ReadWriteAccumulator, // ShiftRightSmi
        ImplicitRegisterUse.ReadWriteAccumulator, // ShiftRightLogicalSmi
        ImplicitRegisterUse.ReadWriteAccumulator, // Inc
        ImplicitRegisterUse.ReadWriteAccumulator, // Dec
        ImplicitRegisterUse.ReadWriteAccumulator, // Negate
        ImplicitRegisterUse.ReadWriteAccumulator, // BitwiseNot
        ImplicitRegisterUse.ReadWriteAccumulator, // ToBooleanLogicalNot
        ImplicitRegisterUse.ReadWriteAccumulator, // LogicalNot
        ImplicitRegisterUse.ReadWriteAccumulator, // TypeOf
        ImplicitRegisterUse.ReadWriteAccumulator, // DeletePropertyStrict
        ImplicitRegisterUse.ReadWriteAccumulator, // DeletePropertySloppy
        ImplicitRegisterUse.ReadAccumulator, // GetSuperConstructor
        ImplicitRegisterUse.None, // FindNonDefaultConstructorOrConstruct
        ImplicitRegisterUse.WriteAccumulator, // CallAnyReceiver
        ImplicitRegisterUse.WriteAccumulator, // CallProperty
        ImplicitRegisterUse.WriteAccumulator, // CallProperty0
        ImplicitRegisterUse.WriteAccumulator, // CallProperty1
        ImplicitRegisterUse.WriteAccumulator, // CallProperty2
        ImplicitRegisterUse.WriteAccumulator, // CallUndefinedReceiver
        ImplicitRegisterUse.WriteAccumulator, // CallUndefinedReceiver0
        ImplicitRegisterUse.WriteAccumulator, // CallUndefinedReceiver1
        ImplicitRegisterUse.WriteAccumulator, // CallUndefinedReceiver2
        ImplicitRegisterUse.WriteAccumulator, // CallWithSpread
        ImplicitRegisterUse.WriteAccumulator, // CallRuntime
        ImplicitRegisterUse.ClobberAccumulator, // CallRuntimeForPair
        ImplicitRegisterUse.WriteAccumulator, // CallJSRuntime
        ImplicitRegisterUse.WriteAccumulator, // InvokeIntrinsic
        ImplicitRegisterUse.ReadWriteAccumulator, // Construct
        ImplicitRegisterUse.ReadWriteAccumulator, // ConstructWithSpread
        ImplicitRegisterUse.ReadWriteAccumulator, // ConstructForwardAllArgs
        ImplicitRegisterUse.ReadWriteAccumulator, // TestEqual
        ImplicitRegisterUse.ReadWriteAccumulator, // TestEqualStrict
        ImplicitRegisterUse.ReadWriteAccumulator, // TestLessThan
        ImplicitRegisterUse.ReadWriteAccumulator, // TestGreaterThan
        ImplicitRegisterUse.ReadWriteAccumulator, // TestLessThanOrEqual
        ImplicitRegisterUse.ReadWriteAccumulator, // TestGreaterThanOrEqual
        ImplicitRegisterUse.ReadWriteAccumulator, // TestInstanceOf
        ImplicitRegisterUse.ReadWriteAccumulator, // TestIn
        ImplicitRegisterUse.ReadWriteAccumulator, // ToName
        ImplicitRegisterUse.ReadWriteAccumulator, // ToNumber
        ImplicitRegisterUse.ReadWriteAccumulator, // ToNumeric
        ImplicitRegisterUse.ReadAccumulator, // ToObject
        ImplicitRegisterUse.ReadWriteAccumulator, // ToString
        ImplicitRegisterUse.ReadWriteAccumulator, // ToBoolean
        ImplicitRegisterUse.WriteAccumulator, // CreateRegExpLiteral
        ImplicitRegisterUse.WriteAccumulator, // CreateArrayLiteral
        ImplicitRegisterUse.ReadWriteAccumulator, // CreateArrayFromIterable
        ImplicitRegisterUse.WriteAccumulator, // CreateEmptyArrayLiteral
        ImplicitRegisterUse.WriteAccumulator, // CreateObjectLiteral
        ImplicitRegisterUse.WriteAccumulator, // CreateEmptyObjectLiteral
        ImplicitRegisterUse.WriteAccumulator, // CloneObject
        ImplicitRegisterUse.WriteAccumulator, // GetTemplateObject
        ImplicitRegisterUse.WriteAccumulator, // CreateClosure
        ImplicitRegisterUse.WriteAccumulator, // CreateBlockContext
        ImplicitRegisterUse.WriteAccumulator, // CreateCatchContext
        ImplicitRegisterUse.WriteAccumulator, // CreateFunctionContext
        ImplicitRegisterUse.WriteAccumulator, // CreateFunctionContextWithCells
        ImplicitRegisterUse.WriteAccumulator, // CreateEvalContext
        ImplicitRegisterUse.WriteAccumulator, // CreateWithContext
        ImplicitRegisterUse.WriteAccumulator, // CreateMappedArguments
        ImplicitRegisterUse.WriteAccumulator, // CreateUnmappedArguments
        ImplicitRegisterUse.WriteAccumulator, // CreateRestParameter
        ImplicitRegisterUse.ClobberAccumulator, // JumpLoop
        ImplicitRegisterUse.None, // Jump
        ImplicitRegisterUse.None, // JumpConstant
        ImplicitRegisterUse.ReadAccumulator, // JumpIfNullConstant
        ImplicitRegisterUse.ReadAccumulator, // JumpIfNotNullConstant
        ImplicitRegisterUse.ReadAccumulator, // JumpIfUndefinedConstant
        ImplicitRegisterUse.ReadAccumulator, // JumpIfNotUndefinedConstant
        ImplicitRegisterUse.ReadAccumulator, // JumpIfUndefinedOrNullConstant
        ImplicitRegisterUse.ReadAccumulator, // JumpIfTrueConstant
        ImplicitRegisterUse.ReadAccumulator, // JumpIfFalseConstant
        ImplicitRegisterUse.ReadAccumulator, // JumpIfJSReceiverConstant
        ImplicitRegisterUse.None, // JumpIfForInDoneConstant
        ImplicitRegisterUse.ReadAccumulator, // JumpIfToBooleanTrueConstant
        ImplicitRegisterUse.ReadAccumulator, // JumpIfToBooleanFalseConstant
        ImplicitRegisterUse.ReadAccumulator, // JumpIfToBooleanTrue
        ImplicitRegisterUse.ReadAccumulator, // JumpIfToBooleanFalse
        ImplicitRegisterUse.ReadAccumulator, // JumpIfTrue
        ImplicitRegisterUse.ReadAccumulator, // JumpIfFalse
        ImplicitRegisterUse.ReadAccumulator, // JumpIfNull
        ImplicitRegisterUse.ReadAccumulator, // JumpIfNotNull
        ImplicitRegisterUse.ReadAccumulator, // JumpIfUndefined
        ImplicitRegisterUse.ReadAccumulator, // JumpIfNotUndefined
        ImplicitRegisterUse.ReadAccumulator, // JumpIfUndefinedOrNull
        ImplicitRegisterUse.ReadAccumulator, // JumpIfJSReceiver
        ImplicitRegisterUse.None, // JumpIfForInDone
        ImplicitRegisterUse.ReadAccumulator, // SwitchOnSmiNoFeedback
        ImplicitRegisterUse.WriteAccumulator, // ForInEnumerate
        ImplicitRegisterUse.ReadAndClobberAccumulator, // ForInPrepare
        ImplicitRegisterUse.WriteAccumulator, // ForInNext
        ImplicitRegisterUse.None, // ForInStep
        ImplicitRegisterUse.WriteAccumulator, // ForOfNext
        ImplicitRegisterUse.ReadWriteAccumulator, // SetPendingMessage
        ImplicitRegisterUse.ReadAccumulator, // Throw
        ImplicitRegisterUse.ReadAccumulator, // ReThrow
        ImplicitRegisterUse.ReadAccumulator, // Return
        ImplicitRegisterUse.ReadAccumulator, // ThrowReferenceErrorIfTdzHole
        ImplicitRegisterUse.ReadAccumulator, // ThrowSuperNotCalledIfTdzHole
        ImplicitRegisterUse.ReadAccumulator, // ThrowSuperAlreadyCalledIfNotTdzHole
        ImplicitRegisterUse.None, // ThrowIfNotSuperConstructor
        ImplicitRegisterUse.None, // SwitchOnGeneratorState
        ImplicitRegisterUse.ReadAccumulator, // SuspendGenerator
        ImplicitRegisterUse.WriteAccumulator, // ResumeGenerator
        ImplicitRegisterUse.WriteAccumulator, // GetIterator
        ImplicitRegisterUse.ReadAndClobberAccumulator, // ArrayDestructure
        ImplicitRegisterUse.ClobberAccumulator, // Debugger
        ImplicitRegisterUse.None, // IncBlockCounter
        ImplicitRegisterUse.None, // Abort
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star15
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star14
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star13
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star12
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star11
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star10
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star9
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star8
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star7
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star6
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star5
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star4
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star3
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star2
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star1
        ImplicitRegisterUse.ReadAccumulatorWriteShortStar, // Star0
        ImplicitRegisterUse.None, // Illegal
    ];

    static readonly OperandType[][] s_operandTypes =
    [
        [], // Wide
        [], // ExtraWide
        [], // DebugBreakWide
        [], // DebugBreakExtraWide
        [], // DebugBreak0
        [OperandType.Reg], // DebugBreak1
        [OperandType.Reg, OperandType.Reg], // DebugBreak2
        [OperandType.Reg, OperandType.Reg, OperandType.Reg], // DebugBreak3
        [OperandType.Reg, OperandType.Reg, OperandType.Reg, OperandType.Reg], // DebugBreak4
        [OperandType.RuntimeId, OperandType.Reg, OperandType.Reg], // DebugBreak5
        [OperandType.RuntimeId, OperandType.Reg, OperandType.Reg, OperandType.Reg], // DebugBreak6
        [OperandType.Reg], // Ldar
        [], // LdaZero
        [OperandType.Imm], // LdaSmi
        [], // LdaUndefined
        [], // LdaNull
        [], // LdaTheHole
        [], // LdaTdzHole
        [], // LdaTrue
        [], // LdaFalse
        [OperandType.ConstantPoolIndex], // LdaConstant
        [OperandType.Reg, OperandType.ContextSlot, OperandType.UImm], // LdaContextSlotNoCell
        [OperandType.Reg, OperandType.ContextSlot, OperandType.UImm], // LdaContextSlot
        [OperandType.Reg, OperandType.ContextSlot, OperandType.UImm], // LdaImmutableContextSlot
        [OperandType.ContextSlot], // LdaCurrentContextSlotNoCell
        [OperandType.ContextSlot], // LdaCurrentContextSlot
        [OperandType.ContextSlot], // LdaImmutableCurrentContextSlot
        [OperandType.RegOut], // Star
        [OperandType.Reg, OperandType.RegOut], // Mov
        [OperandType.RegOut], // PushContext
        [OperandType.Reg], // PopContext
        [OperandType.Reg], // TestReferenceEqual
        [], // TestUndetectable
        [], // TestNull
        [], // TestUndefined
        [OperandType.Flag8], // TestTypeOf
        [OperandType.ConstantPoolIndex, OperandType.FeedbackSlot], // LdaGlobal
        [OperandType.ConstantPoolIndex, OperandType.FeedbackSlot], // LdaGlobalInsideTypeof
        [OperandType.ConstantPoolIndex, OperandType.FeedbackSlot], // StaGlobal
        [OperandType.Reg, OperandType.ContextSlot, OperandType.UImm], // StaContextSlotNoCell
        [OperandType.ContextSlot], // StaCurrentContextSlotNoCell
        [OperandType.Reg, OperandType.ContextSlot, OperandType.UImm], // StaContextSlot
        [OperandType.ContextSlot], // StaCurrentContextSlot
        [OperandType.ConstantPoolIndex], // LdaLookupSlot
        [OperandType.ConstantPoolIndex, OperandType.ContextSlot, OperandType.UImm], // LdaLookupContextSlotNoCell
        [OperandType.ConstantPoolIndex, OperandType.ContextSlot, OperandType.UImm], // LdaLookupContextSlot
        [OperandType.ConstantPoolIndex, OperandType.FeedbackSlot, OperandType.UImm], // LdaLookupGlobalSlot
        [OperandType.ConstantPoolIndex], // LdaLookupSlotInsideTypeof
        [OperandType.ConstantPoolIndex, OperandType.ContextSlot, OperandType.UImm], // LdaLookupContextSlotNoCellInsideTypeof
        [OperandType.ConstantPoolIndex, OperandType.ContextSlot, OperandType.UImm], // LdaLookupContextSlotInsideTypeof
        [OperandType.ConstantPoolIndex, OperandType.FeedbackSlot, OperandType.UImm], // LdaLookupGlobalSlotInsideTypeof
        [OperandType.ConstantPoolIndex, OperandType.Flag8], // StaLookupSlot
        [OperandType.Reg, OperandType.ConstantPoolIndex, OperandType.FeedbackSlot], // GetNamedProperty
        [OperandType.Reg, OperandType.ConstantPoolIndex, OperandType.FeedbackSlot], // GetNamedPropertyFromSuper
        [OperandType.Reg, OperandType.FeedbackSlot], // GetKeyedProperty
        [OperandType.Reg, OperandType.Reg, OperandType.Reg, OperandType.FeedbackSlot], // GetEnumeratedKeyedProperty
        [OperandType.Reg, OperandType.ContextSlot, OperandType.UImm, OperandType.Reg, OperandType.FeedbackSlot], // GetPrivateField
        [OperandType.Imm, OperandType.UImm], // LdaModuleVariable
        [OperandType.Imm, OperandType.UImm], // StaModuleVariable
        [OperandType.Reg, OperandType.ConstantPoolIndex, OperandType.FeedbackSlot], // SetNamedProperty
        [OperandType.Reg, OperandType.ConstantPoolIndex, OperandType.FeedbackSlot], // DefineNamedOwnProperty
        [OperandType.Reg, OperandType.Reg, OperandType.FeedbackSlot], // SetKeyedProperty
        [OperandType.Reg, OperandType.Reg, OperandType.Flag8, OperandType.FeedbackSlot], // DefineKeyedOwnProperty
        [OperandType.Reg, OperandType.Reg, OperandType.FeedbackSlot], // StaInArrayLiteral
        [OperandType.Reg, OperandType.Reg, OperandType.Flag8, OperandType.FeedbackSlot], // DefineKeyedOwnPropertyInLiteral
        [OperandType.ConstantPoolIndex, OperandType.FeedbackSlot], // SetPrototypeProperties
        [OperandType.Reg, OperandType.ContextSlot, OperandType.UImm, OperandType.Reg, OperandType.FeedbackSlot], // SetPrivateField
        [OperandType.Reg, OperandType.EmbeddedFeedback], // Add
        [OperandType.Reg, OperandType.EmbeddedFeedback], // Sub
        [OperandType.Reg, OperandType.EmbeddedFeedback], // Mul
        [OperandType.Reg, OperandType.EmbeddedFeedback], // Div
        [OperandType.Reg, OperandType.EmbeddedFeedback], // Mod
        [OperandType.Reg, OperandType.EmbeddedFeedback], // Exp
        [OperandType.Reg, OperandType.EmbeddedFeedback], // BitwiseOr
        [OperandType.Reg, OperandType.EmbeddedFeedback], // BitwiseXor
        [OperandType.Reg, OperandType.EmbeddedFeedback], // BitwiseAnd
        [OperandType.Reg, OperandType.EmbeddedFeedback], // ShiftLeft
        [OperandType.Reg, OperandType.EmbeddedFeedback], // ShiftRight
        [OperandType.Reg, OperandType.EmbeddedFeedback], // ShiftRightLogical
        [OperandType.Reg, OperandType.FeedbackSlot, OperandType.Flag8], // Add_StringConstant_Internalize
        [OperandType.Imm, OperandType.EmbeddedFeedback], // AddSmi
        [OperandType.Imm, OperandType.EmbeddedFeedback], // SubSmi
        [OperandType.Imm, OperandType.EmbeddedFeedback], // MulSmi
        [OperandType.Imm, OperandType.EmbeddedFeedback], // DivSmi
        [OperandType.Imm, OperandType.EmbeddedFeedback], // ModSmi
        [OperandType.Imm, OperandType.EmbeddedFeedback], // ExpSmi
        [OperandType.Imm, OperandType.EmbeddedFeedback], // BitwiseOrSmi
        [OperandType.Imm, OperandType.EmbeddedFeedback], // BitwiseXorSmi
        [OperandType.Imm, OperandType.EmbeddedFeedback], // BitwiseAndSmi
        [OperandType.Imm, OperandType.EmbeddedFeedback], // ShiftLeftSmi
        [OperandType.Imm, OperandType.EmbeddedFeedback], // ShiftRightSmi
        [OperandType.Imm, OperandType.EmbeddedFeedback], // ShiftRightLogicalSmi
        [OperandType.EmbeddedFeedback], // Inc
        [OperandType.EmbeddedFeedback], // Dec
        [OperandType.EmbeddedFeedback], // Negate
        [OperandType.EmbeddedFeedback], // BitwiseNot
        [], // ToBooleanLogicalNot
        [], // LogicalNot
        [OperandType.FeedbackSlot], // TypeOf
        [OperandType.Reg], // DeletePropertyStrict
        [OperandType.Reg], // DeletePropertySloppy
        [OperandType.RegOut], // GetSuperConstructor
        [OperandType.Reg, OperandType.Reg, OperandType.RegOutPair], // FindNonDefaultConstructorOrConstruct
        [OperandType.Reg, OperandType.RegList, OperandType.RegCount, OperandType.FeedbackSlot], // CallAnyReceiver
        [OperandType.Reg, OperandType.RegList, OperandType.RegCount, OperandType.FeedbackSlot], // CallProperty
        [OperandType.Reg, OperandType.Reg, OperandType.FeedbackSlot], // CallProperty0
        [OperandType.Reg, OperandType.Reg, OperandType.Reg, OperandType.FeedbackSlot], // CallProperty1
        [OperandType.Reg, OperandType.Reg, OperandType.Reg, OperandType.Reg, OperandType.FeedbackSlot], // CallProperty2
        [OperandType.Reg, OperandType.RegList, OperandType.RegCount, OperandType.FeedbackSlot], // CallUndefinedReceiver
        [OperandType.Reg, OperandType.FeedbackSlot], // CallUndefinedReceiver0
        [OperandType.Reg, OperandType.Reg, OperandType.FeedbackSlot], // CallUndefinedReceiver1
        [OperandType.Reg, OperandType.Reg, OperandType.Reg, OperandType.FeedbackSlot], // CallUndefinedReceiver2
        [OperandType.Reg, OperandType.RegList, OperandType.RegCount, OperandType.FeedbackSlot], // CallWithSpread
        [OperandType.RuntimeId, OperandType.RegList, OperandType.RegCount], // CallRuntime
        [OperandType.RuntimeId, OperandType.RegList, OperandType.RegCount, OperandType.RegOutPair], // CallRuntimeForPair
        [OperandType.NativeContextIndex, OperandType.RegList, OperandType.RegCount], // CallJSRuntime
        [OperandType.IntrinsicId, OperandType.RegList, OperandType.RegCount], // InvokeIntrinsic
        [OperandType.Reg, OperandType.RegList, OperandType.RegCount, OperandType.FeedbackSlot], // Construct
        [OperandType.Reg, OperandType.RegList, OperandType.RegCount, OperandType.FeedbackSlot], // ConstructWithSpread
        [OperandType.Reg, OperandType.FeedbackSlot], // ConstructForwardAllArgs
        [OperandType.Reg, OperandType.EmbeddedFeedback], // TestEqual
        [OperandType.Reg, OperandType.EmbeddedFeedback], // TestEqualStrict
        [OperandType.Reg, OperandType.EmbeddedFeedback], // TestLessThan
        [OperandType.Reg, OperandType.EmbeddedFeedback], // TestGreaterThan
        [OperandType.Reg, OperandType.EmbeddedFeedback], // TestLessThanOrEqual
        [OperandType.Reg, OperandType.EmbeddedFeedback], // TestGreaterThanOrEqual
        [OperandType.Reg, OperandType.FeedbackSlot], // TestInstanceOf
        [OperandType.Reg, OperandType.FeedbackSlot], // TestIn
        [], // ToName
        [OperandType.FeedbackSlot], // ToNumber
        [OperandType.FeedbackSlot], // ToNumeric
        [OperandType.RegOut], // ToObject
        [], // ToString
        [], // ToBoolean
        [OperandType.ConstantPoolIndex, OperandType.FeedbackSlot, OperandType.Flag16], // CreateRegExpLiteral
        [OperandType.ConstantPoolIndex, OperandType.FeedbackSlot, OperandType.Flag8], // CreateArrayLiteral
        [], // CreateArrayFromIterable
        [OperandType.FeedbackSlot], // CreateEmptyArrayLiteral
        [OperandType.ConstantPoolIndex, OperandType.FeedbackSlot, OperandType.Flag8], // CreateObjectLiteral
        [], // CreateEmptyObjectLiteral
        [OperandType.Reg, OperandType.Flag8, OperandType.FeedbackSlot], // CloneObject
        [OperandType.ConstantPoolIndex, OperandType.FeedbackSlot], // GetTemplateObject
        [OperandType.ConstantPoolIndex, OperandType.FeedbackSlot, OperandType.Flag8], // CreateClosure
        [OperandType.ConstantPoolIndex], // CreateBlockContext
        [OperandType.Reg, OperandType.ConstantPoolIndex], // CreateCatchContext
        [OperandType.ConstantPoolIndex, OperandType.UImm], // CreateFunctionContext
        [OperandType.ConstantPoolIndex, OperandType.UImm], // CreateFunctionContextWithCells
        [OperandType.ConstantPoolIndex, OperandType.UImm], // CreateEvalContext
        [OperandType.Reg, OperandType.ConstantPoolIndex], // CreateWithContext
        [], // CreateMappedArguments
        [], // CreateUnmappedArguments
        [], // CreateRestParameter
        [OperandType.UImm, OperandType.Imm, OperandType.FeedbackSlot], // JumpLoop
        [OperandType.UImm], // Jump
        [OperandType.ConstantPoolIndex], // JumpConstant
        [OperandType.ConstantPoolIndex], // JumpIfNullConstant
        [OperandType.ConstantPoolIndex], // JumpIfNotNullConstant
        [OperandType.ConstantPoolIndex], // JumpIfUndefinedConstant
        [OperandType.ConstantPoolIndex], // JumpIfNotUndefinedConstant
        [OperandType.ConstantPoolIndex], // JumpIfUndefinedOrNullConstant
        [OperandType.ConstantPoolIndex], // JumpIfTrueConstant
        [OperandType.ConstantPoolIndex], // JumpIfFalseConstant
        [OperandType.ConstantPoolIndex], // JumpIfJSReceiverConstant
        [OperandType.ConstantPoolIndex, OperandType.Reg, OperandType.Reg], // JumpIfForInDoneConstant
        [OperandType.ConstantPoolIndex], // JumpIfToBooleanTrueConstant
        [OperandType.ConstantPoolIndex], // JumpIfToBooleanFalseConstant
        [OperandType.UImm], // JumpIfToBooleanTrue
        [OperandType.UImm], // JumpIfToBooleanFalse
        [OperandType.UImm], // JumpIfTrue
        [OperandType.UImm], // JumpIfFalse
        [OperandType.UImm], // JumpIfNull
        [OperandType.UImm], // JumpIfNotNull
        [OperandType.UImm], // JumpIfUndefined
        [OperandType.UImm], // JumpIfNotUndefined
        [OperandType.UImm], // JumpIfUndefinedOrNull
        [OperandType.UImm], // JumpIfJSReceiver
        [OperandType.UImm, OperandType.Reg, OperandType.Reg], // JumpIfForInDone
        [OperandType.ConstantPoolIndex, OperandType.UImm, OperandType.Imm], // SwitchOnSmiNoFeedback
        [OperandType.Reg], // ForInEnumerate
        [OperandType.RegOutTriple, OperandType.FeedbackSlot], // ForInPrepare
        [OperandType.Reg, OperandType.Reg, OperandType.RegPair, OperandType.FeedbackSlot], // ForInNext
        [OperandType.RegInOut], // ForInStep
        [OperandType.Reg, OperandType.Reg, OperandType.FeedbackSlot], // ForOfNext
        [], // SetPendingMessage
        [], // Throw
        [], // ReThrow
        [], // Return
        [OperandType.ConstantPoolIndex], // ThrowReferenceErrorIfTdzHole
        [], // ThrowSuperNotCalledIfTdzHole
        [], // ThrowSuperAlreadyCalledIfNotTdzHole
        [OperandType.Reg], // ThrowIfNotSuperConstructor
        [OperandType.Reg, OperandType.ConstantPoolIndex, OperandType.UImm], // SwitchOnGeneratorState
        [OperandType.Reg, OperandType.RegList, OperandType.RegCount, OperandType.UImm], // SuspendGenerator
        [OperandType.Reg, OperandType.RegOutList, OperandType.RegCount], // ResumeGenerator
        [OperandType.Reg, OperandType.FeedbackSlot, OperandType.FeedbackSlot], // GetIterator
        [OperandType.RegOutList, OperandType.RegCount], // ArrayDestructure
        [], // Debugger
        [OperandType.CoverageSlot], // IncBlockCounter
        [OperandType.AbortReason], // Abort
        [], // Star15
        [], // Star14
        [], // Star13
        [], // Star12
        [], // Star11
        [], // Star10
        [], // Star9
        [], // Star8
        [], // Star7
        [], // Star6
        [], // Star5
        [], // Star4
        [], // Star3
        [], // Star2
        [], // Star1
        [], // Star0
        [], // Illegal
    ];

    /// <summary>JUMP_BYTECODE_LIST.</summary>
    public static ReadOnlySpan<Bytecode> JumpBytecodeList => [Bytecode.Jump, Bytecode.JumpConstant, Bytecode.JumpIfToBooleanTrue, Bytecode.JumpIfToBooleanFalse, Bytecode.JumpIfTrue, Bytecode.JumpIfFalse, Bytecode.JumpIfNull, Bytecode.JumpIfNotNull, Bytecode.JumpIfUndefined, Bytecode.JumpIfNotUndefined, Bytecode.JumpIfUndefinedOrNull, Bytecode.JumpIfJSReceiver, Bytecode.JumpIfForInDone, Bytecode.JumpIfToBooleanTrueConstant, Bytecode.JumpIfToBooleanFalseConstant, Bytecode.JumpIfNullConstant, Bytecode.JumpIfNotNullConstant, Bytecode.JumpIfUndefinedConstant, Bytecode.JumpIfNotUndefinedConstant, Bytecode.JumpIfUndefinedOrNullConstant, Bytecode.JumpIfTrueConstant, Bytecode.JumpIfFalseConstant, Bytecode.JumpIfJSReceiverConstant, Bytecode.JumpIfForInDoneConstant, Bytecode.JumpLoop];
    /// <summary>JUMP_FORWARD_BYTECODE_LIST.</summary>
    public static ReadOnlySpan<Bytecode> JumpForwardBytecodeList => [Bytecode.Jump, Bytecode.JumpConstant, Bytecode.JumpIfToBooleanTrue, Bytecode.JumpIfToBooleanFalse, Bytecode.JumpIfTrue, Bytecode.JumpIfFalse, Bytecode.JumpIfNull, Bytecode.JumpIfNotNull, Bytecode.JumpIfUndefined, Bytecode.JumpIfNotUndefined, Bytecode.JumpIfUndefinedOrNull, Bytecode.JumpIfJSReceiver, Bytecode.JumpIfForInDone, Bytecode.JumpIfToBooleanTrueConstant, Bytecode.JumpIfToBooleanFalseConstant, Bytecode.JumpIfNullConstant, Bytecode.JumpIfNotNullConstant, Bytecode.JumpIfUndefinedConstant, Bytecode.JumpIfNotUndefinedConstant, Bytecode.JumpIfUndefinedOrNullConstant, Bytecode.JumpIfTrueConstant, Bytecode.JumpIfFalseConstant, Bytecode.JumpIfJSReceiverConstant, Bytecode.JumpIfForInDoneConstant];
    /// <summary>JUMP_CONDITIONAL_BYTECODE_LIST.</summary>
    public static ReadOnlySpan<Bytecode> JumpConditionalBytecodeList => [Bytecode.JumpIfToBooleanTrue, Bytecode.JumpIfToBooleanFalse, Bytecode.JumpIfTrue, Bytecode.JumpIfFalse, Bytecode.JumpIfNull, Bytecode.JumpIfNotNull, Bytecode.JumpIfUndefined, Bytecode.JumpIfNotUndefined, Bytecode.JumpIfUndefinedOrNull, Bytecode.JumpIfJSReceiver, Bytecode.JumpIfForInDone, Bytecode.JumpIfToBooleanTrueConstant, Bytecode.JumpIfToBooleanFalseConstant, Bytecode.JumpIfNullConstant, Bytecode.JumpIfNotNullConstant, Bytecode.JumpIfUndefinedConstant, Bytecode.JumpIfNotUndefinedConstant, Bytecode.JumpIfUndefinedOrNullConstant, Bytecode.JumpIfTrueConstant, Bytecode.JumpIfFalseConstant, Bytecode.JumpIfJSReceiverConstant, Bytecode.JumpIfForInDoneConstant];
    /// <summary>JUMP_UNCONDITIONAL_BYTECODE_LIST.</summary>
    public static ReadOnlySpan<Bytecode> JumpUnconditionalBytecodeList => [Bytecode.JumpLoop, Bytecode.Jump, Bytecode.JumpConstant];
    /// <summary>JUMP_IMMEDIATE_BYTECODE_LIST.</summary>
    public static ReadOnlySpan<Bytecode> JumpImmediateBytecodeList => [Bytecode.JumpLoop, Bytecode.Jump, Bytecode.JumpIfToBooleanTrue, Bytecode.JumpIfToBooleanFalse, Bytecode.JumpIfTrue, Bytecode.JumpIfFalse, Bytecode.JumpIfNull, Bytecode.JumpIfNotNull, Bytecode.JumpIfUndefined, Bytecode.JumpIfNotUndefined, Bytecode.JumpIfUndefinedOrNull, Bytecode.JumpIfJSReceiver, Bytecode.JumpIfForInDone];
    /// <summary>JUMP_CONSTANT_BYTECODE_LIST.</summary>
    public static ReadOnlySpan<Bytecode> JumpConstantBytecodeList => [Bytecode.JumpConstant, Bytecode.JumpIfToBooleanTrueConstant, Bytecode.JumpIfToBooleanFalseConstant, Bytecode.JumpIfNullConstant, Bytecode.JumpIfNotNullConstant, Bytecode.JumpIfUndefinedConstant, Bytecode.JumpIfNotUndefinedConstant, Bytecode.JumpIfUndefinedOrNullConstant, Bytecode.JumpIfTrueConstant, Bytecode.JumpIfFalseConstant, Bytecode.JumpIfJSReceiverConstant, Bytecode.JumpIfForInDoneConstant];
    /// <summary>JUMP_TO_BOOLEAN_BYTECODE_LIST.</summary>
    public static ReadOnlySpan<Bytecode> JumpToBooleanBytecodeList => [Bytecode.JumpIfToBooleanTrue, Bytecode.JumpIfToBooleanFalse, Bytecode.JumpIfToBooleanTrueConstant, Bytecode.JumpIfToBooleanFalseConstant];
    /// <summary>DEBUG_BREAK_BYTECODE_LIST.</summary>
    public static ReadOnlySpan<Bytecode> DebugBreakBytecodeList => [Bytecode.DebugBreak0, Bytecode.DebugBreak1, Bytecode.DebugBreak2, Bytecode.DebugBreak3, Bytecode.DebugBreak4, Bytecode.DebugBreak5, Bytecode.DebugBreak6, Bytecode.DebugBreakWide, Bytecode.DebugBreakExtraWide];
    /// <summary>DEBUG_BREAK_PLAIN_BYTECODE_LIST.</summary>
    public static ReadOnlySpan<Bytecode> DebugBreakPlainBytecodeList => [Bytecode.DebugBreak0, Bytecode.DebugBreak1, Bytecode.DebugBreak2, Bytecode.DebugBreak3, Bytecode.DebugBreak4, Bytecode.DebugBreak5, Bytecode.DebugBreak6];
    /// <summary>RETURN_BYTECODE_LIST.</summary>
    public static ReadOnlySpan<Bytecode> ReturnBytecodeList => [Bytecode.Return, Bytecode.SuspendGenerator];
    /// <summary>UNCONDITIONAL_THROW_BYTECODE_LIST.</summary>
    public static ReadOnlySpan<Bytecode> UnconditionalThrowBytecodeList => [Bytecode.Throw, Bytecode.ReThrow];
}
