// The index names of NATIVE_CONTEXT_FIELDS from src/objects/contexts.h, for
// printing kNativeContextIndex operands (bytecode-decoder.cc NameForNativeContextIndex).
// Generated by expanding the macro list (without V8_TEMPORAL_SUPPORT); do not edit by hand.
//
// TODO(merge): replace with the object model's Context.Field enum (Context::REFLECT_APPLY_INDEX ...).
namespace V8Sharp.Interpreter;

public static class NativeContextFields
{
    /// <summary>Context::MIN_CONTEXT_EXTENDED_SLOTS: native context fields start after
    /// SCOPE_INFO_INDEX, PREVIOUS_INDEX and EXTENSION_INDEX.</summary>
    public const int kFirstNativeContextField = 3;

    public const int GLOBAL_PROXY_INDEX = 3;
    public const int EMBEDDER_DATA_INDEX = 4;
    public const int CONTINUATION_PRESERVED_EMBEDDER_DATA_INDEX = 5;
    public const int GENERATOR_NEXT_INTERNAL = 6;
    public const int ASYNC_MODULE_EVALUATE_INTERNAL = 7;
    public const int REFLECT_APPLY_INDEX = 8;
    public const int REFLECT_CONSTRUCT_INDEX = 9;
    public const int PERFORM_PROMISE_THEN_INDEX = 10;
    public const int PROMISE_THEN_INDEX = 11;
    public const int PROMISE_RESOLVE_INDEX = 12;
    public const int FUNCTION_PROTOTYPE_APPLY_INDEX = 13;
    public const int UINT8_ARRAY_FUN_INDEX = 14;
    public const int INT8_ARRAY_FUN_INDEX = 15;
    public const int UINT16_ARRAY_FUN_INDEX = 16;
    public const int INT16_ARRAY_FUN_INDEX = 17;
    public const int UINT32_ARRAY_FUN_INDEX = 18;
    public const int INT32_ARRAY_FUN_INDEX = 19;
    public const int BIGUINT64_ARRAY_FUN_INDEX = 20;
    public const int BIGINT64_ARRAY_FUN_INDEX = 21;
    public const int UINT8_CLAMPED_ARRAY_FUN_INDEX = 22;
    public const int FLOAT32_ARRAY_FUN_INDEX = 23;
    public const int FLOAT64_ARRAY_FUN_INDEX = 24;
    public const int FLOAT16_ARRAY_FUN_INDEX = 25;
    public const int RAB_GSAB_UINT8_ARRAY_MAP_INDEX = 26;
    public const int RAB_GSAB_INT8_ARRAY_MAP_INDEX = 27;
    public const int RAB_GSAB_UINT16_ARRAY_MAP_INDEX = 28;
    public const int RAB_GSAB_INT16_ARRAY_MAP_INDEX = 29;
    public const int RAB_GSAB_UINT32_ARRAY_MAP_INDEX = 30;
    public const int RAB_GSAB_INT32_ARRAY_MAP_INDEX = 31;
    public const int RAB_GSAB_BIGUINT64_ARRAY_MAP_INDEX = 32;
    public const int RAB_GSAB_BIGINT64_ARRAY_MAP_INDEX = 33;
    public const int RAB_GSAB_UINT8_CLAMPED_ARRAY_MAP_INDEX = 34;
    public const int RAB_GSAB_FLOAT32_ARRAY_MAP_INDEX = 35;
    public const int RAB_GSAB_FLOAT64_ARRAY_MAP_INDEX = 36;
    public const int RAB_GSAB_FLOAT16_ARRAY_MAP_INDEX = 37;
    public const int ABSTRACT_MODULE_SOURCE_FUNCTION_INDEX = 38;
    public const int ABSTRACT_MODULE_SOURCE_PROTOTYPE_INDEX = 39;
    public const int ACCESSOR_PROPERTY_DESCRIPTOR_MAP_INDEX = 40;
    public const int ALLOW_CODE_GEN_FROM_STRINGS_INDEX = 41;
    public const int ARRAY_BUFFER_FUN_INDEX = 42;
    public const int ARRAY_BUFFER_MAP_INDEX = 43;
    public const int ARRAY_BUFFER_NOINIT_FUN_INDEX = 44;
    public const int ARRAY_FUNCTION_INDEX = 45;
    public const int ARRAY_JOIN_STACK_INDEX = 46;
    public const int ARRAY_FROM_ASYNC_INDEX = 47;
    public const int ASYNC_FROM_SYNC_ITERATOR_MAP_INDEX = 48;
    public const int ASYNC_FUNCTION_FUNCTION_INDEX = 49;
    public const int ASYNC_FUNCTION_OBJECT_MAP_INDEX = 50;
    public const int ASYNC_GENERATOR_FUNCTION_FUNCTION_INDEX = 51;
    public const int BIGINT_FUNCTION_INDEX = 52;
    public const int BOOLEAN_FUNCTION_INDEX = 53;
    public const int BOUND_FUNCTION_WITH_CONSTRUCTOR_MAP_INDEX = 54;
    public const int BOUND_FUNCTION_WITHOUT_CONSTRUCTOR_MAP_INDEX = 55;
    public const int CALL_AS_CONSTRUCTOR_DELEGATE_INDEX = 56;
    public const int CALL_AS_FUNCTION_DELEGATE_INDEX = 57;
    public const int CALLSITE_FUNCTION_INDEX = 58;
    public const int CONTEXT_EXTENSION_FUNCTION_INDEX = 59;
    public const int DATA_PROPERTY_DESCRIPTOR_MAP_INDEX = 60;
    public const int DATA_VIEW_FUN_INDEX = 61;
    public const int DATE_FUNCTION_INDEX = 62;
    public const int DEBUG_CONTEXT_ID_INDEX = 63;
    public const int EMPTY_FUNCTION_INDEX = 64;
    public const int ERROR_MESSAGE_FOR_CODE_GEN_FROM_STRINGS_INDEX = 65;
    public const int ERROR_MESSAGE_FOR_WASM_CODE_GEN_INDEX = 66;
    public const int ERRORS_THROWN_INDEX = 67;
    public const int EXTRAS_BINDING_OBJECT_INDEX = 68;
    public const int FAST_ALIASED_ARGUMENTS_MAP_INDEX = 69;
    public const int FAST_TEMPLATE_INSTANTIATIONS_CACHE_INDEX = 70;
    public const int FUNCTION_FUNCTION_INDEX = 71;
    public const int FUNCTION_PROTOTYPE_INDEX = 72;
    public const int GENERATOR_FUNCTION_FUNCTION_INDEX = 73;
    public const int GENERATOR_OBJECT_PROTOTYPE_MAP_INDEX = 74;
    public const int ASYNC_GENERATOR_OBJECT_PROTOTYPE_MAP_INDEX = 75;
    public const int INITIAL_ARRAY_ITERATOR_MAP_INDEX = 76;
    public const int INITIAL_ARRAY_ITERATOR_PROTOTYPE_INDEX = 77;
    public const int INITIAL_ARRAY_PROTOTYPE_INDEX = 78;
    public const int INITIAL_ERROR_PROTOTYPE_INDEX = 79;
    public const int INITIAL_GENERATOR_PROTOTYPE_INDEX = 80;
    public const int INITIAL_ASYNC_ITERATOR_PROTOTYPE_INDEX = 81;
    public const int INITIAL_ASYNC_GENERATOR_PROTOTYPE_INDEX = 82;
    public const int INITIAL_ITERATOR_FUNCTION_INDEX = 83;
    public const int INITIAL_ITERATOR_HELPER_PROTOTYPE_INDEX = 84;
    public const int INITIAL_ITERATOR_PROTOTYPE_INDEX = 85;
    public const int INITIAL_DISPOSABLE_STACK_PROTOTYPE_INDEX = 86;
    public const int INITIAL_MAP_ITERATOR_PROTOTYPE_INDEX = 87;
    public const int INITIAL_MAP_PROTOTYPE_MAP_INDEX = 88;
    public const int INITIAL_OBJECT_PROTOTYPE_INDEX = 89;
    public const int INITIAL_SET_ITERATOR_PROTOTYPE_INDEX = 90;
    public const int INITIAL_SET_PROTOTYPE_INDEX = 91;
    public const int INITIAL_SET_PROTOTYPE_MAP_INDEX = 92;
    public const int INITIAL_STRING_ITERATOR_MAP_INDEX = 93;
    public const int INITIAL_STRING_ITERATOR_PROTOTYPE_INDEX = 94;
    public const int INITIAL_STRING_PROTOTYPE_INDEX = 95;
    public const int INITIAL_WEAKMAP_PROTOTYPE_MAP_INDEX = 96;
    public const int INITIAL_WEAKSET_PROTOTYPE_MAP_INDEX = 97;
    public const int INTL_COLLATOR_FUNCTION_INDEX = 98;
    public const int INTL_DATE_TIME_FORMAT_FUNCTION_INDEX = 99;
    public const int INTL_DISPLAY_NAMES_FUNCTION_INDEX = 100;
    public const int INTL_DURATION_FORMAT_FUNCTION_INDEX = 101;
    public const int INTL_NUMBER_FORMAT_FUNCTION_INDEX = 102;
    public const int INTL_LOCALE_FUNCTION_INDEX = 103;
    public const int INTL_LIST_FORMAT_FUNCTION_INDEX = 104;
    public const int INTL_PLURAL_RULES_FUNCTION_INDEX = 105;
    public const int INTL_RELATIVE_TIME_FORMAT_FUNCTION_INDEX = 106;
    public const int INTL_SEGMENTER_FUNCTION_INDEX = 107;
    public const int INTL_SEGMENTS_MAP_INDEX = 108;
    public const int INTL_SEGMENT_DATA_OBJECT_MAP_INDEX = 109;
    public const int INTL_SEGMENT_DATA_OBJECT_WORDLIKE_MAP_INDEX = 110;
    public const int INTL_SEGMENT_ITERATOR_MAP_INDEX = 111;
    public const int ITERATOR_FILTER_HELPER_MAP_INDEX = 112;
    public const int ITERATOR_MAP_HELPER_MAP_INDEX = 113;
    public const int ITERATOR_TAKE_HELPER_MAP_INDEX = 114;
    public const int ITERATOR_DROP_HELPER_MAP_INDEX = 115;
    public const int ITERATOR_FLAT_MAP_HELPER_MAP_INDEX = 116;
    public const int ITERATOR_CONCAT_HELPER_MAP_INDEX = 117;
    public const int ITERATOR_ZIP_HELPER_MAP_INDEX = 118;
    public const int ITERATOR_ZIP_KEYED_HELPER_MAP_INDEX = 119;
    public const int ITERATOR_FUNCTION_INDEX = 120;
    public const int VALID_ITERATOR_WRAPPER_MAP_INDEX = 121;
    public const int ITERATOR_RESULT_MAP_INDEX = 122;
    public const int JS_ARRAY_PACKED_SMI_ELEMENTS_MAP_INDEX = 123;
    public const int JS_ARRAY_HOLEY_SMI_ELEMENTS_MAP_INDEX = 124;
    public const int JS_ARRAY_PACKED_ELEMENTS_MAP_INDEX = 125;
    public const int JS_ARRAY_HOLEY_ELEMENTS_MAP_INDEX = 126;
    public const int JS_ARRAY_PACKED_DOUBLE_ELEMENTS_MAP_INDEX = 127;
    public const int JS_ARRAY_HOLEY_DOUBLE_ELEMENTS_MAP_INDEX = 128;
    public const int JS_ARRAY_TEMPLATE_LITERAL_OBJECT_MAP = 129;
    public const int JS_DISPOSABLE_STACK_FUNCTION_INDEX = 130;
    public const int JS_ASYNC_DISPOSABLE_STACK_FUNCTION_INDEX = 131;
    public const int JS_DISPOSABLE_STACK_MAP_INDEX = 132;
    public const int JS_MAP_FUN_INDEX = 133;
    public const int JS_MAP_MAP_INDEX = 134;
    public const int JS_MODULE_NAMESPACE_MAP = 135;
    public const int JS_DEFERRED_MODULE_NAMESPACE_MAP = 136;
    public const int JS_RAW_JSON_MAP = 137;
    public const int JS_SET_FUN_INDEX = 138;
    public const int JS_SET_MAP_INDEX = 139;
    public const int JS_WEAK_MAP_FUN_INDEX = 140;
    public const int JS_WEAK_SET_FUN_INDEX = 141;
    public const int JS_WEAK_REF_FUNCTION_INDEX = 142;
    public const int JS_FINALIZATION_REGISTRY_FUNCTION_INDEX = 143;
    public const int JSON_OBJECT = 144;
    public const int PROMISE_WITHRESOLVERS_RESULT_MAP_INDEX = 145;
    public const int META_MAP_INDEX = 146;
    public const int FUNCTION_CONTEXT_MAP_INDEX = 147;
    public const int MODULE_CONTEXT_MAP_INDEX = 148;
    public const int EVAL_CONTEXT_MAP_INDEX = 149;
    public const int SCRIPT_CONTEXT_MAP_INDEX = 150;
    public const int AWAIT_CONTEXT_MAP_INDEX = 151;
    public const int BLOCK_CONTEXT_MAP_INDEX = 152;
    public const int CATCH_CONTEXT_MAP_INDEX = 153;
    public const int WITH_CONTEXT_MAP_INDEX = 154;
    public const int DEBUG_EVALUATE_CONTEXT_MAP_INDEX = 155;
    public const int JS_RAB_GSAB_DATA_VIEW_MAP_INDEX = 156;
    public const int MAP_CACHE_INDEX = 157;
    public const int MAP_KEY_ITERATOR_MAP_INDEX = 158;
    public const int MAP_KEY_VALUE_ITERATOR_MAP_INDEX = 159;
    public const int MAP_VALUE_ITERATOR_MAP_INDEX = 160;
    public const int MATH_RANDOM_INDEX_INDEX = 161;
    public const int MATH_RANDOM_STATE_INDEX = 162;
    public const int MATH_RANDOM_CACHE_INDEX = 163;
    public const int NORMALIZED_MAP_CACHE_INDEX = 164;
    public const int NUMBER_FUNCTION_INDEX = 165;
    public const int OBJECT_FUNCTION_INDEX = 166;
    public const int OBJECT_FUNCTION_PROTOTYPE_INDEX = 167;
    public const int OBJECT_FUNCTION_PROTOTYPE_MAP_INDEX = 168;
    public const int PROMISE_HOOK_INIT_FUNCTION_INDEX = 169;
    public const int PROMISE_HOOK_BEFORE_FUNCTION_INDEX = 170;
    public const int PROMISE_HOOK_AFTER_FUNCTION_INDEX = 171;
    public const int PROMISE_HOOK_RESOLVE_FUNCTION_INDEX = 172;
    public const int PROXY_CALLABLE_MAP_INDEX = 173;
    public const int PROXY_CONSTRUCTOR_MAP_INDEX = 174;
    public const int PROXY_FUNCTION_INDEX = 175;
    public const int PROXY_MAP_INDEX = 176;
    public const int PROXY_REVOCABLE_RESULT_MAP_INDEX = 177;
    public const int PROMISE_PROTOTYPE_INDEX = 178;
    public const int RECORDER_CONTEXT_ID = 179;
    public const int REGEXP_EXEC_FUNCTION_INDEX = 180;
    public const int REGEXP_FUNCTION_INDEX = 181;
    public const int REGEXP_LAST_MATCH_INFO_INDEX = 182;
    public const int REGEXP_MATCH_ALL_FUNCTION_INDEX = 183;
    public const int REGEXP_MATCH_FUNCTION_INDEX = 184;
    public const int REGEXP_PROTOTYPE_INDEX = 185;
    public const int REGEXP_PROTOTYPE_MAP_INDEX = 186;
    public const int REGEXP_REPLACE_FUNCTION_INDEX = 187;
    public const int REGEXP_RESULT_MAP_INDEX = 188;
    public const int REGEXP_RESULT_WITH_INDICES_MAP_INDEX = 189;
    public const int REGEXP_RESULT_INDICES_MAP_INDEX = 190;
    public const int REGEXP_SEARCH_FUNCTION_INDEX = 191;
    public const int REGEXP_SPLIT_FUNCTION_INDEX = 192;
    public const int INITIAL_REGEXP_STRING_ITERATOR_PROTOTYPE_MAP_INDEX = 193;
    public const int SCRIPT_CONTEXT_TABLE_INDEX = 194;
    public const int SCRIPT_EXECUTION_CALLBACK_INDEX = 195;
    public const int TEMPORAL_GET_EPOCH_NANOSECONDS_CALLBACK_INDEX = 196;
    public const int SECURITY_TOKEN_INDEX = 197;
    public const int SERIALIZED_OBJECTS = 198;
    public const int SET_VALUE_ITERATOR_MAP_INDEX = 199;
    public const int SET_KEY_VALUE_ITERATOR_MAP_INDEX = 200;
    public const int SHARED_ARRAY_BUFFER_FUN_INDEX = 201;
    public const int SLOPPY_ARGUMENTS_MAP_INDEX = 202;
    public const int SLOW_ALIASED_ARGUMENTS_MAP_INDEX = 203;
    public const int STRICT_ARGUMENTS_MAP_INDEX = 204;
    public const int SLOW_OBJECT_WITH_NULL_PROTOTYPE_MAP = 205;
    public const int SLOW_OBJECT_WITH_OBJECT_PROTOTYPE_MAP = 206;
    public const int SLOW_TEMPLATE_INSTANTIATIONS_CACHE_INDEX = 207;
    public const int ATOMICS_WAITASYNC_PROMISES = 208;
    public const int SET_UINT8_ARRAY_RESULT_MAP = 209;
    public const int WASM_DEBUG_MAPS = 210;
    public const int INITIAL_ARRAY_PROTOTYPE_VALIDITY_CELL_INDEX = 211;
    public const int SLOPPY_FUNCTION_MAP_INDEX = 212;
    public const int SLOPPY_FUNCTION_WITH_NAME_MAP_INDEX = 213;
    public const int SLOPPY_FUNCTION_WITHOUT_PROTOTYPE_MAP_INDEX = 214;
    public const int SLOPPY_FUNCTION_WITH_READONLY_PROTOTYPE_MAP_INDEX = 215;
    public const int STRICT_FUNCTION_MAP_INDEX = 216;
    public const int STRICT_FUNCTION_WITH_NAME_MAP_INDEX = 217;
    public const int STRICT_FUNCTION_WITH_READONLY_PROTOTYPE_MAP_INDEX = 218;
    public const int STRICT_FUNCTION_WITHOUT_PROTOTYPE_MAP_INDEX = 219;
    public const int METHOD_WITH_NAME_MAP_INDEX = 220;
    public const int ASYNC_FUNCTION_MAP_INDEX = 221;
    public const int ASYNC_FUNCTION_WITH_NAME_MAP_INDEX = 222;
    public const int GENERATOR_FUNCTION_MAP_INDEX = 223;
    public const int GENERATOR_FUNCTION_WITH_NAME_MAP_INDEX = 224;
    public const int ASYNC_GENERATOR_FUNCTION_MAP_INDEX = 225;
    public const int ASYNC_GENERATOR_FUNCTION_WITH_NAME_MAP_INDEX = 226;
    public const int CLASS_FUNCTION_MAP_INDEX = 227;
    public const int STRING_FUNCTION_INDEX = 228;
    public const int STRING_FUNCTION_PROTOTYPE_MAP_INDEX = 229;
    public const int SYMBOL_FUNCTION_INDEX = 230;
    public const int IS_WASM_JS_INSTALLED_INDEX = 231;
    public const int IS_WASM_JSPI_INSTALLED_INDEX = 232;
    public const int WASM_WEBASSEMBLY_OBJECT_INDEX = 233;
    public const int WASM_EXPORTED_FUNCTION_MAP_INDEX = 234;
    public const int WASM_TAG_CONSTRUCTOR_INDEX = 235;
    public const int WASM_EXCEPTION_CONSTRUCTOR_INDEX = 236;
    public const int WASM_GLOBAL_CONSTRUCTOR_INDEX = 237;
    public const int WASM_INSTANCE_CONSTRUCTOR_INDEX = 238;
    public const int WASM_JS_TAG_INDEX = 239;
    public const int WASM_MEMORY_CONSTRUCTOR_INDEX = 240;
    public const int WASM_MODULE_CONSTRUCTOR_INDEX = 241;
    public const int WASM_TABLE_CONSTRUCTOR_INDEX = 242;
    public const int WASM_SUSPENDING_CONSTRUCTOR_INDEX = 243;
    public const int WASM_SUSPENDER_CONSTRUCTOR_INDEX = 244;
    public const int WASM_SUSPENDING_MAP = 245;
    public const int WASM_SUSPENDING_PROTOTYPE = 246;
    public const int WASM_MEMORY_MAP_DESCRIPTOR_TEMPLATE_INDEX = 247;
    public const int WASM_MEMORY_MAP_DESCRIPTOR_CONSTRUCTOR_INDEX = 248;
    public const int TEMPLATE_WEAKMAP_INDEX = 249;
    public const int TYPED_ARRAY_FUN_INDEX = 250;
    public const int TYPED_ARRAY_PROTOTYPE_INDEX = 251;
    public const int ARRAY_ENTRIES_ITERATOR_INDEX = 252;
    public const int ARRAY_FOR_EACH_ITERATOR_INDEX = 253;
    public const int ARRAY_KEYS_ITERATOR_INDEX = 254;
    public const int ARRAY_VALUES_ITERATOR_INDEX = 255;
    public const int ERROR_FUNCTION_INDEX = 256;
    public const int ERROR_TO_STRING = 257;
    public const int EVAL_ERROR_FUNCTION_INDEX = 258;
    public const int AGGREGATE_ERROR_FUNCTION_INDEX = 259;
    public const int GLOBAL_EVAL_FUN_INDEX = 260;
    public const int GLOBAL_PARSE_FLOAT_FUN_INDEX = 261;
    public const int GLOBAL_PARSE_INT_FUN_INDEX = 262;
    public const int GLOBAL_PROXY_FUNCTION_INDEX = 263;
    public const int MAP_DELETE_INDEX = 264;
    public const int MAP_GET_INDEX = 265;
    public const int MAP_HAS_INDEX = 266;
    public const int MAP_SET_INDEX = 267;
    public const int FUNCTION_HAS_INSTANCE_INDEX = 268;
    public const int FUNCTION_TO_STRING_INDEX = 269;
    public const int OBJECT_TO_STRING = 270;
    public const int OBJECT_VALUE_OF_FUNCTION_INDEX = 271;
    public const int PROMISE_ALL_INDEX = 272;
    public const int PROMISE_ALL_SETTLED_INDEX = 273;
    public const int PROMISE_ANY_INDEX = 274;
    public const int PROMISE_FUNCTION_INDEX = 275;
    public const int RANGE_ERROR_FUNCTION_INDEX = 276;
    public const int REFERENCE_ERROR_FUNCTION_INDEX = 277;
    public const int SET_ADD_INDEX = 278;
    public const int SET_DELETE_INDEX = 279;
    public const int SET_HAS_INDEX = 280;
    public const int SHADOW_REALM_IMPORT_VALUE_REJECTED_INDEX = 281;
    public const int SUPPRESSED_ERROR_FUNCTION_INDEX = 282;
    public const int SYNTAX_ERROR_FUNCTION_INDEX = 283;
    public const int TYPE_ERROR_FUNCTION_INDEX = 284;
    public const int URI_ERROR_FUNCTION_INDEX = 285;
    public const int WASM_COMPILE_ERROR_FUNCTION_INDEX = 286;
    public const int WASM_LINK_ERROR_FUNCTION_INDEX = 287;
    public const int WASM_SUSPEND_ERROR_FUNCTION_INDEX = 288;
    public const int WASM_RUNTIME_ERROR_FUNCTION_INDEX = 289;
    public const int WEAKMAP_SET_INDEX = 290;
    public const int WEAKMAP_GET_INDEX = 291;
    public const int WEAKMAP_DELETE_INDEX = 292;
    public const int WEAKSET_ADD_INDEX = 293;
    public const int WRAPPED_FUNCTION_MAP_INDEX = 294;
    public const int RETAINED_MAPS = 295;
    public const int SHARED_SPACE_JS_OBJECT_HAS_INSTANCE_INDEX = 296;

    static readonly string[] s_names =
    [
        "global_proxy_object",
        "embedder_data",
        "continuation_preserved_embedder_data",
        "generator_next_internal",
        "async_module_evaluate_internal",
        "reflect_apply",
        "reflect_construct",
        "perform_promise_then",
        "promise_then",
        "promise_resolve",
        "function_prototype_apply",
        "uint8_array_fun",
        "int8_array_fun",
        "uint16_array_fun",
        "int16_array_fun",
        "uint32_array_fun",
        "int32_array_fun",
        "biguint64_array_fun",
        "bigint64_array_fun",
        "uint8_clamped_array_fun",
        "float32_array_fun",
        "float64_array_fun",
        "float16_array_fun",
        "rab_gsab_uint8_array_map",
        "rab_gsab_int8_array_map",
        "rab_gsab_uint16_array_map",
        "rab_gsab_int16_array_map",
        "rab_gsab_uint32_array_map",
        "rab_gsab_int32_array_map",
        "rab_gsab_biguint64_array_map",
        "rab_gsab_bigint64_array_map",
        "rab_gsab_uint8_clamped_array_map",
        "rab_gsab_float32_array_map",
        "rab_gsab_float64_array_map",
        "rab_gsab_float16_array_map",
        "abstract_module_source_function",
        "abstract_module_source_prototype",
        "accessor_property_descriptor_map",
        "allow_code_gen_from_strings",
        "array_buffer_fun",
        "array_buffer_map",
        "array_buffer_noinit_fun",
        "array_function",
        "array_join_stack",
        "from_async",
        "async_from_sync_iterator_map",
        "async_function_constructor",
        "async_function_object_map",
        "async_generator_function_function",
        "bigint_function",
        "boolean_function",
        "bound_function_with_constructor_map",
        "bound_function_without_constructor_map",
        "call_as_constructor_delegate",
        "call_as_function_delegate",
        "callsite_function",
        "context_extension_function",
        "data_property_descriptor_map",
        "data_view_fun",
        "date_function",
        "debug_context_id",
        "empty_function",
        "error_message_for_code_gen_from_strings",
        "error_message_for_wasm_code_gen",
        "errors_thrown",
        "extras_binding_object",
        "fast_aliased_arguments_map",
        "fast_template_instantiations_cache",
        "function_function",
        "function_prototype",
        "generator_function_function",
        "generator_object_prototype_map",
        "async_generator_object_prototype_map",
        "initial_array_iterator_map",
        "initial_array_iterator_prototype",
        "initial_array_prototype",
        "initial_error_prototype",
        "initial_generator_prototype",
        "initial_async_iterator_prototype",
        "initial_async_generator_prototype",
        "initial_iterator_function",
        "initial_iterator_helper_prototype",
        "initial_iterator_prototype",
        "initial_disposable_stack_prototype",
        "initial_map_iterator_prototype",
        "initial_map_prototype_map",
        "initial_object_prototype",
        "initial_set_iterator_prototype",
        "initial_set_prototype",
        "initial_set_prototype_map",
        "initial_string_iterator_map",
        "initial_string_iterator_prototype",
        "initial_string_prototype",
        "initial_weakmap_prototype_map",
        "initial_weakset_prototype_map",
        "intl_collator_function",
        "intl_date_time_format_function",
        "intl_display_names_function",
        "intl_duration_format_function",
        "intl_number_format_function",
        "intl_locale_function",
        "intl_list_format_function",
        "intl_plural_rules_function",
        "intl_relative_time_format_function",
        "intl_segmenter_function",
        "intl_segments_map",
        "intl_segment_data_object_map",
        "intl_segment_data_object_wordlike_map",
        "intl_segment_iterator_map",
        "iterator_filter_helper_map",
        "iterator_map_helper_map",
        "iterator_take_helper_map",
        "iterator_drop_helper_map",
        "iterator_flatMap_helper_map",
        "iterator_concat_helper_map",
        "iterator_zip_helper_map",
        "iterator_zip_keyed_helper_map",
        "iterator_function",
        "valid_iterator_wrapper_map",
        "iterator_result_map",
        "js_array_packed_smi_elements_map",
        "js_array_holey_smi_elements_map",
        "js_array_packed_elements_map",
        "js_array_holey_elements_map",
        "js_array_packed_double_elements_map",
        "js_array_holey_double_elements_map",
        "js_array_template_literal_object_map",
        "js_disposable_stack_function",
        "js_async_disposable_stack_function",
        "js_disposable_stack_map",
        "js_map_fun",
        "js_map_map",
        "js_module_namespace_map",
        "js_deferred_module_namespace_map",
        "js_raw_json_map",
        "js_set_fun",
        "js_set_map",
        "js_weak_map_fun",
        "js_weak_set_fun",
        "js_weak_ref_fun",
        "js_finalization_registry_fun",
        "json_object",
        "promise_withresolvers_result_map",
        "meta_map",
        "function_context_map",
        "module_context_map",
        "eval_context_map",
        "script_context_map",
        "await_context_map",
        "block_context_map",
        "catch_context_map",
        "with_context_map",
        "debug_evaluate_context_map",
        "js_rab_gsab_data_view_map",
        "map_cache",
        "map_key_iterator_map",
        "map_key_value_iterator_map",
        "map_value_iterator_map",
        "math_random_index",
        "math_random_state",
        "math_random_cache",
        "normalized_map_cache",
        "number_function",
        "object_function",
        "object_function_prototype",
        "object_function_prototype_map",
        "promise_hook_init_function",
        "promise_hook_before_function",
        "promise_hook_after_function",
        "promise_hook_resolve_function",
        "proxy_callable_map",
        "proxy_constructor_map",
        "proxy_function",
        "proxy_map",
        "proxy_revocable_result_map",
        "promise_prototype",
        "recorder_context_id",
        "regexp_exec_function",
        "regexp_function",
        "regexp_last_match_info",
        "regexp_match_all_function",
        "regexp_match_function",
        "regexp_prototype",
        "regexp_prototype_map",
        "regexp_replace_function",
        "regexp_result_map",
        "regexp_result_with_indices_map",
        "regexp_result_indices_map",
        "regexp_search_function",
        "regexp_split_function",
        "initial_regexp_string_iterator_prototype_map",
        "script_context_table",
        "script_execution_callback",
        "temporal_get_epoch_nanoseconds_callback",
        "security_token",
        "serialized_objects",
        "set_value_iterator_map",
        "set_key_value_iterator_map",
        "shared_array_buffer_fun",
        "sloppy_arguments_map",
        "slow_aliased_arguments_map",
        "strict_arguments_map",
        "slow_object_with_null_prototype_map",
        "slow_object_with_object_prototype_map",
        "slow_template_instantiations_cache",
        "atomics_waitasync_promises",
        "set_unit8_array_result_map",
        "wasm_debug_maps",
        "initial_array_prototype_validity_cell",
        "sloppy_function_map",
        "sloppy_function_with_name_map",
        "sloppy_function_without_prototype_map",
        "sloppy_function_with_readonly_prototype_map",
        "strict_function_map",
        "strict_function_with_name_map",
        "strict_function_with_readonly_prototype_map",
        "strict_function_without_prototype_map",
        "method_with_name_map",
        "async_function_map",
        "async_function_with_name_map",
        "generator_function_map",
        "generator_function_with_name_map",
        "async_generator_function_map",
        "async_generator_function_with_name_map",
        "class_function_map",
        "string_function",
        "string_function_prototype_map",
        "symbol_function",
        "is_wasm_js_installed",
        "is_wasm_jspi_installed",
        "wasm_webassembly_object",
        "wasm_exported_function_map",
        "wasm_tag_constructor",
        "wasm_exception_constructor",
        "wasm_global_constructor",
        "wasm_instance_constructor",
        "wasm_js_tag",
        "wasm_memory_constructor",
        "wasm_module_constructor",
        "wasm_table_constructor",
        "wasm_suspending_constructor",
        "wasm_suspender_constructor",
        "wasm_suspending_map",
        "wasm_suspending_prototype",
        "wasm_memory_map_descriptor_template",
        "wasm_memory_map_descriptor_constructor",
        "template_weakmap",
        "typed_array_function",
        "typed_array_prototype",
        "array_entries_iterator",
        "array_for_each_iterator",
        "array_keys_iterator",
        "array_values_iterator",
        "error_function",
        "error_to_string",
        "eval_error_function",
        "aggregate_error_function",
        "global_eval_fun",
        "global_parse_float_fun",
        "global_parse_int_fun",
        "global_proxy_function",
        "map_delete",
        "map_get",
        "map_has",
        "map_set",
        "function_has_instance",
        "function_to_string",
        "object_to_string",
        "object_value_of_function",
        "promise_all",
        "promise_all_settled",
        "promise_any",
        "promise_function",
        "range_error_function",
        "reference_error_function",
        "set_add",
        "set_delete",
        "set_has",
        "shadow_realm_import_value_rejected",
        "suppressed_error_function",
        "syntax_error_function",
        "type_error_function",
        "uri_error_function",
        "wasm_compile_error_function",
        "wasm_link_error_function",
        "wasm_suspend_error_function",
        "wasm_runtime_error_function",
        "weakmap_set",
        "weakmap_get",
        "weakmap_delete",
        "weakset_add",
        "wrapped_function_map",
        "retained_maps",
        "shared_space_js_object_has_instance",
    ];

    public const int NATIVE_CONTEXT_SLOTS_WITHOUT_LINK = 297;

    /// <summary>The lower-case field name for a native context index, or null.</summary>
    public static string? NameForIndex(int index)
    {
        int i = index - kFirstNativeContextField;
        return (uint)i < (uint)s_names.Length ? s_names[i] : null;
    }

    public static int IndexForName(string name)
    {
        for (int i = 0; i < s_names.Length; i++)
        {
            if (s_names[i] == name) return i + kFirstNativeContextField;
        }
        return -1;
    }
}
