// Port of src/codegen/unoptimized-compilation-info.h/.cc.
//
// TODO(merge): V8 keeps this in src/codegen; it lives with the interpreter
// until the compiler pipeline (src/codegen/compiler.cc) is ported.
using V8Sharp.Ast;
using V8Sharp.Codegen;
using V8Sharp.Parsing;

namespace V8Sharp.Interpreter;

/// <summary>UnoptimizedCompilationInfo encapsulates the information needed to
/// compile unoptimized code for one function.</summary>
public sealed class UnoptimizedCompilationInfo
{
    // Compilation flags.
    readonly UnoptimizedCompileFlags _flags;

    // The root AST node of the unit to compile.
    readonly FunctionLiteral _literal;

    // Used when block coverage is enabled.
    readonly SourceRangeMap? _sourceRangeMap;

    // Encapsulates coverage information gathered by the bytecode generator.
    // Needs to be stored on the shared function info once compilation completes.
    object? _coverageInfo;

    // Holds the bytecode array generated by the interpreter.
    BytecodeArray? _bytecodeArray;

    readonly FeedbackVectorSpec _feedbackVectorSpec = new();

    public UnoptimizedCompilationInfo(ParseInfo parse_info, FunctionLiteral literal)
    {
        // NOTE: The parse_info passed here represents the global information gathered
        // during parsing, but does not represent specific details of the actual
        // function literal being compiled for this OptimizedCompilationInfo. As such,
        // parse_info->literal() might be different from literal, and only global
        // details of the script being parsed are relevant to this
        // OptimizedCompilationInfo.
        _flags = parse_info.flags();
        _literal = literal;
        _sourceRangeMap = parse_info.source_range_map();
    }

    public UnoptimizedCompileFlags flags() => _flags;

    // Accessors for the input data of the function being compiled.
    public FunctionLiteral literal() => _literal;

    public DeclarationScope scope() => _literal.scope();

    public int num_parameters() => scope().num_parameters();
    public int num_parameters_including_this() => scope().num_parameters() + 1;

    // Source range map for code coverage.
    public SourceRangeMap? source_range_map() => _sourceRangeMap;
    public bool has_source_range_map() => _sourceRangeMap is not null;

    // Coverage info.
    public object? coverage_info() => _coverageInfo;
    public bool has_coverage_info() => _coverageInfo is not null;
    public void set_coverage_info(object? coverage_info) => _coverageInfo = coverage_info;

    // The source position recording mode.
    public SourcePositionTableBuilder.RecordingMode SourcePositionRecordingMode()
    {
        if (flags().collect_source_positions())
        {
            return SourcePositionTableBuilder.RecordingMode.RECORD_SOURCE_POSITIONS;
        }

        // Always collect source positions for functions that cannot be lazily
        // compiled, e.g. class member initializer functions.
        return !_literal.AllowsLazyCompilation()
            ? SourcePositionTableBuilder.RecordingMode.RECORD_SOURCE_POSITIONS
            : SourcePositionTableBuilder.RecordingMode.LAZY_SOURCE_POSITIONS;
    }

    // Accessors for the output data of the function being compiled.
    public bool has_bytecode_array() => _bytecodeArray is not null;
    public BytecodeArray? bytecode_array() => _bytecodeArray;
    public void SetBytecodeArray(BytecodeArray bytecode_array) => _bytecodeArray = bytecode_array;

    public FeedbackVectorSpec feedback_vector_spec() => _feedbackVectorSpec;
}
