// Checks BytecodeDecoder's disassembly format against real V8 (the oracle,
// V8 14.7): V8 prints bytecode with --print-bytecode to the native stdout, so
// a child process runs the scripts and this test parses what it printed.
//
// The oracle is older than this tree, so its opcode numbering can differ.
// Each printed instruction is matched to V8Sharp's bytecode of the same name;
// when the operand layout agrees, the opcode byte is replaced by V8Sharp's and
// the line is decoded with BytecodeDecoder, which must print it identically
// (hex bytes aside from the opcode, name, scale suffix and operands).
// Constant pool operands are compared up to the index, since the pool itself
// is not printed by a release V8.
using System.Diagnostics;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using V8Sharp.Interpreter;
using V8Sharp.Oracle;

namespace V8Sharp.Tests.Interpreter;

public partial class OracleBytecodeFormatTest
{
    const string kChildEnv = "V8SHARP_ORACLE_PRINT_BYTECODE";
    const string kBeginMarker = "@@@ORACLE-BEGIN@@@";
    const string kEndMarker = "@@@ORACLE-END@@@";

    // Scripts whose function f exercises registers, parameters, the receiver,
    // closures, contexts, feedback slots, flags, immediates, wide operands,
    // jumps, register lists and runtime calls.
    const string kScript = """
        function f(a, b, c) {
          var x = a + b * 3;
          var o = { p: x, q: [1, 2, 3] };
          let s = 0;
          for (let i = 0; i < 10; i++) { s += i; if (s > 1000) break; }
          for (var k in o) { s += o[k] ? 1 : 0; }
          try { g(this, a, b, c); } catch (e) { s = e; }
          var h = () => s + x;
          x = typeof a == "number" ? h() : -x;
          c = [a, ...b];
          x = 100000 + x;
          x = x | 70000;
          return [s, x, o.p, c, new Array(a, b), `${a}${b}`, a?.b, a ?? b];
        }
        function g() { return arguments.length; }
        f(1, [2], 3);
        """;

    [Fact]
    public void OracleChild_PrintBytecode()
    {
        // Runs only in the child process started by the test below.
        if (Environment.GetEnvironmentVariable(kChildEnv) != "1") return;
        ReferenceV8.EnsureFlags("--print-bytecode --print-bytecode-filter=f");
        using var v8 = new ReferenceV8();
        Console.Out.Flush();
        Console.WriteLine(kBeginMarker);
        Console.Out.Flush();
        v8.Run(kScript);
        Console.Out.Flush();
        Console.WriteLine(kEndMarker);
        Console.Out.Flush();
    }

    static string? RunChild()
    {
        string assembly = typeof(OracleBytecodeFormatTest).Assembly.Location;
        string dotnet = Environment.GetEnvironmentVariable("DOTNET_HOST_PATH") ?? "dotnet";
        var psi = new ProcessStartInfo(dotnet)
        {
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
        };
        psi.ArgumentList.Add("exec");
        psi.ArgumentList.Add(assembly);
        psi.ArgumentList.Add("-method");
        psi.ArgumentList.Add(typeof(OracleBytecodeFormatTest).FullName + "." + nameof(OracleChild_PrintBytecode));
        psi.Environment[kChildEnv] = "1";
        using Process? p = Process.Start(psi);
        if (p is null) return null;
        Task<string> stderr = p.StandardError.ReadToEndAsync();
        string stdout = p.StandardOutput.ReadToEnd();
        if (!p.WaitForExit(120_000))
        {
            p.Kill();
            return null;
        }
        _ = stderr.Result;
        return stdout;
    }

    // "         0x3a0c0010088c @    0 : 0b 03             Ldar a0"
    [GeneratedRegex(@"^\s*(?:\d+ [SEse]> )?\s*0x[0-9a-f]+ @\s+\d+ : (?<hex>(?:[0-9a-f]{2} )+)\s*(?<text>\S.*)$")]
    private static partial Regex BytecodeLineRegex();

    [Fact]
    public void BytecodeDecoder_MatchesOracleDisassembly()
    {
        string? output = RunChild();
        Assert.NotNull(output);
        int begin = output!.IndexOf(kBeginMarker, StringComparison.Ordinal);
        int end = output.IndexOf(kEndMarker, StringComparison.Ordinal);
        Assert.True(begin >= 0 && end > begin, "oracle child did not run:\n" + output);
        string printed = output[begin..end];
        Assert.Contains("[generated bytecode for function: f", printed, StringComparison.Ordinal);

        var names = new Dictionary<string, Bytecode>(StringComparer.Ordinal);
        for (int i = 0; i < Bytecodes.kBytecodeCount; i++) names[Bytecodes.ToString((Bytecode)i)] = (Bytecode)i;

        int compared = 0, skipped = 0;
        var failures = new StringBuilder();
        foreach (string raw in printed.Split('\n'))
        {
            string line = raw.TrimEnd('\r');
            Match m = BytecodeLineRegex().Match(line);
            if (!m.Success) continue;

            byte[] bytes = [.. m.Groups["hex"].Value.Split(' ', StringSplitOptions.RemoveEmptyEntries)
                                .Select(h => byte.Parse(h, NumberStyles.HexNumber, CultureInfo.InvariantCulture))];
            string text = m.Groups["text"].Value.TrimEnd();
            int space = text.IndexOf(' ');
            string mnemonic = space < 0 ? text : text[..space];
            int dot = mnemonic.IndexOf('.');
            string name = dot < 0 ? mnemonic : mnemonic[..dot];
            OperandScale scale = dot < 0 ? OperandScale.Single
                : mnemonic[(dot + 1)..] == "Wide" ? OperandScale.Double : OperandScale.Quadruple;
            int prefix = scale == OperandScale.Single ? 0 : 1;

            if (!names.TryGetValue(name, out Bytecode bytecode) ||
                Bytecodes.Size(bytecode, scale) + prefix != bytes.Length ||
                // Embedded feedback is newer than the oracle (V8 14.7 has a feedback slot there).
                Bytecodes.IsEmbeddedFeedbackBytecode(bytecode))
            {
                skipped++;
                continue;
            }

            // Re-number the opcode (and prefix) with V8Sharp's values.
            if (prefix == 1) bytes[0] = Bytecodes.ToByte(Bytecodes.OperandScaleToPrefixBytecode(scale));
            bytes[prefix] = Bytecodes.ToByte(bytecode);

            string ours = BytecodeDecoder.Decode(bytes, constantPool: [], withHex: false);
            // BytecodeArray::Disassemble, not the decoder, appends jump targets.
            string theirs = Regex.Replace(text, @" \(0x[0-9a-f]+ @ \d+\)$", "");
            if (bytecode is Bytecode.CallRuntime or Bytecode.CallRuntimeForPair)
            {
                // Runtime function ids are numbered differently in the oracle's V8;
                // compare the operand format only.
                ours = Regex.Replace(ours, @"^(\S+) \[\w+\]", "$1 [F]");
                theirs = Regex.Replace(theirs, @"^(\S+) \[\w+\]", "$1 [F]");
            }
            // Constant pool entries are not available: compare "[index:" only.
            ours = Regex.Replace(ours, @"\[(\d+):[^\]]*\]", "[$1:]");
            theirs = Regex.Replace(theirs, @"\[(\d+):.*?\](?=, |$)", "[$1:]");
            if (ours != theirs) failures.Append("V8:       ").Append(theirs).Append("\nV8Sharp:  ").Append(ours).Append('\n');
            compared++;
        }

        Assert.True(compared >= 40, $"too few bytecodes compared ({compared}, skipped {skipped}):\n{printed}");
        Assert.True(failures.Length == 0, failures.ToString());
    }
}
