// Copyright 2026 Kelvin Nishikawa
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

using System;
using System.Collections.Generic;
using System.Threading;
using Wacs.Core.Compilation;
using Wacs.Core.Instructions;
using Wacs.Core.Runtime.Exceptions;
using Wacs.Core.Runtime.Types;
using Wacs.Core.Types;
using Wacs.Core.Types.Defs;

namespace Wacs.Core.Runtime.Concurrency
{
    /// <summary>
    /// Static runtime entry points for the Stack Switching opcodes
    /// called from CIL emitted by the WACS transpiler. Each helper
    /// is the morally-identical operation that the corresponding
    /// <c>Inst*.Execute</c> performs, restructured to take typed
    /// CLR arguments (instead of popping from the interpreter's
    /// OpStack) and to be safely callable from emitted IL.
    ///
    /// <para>Helpers take an <see cref="IContinuationContext"/> —
    /// the transpiler's ThinContext implements it via explicit-
    /// interface forwarders, no runtime reflection (AOT-safe).
    /// Each op branches on availability:</para>
    ///
    /// <list type="bullet">
    ///   <item><b>Mixed mode</b> (ExecContext != null): use the
    ///     runtime's Store + Frame + OpStack — identical to the
    ///     interpreter's <c>Inst*.Execute</c> path.</item>
    ///   <item><b>Standalone mode</b> (ExecContext == null): use
    ///     the Module-local <c>ContinuationStore</c> + Tags array
    ///     on ThinContext. <c>cont.new</c> / <c>cont.bind</c> /
    ///     <c>suspend</c> work without ExecContext. <c>resume</c>
    ///     / <c>resume_throw</c> / <c>switch</c> still throw
    ///     <see cref="NotSupportedException"/> — they need
    ///     reflection-based delegate marshaling that is a
    ///     separate slice.</item>
    /// </list>
    /// </summary>
    public static class StackSwitchingHelpers
    {
        private const string NoHostContextMessage =
            "Stack switching opcodes (cont.*) require a WasmRuntime host context " +
            "for runtime support. Standalone-mode transpiled modules do not yet " +
            "include a self-contained continuation runtime.";

        private const string StandaloneInvokeUnsupported =
            "Standalone-mode resume / resume_throw / switch require a typed " +
            "StandaloneContInvoker generated by the transpiler for the " +
            "continuation's signature. The current emit does not yet generate " +
            "these invokers; the call site passed null.";

        private static ExecContext RequireExec(ExecContext? exec)
        {
            if (exec == null)
                throw new NotSupportedException(NoHostContextMessage);
            return exec;
        }

        // Standalone funcref carries an IDelegateRef in
        // Value.GcRef whose Target is the function delegate.
        // Interface dispatch — AOT-safe.
        private static Delegate? ExtractDelegateRefTarget(IGcRef? gcRef) =>
            (gcRef as IDelegateRef)?.Target;

        // Synthetic ExnIdx counter for standalone-mode resume_throw.
        // The mixed-mode path goes through Store.AllocateExn which
        // produces a Store-scoped idx; standalone has no Store, so
        // mint a process-wide unique id directly. Catch sites compare
        // by Tag identity (synthesized TagAddr), not by ExnIdx.
        private static int s_standaloneExnIdSeed;

        // Standalone resume: validate the cont, dispatch via the
        // transpiler-generated typed invoker, mark Completed on
        // any exit. SuspensionException propagates naturally to
        // the caller's emitted try/catch arm.
        private static Value[] ResumeStandalone(
            IContinuationContext hctx, Value contRef, Value[] args,
            StandaloneContInvoker? invoker)
        {
            if (invoker == null)
                throw new NotSupportedException(StandaloneInvokeUnsupported);
            if (contRef.IsNullRef)
                throw new TrapException("resume: null continuation reference.");
            var cont = contRef.GcRef as ContInstance
                       ?? throw new TrapException(
                           "resume: ref does not point to a continuation.");
            if (cont.State != ContState.Fresh)
                throw new TrapException(
                    $"resume: continuation is not resumable (state {cont.State}).");
            cont.State = ContState.Running;
            try
            {
                var result = invoker.Invoke(hctx, cont, args);
                cont.State = ContState.Completed;
                return result;
            }
            catch
            {
                cont.State = ContState.Completed;
                throw;
            }
        }

        // Standalone resume_throw: construct an ExnInstance directly
        // (Store-less; the public ExnInstance ctor is AOT-safe), run
        // the cont via the typed invoker mirroring mixed-mode semantics
        // for fresh-only continuations (body runs, then exn throws),
        // then raise WasmException. SuspensionException raised during
        // invocation propagates naturally to the caller's emitted
        // try/catch arm — resume_throw degenerates into resume on a
        // suspending body.
        private static Value[] ResumeThrowStandalone(
            IContinuationContext hctx, int tagIdxValue,
            Value[] excArgs, Value contRef, Value[] args,
            StandaloneContInvoker? invoker)
        {
            if (invoker == null)
                throw new NotSupportedException(StandaloneInvokeUnsupported);
            if (contRef.IsNullRef)
                throw new TrapException("resume_throw: null continuation reference.");
            var cont = contRef.GcRef as ContInstance
                       ?? throw new TrapException(
                           "resume_throw: ref does not point to a continuation.");
            if (cont.State != ContState.Fresh)
                throw new TrapException(
                    $"resume_throw: continuation is not resumable (state {cont.State}).");

            // Build the exn ahead of body invocation so any allocation
            // failure surfaces before state transitions. TagAddr is
            // synthesized from the raw tag idx — same convention as
            // Suspend so catch arms can compare by tag identity.
            var fields = new Stack<Value>();
            for (int i = 0; i < excArgs.Length; i++)
                fields.Push(excArgs[i]);
            var tagAddr = new TagAddr(tagIdxValue);
            var nextId = (uint)Interlocked.Increment(ref s_standaloneExnIdSeed);
            var exn = new ExnInstance(nextId, tagAddr, fields);

            cont.State = ContState.Running;
            try
            {
                invoker.Invoke(hctx, cont, args);
            }
            catch
            {
                cont.State = ContState.Completed;
                throw;
            }
            cont.State = ContState.Completed;

            throw new WasmException(exn);
        }

        // Standalone switch: same shape as ResumeStandalone but
        // the target is invoked with t1* args + a Completed
        // placeholder reified-self; that bookkeeping is the
        // invoker's responsibility (per-signature impl).
        private static Value[] SwitchStandalone(
            IContinuationContext hctx, Value contRef, Value[] args,
            StandaloneContInvoker? invoker)
        {
            if (invoker == null)
                throw new NotSupportedException(StandaloneInvokeUnsupported);
            if (contRef.IsNullRef)
                throw new TrapException("switch: null continuation reference.");
            var target = contRef.GcRef as ContInstance
                         ?? throw new TrapException(
                             "switch: ref does not point to a continuation.");
            if (target.State != ContState.Fresh)
                throw new TrapException(
                    $"switch: continuation is not resumable (state {target.State}).");
            target.State = ContState.Running;
            try
            {
                var result = invoker.Invoke(hctx, target, args);
                target.State = ContState.Completed;
                return result;
            }
            catch
            {
                target.State = ContState.Completed;
                throw;
            }
        }

        // Convert the transpiler-passed handler-tag indices to
        // StackSwitchHandler[] for ResumeHandlerFrame storage.
        // Label is a dummy zero — transpiler-installed frames
        // use HandlerTargets=null and the CIL catch arm owns the
        // dispatch label.
        private static StackSwitchHandler[] TagsToHandlers(int[] tagIdxs)
        {
            var arr = new StackSwitchHandler[tagIdxs.Length];
            for (int i = 0; i < tagIdxs.Length; i++)
                arr[i] = new StackSwitchHandler(
                    (TagIdx)(uint)tagIdxs[i],
                    (LabelIdx)(uint)0,
                    onSwitch: false);
            return arr;
        }

        /// <summary>
        /// <c>cont.new $ct</c>: pop a function reference, allocate
        /// a Fresh continuation tied to that function, push a
        /// non-nullable continuation ref.
        /// </summary>
        public static Value ContNew(IContinuationContext hctx, int typeIdx, Value funcRef)
        {
            if (funcRef.IsNullRef)
                throw new TrapException("cont.new: null function reference.");

            var exec = hctx.ExecContext;
            ContInstance contInst;
            if (exec != null)
            {
                // Mixed mode: allocate via the runtime's Store so
                // interpreter and transpiled callers share state.
                var funcAddr = funcRef.GetFuncAddr(exec.Frame.Module.Types);
                if (!exec.Store.Contains(funcAddr))
                    throw new TrapException(
                        $"cont.new: function address {funcAddr} is not in the store.");
                contInst = exec.Store.AllocateContinuation((TypeIdx)typeIdx, funcAddr);
            }
            else
            {
                // Standalone: stash the delegate from the funcref
                // (set by RefFunc / call_indirect's table entry).
                var del = ExtractDelegateRefTarget(funcRef.GcRef);
                if (del == null)
                {
                    // Some standalone refs carry the funcidx in
                    // Data.Ptr and the delegate is reachable via
                    // FuncTable.
                    var ft = hctx.FuncTable;
                    long idx = funcRef.Data.Ptr;
                    if (idx >= 0 && idx < ft.Length) del = ft[idx];
                }
                if (del == null)
                    throw new TrapException(
                        "cont.new: standalone funcref has no resolvable delegate.");
                contInst = hctx.Continuations.Allocate((TypeIdx)typeIdx, del);
            }
            return new Value(ValType.ContRefNN, contInst);
        }

        /// <summary>
        /// <c>cont.bind $ct1 $ct2</c>: pop a Fresh source
        /// continuation and a prefix-args tuple, allocate a new
        /// continuation typed as $ct2 with the prefix args bound,
        /// mark the source Completed, push the new continuation.
        /// <paramref name="prefixArgs"/> must be in source-stack
        /// order (leftmost first); the emitter is responsible for
        /// packing the CIL stack values into the array in the
        /// right order.
        /// </summary>
        public static Value ContBind(
            IContinuationContext hctx, int targetTypeIdx,
            Value contRef, Value[] prefixArgs)
        {
            if (contRef.IsNullRef)
                throw new TrapException("cont.bind: null continuation reference.");
            var source = contRef.GcRef as ContInstance
                         ?? throw new TrapException(
                             "cont.bind: ref does not point to a continuation.");
            if (source.State != ContState.Fresh)
                throw new TrapException(
                    $"cont.bind: continuation is not fresh (state {source.State}).");

            var exec = hctx.ExecContext;
            ContInstance bound;
            if (exec != null && source.StandaloneDelegate == null)
            {
                bound = exec.Store.AllocateContinuation(
                    (TypeIdx)targetTypeIdx, source.Function);
            }
            else
            {
                // Standalone or mixed mode with a source that
                // came from a standalone allocation — keep the
                // delegate so future invocations route the same way.
                var store = hctx.Continuations;
                bound = source.StandaloneDelegate != null
                    ? store.Allocate((TypeIdx)targetTypeIdx, source.StandaloneDelegate)
                    : store.Allocate((TypeIdx)targetTypeIdx, source.Function);
            }
            bound.BoundArgs.AddRange(source.BoundArgs);
            bound.BoundArgs.AddRange(prefixArgs);
            source.State = ContState.Completed;
            return new Value(ValType.ContRefNN, bound);
        }

        /// <summary>
        /// <c>suspend $tag</c>: throw a SuspensionException
        /// carrying the tag's address and the payload values, in
        /// the order that the interpreter's PopResults would have
        /// produced (last-pushed first when iterating the
        /// returned Stack).
        /// </summary>
        public static void Suspend(IContinuationContext hctx, int tagIdxValue, Value[] payload)
        {
            var exec = hctx.ExecContext;
            TagAddr tagAddr;
            if (exec != null)
            {
                var tagIdx = (TagIdx)(uint)tagIdxValue;
                if (!exec.Frame.Module.TagAddrs.Contains(tagIdx))
                    throw new TrapException(
                        $"suspend: tag {tagIdx} not addressable in this frame's module.");
                tagAddr = exec.Frame.Module.TagAddrs[tagIdx];
                if (!exec.Store.Contains(tagAddr))
                    throw new TrapException(
                        $"suspend: tag address {tagAddr} is not in the store.");
            }
            else
            {
                // Standalone: synthesize a TagAddr from the tag
                // index so the catch arm can compare against a
                // similarly-synthesized value. The transpiled
                // catch in the same module sees the same idx
                // because no Store-renumbering happens between
                // throw and catch.
                tagAddr = new TagAddr(tagIdxValue);
            }

            // Build a stack of payload values matching the order
            // the interpreter would have left them after
            // PopResults (last pushed by guest = top of stack).
            var stack = new Stack<Value>();
            for (int i = 0; i < payload.Length; i++)
                stack.Push(payload[i]);
            throw new SuspensionException(tagAddr, stack);
        }

        /// <summary>
        /// <c>resume $ct handler*</c>: install the handlers as a
        /// transpiler-installed frame, invoke the continuation's
        /// inner function via the runtime, and on normal return
        /// pop the function's <c>t2*</c> results.
        ///
        /// <para>A <c>SuspensionException</c> raised during
        /// invocation is intercepted by
        /// <see cref="SuspensionDispatcher"/>; if the suspend's
        /// tag matches one of <paramref name="handlers"/>, the
        /// dispatcher unwinds the call stack to this resume's
        /// install depth, pops the handler frame, marks the cont
        /// Completed, and returns false — letting the CLR
        /// propagate the exception up to the caller's emitted
        /// try/catch where the actual branch to the wasm handler
        /// label is performed.</para>
        /// </summary>
        public static Value[] Resume(
            IContinuationContext hctx, int typeIdx,
            Value[] args, Value contRef,
            int[] handlerTagIdxs,
            StandaloneContInvoker? standaloneInvoker = null)
        {
            var exec = hctx.ExecContext;
            if (exec == null)
                return ResumeStandalone(hctx, contRef, args, standaloneInvoker);
            var ctx = exec;
            var handlers = TagsToHandlers(handlerTagIdxs);
            if (contRef.IsNullRef)
                throw new TrapException("resume: null continuation reference.");
            var cont = contRef.GcRef as ContInstance
                       ?? throw new TrapException(
                           "resume: ref does not point to a continuation.");
            if (cont.State != ContState.Fresh)
                throw new TrapException(
                    $"resume: continuation is not resumable (state {cont.State}).");

            // Push BoundArgs from any prior cont.bind, then the
            // caller-supplied args in order — the inner function
            // pops them as its parameters.
            foreach (var bound in cont.BoundArgs)
                ctx.OpStack.PushValue(bound);
            for (int i = 0; i < args.Length; i++)
                ctx.OpStack.PushValue(args[i]);

            if (!ctx.Store.Contains(cont.Function))
                throw new TrapException(
                    $"resume: function address {cont.Function} is not in the store.");
            var funcInst = ctx.Store[cont.Function];
            var ft = (funcInst.Type as FunctionType)
                     ?? throw new TrapException(
                         "resume: continuation inner func is not a FunctionType.");

            // HandlerTargets=null marks the frame as transpiler-
            // installed; SuspensionDispatcher.TryHandle will
            // unwind + return false rather than dispatch.
            var frame = new ResumeHandlerFrame(
                handlers, handlerTargets: null,
                installFrameDepth: ctx.StackHeight + 1,
                cont: cont);
            ctx.ActiveResumeHandlers.Push(frame);
            cont.State = ContState.Running;
            try
            {
                ctx.InvokeResolved(funcInst);
            }
            catch
            {
                if (ctx.ActiveResumeHandlers.Count > 0
                    && ReferenceEquals(ctx.ActiveResumeHandlers.Peek(), frame))
                    ctx.ActiveResumeHandlers.Pop();
                cont.State = ContState.Completed;
                throw;
            }

            cont.State = ContState.Completed;
            if (ctx.ActiveResumeHandlers.Count > 0
                && ReferenceEquals(ctx.ActiveResumeHandlers.Peek(), frame))
                ctx.ActiveResumeHandlers.Pop();

            // Pop t2* results from the opstack.
            int rArity = ft.ResultType.Arity;
            var results = new Value[rArity];
            for (int i = rArity - 1; i >= 0; i--)
                results[i] = ctx.OpStack.PopAny();
            return results;
        }

        /// <summary>
        /// <c>resume_throw $ct $tag handler*</c>: allocate an
        /// exception from the tag + payload values, install
        /// handlers as transpiler-installed, invoke the cont's
        /// function, and inject the exception at function entry
        /// via <c>InstThrowRef.ExecuteInstruction</c>. The exception
        /// unwinds the cont's frame and continues up through the
        /// caller's enclosing try chain.
        /// </summary>
        public static Value[] ResumeThrow(
            IContinuationContext hctx, int typeIdx, int tagIdxValue,
            Value[] excArgs, Value contRef,
            int[] handlerTagIdxs,
            StandaloneContInvoker? standaloneInvoker = null)
        {
            var exec = hctx.ExecContext;
            if (exec == null)
                return ResumeThrowStandalone(
                    hctx, tagIdxValue, excArgs, contRef, Array.Empty<Value>(),
                    standaloneInvoker);
            var ctx = exec;
            var handlers = TagsToHandlers(handlerTagIdxs);
            if (contRef.IsNullRef)
                throw new TrapException("resume_throw: null continuation reference.");
            var cont = contRef.GcRef as ContInstance
                       ?? throw new TrapException(
                           "resume_throw: ref does not point to a continuation.");
            if (cont.State != ContState.Fresh)
                throw new TrapException(
                    $"resume_throw: continuation is not resumable (state {cont.State}).");

            var tagIdx = (TagIdx)(uint)tagIdxValue;
            if (!ctx.Frame.Module.TagAddrs.Contains(tagIdx))
                throw new TrapException(
                    $"resume_throw: tag {tagIdx} not addressable in this frame's module.");
            var tagAddr = ctx.Frame.Module.TagAddrs[tagIdx];

            // Allocate the exn from the payload values.
            var fields = new Stack<Value>();
            for (int i = 0; i < excArgs.Length; i++)
                fields.Push(excArgs[i]);
            var exnAddr = ctx.Store.AllocateExn(tagAddr, fields);
            var exn = ctx.Store[exnAddr];

            foreach (var bound in cont.BoundArgs)
                ctx.OpStack.PushValue(bound);

            if (!ctx.Store.Contains(cont.Function))
                throw new TrapException(
                    $"resume_throw: function address {cont.Function} is not in the store.");
            var funcInst = ctx.Store[cont.Function];

            var frame = new ResumeHandlerFrame(
                handlers, handlerTargets: null,
                installFrameDepth: ctx.StackHeight + 1,
                cont: cont);
            ctx.ActiveResumeHandlers.Push(frame);
            cont.State = ContState.Running;
            try
            {
                ctx.InvokeResolved(funcInst);
            }
            catch
            {
                if (ctx.ActiveResumeHandlers.Count > 0
                    && ReferenceEquals(ctx.ActiveResumeHandlers.Peek(), frame))
                    ctx.ActiveResumeHandlers.Pop();
                cont.State = ContState.Completed;
                throw;
            }

            // Inject the exception inside the cont's frame and
            // run throw_ref's unwind. This always either
            // propagates the WasmException (caught upstream by a
            // try_table or surfacing as Unhandled) or hits a
            // catch — never returns normally on this path.
            ctx.OpStack.PushValue(new Value(ValType.Exn, exn));
            InstThrowRef.ExecuteInstruction(ctx);
            // Unreachable: ExecuteInstruction either branches to
            // a catch (control transferred) or throws.
            return Array.Empty<Value>();
        }

        /// <summary>
        /// Catch-arm helper: scan a SuspensionException's tag
        /// against the resume's tag-index list. Returns the
        /// matching handler index or -1 if none — the emitted CIL
        /// switches on the result, dispatching to the per-handler
        /// label or rethrowing.
        /// </summary>
        public static int FindHandlerMatch(
            IContinuationContext hctx, int[] handlerTagIdxs, SuspensionException ex)
        {
            var exec = hctx.ExecContext;
            if (exec == null)
            {
                // Standalone path: tag identity = raw int value
                // synthesized in Suspend. ex.Tag.Value matches the
                // handler's tag idx directly.
                for (int i = 0; i < handlerTagIdxs.Length; i++)
                    if ((int)ex.Tag.Value == handlerTagIdxs[i]) return i;
                return -1;
            }
            var ctx = exec;
            for (int i = 0; i < handlerTagIdxs.Length; i++)
            {
                var ti = (TagIdx)(uint)handlerTagIdxs[i];
                if (!ctx.Frame.Module.TagAddrs.Contains(ti)) continue;
                var ta = ctx.Frame.Module.TagAddrs[ti];
                if (ta.Equals(ex.Tag)) return i;
            }
            return -1;
        }

        /// <summary>
        /// Catch-arm helper: allocate the one-shot reified
        /// continuation placeholder and return it together with
        /// the suspend's payload values. The returned array's
        /// layout is <c>[payload0, payload1, …, reifiedCont]</c>
        /// — the emitted CIL unbox-fans the payload values to
        /// the CIL stack per tag's param types and pushes the
        /// reified cont as the trailing slot.
        /// </summary>
        public static Value[] ReifyHandlerArgs(
            IContinuationContext hctx, Value contRef, SuspensionException ex)
        {
            var exec = hctx.ExecContext;
            if (exec == null)
                throw new NotSupportedException(StandaloneInvokeUnsupported);
            var ctx = exec;
            var cont = contRef.GcRef as ContInstance
                       ?? throw new TrapException(
                           "reify: ref does not point to a continuation.");
            var dead = ctx.Store.AllocateContinuation(
                cont.ContTypeIndex, cont.Function);
            dead.State = ContState.Completed;

            // Payload was pushed onto SuspensionException's Stack
            // in source order; popping gives reverse order. Build
            // the array in source order (matching what the wasm
            // handler label expects to arrive in).
            int n = ex.Payload.Count;
            var arr = new Value[n + 1];
            // Snapshot to an array since we mutate the stack.
            var snapshot = ex.Payload.ToArray();
            // Stack.ToArray() returns top-first, but the source
            // order for a handler arrival is bottom-first — reverse.
            for (int i = 0; i < n; i++)
                arr[i] = snapshot[n - 1 - i];
            arr[n] = new Value(ValType.ContRefNN, dead);
            return arr;
        }

        /// <summary>
        /// <c>switch $ct $tag</c>: symmetric switch. Pop the
        /// target continuation, reify the current computation as
        /// a one-shot Completed placeholder, push args + the
        /// placeholder onto the opstack, invoke the target's
        /// function via the runtime. Switch does NOT install a
        /// new handler frame; suspends inside the switched-to
        /// cont continue up through whatever handler chain is
        /// already in scope.
        /// </summary>
        public static Value[] Switch(
            IContinuationContext hctx, int typeIdx, int tagIdxValue,
            Value[] args, Value contRef,
            StandaloneContInvoker? standaloneInvoker = null)
        {
            var exec = hctx.ExecContext;
            if (exec == null)
                return SwitchStandalone(hctx, contRef, args, standaloneInvoker);
            var ctx = exec;
            if (contRef.IsNullRef)
                throw new TrapException("switch: null continuation reference.");
            var target = contRef.GcRef as ContInstance
                         ?? throw new TrapException(
                             "switch: ref does not point to a continuation.");
            if (target.State != ContState.Fresh)
                throw new TrapException(
                    $"switch: continuation is not resumable (state {target.State}).");

            // One-shot reified self.
            var placeholder = ctx.Store.AllocateContinuation(
                target.ContTypeIndex, target.Function);
            placeholder.State = ContState.Completed;

            foreach (var bound in target.BoundArgs)
                ctx.OpStack.PushValue(bound);
            for (int i = 0; i < args.Length; i++)
                ctx.OpStack.PushValue(args[i]);
            ctx.OpStack.PushValue(new Value(ValType.ContRefNN, placeholder));

            if (!ctx.Store.Contains(target.Function))
                throw new TrapException(
                    $"switch: function address {target.Function} is not in the store.");
            var funcInst = ctx.Store[target.Function];
            var ft = (funcInst.Type as FunctionType)
                     ?? throw new TrapException(
                         "switch: continuation inner func is not a FunctionType.");

            target.State = ContState.Running;
            try
            {
                ctx.InvokeResolved(funcInst);
            }
            catch
            {
                target.State = ContState.Completed;
                throw;
            }
            target.State = ContState.Completed;

            int rArity = ft.ResultType.Arity;
            var results = new Value[rArity];
            for (int i = rArity - 1; i >= 0; i--)
                results[i] = ctx.OpStack.PopAny();
            return results;
        }
    }
}
