// <auto-generated> from NATIVE_CONTEXT_FIELDS in src/objects/contexts.h by gen_ctx.py.
// Includes the V8_TEMPORAL_SUPPORT fields (NATIVE_CONTEXT_FIELDS_TEMPORAL, at the end of the list).
#nullable enable
namespace V8Sharp.Objects;

public partial class Context
{
    /// <summary>Context::Field: the slot indices shared by every context and those of the native context.</summary>
    public enum Field
    {
        SCOPE_INFO_INDEX,
        PREVIOUS_INDEX,
        EXTENSION_INDEX,
        GLOBAL_PROXY_INDEX,
        EMBEDDER_DATA_INDEX,
        CONTINUATION_PRESERVED_EMBEDDER_DATA_INDEX,
        GENERATOR_NEXT_INTERNAL,
        ASYNC_MODULE_EVALUATE_INTERNAL,
        REFLECT_APPLY_INDEX,
        REFLECT_CONSTRUCT_INDEX,
        PERFORM_PROMISE_THEN_INDEX,
        PROMISE_THEN_INDEX,
        PROMISE_RESOLVE_INDEX,
        FUNCTION_PROTOTYPE_APPLY_INDEX,
        UINT8_ARRAY_FUN_INDEX,
        INT8_ARRAY_FUN_INDEX,
        UINT16_ARRAY_FUN_INDEX,
        INT16_ARRAY_FUN_INDEX,
        UINT32_ARRAY_FUN_INDEX,
        INT32_ARRAY_FUN_INDEX,
        BIGUINT64_ARRAY_FUN_INDEX,
        BIGINT64_ARRAY_FUN_INDEX,
        UINT8_CLAMPED_ARRAY_FUN_INDEX,
        FLOAT32_ARRAY_FUN_INDEX,
        FLOAT64_ARRAY_FUN_INDEX,
        FLOAT16_ARRAY_FUN_INDEX,
        RAB_GSAB_UINT8_ARRAY_MAP_INDEX,
        RAB_GSAB_INT8_ARRAY_MAP_INDEX,
        RAB_GSAB_UINT16_ARRAY_MAP_INDEX,
        RAB_GSAB_INT16_ARRAY_MAP_INDEX,
        RAB_GSAB_UINT32_ARRAY_MAP_INDEX,
        RAB_GSAB_INT32_ARRAY_MAP_INDEX,
        RAB_GSAB_BIGUINT64_ARRAY_MAP_INDEX,
        RAB_GSAB_BIGINT64_ARRAY_MAP_INDEX,
        RAB_GSAB_UINT8_CLAMPED_ARRAY_MAP_INDEX,
        RAB_GSAB_FLOAT32_ARRAY_MAP_INDEX,
        RAB_GSAB_FLOAT64_ARRAY_MAP_INDEX,
        RAB_GSAB_FLOAT16_ARRAY_MAP_INDEX,
        ABSTRACT_MODULE_SOURCE_FUNCTION_INDEX,
        ABSTRACT_MODULE_SOURCE_PROTOTYPE_INDEX,
        ACCESSOR_PROPERTY_DESCRIPTOR_MAP_INDEX,
        ALLOW_CODE_GEN_FROM_STRINGS_INDEX,
        ARRAY_BUFFER_FUN_INDEX,
        ARRAY_BUFFER_MAP_INDEX,
        ARRAY_BUFFER_NOINIT_FUN_INDEX,
        ARRAY_FUNCTION_INDEX,
        ARRAY_JOIN_STACK_INDEX,
        ARRAY_FROM_ASYNC_INDEX,
        ASYNC_FROM_SYNC_ITERATOR_MAP_INDEX,
        ASYNC_FUNCTION_FUNCTION_INDEX,
        ASYNC_FUNCTION_OBJECT_MAP_INDEX,
        ASYNC_GENERATOR_FUNCTION_FUNCTION_INDEX,
        BIGINT_FUNCTION_INDEX,
        BOOLEAN_FUNCTION_INDEX,
        BOUND_FUNCTION_WITH_CONSTRUCTOR_MAP_INDEX,
        BOUND_FUNCTION_WITHOUT_CONSTRUCTOR_MAP_INDEX,
        CALL_AS_CONSTRUCTOR_DELEGATE_INDEX,
        CALL_AS_FUNCTION_DELEGATE_INDEX,
        CALLSITE_FUNCTION_INDEX,
        CONTEXT_EXTENSION_FUNCTION_INDEX,
        DATA_PROPERTY_DESCRIPTOR_MAP_INDEX,
        DATA_VIEW_FUN_INDEX,
        DATE_FUNCTION_INDEX,
        DEBUG_CONTEXT_ID_INDEX,
        EMPTY_FUNCTION_INDEX,
        ERROR_MESSAGE_FOR_CODE_GEN_FROM_STRINGS_INDEX,
        ERROR_MESSAGE_FOR_WASM_CODE_GEN_INDEX,
        ERRORS_THROWN_INDEX,
        EXTRAS_BINDING_OBJECT_INDEX,
        FAST_ALIASED_ARGUMENTS_MAP_INDEX,
        FAST_TEMPLATE_INSTANTIATIONS_CACHE_INDEX,
        FUNCTION_FUNCTION_INDEX,
        FUNCTION_PROTOTYPE_INDEX,
        GENERATOR_FUNCTION_FUNCTION_INDEX,
        GENERATOR_OBJECT_PROTOTYPE_MAP_INDEX,
        ASYNC_GENERATOR_OBJECT_PROTOTYPE_MAP_INDEX,
        INITIAL_ARRAY_ITERATOR_MAP_INDEX,
        INITIAL_ARRAY_ITERATOR_PROTOTYPE_INDEX,
        INITIAL_ARRAY_PROTOTYPE_INDEX,
        INITIAL_ERROR_PROTOTYPE_INDEX,
        INITIAL_GENERATOR_PROTOTYPE_INDEX,
        INITIAL_ASYNC_ITERATOR_PROTOTYPE_INDEX,
        INITIAL_ASYNC_GENERATOR_PROTOTYPE_INDEX,
        INITIAL_ITERATOR_FUNCTION_INDEX,
        INITIAL_ITERATOR_HELPER_PROTOTYPE_INDEX,
        INITIAL_ITERATOR_PROTOTYPE_INDEX,
        INITIAL_DISPOSABLE_STACK_PROTOTYPE_INDEX,
        INITIAL_MAP_ITERATOR_PROTOTYPE_INDEX,
        INITIAL_MAP_PROTOTYPE_MAP_INDEX,
        INITIAL_OBJECT_PROTOTYPE_INDEX,
        INITIAL_SET_ITERATOR_PROTOTYPE_INDEX,
        INITIAL_SET_PROTOTYPE_INDEX,
        INITIAL_SET_PROTOTYPE_MAP_INDEX,
        INITIAL_STRING_ITERATOR_MAP_INDEX,
        INITIAL_STRING_ITERATOR_PROTOTYPE_INDEX,
        INITIAL_STRING_PROTOTYPE_INDEX,
        INITIAL_WEAKMAP_PROTOTYPE_MAP_INDEX,
        INITIAL_WEAKSET_PROTOTYPE_MAP_INDEX,
        INTL_COLLATOR_FUNCTION_INDEX,
        INTL_DATE_TIME_FORMAT_FUNCTION_INDEX,
        INTL_DISPLAY_NAMES_FUNCTION_INDEX,
        INTL_DURATION_FORMAT_FUNCTION_INDEX,
        INTL_NUMBER_FORMAT_FUNCTION_INDEX,
        INTL_LOCALE_FUNCTION_INDEX,
        INTL_LIST_FORMAT_FUNCTION_INDEX,
        INTL_PLURAL_RULES_FUNCTION_INDEX,
        INTL_RELATIVE_TIME_FORMAT_FUNCTION_INDEX,
        INTL_SEGMENTER_FUNCTION_INDEX,
        INTL_SEGMENTS_MAP_INDEX,
        INTL_SEGMENT_DATA_OBJECT_MAP_INDEX,
        INTL_SEGMENT_DATA_OBJECT_WORDLIKE_MAP_INDEX,
        INTL_SEGMENT_ITERATOR_MAP_INDEX,
        ITERATOR_FILTER_HELPER_MAP_INDEX,
        ITERATOR_MAP_HELPER_MAP_INDEX,
        ITERATOR_TAKE_HELPER_MAP_INDEX,
        ITERATOR_DROP_HELPER_MAP_INDEX,
        ITERATOR_FLAT_MAP_HELPER_MAP_INDEX,
        ITERATOR_CONCAT_HELPER_MAP_INDEX,
        ITERATOR_ZIP_HELPER_MAP_INDEX,
        ITERATOR_ZIP_KEYED_HELPER_MAP_INDEX,
        ITERATOR_FUNCTION_INDEX,
        VALID_ITERATOR_WRAPPER_MAP_INDEX,
        ITERATOR_RESULT_MAP_INDEX,
        JS_ARRAY_PACKED_SMI_ELEMENTS_MAP_INDEX,
        JS_ARRAY_HOLEY_SMI_ELEMENTS_MAP_INDEX,
        JS_ARRAY_PACKED_ELEMENTS_MAP_INDEX,
        JS_ARRAY_HOLEY_ELEMENTS_MAP_INDEX,
        JS_ARRAY_PACKED_DOUBLE_ELEMENTS_MAP_INDEX,
        JS_ARRAY_HOLEY_DOUBLE_ELEMENTS_MAP_INDEX,
        JS_ARRAY_TEMPLATE_LITERAL_OBJECT_MAP,
        JS_DISPOSABLE_STACK_FUNCTION_INDEX,
        JS_ASYNC_DISPOSABLE_STACK_FUNCTION_INDEX,
        JS_DISPOSABLE_STACK_MAP_INDEX,
        JS_MAP_FUN_INDEX,
        JS_MAP_MAP_INDEX,
        JS_MODULE_NAMESPACE_MAP,
        JS_DEFERRED_MODULE_NAMESPACE_MAP,
        JS_RAW_JSON_MAP,
        JS_SET_FUN_INDEX,
        JS_SET_MAP_INDEX,
        JS_WEAK_MAP_FUN_INDEX,
        JS_WEAK_SET_FUN_INDEX,
        JS_WEAK_REF_FUNCTION_INDEX,
        JS_FINALIZATION_REGISTRY_FUNCTION_INDEX,
        JSON_OBJECT,
        PROMISE_WITHRESOLVERS_RESULT_MAP_INDEX,
        META_MAP_INDEX,
        FUNCTION_CONTEXT_MAP_INDEX,
        MODULE_CONTEXT_MAP_INDEX,
        EVAL_CONTEXT_MAP_INDEX,
        SCRIPT_CONTEXT_MAP_INDEX,
        AWAIT_CONTEXT_MAP_INDEX,
        BLOCK_CONTEXT_MAP_INDEX,
        CATCH_CONTEXT_MAP_INDEX,
        WITH_CONTEXT_MAP_INDEX,
        DEBUG_EVALUATE_CONTEXT_MAP_INDEX,
        JS_RAB_GSAB_DATA_VIEW_MAP_INDEX,
        MAP_CACHE_INDEX,
        MAP_KEY_ITERATOR_MAP_INDEX,
        MAP_KEY_VALUE_ITERATOR_MAP_INDEX,
        MAP_VALUE_ITERATOR_MAP_INDEX,
        MATH_RANDOM_INDEX_INDEX,
        MATH_RANDOM_STATE_INDEX,
        MATH_RANDOM_CACHE_INDEX,
        NORMALIZED_MAP_CACHE_INDEX,
        NUMBER_FUNCTION_INDEX,
        OBJECT_FUNCTION_INDEX,
        OBJECT_FUNCTION_PROTOTYPE_INDEX,
        OBJECT_FUNCTION_PROTOTYPE_MAP_INDEX,
        PROMISE_HOOK_INIT_FUNCTION_INDEX,
        PROMISE_HOOK_BEFORE_FUNCTION_INDEX,
        PROMISE_HOOK_AFTER_FUNCTION_INDEX,
        PROMISE_HOOK_RESOLVE_FUNCTION_INDEX,
        PROXY_CALLABLE_MAP_INDEX,
        PROXY_CONSTRUCTOR_MAP_INDEX,
        PROXY_FUNCTION_INDEX,
        PROXY_MAP_INDEX,
        PROXY_REVOCABLE_RESULT_MAP_INDEX,
        PROMISE_PROTOTYPE_INDEX,
        RECORDER_CONTEXT_ID,
        REGEXP_EXEC_FUNCTION_INDEX,
        REGEXP_FUNCTION_INDEX,
        REGEXP_LAST_MATCH_INFO_INDEX,
        REGEXP_MATCH_ALL_FUNCTION_INDEX,
        REGEXP_MATCH_FUNCTION_INDEX,
        REGEXP_PROTOTYPE_INDEX,
        REGEXP_PROTOTYPE_MAP_INDEX,
        REGEXP_REPLACE_FUNCTION_INDEX,
        REGEXP_RESULT_MAP_INDEX,
        REGEXP_RESULT_WITH_INDICES_MAP_INDEX,
        REGEXP_RESULT_INDICES_MAP_INDEX,
        REGEXP_SEARCH_FUNCTION_INDEX,
        REGEXP_SPLIT_FUNCTION_INDEX,
        INITIAL_REGEXP_STRING_ITERATOR_PROTOTYPE_MAP_INDEX,
        SCRIPT_CONTEXT_TABLE_INDEX,
        SCRIPT_EXECUTION_CALLBACK_INDEX,
        TEMPORAL_GET_EPOCH_NANOSECONDS_CALLBACK_INDEX,
        SECURITY_TOKEN_INDEX,
        SERIALIZED_OBJECTS,
        SET_VALUE_ITERATOR_MAP_INDEX,
        SET_KEY_VALUE_ITERATOR_MAP_INDEX,
        SHARED_ARRAY_BUFFER_FUN_INDEX,
        SLOPPY_ARGUMENTS_MAP_INDEX,
        SLOW_ALIASED_ARGUMENTS_MAP_INDEX,
        STRICT_ARGUMENTS_MAP_INDEX,
        SLOW_OBJECT_WITH_NULL_PROTOTYPE_MAP,
        SLOW_OBJECT_WITH_OBJECT_PROTOTYPE_MAP,
        SLOW_TEMPLATE_INSTANTIATIONS_CACHE_INDEX,
        ATOMICS_WAITASYNC_PROMISES,
        SET_UINT8_ARRAY_RESULT_MAP,
        WASM_DEBUG_MAPS,
        INITIAL_ARRAY_PROTOTYPE_VALIDITY_CELL_INDEX,
        SLOPPY_FUNCTION_MAP_INDEX,
        SLOPPY_FUNCTION_WITH_NAME_MAP_INDEX,
        SLOPPY_FUNCTION_WITHOUT_PROTOTYPE_MAP_INDEX,
        SLOPPY_FUNCTION_WITH_READONLY_PROTOTYPE_MAP_INDEX,
        STRICT_FUNCTION_MAP_INDEX,
        STRICT_FUNCTION_WITH_NAME_MAP_INDEX,
        STRICT_FUNCTION_WITH_READONLY_PROTOTYPE_MAP_INDEX,
        STRICT_FUNCTION_WITHOUT_PROTOTYPE_MAP_INDEX,
        METHOD_WITH_NAME_MAP_INDEX,
        ASYNC_FUNCTION_MAP_INDEX,
        ASYNC_FUNCTION_WITH_NAME_MAP_INDEX,
        GENERATOR_FUNCTION_MAP_INDEX,
        GENERATOR_FUNCTION_WITH_NAME_MAP_INDEX,
        ASYNC_GENERATOR_FUNCTION_MAP_INDEX,
        ASYNC_GENERATOR_FUNCTION_WITH_NAME_MAP_INDEX,
        CLASS_FUNCTION_MAP_INDEX,
        STRING_FUNCTION_INDEX,
        STRING_FUNCTION_PROTOTYPE_MAP_INDEX,
        SYMBOL_FUNCTION_INDEX,
        IS_WASM_JS_INSTALLED_INDEX,
        IS_WASM_JSPI_INSTALLED_INDEX,
        WASM_WEBASSEMBLY_OBJECT_INDEX,
        WASM_EXPORTED_FUNCTION_MAP_INDEX,
        WASM_TAG_CONSTRUCTOR_INDEX,
        WASM_EXCEPTION_CONSTRUCTOR_INDEX,
        WASM_GLOBAL_CONSTRUCTOR_INDEX,
        WASM_INSTANCE_CONSTRUCTOR_INDEX,
        WASM_JS_TAG_INDEX,
        WASM_MEMORY_CONSTRUCTOR_INDEX,
        WASM_MODULE_CONSTRUCTOR_INDEX,
        WASM_TABLE_CONSTRUCTOR_INDEX,
        WASM_SUSPENDING_CONSTRUCTOR_INDEX,
        WASM_SUSPENDER_CONSTRUCTOR_INDEX,
        WASM_SUSPENDING_MAP,
        WASM_SUSPENDING_PROTOTYPE,
        WASM_MEMORY_MAP_DESCRIPTOR_TEMPLATE_INDEX,
        WASM_MEMORY_MAP_DESCRIPTOR_CONSTRUCTOR_INDEX,
        TEMPLATE_WEAKMAP_INDEX,
        TYPED_ARRAY_FUN_INDEX,
        TYPED_ARRAY_PROTOTYPE_INDEX,
        ARRAY_ENTRIES_ITERATOR_INDEX,
        ARRAY_FOR_EACH_ITERATOR_INDEX,
        ARRAY_KEYS_ITERATOR_INDEX,
        ARRAY_VALUES_ITERATOR_INDEX,
        ERROR_FUNCTION_INDEX,
        ERROR_TO_STRING,
        EVAL_ERROR_FUNCTION_INDEX,
        AGGREGATE_ERROR_FUNCTION_INDEX,
        GLOBAL_EVAL_FUN_INDEX,
        GLOBAL_PARSE_FLOAT_FUN_INDEX,
        GLOBAL_PARSE_INT_FUN_INDEX,
        GLOBAL_PROXY_FUNCTION_INDEX,
        MAP_DELETE_INDEX,
        MAP_GET_INDEX,
        MAP_HAS_INDEX,
        MAP_SET_INDEX,
        FUNCTION_HAS_INSTANCE_INDEX,
        FUNCTION_TO_STRING_INDEX,
        OBJECT_TO_STRING,
        OBJECT_VALUE_OF_FUNCTION_INDEX,
        PROMISE_ALL_INDEX,
        PROMISE_ALL_SETTLED_INDEX,
        PROMISE_ANY_INDEX,
        PROMISE_FUNCTION_INDEX,
        RANGE_ERROR_FUNCTION_INDEX,
        REFERENCE_ERROR_FUNCTION_INDEX,
        SET_ADD_INDEX,
        SET_DELETE_INDEX,
        SET_HAS_INDEX,
        SHADOW_REALM_IMPORT_VALUE_REJECTED_INDEX,
        SUPPRESSED_ERROR_FUNCTION_INDEX,
        SYNTAX_ERROR_FUNCTION_INDEX,
        TYPE_ERROR_FUNCTION_INDEX,
        URI_ERROR_FUNCTION_INDEX,
        WASM_COMPILE_ERROR_FUNCTION_INDEX,
        WASM_LINK_ERROR_FUNCTION_INDEX,
        WASM_SUSPEND_ERROR_FUNCTION_INDEX,
        WASM_RUNTIME_ERROR_FUNCTION_INDEX,
        WEAKMAP_SET_INDEX,
        WEAKMAP_GET_INDEX,
        WEAKMAP_DELETE_INDEX,
        WEAKSET_ADD_INDEX,
        WRAPPED_FUNCTION_MAP_INDEX,
        RETAINED_MAPS,
        SHARED_SPACE_JS_OBJECT_HAS_INSTANCE_INDEX,
        JS_TEMPORAL_DURATION_FUNCTION_INDEX,
        JS_TEMPORAL_INSTANT_FUNCTION_INDEX,
        JS_TEMPORAL_PLAIN_DATE_FUNCTION_INDEX,
        JS_TEMPORAL_PLAIN_DATE_TIME_FUNCTION_INDEX,
        JS_TEMPORAL_PLAIN_MONTH_DAY_FUNCTION_INDEX,
        JS_TEMPORAL_PLAIN_TIME_FUNCTION_INDEX,
        JS_TEMPORAL_PLAIN_YEAR_MONTH_FUNCTION_INDEX,
        JS_TEMPORAL_TIME_ZONE_FUNCTION_INDEX,
        JS_TEMPORAL_ZONED_DATE_TIME_FUNCTION_INDEX,
        TEMPORAL_OBJECT_INDEX,
        NEXT_CONTEXT_LINK,
        NATIVE_CONTEXT_SLOTS,
        FIRST_WEAK_SLOT = NEXT_CONTEXT_LINK,
        FIRST_JS_ARRAY_MAP_SLOT = JS_ARRAY_PACKED_SMI_ELEMENTS_MAP_INDEX,
        MIN_CONTEXT_SLOTS = EXTENSION_INDEX,
        MIN_CONTEXT_EXTENDED_SLOTS = EXTENSION_INDEX + 1,
        THROWN_OBJECT_INDEX = MIN_CONTEXT_SLOTS,
        WRAPPED_CONTEXT_INDEX = MIN_CONTEXT_EXTENDED_SLOTS,
    }
}

public sealed partial class NativeContext
{
    public JSGlobalProxy GlobalProxyObject { get => Slots[(int)Field.GLOBAL_PROXY_INDEX].As<JSGlobalProxy>(); set => Slots[(int)Field.GLOBAL_PROXY_INDEX] = value; }
    public JSValue EmbedderData { get => Slots[(int)Field.EMBEDDER_DATA_INDEX]; set => Slots[(int)Field.EMBEDDER_DATA_INDEX] = value; }
    public JSValue ContinuationPreservedEmbedderData { get => Slots[(int)Field.CONTINUATION_PRESERVED_EMBEDDER_DATA_INDEX]; set => Slots[(int)Field.CONTINUATION_PRESERVED_EMBEDDER_DATA_INDEX] = value; }
    public JSFunction GeneratorNextInternal { get => Slots[(int)Field.GENERATOR_NEXT_INTERNAL].As<JSFunction>(); set => Slots[(int)Field.GENERATOR_NEXT_INTERNAL] = value; }
    public JSFunction AsyncModuleEvaluateInternal { get => Slots[(int)Field.ASYNC_MODULE_EVALUATE_INTERNAL].As<JSFunction>(); set => Slots[(int)Field.ASYNC_MODULE_EVALUATE_INTERNAL] = value; }
    public JSFunction ReflectApply { get => Slots[(int)Field.REFLECT_APPLY_INDEX].As<JSFunction>(); set => Slots[(int)Field.REFLECT_APPLY_INDEX] = value; }
    public JSFunction ReflectConstruct { get => Slots[(int)Field.REFLECT_CONSTRUCT_INDEX].As<JSFunction>(); set => Slots[(int)Field.REFLECT_CONSTRUCT_INDEX] = value; }
    public JSFunction PerformPromiseThen { get => Slots[(int)Field.PERFORM_PROMISE_THEN_INDEX].As<JSFunction>(); set => Slots[(int)Field.PERFORM_PROMISE_THEN_INDEX] = value; }
    public JSFunction PromiseThen { get => Slots[(int)Field.PROMISE_THEN_INDEX].As<JSFunction>(); set => Slots[(int)Field.PROMISE_THEN_INDEX] = value; }
    public JSFunction PromiseResolve { get => Slots[(int)Field.PROMISE_RESOLVE_INDEX].As<JSFunction>(); set => Slots[(int)Field.PROMISE_RESOLVE_INDEX] = value; }
    public JSFunction FunctionPrototypeApply { get => Slots[(int)Field.FUNCTION_PROTOTYPE_APPLY_INDEX].As<JSFunction>(); set => Slots[(int)Field.FUNCTION_PROTOTYPE_APPLY_INDEX] = value; }
    public JSFunction Uint8ArrayFun { get => Slots[(int)Field.UINT8_ARRAY_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.UINT8_ARRAY_FUN_INDEX] = value; }
    public JSFunction Int8ArrayFun { get => Slots[(int)Field.INT8_ARRAY_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.INT8_ARRAY_FUN_INDEX] = value; }
    public JSFunction Uint16ArrayFun { get => Slots[(int)Field.UINT16_ARRAY_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.UINT16_ARRAY_FUN_INDEX] = value; }
    public JSFunction Int16ArrayFun { get => Slots[(int)Field.INT16_ARRAY_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.INT16_ARRAY_FUN_INDEX] = value; }
    public JSFunction Uint32ArrayFun { get => Slots[(int)Field.UINT32_ARRAY_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.UINT32_ARRAY_FUN_INDEX] = value; }
    public JSFunction Int32ArrayFun { get => Slots[(int)Field.INT32_ARRAY_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.INT32_ARRAY_FUN_INDEX] = value; }
    public JSFunction BigUint64ArrayFun { get => Slots[(int)Field.BIGUINT64_ARRAY_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.BIGUINT64_ARRAY_FUN_INDEX] = value; }
    public JSFunction BigInt64ArrayFun { get => Slots[(int)Field.BIGINT64_ARRAY_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.BIGINT64_ARRAY_FUN_INDEX] = value; }
    public JSFunction Uint8ClampedArrayFun { get => Slots[(int)Field.UINT8_CLAMPED_ARRAY_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.UINT8_CLAMPED_ARRAY_FUN_INDEX] = value; }
    public JSFunction Float32ArrayFun { get => Slots[(int)Field.FLOAT32_ARRAY_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.FLOAT32_ARRAY_FUN_INDEX] = value; }
    public JSFunction Float64ArrayFun { get => Slots[(int)Field.FLOAT64_ARRAY_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.FLOAT64_ARRAY_FUN_INDEX] = value; }
    public JSFunction Float16ArrayFun { get => Slots[(int)Field.FLOAT16_ARRAY_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.FLOAT16_ARRAY_FUN_INDEX] = value; }
    public Map RabGsabUint8ArrayMap { get => Slots[(int)Field.RAB_GSAB_UINT8_ARRAY_MAP_INDEX].As<Map>(); set => Slots[(int)Field.RAB_GSAB_UINT8_ARRAY_MAP_INDEX] = value; }
    public Map RabGsabInt8ArrayMap { get => Slots[(int)Field.RAB_GSAB_INT8_ARRAY_MAP_INDEX].As<Map>(); set => Slots[(int)Field.RAB_GSAB_INT8_ARRAY_MAP_INDEX] = value; }
    public Map RabGsabUint16ArrayMap { get => Slots[(int)Field.RAB_GSAB_UINT16_ARRAY_MAP_INDEX].As<Map>(); set => Slots[(int)Field.RAB_GSAB_UINT16_ARRAY_MAP_INDEX] = value; }
    public Map RabGsabInt16ArrayMap { get => Slots[(int)Field.RAB_GSAB_INT16_ARRAY_MAP_INDEX].As<Map>(); set => Slots[(int)Field.RAB_GSAB_INT16_ARRAY_MAP_INDEX] = value; }
    public Map RabGsabUint32ArrayMap { get => Slots[(int)Field.RAB_GSAB_UINT32_ARRAY_MAP_INDEX].As<Map>(); set => Slots[(int)Field.RAB_GSAB_UINT32_ARRAY_MAP_INDEX] = value; }
    public Map RabGsabInt32ArrayMap { get => Slots[(int)Field.RAB_GSAB_INT32_ARRAY_MAP_INDEX].As<Map>(); set => Slots[(int)Field.RAB_GSAB_INT32_ARRAY_MAP_INDEX] = value; }
    public Map RabGsabBigUint64ArrayMap { get => Slots[(int)Field.RAB_GSAB_BIGUINT64_ARRAY_MAP_INDEX].As<Map>(); set => Slots[(int)Field.RAB_GSAB_BIGUINT64_ARRAY_MAP_INDEX] = value; }
    public Map RabGsabBigInt64ArrayMap { get => Slots[(int)Field.RAB_GSAB_BIGINT64_ARRAY_MAP_INDEX].As<Map>(); set => Slots[(int)Field.RAB_GSAB_BIGINT64_ARRAY_MAP_INDEX] = value; }
    public Map RabGsabUint8ClampedArrayMap { get => Slots[(int)Field.RAB_GSAB_UINT8_CLAMPED_ARRAY_MAP_INDEX].As<Map>(); set => Slots[(int)Field.RAB_GSAB_UINT8_CLAMPED_ARRAY_MAP_INDEX] = value; }
    public Map RabGsabFloat32ArrayMap { get => Slots[(int)Field.RAB_GSAB_FLOAT32_ARRAY_MAP_INDEX].As<Map>(); set => Slots[(int)Field.RAB_GSAB_FLOAT32_ARRAY_MAP_INDEX] = value; }
    public Map RabGsabFloat64ArrayMap { get => Slots[(int)Field.RAB_GSAB_FLOAT64_ARRAY_MAP_INDEX].As<Map>(); set => Slots[(int)Field.RAB_GSAB_FLOAT64_ARRAY_MAP_INDEX] = value; }
    public Map RabGsabFloat16ArrayMap { get => Slots[(int)Field.RAB_GSAB_FLOAT16_ARRAY_MAP_INDEX].As<Map>(); set => Slots[(int)Field.RAB_GSAB_FLOAT16_ARRAY_MAP_INDEX] = value; }
    public JSFunction AbstractModuleSourceFunction { get => Slots[(int)Field.ABSTRACT_MODULE_SOURCE_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.ABSTRACT_MODULE_SOURCE_FUNCTION_INDEX] = value; }
    public JSObject AbstractModuleSourcePrototype { get => Slots[(int)Field.ABSTRACT_MODULE_SOURCE_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.ABSTRACT_MODULE_SOURCE_PROTOTYPE_INDEX] = value; }
    public Map AccessorPropertyDescriptorMap { get => Slots[(int)Field.ACCESSOR_PROPERTY_DESCRIPTOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ACCESSOR_PROPERTY_DESCRIPTOR_MAP_INDEX] = value; }
    public JSValue AllowCodeGenFromStrings { get => Slots[(int)Field.ALLOW_CODE_GEN_FROM_STRINGS_INDEX]; set => Slots[(int)Field.ALLOW_CODE_GEN_FROM_STRINGS_INDEX] = value; }
    public JSFunction ArrayBufferFun { get => Slots[(int)Field.ARRAY_BUFFER_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.ARRAY_BUFFER_FUN_INDEX] = value; }
    public Map ArrayBufferMap { get => Slots[(int)Field.ARRAY_BUFFER_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ARRAY_BUFFER_MAP_INDEX] = value; }
    public JSFunction ArrayBufferNoinitFun { get => Slots[(int)Field.ARRAY_BUFFER_NOINIT_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.ARRAY_BUFFER_NOINIT_FUN_INDEX] = value; }
    public JSFunction ArrayFunction { get => Slots[(int)Field.ARRAY_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.ARRAY_FUNCTION_INDEX] = value; }
    public JSValue ArrayJoinStack { get => Slots[(int)Field.ARRAY_JOIN_STACK_INDEX]; set => Slots[(int)Field.ARRAY_JOIN_STACK_INDEX] = value; }
    public JSFunction FromAsync { get => Slots[(int)Field.ARRAY_FROM_ASYNC_INDEX].As<JSFunction>(); set => Slots[(int)Field.ARRAY_FROM_ASYNC_INDEX] = value; }
    public Map AsyncFromSyncIteratorMap { get => Slots[(int)Field.ASYNC_FROM_SYNC_ITERATOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ASYNC_FROM_SYNC_ITERATOR_MAP_INDEX] = value; }
    public JSFunction AsyncFunctionConstructor { get => Slots[(int)Field.ASYNC_FUNCTION_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.ASYNC_FUNCTION_FUNCTION_INDEX] = value; }
    public Map AsyncFunctionObjectMap { get => Slots[(int)Field.ASYNC_FUNCTION_OBJECT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ASYNC_FUNCTION_OBJECT_MAP_INDEX] = value; }
    public JSFunction AsyncGeneratorFunctionFunction { get => Slots[(int)Field.ASYNC_GENERATOR_FUNCTION_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.ASYNC_GENERATOR_FUNCTION_FUNCTION_INDEX] = value; }
    public JSFunction BigIntFunction { get => Slots[(int)Field.BIGINT_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.BIGINT_FUNCTION_INDEX] = value; }
    public JSFunction BooleanFunction { get => Slots[(int)Field.BOOLEAN_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.BOOLEAN_FUNCTION_INDEX] = value; }
    public Map BoundFunctionWithConstructorMap { get => Slots[(int)Field.BOUND_FUNCTION_WITH_CONSTRUCTOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.BOUND_FUNCTION_WITH_CONSTRUCTOR_MAP_INDEX] = value; }
    public Map BoundFunctionWithoutConstructorMap { get => Slots[(int)Field.BOUND_FUNCTION_WITHOUT_CONSTRUCTOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.BOUND_FUNCTION_WITHOUT_CONSTRUCTOR_MAP_INDEX] = value; }
    public JSFunction CallAsConstructorDelegate { get => Slots[(int)Field.CALL_AS_CONSTRUCTOR_DELEGATE_INDEX].As<JSFunction>(); set => Slots[(int)Field.CALL_AS_CONSTRUCTOR_DELEGATE_INDEX] = value; }
    public JSFunction CallAsFunctionDelegate { get => Slots[(int)Field.CALL_AS_FUNCTION_DELEGATE_INDEX].As<JSFunction>(); set => Slots[(int)Field.CALL_AS_FUNCTION_DELEGATE_INDEX] = value; }
    public JSFunction CallSiteFunction { get => Slots[(int)Field.CALLSITE_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.CALLSITE_FUNCTION_INDEX] = value; }
    public JSFunction ContextExtensionFunction { get => Slots[(int)Field.CONTEXT_EXTENSION_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.CONTEXT_EXTENSION_FUNCTION_INDEX] = value; }
    public Map DataPropertyDescriptorMap { get => Slots[(int)Field.DATA_PROPERTY_DESCRIPTOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.DATA_PROPERTY_DESCRIPTOR_MAP_INDEX] = value; }
    public JSFunction DataViewFun { get => Slots[(int)Field.DATA_VIEW_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.DATA_VIEW_FUN_INDEX] = value; }
    public JSFunction DateFunction { get => Slots[(int)Field.DATE_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.DATE_FUNCTION_INDEX] = value; }
    public JSValue DebugContextId { get => Slots[(int)Field.DEBUG_CONTEXT_ID_INDEX]; set => Slots[(int)Field.DEBUG_CONTEXT_ID_INDEX] = value; }
    public JSFunction EmptyFunction { get => Slots[(int)Field.EMPTY_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.EMPTY_FUNCTION_INDEX] = value; }
    public JSValue ErrorMessageForCodeGenFromStrings { get => Slots[(int)Field.ERROR_MESSAGE_FOR_CODE_GEN_FROM_STRINGS_INDEX]; set => Slots[(int)Field.ERROR_MESSAGE_FOR_CODE_GEN_FROM_STRINGS_INDEX] = value; }
    public JSValue ErrorMessageForWasmCodeGen { get => Slots[(int)Field.ERROR_MESSAGE_FOR_WASM_CODE_GEN_INDEX]; set => Slots[(int)Field.ERROR_MESSAGE_FOR_WASM_CODE_GEN_INDEX] = value; }
    public JSValue ErrorsThrown { get => Slots[(int)Field.ERRORS_THROWN_INDEX]; set => Slots[(int)Field.ERRORS_THROWN_INDEX] = value; }
    public JSObject ExtrasBindingObject { get => Slots[(int)Field.EXTRAS_BINDING_OBJECT_INDEX].As<JSObject>(); set => Slots[(int)Field.EXTRAS_BINDING_OBJECT_INDEX] = value; }
    public Map FastAliasedArgumentsMap { get => Slots[(int)Field.FAST_ALIASED_ARGUMENTS_MAP_INDEX].As<Map>(); set => Slots[(int)Field.FAST_ALIASED_ARGUMENTS_MAP_INDEX] = value; }
    public FixedArray FastTemplateInstantiationsCache { get => Slots[(int)Field.FAST_TEMPLATE_INSTANTIATIONS_CACHE_INDEX].As<FixedArray>(); set => Slots[(int)Field.FAST_TEMPLATE_INSTANTIATIONS_CACHE_INDEX] = value; }
    public JSFunction FunctionFunction { get => Slots[(int)Field.FUNCTION_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.FUNCTION_FUNCTION_INDEX] = value; }
    public JSObject FunctionPrototype { get => Slots[(int)Field.FUNCTION_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.FUNCTION_PROTOTYPE_INDEX] = value; }
    public JSFunction GeneratorFunctionFunction { get => Slots[(int)Field.GENERATOR_FUNCTION_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.GENERATOR_FUNCTION_FUNCTION_INDEX] = value; }
    public Map GeneratorObjectPrototypeMap { get => Slots[(int)Field.GENERATOR_OBJECT_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.GENERATOR_OBJECT_PROTOTYPE_MAP_INDEX] = value; }
    public Map AsyncGeneratorObjectPrototypeMap { get => Slots[(int)Field.ASYNC_GENERATOR_OBJECT_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ASYNC_GENERATOR_OBJECT_PROTOTYPE_MAP_INDEX] = value; }
    public Map InitialArrayIteratorMap { get => Slots[(int)Field.INITIAL_ARRAY_ITERATOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.INITIAL_ARRAY_ITERATOR_MAP_INDEX] = value; }
    public JSObject InitialArrayIteratorPrototype { get => Slots[(int)Field.INITIAL_ARRAY_ITERATOR_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_ARRAY_ITERATOR_PROTOTYPE_INDEX] = value; }
    public JSObject InitialArrayPrototype { get => Slots[(int)Field.INITIAL_ARRAY_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_ARRAY_PROTOTYPE_INDEX] = value; }
    public JSObject InitialErrorPrototype { get => Slots[(int)Field.INITIAL_ERROR_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_ERROR_PROTOTYPE_INDEX] = value; }
    public JSObject InitialGeneratorPrototype { get => Slots[(int)Field.INITIAL_GENERATOR_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_GENERATOR_PROTOTYPE_INDEX] = value; }
    public JSObject InitialAsyncIteratorPrototype { get => Slots[(int)Field.INITIAL_ASYNC_ITERATOR_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_ASYNC_ITERATOR_PROTOTYPE_INDEX] = value; }
    public JSObject InitialAsyncGeneratorPrototype { get => Slots[(int)Field.INITIAL_ASYNC_GENERATOR_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_ASYNC_GENERATOR_PROTOTYPE_INDEX] = value; }
    public JSFunction InitialIteratorFunction { get => Slots[(int)Field.INITIAL_ITERATOR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.INITIAL_ITERATOR_FUNCTION_INDEX] = value; }
    public JSObject InitialIteratorHelperPrototype { get => Slots[(int)Field.INITIAL_ITERATOR_HELPER_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_ITERATOR_HELPER_PROTOTYPE_INDEX] = value; }
    public JSObject InitialIteratorPrototype { get => Slots[(int)Field.INITIAL_ITERATOR_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_ITERATOR_PROTOTYPE_INDEX] = value; }
    public JSObject InitialDisposableStackPrototype { get => Slots[(int)Field.INITIAL_DISPOSABLE_STACK_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_DISPOSABLE_STACK_PROTOTYPE_INDEX] = value; }
    public JSObject InitialMapIteratorPrototype { get => Slots[(int)Field.INITIAL_MAP_ITERATOR_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_MAP_ITERATOR_PROTOTYPE_INDEX] = value; }
    public Map InitialMapPrototypeMap { get => Slots[(int)Field.INITIAL_MAP_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.INITIAL_MAP_PROTOTYPE_MAP_INDEX] = value; }
    public JSObject InitialObjectPrototype { get => Slots[(int)Field.INITIAL_OBJECT_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_OBJECT_PROTOTYPE_INDEX] = value; }
    public JSObject InitialSetIteratorPrototype { get => Slots[(int)Field.INITIAL_SET_ITERATOR_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_SET_ITERATOR_PROTOTYPE_INDEX] = value; }
    public JSObject InitialSetPrototype { get => Slots[(int)Field.INITIAL_SET_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_SET_PROTOTYPE_INDEX] = value; }
    public Map InitialSetPrototypeMap { get => Slots[(int)Field.INITIAL_SET_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.INITIAL_SET_PROTOTYPE_MAP_INDEX] = value; }
    public Map InitialStringIteratorMap { get => Slots[(int)Field.INITIAL_STRING_ITERATOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.INITIAL_STRING_ITERATOR_MAP_INDEX] = value; }
    public JSObject InitialStringIteratorPrototype { get => Slots[(int)Field.INITIAL_STRING_ITERATOR_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_STRING_ITERATOR_PROTOTYPE_INDEX] = value; }
    public JSObject InitialStringPrototype { get => Slots[(int)Field.INITIAL_STRING_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.INITIAL_STRING_PROTOTYPE_INDEX] = value; }
    public Map InitialWeakMapPrototypeMap { get => Slots[(int)Field.INITIAL_WEAKMAP_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.INITIAL_WEAKMAP_PROTOTYPE_MAP_INDEX] = value; }
    public Map InitialWeakSetPrototypeMap { get => Slots[(int)Field.INITIAL_WEAKSET_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.INITIAL_WEAKSET_PROTOTYPE_MAP_INDEX] = value; }
    public JSFunction IntlCollatorFunction { get => Slots[(int)Field.INTL_COLLATOR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.INTL_COLLATOR_FUNCTION_INDEX] = value; }
    public JSFunction IntlDateTimeFormatFunction { get => Slots[(int)Field.INTL_DATE_TIME_FORMAT_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.INTL_DATE_TIME_FORMAT_FUNCTION_INDEX] = value; }
    public JSFunction IntlDisplayNamesFunction { get => Slots[(int)Field.INTL_DISPLAY_NAMES_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.INTL_DISPLAY_NAMES_FUNCTION_INDEX] = value; }
    public JSFunction IntlDurationFormatFunction { get => Slots[(int)Field.INTL_DURATION_FORMAT_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.INTL_DURATION_FORMAT_FUNCTION_INDEX] = value; }
    public JSFunction IntlNumberFormatFunction { get => Slots[(int)Field.INTL_NUMBER_FORMAT_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.INTL_NUMBER_FORMAT_FUNCTION_INDEX] = value; }
    public JSFunction IntlLocaleFunction { get => Slots[(int)Field.INTL_LOCALE_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.INTL_LOCALE_FUNCTION_INDEX] = value; }
    public JSFunction IntlListFormatFunction { get => Slots[(int)Field.INTL_LIST_FORMAT_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.INTL_LIST_FORMAT_FUNCTION_INDEX] = value; }
    public JSFunction IntlPluralRulesFunction { get => Slots[(int)Field.INTL_PLURAL_RULES_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.INTL_PLURAL_RULES_FUNCTION_INDEX] = value; }
    public JSFunction IntlRelativeTimeFormatFunction { get => Slots[(int)Field.INTL_RELATIVE_TIME_FORMAT_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.INTL_RELATIVE_TIME_FORMAT_FUNCTION_INDEX] = value; }
    public JSFunction IntlSegmenterFunction { get => Slots[(int)Field.INTL_SEGMENTER_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.INTL_SEGMENTER_FUNCTION_INDEX] = value; }
    public Map IntlSegmentsMap { get => Slots[(int)Field.INTL_SEGMENTS_MAP_INDEX].As<Map>(); set => Slots[(int)Field.INTL_SEGMENTS_MAP_INDEX] = value; }
    public Map IntlSegmentDataObjectMap { get => Slots[(int)Field.INTL_SEGMENT_DATA_OBJECT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.INTL_SEGMENT_DATA_OBJECT_MAP_INDEX] = value; }
    public Map IntlSegmentDataObjectWordlikeMap { get => Slots[(int)Field.INTL_SEGMENT_DATA_OBJECT_WORDLIKE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.INTL_SEGMENT_DATA_OBJECT_WORDLIKE_MAP_INDEX] = value; }
    public Map IntlSegmentIteratorMap { get => Slots[(int)Field.INTL_SEGMENT_ITERATOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.INTL_SEGMENT_ITERATOR_MAP_INDEX] = value; }
    public Map IteratorFilterHelperMap { get => Slots[(int)Field.ITERATOR_FILTER_HELPER_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ITERATOR_FILTER_HELPER_MAP_INDEX] = value; }
    public Map IteratorMapHelperMap { get => Slots[(int)Field.ITERATOR_MAP_HELPER_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ITERATOR_MAP_HELPER_MAP_INDEX] = value; }
    public Map IteratorTakeHelperMap { get => Slots[(int)Field.ITERATOR_TAKE_HELPER_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ITERATOR_TAKE_HELPER_MAP_INDEX] = value; }
    public Map IteratorDropHelperMap { get => Slots[(int)Field.ITERATOR_DROP_HELPER_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ITERATOR_DROP_HELPER_MAP_INDEX] = value; }
    public Map IteratorFlatMapHelperMap { get => Slots[(int)Field.ITERATOR_FLAT_MAP_HELPER_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ITERATOR_FLAT_MAP_HELPER_MAP_INDEX] = value; }
    public Map IteratorConcatHelperMap { get => Slots[(int)Field.ITERATOR_CONCAT_HELPER_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ITERATOR_CONCAT_HELPER_MAP_INDEX] = value; }
    public Map IteratorZipHelperMap { get => Slots[(int)Field.ITERATOR_ZIP_HELPER_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ITERATOR_ZIP_HELPER_MAP_INDEX] = value; }
    public Map IteratorZipKeyedHelperMap { get => Slots[(int)Field.ITERATOR_ZIP_KEYED_HELPER_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ITERATOR_ZIP_KEYED_HELPER_MAP_INDEX] = value; }
    public JSFunction IteratorFunction { get => Slots[(int)Field.ITERATOR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.ITERATOR_FUNCTION_INDEX] = value; }
    public Map ValidIteratorWrapperMap { get => Slots[(int)Field.VALID_ITERATOR_WRAPPER_MAP_INDEX].As<Map>(); set => Slots[(int)Field.VALID_ITERATOR_WRAPPER_MAP_INDEX] = value; }
    public Map IteratorResultMap { get => Slots[(int)Field.ITERATOR_RESULT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ITERATOR_RESULT_MAP_INDEX] = value; }
    public Map JSArrayPackedSmiElementsMap { get => Slots[(int)Field.JS_ARRAY_PACKED_SMI_ELEMENTS_MAP_INDEX].As<Map>(); set => Slots[(int)Field.JS_ARRAY_PACKED_SMI_ELEMENTS_MAP_INDEX] = value; }
    public Map JSArrayHoleySmiElementsMap { get => Slots[(int)Field.JS_ARRAY_HOLEY_SMI_ELEMENTS_MAP_INDEX].As<Map>(); set => Slots[(int)Field.JS_ARRAY_HOLEY_SMI_ELEMENTS_MAP_INDEX] = value; }
    public Map JSArrayPackedElementsMap { get => Slots[(int)Field.JS_ARRAY_PACKED_ELEMENTS_MAP_INDEX].As<Map>(); set => Slots[(int)Field.JS_ARRAY_PACKED_ELEMENTS_MAP_INDEX] = value; }
    public Map JSArrayHoleyElementsMap { get => Slots[(int)Field.JS_ARRAY_HOLEY_ELEMENTS_MAP_INDEX].As<Map>(); set => Slots[(int)Field.JS_ARRAY_HOLEY_ELEMENTS_MAP_INDEX] = value; }
    public Map JSArrayPackedDoubleElementsMap { get => Slots[(int)Field.JS_ARRAY_PACKED_DOUBLE_ELEMENTS_MAP_INDEX].As<Map>(); set => Slots[(int)Field.JS_ARRAY_PACKED_DOUBLE_ELEMENTS_MAP_INDEX] = value; }
    public Map JSArrayHoleyDoubleElementsMap { get => Slots[(int)Field.JS_ARRAY_HOLEY_DOUBLE_ELEMENTS_MAP_INDEX].As<Map>(); set => Slots[(int)Field.JS_ARRAY_HOLEY_DOUBLE_ELEMENTS_MAP_INDEX] = value; }
    public Map JSArrayTemplateLiteralObjectMap { get => Slots[(int)Field.JS_ARRAY_TEMPLATE_LITERAL_OBJECT_MAP].As<Map>(); set => Slots[(int)Field.JS_ARRAY_TEMPLATE_LITERAL_OBJECT_MAP] = value; }
    public JSFunction JSDisposableStackFunction { get => Slots[(int)Field.JS_DISPOSABLE_STACK_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.JS_DISPOSABLE_STACK_FUNCTION_INDEX] = value; }
    public JSFunction JSAsyncDisposableStackFunction { get => Slots[(int)Field.JS_ASYNC_DISPOSABLE_STACK_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.JS_ASYNC_DISPOSABLE_STACK_FUNCTION_INDEX] = value; }
    public Map JSDisposableStackMap { get => Slots[(int)Field.JS_DISPOSABLE_STACK_MAP_INDEX].As<Map>(); set => Slots[(int)Field.JS_DISPOSABLE_STACK_MAP_INDEX] = value; }
    public JSFunction JSMapFun { get => Slots[(int)Field.JS_MAP_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.JS_MAP_FUN_INDEX] = value; }
    public Map JSMapMap { get => Slots[(int)Field.JS_MAP_MAP_INDEX].As<Map>(); set => Slots[(int)Field.JS_MAP_MAP_INDEX] = value; }
    public Map JSModuleNamespaceMap { get => Slots[(int)Field.JS_MODULE_NAMESPACE_MAP].As<Map>(); set => Slots[(int)Field.JS_MODULE_NAMESPACE_MAP] = value; }
    public Map JSDeferredModuleNamespaceMap { get => Slots[(int)Field.JS_DEFERRED_MODULE_NAMESPACE_MAP].As<Map>(); set => Slots[(int)Field.JS_DEFERRED_MODULE_NAMESPACE_MAP] = value; }
    public Map JSRawJsonMap { get => Slots[(int)Field.JS_RAW_JSON_MAP].As<Map>(); set => Slots[(int)Field.JS_RAW_JSON_MAP] = value; }
    public JSFunction JSSetFun { get => Slots[(int)Field.JS_SET_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.JS_SET_FUN_INDEX] = value; }
    public Map JSSetMap { get => Slots[(int)Field.JS_SET_MAP_INDEX].As<Map>(); set => Slots[(int)Field.JS_SET_MAP_INDEX] = value; }
    public JSFunction JSWeakMapFun { get => Slots[(int)Field.JS_WEAK_MAP_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.JS_WEAK_MAP_FUN_INDEX] = value; }
    public JSFunction JSWeakSetFun { get => Slots[(int)Field.JS_WEAK_SET_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.JS_WEAK_SET_FUN_INDEX] = value; }
    public JSFunction JSWeakRefFun { get => Slots[(int)Field.JS_WEAK_REF_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.JS_WEAK_REF_FUNCTION_INDEX] = value; }
    public JSFunction JSFinalizationRegistryFun { get => Slots[(int)Field.JS_FINALIZATION_REGISTRY_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.JS_FINALIZATION_REGISTRY_FUNCTION_INDEX] = value; }
    public JSObject JsonObject { get => Slots[(int)Field.JSON_OBJECT].As<JSObject>(); set => Slots[(int)Field.JSON_OBJECT] = value; }
    public Map PromiseWithresolversResultMap { get => Slots[(int)Field.PROMISE_WITHRESOLVERS_RESULT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.PROMISE_WITHRESOLVERS_RESULT_MAP_INDEX] = value; }
    public Map MetaMap { get => Slots[(int)Field.META_MAP_INDEX].As<Map>(); set => Slots[(int)Field.META_MAP_INDEX] = value; }
    public Map FunctionContextMap { get => Slots[(int)Field.FUNCTION_CONTEXT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.FUNCTION_CONTEXT_MAP_INDEX] = value; }
    public Map ModuleContextMap { get => Slots[(int)Field.MODULE_CONTEXT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.MODULE_CONTEXT_MAP_INDEX] = value; }
    public Map EvalContextMap { get => Slots[(int)Field.EVAL_CONTEXT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.EVAL_CONTEXT_MAP_INDEX] = value; }
    public Map ScriptContextMap { get => Slots[(int)Field.SCRIPT_CONTEXT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.SCRIPT_CONTEXT_MAP_INDEX] = value; }
    public Map AwaitContextMap { get => Slots[(int)Field.AWAIT_CONTEXT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.AWAIT_CONTEXT_MAP_INDEX] = value; }
    public Map BlockContextMap { get => Slots[(int)Field.BLOCK_CONTEXT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.BLOCK_CONTEXT_MAP_INDEX] = value; }
    public Map CatchContextMap { get => Slots[(int)Field.CATCH_CONTEXT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.CATCH_CONTEXT_MAP_INDEX] = value; }
    public Map WithContextMap { get => Slots[(int)Field.WITH_CONTEXT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.WITH_CONTEXT_MAP_INDEX] = value; }
    public Map DebugEvaluateContextMap { get => Slots[(int)Field.DEBUG_EVALUATE_CONTEXT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.DEBUG_EVALUATE_CONTEXT_MAP_INDEX] = value; }
    public Map JSRabGsabDataViewMap { get => Slots[(int)Field.JS_RAB_GSAB_DATA_VIEW_MAP_INDEX].As<Map>(); set => Slots[(int)Field.JS_RAB_GSAB_DATA_VIEW_MAP_INDEX] = value; }
    public JSValue MapCache { get => Slots[(int)Field.MAP_CACHE_INDEX]; set => Slots[(int)Field.MAP_CACHE_INDEX] = value; }
    public Map MapKeyIteratorMap { get => Slots[(int)Field.MAP_KEY_ITERATOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.MAP_KEY_ITERATOR_MAP_INDEX] = value; }
    public Map MapKeyValueIteratorMap { get => Slots[(int)Field.MAP_KEY_VALUE_ITERATOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.MAP_KEY_VALUE_ITERATOR_MAP_INDEX] = value; }
    public Map MapValueIteratorMap { get => Slots[(int)Field.MAP_VALUE_ITERATOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.MAP_VALUE_ITERATOR_MAP_INDEX] = value; }
    public JSValue MathRandomIndex { get => Slots[(int)Field.MATH_RANDOM_INDEX_INDEX]; set => Slots[(int)Field.MATH_RANDOM_INDEX_INDEX] = value; }
    public JSValue MathRandomState { get => Slots[(int)Field.MATH_RANDOM_STATE_INDEX]; set => Slots[(int)Field.MATH_RANDOM_STATE_INDEX] = value; }
    public JSValue MathRandomCache { get => Slots[(int)Field.MATH_RANDOM_CACHE_INDEX]; set => Slots[(int)Field.MATH_RANDOM_CACHE_INDEX] = value; }
    public NormalizedMapCache? NormalizedMapCache { get => Slots[(int)Field.NORMALIZED_MAP_CACHE_INDEX].AsOrNull<NormalizedMapCache>(); set => Slots[(int)Field.NORMALIZED_MAP_CACHE_INDEX] = JSValue.FromObject(value); }
    public JSFunction NumberFunction { get => Slots[(int)Field.NUMBER_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.NUMBER_FUNCTION_INDEX] = value; }
    public JSFunction ObjectFunction { get => Slots[(int)Field.OBJECT_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.OBJECT_FUNCTION_INDEX] = value; }
    public JSObject ObjectFunctionPrototype { get => Slots[(int)Field.OBJECT_FUNCTION_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.OBJECT_FUNCTION_PROTOTYPE_INDEX] = value; }
    public Map ObjectFunctionPrototypeMap { get => Slots[(int)Field.OBJECT_FUNCTION_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.OBJECT_FUNCTION_PROTOTYPE_MAP_INDEX] = value; }
    public JSValue PromiseHookInitFunction { get => Slots[(int)Field.PROMISE_HOOK_INIT_FUNCTION_INDEX]; set => Slots[(int)Field.PROMISE_HOOK_INIT_FUNCTION_INDEX] = value; }
    public JSValue PromiseHookBeforeFunction { get => Slots[(int)Field.PROMISE_HOOK_BEFORE_FUNCTION_INDEX]; set => Slots[(int)Field.PROMISE_HOOK_BEFORE_FUNCTION_INDEX] = value; }
    public JSValue PromiseHookAfterFunction { get => Slots[(int)Field.PROMISE_HOOK_AFTER_FUNCTION_INDEX]; set => Slots[(int)Field.PROMISE_HOOK_AFTER_FUNCTION_INDEX] = value; }
    public JSValue PromiseHookResolveFunction { get => Slots[(int)Field.PROMISE_HOOK_RESOLVE_FUNCTION_INDEX]; set => Slots[(int)Field.PROMISE_HOOK_RESOLVE_FUNCTION_INDEX] = value; }
    public Map ProxyCallableMap { get => Slots[(int)Field.PROXY_CALLABLE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.PROXY_CALLABLE_MAP_INDEX] = value; }
    public Map ProxyConstructorMap { get => Slots[(int)Field.PROXY_CONSTRUCTOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.PROXY_CONSTRUCTOR_MAP_INDEX] = value; }
    public JSFunction ProxyFunction { get => Slots[(int)Field.PROXY_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.PROXY_FUNCTION_INDEX] = value; }
    public Map ProxyMap { get => Slots[(int)Field.PROXY_MAP_INDEX].As<Map>(); set => Slots[(int)Field.PROXY_MAP_INDEX] = value; }
    public Map ProxyRevocableResultMap { get => Slots[(int)Field.PROXY_REVOCABLE_RESULT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.PROXY_REVOCABLE_RESULT_MAP_INDEX] = value; }
    public JSObject PromisePrototype { get => Slots[(int)Field.PROMISE_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.PROMISE_PROTOTYPE_INDEX] = value; }
    public JSValue RecorderContextId { get => Slots[(int)Field.RECORDER_CONTEXT_ID]; set => Slots[(int)Field.RECORDER_CONTEXT_ID] = value; }
    public JSFunction RegExpExecFunction { get => Slots[(int)Field.REGEXP_EXEC_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.REGEXP_EXEC_FUNCTION_INDEX] = value; }
    public JSFunction RegExpFunction { get => Slots[(int)Field.REGEXP_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.REGEXP_FUNCTION_INDEX] = value; }
    public JSValue RegExpLastMatchInfo { get => Slots[(int)Field.REGEXP_LAST_MATCH_INFO_INDEX]; set => Slots[(int)Field.REGEXP_LAST_MATCH_INFO_INDEX] = value; }
    public JSFunction RegExpMatchAllFunction { get => Slots[(int)Field.REGEXP_MATCH_ALL_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.REGEXP_MATCH_ALL_FUNCTION_INDEX] = value; }
    public JSFunction RegExpMatchFunction { get => Slots[(int)Field.REGEXP_MATCH_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.REGEXP_MATCH_FUNCTION_INDEX] = value; }
    public JSObject RegExpPrototype { get => Slots[(int)Field.REGEXP_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.REGEXP_PROTOTYPE_INDEX] = value; }
    public Map RegExpPrototypeMap { get => Slots[(int)Field.REGEXP_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.REGEXP_PROTOTYPE_MAP_INDEX] = value; }
    public JSFunction RegExpReplaceFunction { get => Slots[(int)Field.REGEXP_REPLACE_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.REGEXP_REPLACE_FUNCTION_INDEX] = value; }
    public Map RegExpResultMap { get => Slots[(int)Field.REGEXP_RESULT_MAP_INDEX].As<Map>(); set => Slots[(int)Field.REGEXP_RESULT_MAP_INDEX] = value; }
    public Map RegExpResultWithIndicesMap { get => Slots[(int)Field.REGEXP_RESULT_WITH_INDICES_MAP_INDEX].As<Map>(); set => Slots[(int)Field.REGEXP_RESULT_WITH_INDICES_MAP_INDEX] = value; }
    public Map RegExpResultIndicesMap { get => Slots[(int)Field.REGEXP_RESULT_INDICES_MAP_INDEX].As<Map>(); set => Slots[(int)Field.REGEXP_RESULT_INDICES_MAP_INDEX] = value; }
    public JSFunction RegExpSearchFunction { get => Slots[(int)Field.REGEXP_SEARCH_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.REGEXP_SEARCH_FUNCTION_INDEX] = value; }
    public JSFunction RegExpSplitFunction { get => Slots[(int)Field.REGEXP_SPLIT_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.REGEXP_SPLIT_FUNCTION_INDEX] = value; }
    public Map InitialRegExpStringIteratorPrototypeMap { get => Slots[(int)Field.INITIAL_REGEXP_STRING_ITERATOR_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.INITIAL_REGEXP_STRING_ITERATOR_PROTOTYPE_MAP_INDEX] = value; }
    public ScriptContextTable ScriptContextTable { get => Slots[(int)Field.SCRIPT_CONTEXT_TABLE_INDEX].As<ScriptContextTable>(); set => Slots[(int)Field.SCRIPT_CONTEXT_TABLE_INDEX] = value; }
    public JSValue ScriptExecutionCallback { get => Slots[(int)Field.SCRIPT_EXECUTION_CALLBACK_INDEX]; set => Slots[(int)Field.SCRIPT_EXECUTION_CALLBACK_INDEX] = value; }
    public JSValue TemporalGetEpochNanosecondsCallback { get => Slots[(int)Field.TEMPORAL_GET_EPOCH_NANOSECONDS_CALLBACK_INDEX]; set => Slots[(int)Field.TEMPORAL_GET_EPOCH_NANOSECONDS_CALLBACK_INDEX] = value; }
    public JSValue SecurityToken { get => Slots[(int)Field.SECURITY_TOKEN_INDEX]; set => Slots[(int)Field.SECURITY_TOKEN_INDEX] = value; }
    public JSValue SerializedObjects { get => Slots[(int)Field.SERIALIZED_OBJECTS]; set => Slots[(int)Field.SERIALIZED_OBJECTS] = value; }
    public Map SetValueIteratorMap { get => Slots[(int)Field.SET_VALUE_ITERATOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.SET_VALUE_ITERATOR_MAP_INDEX] = value; }
    public Map SetKeyValueIteratorMap { get => Slots[(int)Field.SET_KEY_VALUE_ITERATOR_MAP_INDEX].As<Map>(); set => Slots[(int)Field.SET_KEY_VALUE_ITERATOR_MAP_INDEX] = value; }
    public JSFunction SharedArrayBufferFun { get => Slots[(int)Field.SHARED_ARRAY_BUFFER_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.SHARED_ARRAY_BUFFER_FUN_INDEX] = value; }
    public Map SloppyArgumentsMap { get => Slots[(int)Field.SLOPPY_ARGUMENTS_MAP_INDEX].As<Map>(); set => Slots[(int)Field.SLOPPY_ARGUMENTS_MAP_INDEX] = value; }
    public Map SlowAliasedArgumentsMap { get => Slots[(int)Field.SLOW_ALIASED_ARGUMENTS_MAP_INDEX].As<Map>(); set => Slots[(int)Field.SLOW_ALIASED_ARGUMENTS_MAP_INDEX] = value; }
    public Map StrictArgumentsMap { get => Slots[(int)Field.STRICT_ARGUMENTS_MAP_INDEX].As<Map>(); set => Slots[(int)Field.STRICT_ARGUMENTS_MAP_INDEX] = value; }
    public Map SlowObjectWithNullPrototypeMap { get => Slots[(int)Field.SLOW_OBJECT_WITH_NULL_PROTOTYPE_MAP].As<Map>(); set => Slots[(int)Field.SLOW_OBJECT_WITH_NULL_PROTOTYPE_MAP] = value; }
    public Map SlowObjectWithObjectPrototypeMap { get => Slots[(int)Field.SLOW_OBJECT_WITH_OBJECT_PROTOTYPE_MAP].As<Map>(); set => Slots[(int)Field.SLOW_OBJECT_WITH_OBJECT_PROTOTYPE_MAP] = value; }
    public JSValue SlowTemplateInstantiationsCache { get => Slots[(int)Field.SLOW_TEMPLATE_INSTANTIATIONS_CACHE_INDEX]; set => Slots[(int)Field.SLOW_TEMPLATE_INSTANTIATIONS_CACHE_INDEX] = value; }
    public JSValue AtomicsWaitasyncPromises { get => Slots[(int)Field.ATOMICS_WAITASYNC_PROMISES]; set => Slots[(int)Field.ATOMICS_WAITASYNC_PROMISES] = value; }
    public Map SetUnit8ArrayResultMap { get => Slots[(int)Field.SET_UINT8_ARRAY_RESULT_MAP].As<Map>(); set => Slots[(int)Field.SET_UINT8_ARRAY_RESULT_MAP] = value; }
    public FixedArray WasmDebugMaps { get => Slots[(int)Field.WASM_DEBUG_MAPS].As<FixedArray>(); set => Slots[(int)Field.WASM_DEBUG_MAPS] = value; }
    public JSValue InitialArrayPrototypeValidityCell { get => Slots[(int)Field.INITIAL_ARRAY_PROTOTYPE_VALIDITY_CELL_INDEX]; set => Slots[(int)Field.INITIAL_ARRAY_PROTOTYPE_VALIDITY_CELL_INDEX] = value; }
    public Map SloppyFunctionMap { get => Slots[(int)Field.SLOPPY_FUNCTION_MAP_INDEX].As<Map>(); set => Slots[(int)Field.SLOPPY_FUNCTION_MAP_INDEX] = value; }
    public Map SloppyFunctionWithNameMap { get => Slots[(int)Field.SLOPPY_FUNCTION_WITH_NAME_MAP_INDEX].As<Map>(); set => Slots[(int)Field.SLOPPY_FUNCTION_WITH_NAME_MAP_INDEX] = value; }
    public Map SloppyFunctionWithoutPrototypeMap { get => Slots[(int)Field.SLOPPY_FUNCTION_WITHOUT_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.SLOPPY_FUNCTION_WITHOUT_PROTOTYPE_MAP_INDEX] = value; }
    public Map SloppyFunctionWithReadonlyPrototypeMap { get => Slots[(int)Field.SLOPPY_FUNCTION_WITH_READONLY_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.SLOPPY_FUNCTION_WITH_READONLY_PROTOTYPE_MAP_INDEX] = value; }
    public Map StrictFunctionMap { get => Slots[(int)Field.STRICT_FUNCTION_MAP_INDEX].As<Map>(); set => Slots[(int)Field.STRICT_FUNCTION_MAP_INDEX] = value; }
    public Map StrictFunctionWithNameMap { get => Slots[(int)Field.STRICT_FUNCTION_WITH_NAME_MAP_INDEX].As<Map>(); set => Slots[(int)Field.STRICT_FUNCTION_WITH_NAME_MAP_INDEX] = value; }
    public Map StrictFunctionWithReadonlyPrototypeMap { get => Slots[(int)Field.STRICT_FUNCTION_WITH_READONLY_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.STRICT_FUNCTION_WITH_READONLY_PROTOTYPE_MAP_INDEX] = value; }
    public Map StrictFunctionWithoutPrototypeMap { get => Slots[(int)Field.STRICT_FUNCTION_WITHOUT_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.STRICT_FUNCTION_WITHOUT_PROTOTYPE_MAP_INDEX] = value; }
    public Map MethodWithNameMap { get => Slots[(int)Field.METHOD_WITH_NAME_MAP_INDEX].As<Map>(); set => Slots[(int)Field.METHOD_WITH_NAME_MAP_INDEX] = value; }
    public Map AsyncFunctionMap { get => Slots[(int)Field.ASYNC_FUNCTION_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ASYNC_FUNCTION_MAP_INDEX] = value; }
    public Map AsyncFunctionWithNameMap { get => Slots[(int)Field.ASYNC_FUNCTION_WITH_NAME_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ASYNC_FUNCTION_WITH_NAME_MAP_INDEX] = value; }
    public Map GeneratorFunctionMap { get => Slots[(int)Field.GENERATOR_FUNCTION_MAP_INDEX].As<Map>(); set => Slots[(int)Field.GENERATOR_FUNCTION_MAP_INDEX] = value; }
    public Map GeneratorFunctionWithNameMap { get => Slots[(int)Field.GENERATOR_FUNCTION_WITH_NAME_MAP_INDEX].As<Map>(); set => Slots[(int)Field.GENERATOR_FUNCTION_WITH_NAME_MAP_INDEX] = value; }
    public Map AsyncGeneratorFunctionMap { get => Slots[(int)Field.ASYNC_GENERATOR_FUNCTION_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ASYNC_GENERATOR_FUNCTION_MAP_INDEX] = value; }
    public Map AsyncGeneratorFunctionWithNameMap { get => Slots[(int)Field.ASYNC_GENERATOR_FUNCTION_WITH_NAME_MAP_INDEX].As<Map>(); set => Slots[(int)Field.ASYNC_GENERATOR_FUNCTION_WITH_NAME_MAP_INDEX] = value; }
    public Map ClassFunctionMap { get => Slots[(int)Field.CLASS_FUNCTION_MAP_INDEX].As<Map>(); set => Slots[(int)Field.CLASS_FUNCTION_MAP_INDEX] = value; }
    public JSFunction StringFunction { get => Slots[(int)Field.STRING_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.STRING_FUNCTION_INDEX] = value; }
    public Map StringFunctionPrototypeMap { get => Slots[(int)Field.STRING_FUNCTION_PROTOTYPE_MAP_INDEX].As<Map>(); set => Slots[(int)Field.STRING_FUNCTION_PROTOTYPE_MAP_INDEX] = value; }
    public JSFunction SymbolFunction { get => Slots[(int)Field.SYMBOL_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.SYMBOL_FUNCTION_INDEX] = value; }
    public JSValue IsWasmJSInstalled { get => Slots[(int)Field.IS_WASM_JS_INSTALLED_INDEX]; set => Slots[(int)Field.IS_WASM_JS_INSTALLED_INDEX] = value; }
    public JSValue IsWasmJspiInstalled { get => Slots[(int)Field.IS_WASM_JSPI_INSTALLED_INDEX]; set => Slots[(int)Field.IS_WASM_JSPI_INSTALLED_INDEX] = value; }
    public JSObject WasmWebassemblyObject { get => Slots[(int)Field.WASM_WEBASSEMBLY_OBJECT_INDEX].As<JSObject>(); set => Slots[(int)Field.WASM_WEBASSEMBLY_OBJECT_INDEX] = value; }
    public Map WasmExportedFunctionMap { get => Slots[(int)Field.WASM_EXPORTED_FUNCTION_MAP_INDEX].As<Map>(); set => Slots[(int)Field.WASM_EXPORTED_FUNCTION_MAP_INDEX] = value; }
    public JSFunction WasmTagConstructor { get => Slots[(int)Field.WASM_TAG_CONSTRUCTOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_TAG_CONSTRUCTOR_INDEX] = value; }
    public JSFunction WasmExceptionConstructor { get => Slots[(int)Field.WASM_EXCEPTION_CONSTRUCTOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_EXCEPTION_CONSTRUCTOR_INDEX] = value; }
    public JSFunction WasmGlobalConstructor { get => Slots[(int)Field.WASM_GLOBAL_CONSTRUCTOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_GLOBAL_CONSTRUCTOR_INDEX] = value; }
    public JSFunction WasmInstanceConstructor { get => Slots[(int)Field.WASM_INSTANCE_CONSTRUCTOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_INSTANCE_CONSTRUCTOR_INDEX] = value; }
    public JSObject WasmJSTag { get => Slots[(int)Field.WASM_JS_TAG_INDEX].As<JSObject>(); set => Slots[(int)Field.WASM_JS_TAG_INDEX] = value; }
    public JSFunction WasmMemoryConstructor { get => Slots[(int)Field.WASM_MEMORY_CONSTRUCTOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_MEMORY_CONSTRUCTOR_INDEX] = value; }
    public JSFunction WasmModuleConstructor { get => Slots[(int)Field.WASM_MODULE_CONSTRUCTOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_MODULE_CONSTRUCTOR_INDEX] = value; }
    public JSFunction WasmTableConstructor { get => Slots[(int)Field.WASM_TABLE_CONSTRUCTOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_TABLE_CONSTRUCTOR_INDEX] = value; }
    public JSFunction WasmSuspendingConstructor { get => Slots[(int)Field.WASM_SUSPENDING_CONSTRUCTOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_SUSPENDING_CONSTRUCTOR_INDEX] = value; }
    public JSFunction WasmSuspenderConstructor { get => Slots[(int)Field.WASM_SUSPENDER_CONSTRUCTOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_SUSPENDER_CONSTRUCTOR_INDEX] = value; }
    public Map WasmSuspendingMap { get => Slots[(int)Field.WASM_SUSPENDING_MAP].As<Map>(); set => Slots[(int)Field.WASM_SUSPENDING_MAP] = value; }
    public JSObject WasmSuspendingPrototype { get => Slots[(int)Field.WASM_SUSPENDING_PROTOTYPE].As<JSObject>(); set => Slots[(int)Field.WASM_SUSPENDING_PROTOTYPE] = value; }
    public JSValue WasmMemoryMapDescriptorTemplate { get => Slots[(int)Field.WASM_MEMORY_MAP_DESCRIPTOR_TEMPLATE_INDEX]; set => Slots[(int)Field.WASM_MEMORY_MAP_DESCRIPTOR_TEMPLATE_INDEX] = value; }
    public JSFunction WasmMemoryMapDescriptorConstructor { get => Slots[(int)Field.WASM_MEMORY_MAP_DESCRIPTOR_CONSTRUCTOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_MEMORY_MAP_DESCRIPTOR_CONSTRUCTOR_INDEX] = value; }
    public JSValue TemplateWeakMap { get => Slots[(int)Field.TEMPLATE_WEAKMAP_INDEX]; set => Slots[(int)Field.TEMPLATE_WEAKMAP_INDEX] = value; }
    public JSFunction TypedArrayFunction { get => Slots[(int)Field.TYPED_ARRAY_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.TYPED_ARRAY_FUN_INDEX] = value; }
    public JSObject TypedArrayPrototype { get => Slots[(int)Field.TYPED_ARRAY_PROTOTYPE_INDEX].As<JSObject>(); set => Slots[(int)Field.TYPED_ARRAY_PROTOTYPE_INDEX] = value; }
    public JSFunction ArrayEntriesIterator { get => Slots[(int)Field.ARRAY_ENTRIES_ITERATOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.ARRAY_ENTRIES_ITERATOR_INDEX] = value; }
    public JSFunction ArrayForEachIterator { get => Slots[(int)Field.ARRAY_FOR_EACH_ITERATOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.ARRAY_FOR_EACH_ITERATOR_INDEX] = value; }
    public JSFunction ArrayKeysIterator { get => Slots[(int)Field.ARRAY_KEYS_ITERATOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.ARRAY_KEYS_ITERATOR_INDEX] = value; }
    public JSFunction ArrayValuesIterator { get => Slots[(int)Field.ARRAY_VALUES_ITERATOR_INDEX].As<JSFunction>(); set => Slots[(int)Field.ARRAY_VALUES_ITERATOR_INDEX] = value; }
    public JSFunction ErrorFunction { get => Slots[(int)Field.ERROR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.ERROR_FUNCTION_INDEX] = value; }
    public JSFunction ErrorToString { get => Slots[(int)Field.ERROR_TO_STRING].As<JSFunction>(); set => Slots[(int)Field.ERROR_TO_STRING] = value; }
    public JSFunction EvalErrorFunction { get => Slots[(int)Field.EVAL_ERROR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.EVAL_ERROR_FUNCTION_INDEX] = value; }
    public JSFunction AggregateErrorFunction { get => Slots[(int)Field.AGGREGATE_ERROR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.AGGREGATE_ERROR_FUNCTION_INDEX] = value; }
    public JSFunction GlobalEvalFun { get => Slots[(int)Field.GLOBAL_EVAL_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.GLOBAL_EVAL_FUN_INDEX] = value; }
    public JSFunction GlobalParseFloatFun { get => Slots[(int)Field.GLOBAL_PARSE_FLOAT_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.GLOBAL_PARSE_FLOAT_FUN_INDEX] = value; }
    public JSFunction GlobalParseIntFun { get => Slots[(int)Field.GLOBAL_PARSE_INT_FUN_INDEX].As<JSFunction>(); set => Slots[(int)Field.GLOBAL_PARSE_INT_FUN_INDEX] = value; }
    public JSFunction GlobalProxyFunction { get => Slots[(int)Field.GLOBAL_PROXY_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.GLOBAL_PROXY_FUNCTION_INDEX] = value; }
    public JSFunction MapDelete { get => Slots[(int)Field.MAP_DELETE_INDEX].As<JSFunction>(); set => Slots[(int)Field.MAP_DELETE_INDEX] = value; }
    public JSFunction MapGet { get => Slots[(int)Field.MAP_GET_INDEX].As<JSFunction>(); set => Slots[(int)Field.MAP_GET_INDEX] = value; }
    public JSFunction MapHas { get => Slots[(int)Field.MAP_HAS_INDEX].As<JSFunction>(); set => Slots[(int)Field.MAP_HAS_INDEX] = value; }
    public JSFunction MapSet { get => Slots[(int)Field.MAP_SET_INDEX].As<JSFunction>(); set => Slots[(int)Field.MAP_SET_INDEX] = value; }
    public JSFunction FunctionHasInstance { get => Slots[(int)Field.FUNCTION_HAS_INSTANCE_INDEX].As<JSFunction>(); set => Slots[(int)Field.FUNCTION_HAS_INSTANCE_INDEX] = value; }
    public JSFunction FunctionToString { get => Slots[(int)Field.FUNCTION_TO_STRING_INDEX].As<JSFunction>(); set => Slots[(int)Field.FUNCTION_TO_STRING_INDEX] = value; }
    public JSFunction ObjectToString { get => Slots[(int)Field.OBJECT_TO_STRING].As<JSFunction>(); set => Slots[(int)Field.OBJECT_TO_STRING] = value; }
    public JSFunction ObjectValueOfFunction { get => Slots[(int)Field.OBJECT_VALUE_OF_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.OBJECT_VALUE_OF_FUNCTION_INDEX] = value; }
    public JSFunction PromiseAll { get => Slots[(int)Field.PROMISE_ALL_INDEX].As<JSFunction>(); set => Slots[(int)Field.PROMISE_ALL_INDEX] = value; }
    public JSFunction PromiseAllSettled { get => Slots[(int)Field.PROMISE_ALL_SETTLED_INDEX].As<JSFunction>(); set => Slots[(int)Field.PROMISE_ALL_SETTLED_INDEX] = value; }
    public JSFunction PromiseAny { get => Slots[(int)Field.PROMISE_ANY_INDEX].As<JSFunction>(); set => Slots[(int)Field.PROMISE_ANY_INDEX] = value; }
    public JSFunction PromiseFunction { get => Slots[(int)Field.PROMISE_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.PROMISE_FUNCTION_INDEX] = value; }
    public JSFunction RangeErrorFunction { get => Slots[(int)Field.RANGE_ERROR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.RANGE_ERROR_FUNCTION_INDEX] = value; }
    public JSFunction ReferenceErrorFunction { get => Slots[(int)Field.REFERENCE_ERROR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.REFERENCE_ERROR_FUNCTION_INDEX] = value; }
    public JSFunction SetAdd { get => Slots[(int)Field.SET_ADD_INDEX].As<JSFunction>(); set => Slots[(int)Field.SET_ADD_INDEX] = value; }
    public JSFunction SetDelete { get => Slots[(int)Field.SET_DELETE_INDEX].As<JSFunction>(); set => Slots[(int)Field.SET_DELETE_INDEX] = value; }
    public JSFunction SetHas { get => Slots[(int)Field.SET_HAS_INDEX].As<JSFunction>(); set => Slots[(int)Field.SET_HAS_INDEX] = value; }
    public JSFunction ShadowRealmImportValueRejected { get => Slots[(int)Field.SHADOW_REALM_IMPORT_VALUE_REJECTED_INDEX].As<JSFunction>(); set => Slots[(int)Field.SHADOW_REALM_IMPORT_VALUE_REJECTED_INDEX] = value; }
    public JSFunction SuppressedErrorFunction { get => Slots[(int)Field.SUPPRESSED_ERROR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.SUPPRESSED_ERROR_FUNCTION_INDEX] = value; }
    public JSFunction SyntaxErrorFunction { get => Slots[(int)Field.SYNTAX_ERROR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.SYNTAX_ERROR_FUNCTION_INDEX] = value; }
    public JSFunction TypeErrorFunction { get => Slots[(int)Field.TYPE_ERROR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.TYPE_ERROR_FUNCTION_INDEX] = value; }
    public JSFunction UriErrorFunction { get => Slots[(int)Field.URI_ERROR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.URI_ERROR_FUNCTION_INDEX] = value; }
    public JSFunction WasmCompileErrorFunction { get => Slots[(int)Field.WASM_COMPILE_ERROR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_COMPILE_ERROR_FUNCTION_INDEX] = value; }
    public JSFunction WasmLinkErrorFunction { get => Slots[(int)Field.WASM_LINK_ERROR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_LINK_ERROR_FUNCTION_INDEX] = value; }
    public JSFunction WasmSuspendErrorFunction { get => Slots[(int)Field.WASM_SUSPEND_ERROR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_SUSPEND_ERROR_FUNCTION_INDEX] = value; }
    public JSFunction WasmRuntimeErrorFunction { get => Slots[(int)Field.WASM_RUNTIME_ERROR_FUNCTION_INDEX].As<JSFunction>(); set => Slots[(int)Field.WASM_RUNTIME_ERROR_FUNCTION_INDEX] = value; }
    public JSFunction WeakMapSet { get => Slots[(int)Field.WEAKMAP_SET_INDEX].As<JSFunction>(); set => Slots[(int)Field.WEAKMAP_SET_INDEX] = value; }
    public JSFunction WeakMapGet { get => Slots[(int)Field.WEAKMAP_GET_INDEX].As<JSFunction>(); set => Slots[(int)Field.WEAKMAP_GET_INDEX] = value; }
    public JSFunction WeakMapDelete { get => Slots[(int)Field.WEAKMAP_DELETE_INDEX].As<JSFunction>(); set => Slots[(int)Field.WEAKMAP_DELETE_INDEX] = value; }
    public JSFunction WeakSetAdd { get => Slots[(int)Field.WEAKSET_ADD_INDEX].As<JSFunction>(); set => Slots[(int)Field.WEAKSET_ADD_INDEX] = value; }
    public Map WrappedFunctionMap { get => Slots[(int)Field.WRAPPED_FUNCTION_MAP_INDEX].As<Map>(); set => Slots[(int)Field.WRAPPED_FUNCTION_MAP_INDEX] = value; }
    public JSValue RetainedMaps { get => Slots[(int)Field.RETAINED_MAPS]; set => Slots[(int)Field.RETAINED_MAPS] = value; }
    public JSFunction SharedSpaceJSObjectHasInstance { get => Slots[(int)Field.SHARED_SPACE_JS_OBJECT_HAS_INSTANCE_INDEX].As<JSFunction>(); set => Slots[(int)Field.SHARED_SPACE_JS_OBJECT_HAS_INSTANCE_INDEX] = value; }
    public JSValue TemporalDurationFunction { get => Slots[(int)Field.JS_TEMPORAL_DURATION_FUNCTION_INDEX]; set => Slots[(int)Field.JS_TEMPORAL_DURATION_FUNCTION_INDEX] = value; }
    public JSValue TemporalInstantFunction { get => Slots[(int)Field.JS_TEMPORAL_INSTANT_FUNCTION_INDEX]; set => Slots[(int)Field.JS_TEMPORAL_INSTANT_FUNCTION_INDEX] = value; }
    public JSValue TemporalPlainDateFunction { get => Slots[(int)Field.JS_TEMPORAL_PLAIN_DATE_FUNCTION_INDEX]; set => Slots[(int)Field.JS_TEMPORAL_PLAIN_DATE_FUNCTION_INDEX] = value; }
    public JSValue TemporalPlainDateTimeFunction { get => Slots[(int)Field.JS_TEMPORAL_PLAIN_DATE_TIME_FUNCTION_INDEX]; set => Slots[(int)Field.JS_TEMPORAL_PLAIN_DATE_TIME_FUNCTION_INDEX] = value; }
    public JSValue TemporalPlainMonthDayFunction { get => Slots[(int)Field.JS_TEMPORAL_PLAIN_MONTH_DAY_FUNCTION_INDEX]; set => Slots[(int)Field.JS_TEMPORAL_PLAIN_MONTH_DAY_FUNCTION_INDEX] = value; }
    public JSValue TemporalPlainTimeFunction { get => Slots[(int)Field.JS_TEMPORAL_PLAIN_TIME_FUNCTION_INDEX]; set => Slots[(int)Field.JS_TEMPORAL_PLAIN_TIME_FUNCTION_INDEX] = value; }
    public JSValue TemporalPlainYearMonthFunction { get => Slots[(int)Field.JS_TEMPORAL_PLAIN_YEAR_MONTH_FUNCTION_INDEX]; set => Slots[(int)Field.JS_TEMPORAL_PLAIN_YEAR_MONTH_FUNCTION_INDEX] = value; }
    public JSValue TemporalTimeZoneFunction { get => Slots[(int)Field.JS_TEMPORAL_TIME_ZONE_FUNCTION_INDEX]; set => Slots[(int)Field.JS_TEMPORAL_TIME_ZONE_FUNCTION_INDEX] = value; }
    public JSValue TemporalZonedDateTimeFunction { get => Slots[(int)Field.JS_TEMPORAL_ZONED_DATE_TIME_FUNCTION_INDEX]; set => Slots[(int)Field.JS_TEMPORAL_ZONED_DATE_TIME_FUNCTION_INDEX] = value; }
    public JSValue TemporalObject { get => Slots[(int)Field.TEMPORAL_OBJECT_INDEX]; set => Slots[(int)Field.TEMPORAL_OBJECT_INDEX] = value; }
}
