#!/usr/bin/env python3
# Generates dotnet/src/V8Sharp/Wasm/WasmOpcodes.Generated.cs from V8's
# src/wasm/wasm-opcodes.h: every opcode's name, encoding, signature and
# text-format name (the FOREACH_*_OPCODE lists).
#
#   python3 dotnet/tools/wasm-opcodes/gen_wasm_opcodes.py
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
HEADER = os.path.join(ROOT, "src", "wasm", "wasm-opcodes.h")
OUT = os.path.join(ROOT, "dotnet", "src", "V8Sharp", "Wasm", "WasmOpcodes.Generated.cs")

LISTS = [
    "FOREACH_CONTROL_OPCODE", "FOREACH_MISC_OPCODE", "FOREACH_LOAD_MEM_OPCODE",
    "FOREACH_STORE_MEM_OPCODE", "FOREACH_MISC_MEM_OPCODE", "FOREACH_SIMPLE_EXTENDED_CONST_OPCODE",
    "FOREACH_SIMPLE_NON_CONST_OPCODE", "FOREACH_SIGN_EXTENSION_OPCODE", "FOREACH_WASMFX_OPCODE",
    "FOREACH_SIMD_MEM_OPCODE", "FOREACH_SIMD_MEM_1_OPERAND_OPCODE", "FOREACH_SIMD_CONST_OPCODE",
    "FOREACH_SIMD_MASK_OPERAND_OPCODE", "FOREACH_SIMD_MVP_0_OPERAND_OPCODE", "FOREACH_RELAXED_SIMD_OPCODE",
    "FOREACH_SIMD_1_OPERAND_1_PARAM_OPCODE", "FOREACH_SIMD_1_OPERAND_2_PARAM_OPCODE",
    "FOREACH_NUMERIC_OPCODE_WIDE", "FOREACH_NUMERIC_OPCODE_WITH_SIG", "FOREACH_NUMERIC_OPCODE_VARIADIC",
    "FOREACH_ATOMIC_OPCODE", "FOREACH_ATOMIC_0_OPERAND_OPCODE", "FOREACH_GC_OPCODE",
    "FOREACH_ATOMIC_GC_OPCODE",
]


def macro_bodies(text):
    bodies = {}
    for m in re.finditer(r"#define (FOREACH_\w+)\(V\)((?:[^\n]*\\\n)*[^\n]*)", text):
        bodies[m.group(1)] = m.group(2)
    return bodies


def main():
    text = open(HEADER, encoding="utf-8").read()
    bodies = macro_bodies(text)
    entries = []
    for name in LISTS:
        body = bodies[name].replace("\\\n", " ")
        for m in re.finditer(r'V\((\w+),\s*(0x[0-9a-f]+),\s*(\w+),\s*"([^"]+)"(?:,\s*(\w+))?\)', body):
            entries.append((m.group(1), int(m.group(2), 16), m.group(3), m.group(4), m.group(5) or ""))
    seen = set()
    lines = []
    for (name, code, sig, wat, sig64) in entries:
        if name in seen:
            continue
        seen.add(name)
        lines.append((name, code, sig, wat, sig64))
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("// <auto-generated/>\n")
        f.write("// Generated from src/wasm/wasm-opcodes.h by dotnet/tools/wasm-opcodes/gen_wasm_opcodes.py.\n")
        f.write("// Do not edit.\n")
        f.write("namespace V8Sharp.Wasm;\n\n")
        f.write("public enum WasmOpcode\n{\n")
        for (name, code, sig, wat, sig64) in lines:
            f.write(f"    kExpr{name} = 0x{code:x},\n")
        f.write("}\n\n")
        f.write("public static partial class WasmOpcodes\n{\n")
        f.write("    /// <summary>(opcode, signature, memory64 signature, text name) of every opcode (V8: FOREACH_OPCODE).</summary>\n")
        f.write("    static readonly (WasmOpcode Opcode, string Signature, string Signature64, string Name)[] s_opcodes =\n    [\n")
        for (name, code, sig, wat, sig64) in lines:
            f.write(f'        (WasmOpcode.kExpr{name}, "{sig}", "{sig64}", "{wat}"),\n')
        f.write("    ];\n}\n")
    print(f"{len(lines)} opcodes -> {OUT}")


if __name__ == "__main__":
    sys.exit(main())
