// Port of src/deoptimizer/deoptimize-reason.{h,cc}: why optimized code
// deoptimized (eager and lazy reasons), with V8's messages for --trace-deopt.
namespace V8Sharp.Deoptimizer;

/// <summary>DeoptimizeReason (DEOPTIMIZE_REASON_LIST).</summary>
public enum DeoptimizeReason : byte
{
    kArrayBufferWasDetached,
    kArrayLengthChanged,
    kBigIntTooBig,
    kCouldNotGrowElements,
    kCowArrayElementsChanged,
    kDeoptimizeNow,
    kDivisionByZero,
    kGreaterThanMaxFastElementArray,
    kHole,
    kHoleOrUndefined,
    kInstanceMigrationFailed,
    kInsufficientTypeFeedbackForArrayLiteral,
    kInsufficientTypeFeedbackForBinaryOperation,
    kInsufficientTypeFeedbackForCall,
    kInsufficientTypeFeedbackForCompareOperation,
    kInsufficientTypeFeedbackForConstruct,
    kInsufficientTypeFeedbackForForIn,
    kInsufficientTypeFeedbackForGenericGlobalAccess,
    kInsufficientTypeFeedbackForGenericKeyedAccess,
    kInsufficientTypeFeedbackForGenericNamedAccess,
    kInsufficientTypeFeedbackForInstanceOf,
    kInsufficientTypeFeedbackForObjectLiteral,
    kInsufficientTypeFeedbackForTypeOf,
    kInsufficientTypeFeedbackForUnaryOperation,
    kKeyedAccessChanged,
    kLoopSpeculationFailed,
    kLostPrecision,
    kLostPrecisionOrNaN,
    kMinusZero,
    kNoInitialElement,
    kNotABigInt,
    kNotAHeapNumber,
    kNotAJavaScriptObject,
    kNotAJavaScriptObjectOrNullOrUndefined,
    kNotANumber,
    kNotANumberOrBoolean,
    kNotANumberOrOddball,
    kNotASmi,
    kNotAString,
    kNotAStringOrStringWrapper,
    kNotASymbol,
    kNotAnArrayIndex,
    kNotDetectableReceiver,
    kNotInt32,
    kNotUint32,
    kOSREarlyExit,
    kOutOfBounds,
    kOverflow,
    kPrepareForOnStackReplacement,
    kSmi,
    kStoreToConstant,
    kUnknown,
    kValueMismatch,
    kWrongCallTarget,
    kWrongConstructor,
    kWrongEnumIndices,
    kWrongFeedbackCell,
    kWrongInstanceType,
    kWrongMap,
    kWrongMapDynamic,
    kWrongName,
    kWrongValue,
}

/// <summary>LazyDeoptimizeReason (LAZY_DEOPTIMIZE_REASON_LIST).</summary>
public enum LazyDeoptimizeReason : byte
{
    kAllocationSiteTenuringChange,
    kAllocationSiteTransitionChange,
    kContextCellChange,
    kDebugger,
    kEagerDeopt,
    kEmptyContextExtensionChange,
    kExceptionCaught,
    kFieldRepresentationChange,
    kFieldTypeChange,
    kFieldTypeConstChange,
    kFrameValueMaterialized,
    kInitialMapChange,
    kMapDeprecated,
    kPrototypeChange,
    kPropertyCellChange,
    kTesting,
    kWeakObjects,
}

/// <summary>DeoptimizeKind.</summary>
public enum DeoptimizeKind : byte
{
    kEager,
    kLazy,
}

public static class DeoptimizeReasons
{
    /// <summary>DeoptimizeReasonToString.</summary>
    public static string ToString(DeoptimizeReason reason) => reason switch
    {
        DeoptimizeReason.kArrayBufferWasDetached => "array buffer was detached or immutable",
        DeoptimizeReason.kArrayLengthChanged => "the array length changed",
        DeoptimizeReason.kBigIntTooBig => "BigInt too big",
        DeoptimizeReason.kCouldNotGrowElements => "failed to grow elements store",
        DeoptimizeReason.kCowArrayElementsChanged => "copy-on-write array's elements changed",
        DeoptimizeReason.kDeoptimizeNow => "%_DeoptimizeNow",
        DeoptimizeReason.kDivisionByZero => "division by zero",
        DeoptimizeReason.kGreaterThanMaxFastElementArray => "length is greater than the maximum for fast elements array",
        DeoptimizeReason.kHole => "hole",
        DeoptimizeReason.kHoleOrUndefined => "hole or undefined",
        DeoptimizeReason.kInstanceMigrationFailed => "instance migration failed",
        DeoptimizeReason.kInsufficientTypeFeedbackForArrayLiteral => "Insufficient type feedback for array literal",
        DeoptimizeReason.kInsufficientTypeFeedbackForBinaryOperation => "Insufficient type feedback for binary operation",
        DeoptimizeReason.kInsufficientTypeFeedbackForCall => "Insufficient type feedback for call",
        DeoptimizeReason.kInsufficientTypeFeedbackForCompareOperation => "Insufficient type feedback for compare operation",
        DeoptimizeReason.kInsufficientTypeFeedbackForConstruct => "Insufficient type feedback for construct",
        DeoptimizeReason.kInsufficientTypeFeedbackForForIn => "Insufficient type feedback for for-in",
        DeoptimizeReason.kInsufficientTypeFeedbackForGenericGlobalAccess => "Insufficient type feedback for generic global access",
        DeoptimizeReason.kInsufficientTypeFeedbackForGenericKeyedAccess => "Insufficient type feedback for generic keyed access",
        DeoptimizeReason.kInsufficientTypeFeedbackForGenericNamedAccess => "Insufficient type feedback for generic named access",
        DeoptimizeReason.kInsufficientTypeFeedbackForInstanceOf => "Insufficient type feedback for instanceof",
        DeoptimizeReason.kInsufficientTypeFeedbackForObjectLiteral => "Insufficient type feedback for object literal",
        DeoptimizeReason.kInsufficientTypeFeedbackForTypeOf => "Insufficient type feedback for typeof",
        DeoptimizeReason.kInsufficientTypeFeedbackForUnaryOperation => "Insufficient type feedback for unary operation",
        DeoptimizeReason.kKeyedAccessChanged => "unexpected name in keyed access",
        DeoptimizeReason.kLoopSpeculationFailed => "loop speculation failed",
        DeoptimizeReason.kLostPrecision => "lost precision",
        DeoptimizeReason.kLostPrecisionOrNaN => "lost precision or NaN",
        DeoptimizeReason.kMinusZero => "minus zero",
        DeoptimizeReason.kNoInitialElement => "no initial element",
        DeoptimizeReason.kNotABigInt => "not a BigInt",
        DeoptimizeReason.kNotAHeapNumber => "not a heap number",
        DeoptimizeReason.kNotAJavaScriptObject => "not a JavaScript object",
        DeoptimizeReason.kNotAJavaScriptObjectOrNullOrUndefined => "not a JavaScript object, Null or Undefined",
        DeoptimizeReason.kNotANumber => "not a Number",
        DeoptimizeReason.kNotANumberOrBoolean => "not a Number or Boolean",
        DeoptimizeReason.kNotANumberOrOddball => "not a Number or Oddball",
        DeoptimizeReason.kNotASmi => "not a Smi",
        DeoptimizeReason.kNotAString => "not a String",
        DeoptimizeReason.kNotAStringOrStringWrapper => "not a String or a string wrapper",
        DeoptimizeReason.kNotASymbol => "not a Symbol",
        DeoptimizeReason.kNotAnArrayIndex => "not an array index",
        DeoptimizeReason.kNotDetectableReceiver => "not a detectable receiver",
        DeoptimizeReason.kNotInt32 => "not int32",
        DeoptimizeReason.kNotUint32 => "not unsigned int32",
        DeoptimizeReason.kOSREarlyExit => "exit from OSR'd inner loop",
        DeoptimizeReason.kOutOfBounds => "out of bounds",
        DeoptimizeReason.kOverflow => "overflow",
        DeoptimizeReason.kPrepareForOnStackReplacement => "prepare for on stack replacement (OSR)",
        DeoptimizeReason.kSmi => "Smi",
        DeoptimizeReason.kStoreToConstant => "Storing to a constant field",
        DeoptimizeReason.kValueMismatch => "value mismatch",
        DeoptimizeReason.kWrongCallTarget => "wrong call target",
        DeoptimizeReason.kWrongConstructor => "wrong call target constructor",
        DeoptimizeReason.kWrongEnumIndices => "wrong enum indices",
        DeoptimizeReason.kWrongFeedbackCell => "wrong feedback cell",
        DeoptimizeReason.kWrongInstanceType => "wrong instance type",
        DeoptimizeReason.kWrongMap => "wrong map",
        DeoptimizeReason.kWrongMapDynamic => "map changed during operation",
        DeoptimizeReason.kWrongName => "wrong name",
        DeoptimizeReason.kWrongValue => "wrong value",
        _ => "(unknown)",
    };

    public static string ToString(LazyDeoptimizeReason reason) => reason switch
    {
        LazyDeoptimizeReason.kAllocationSiteTenuringChange => "dependent allocation site tenuring changed",
        LazyDeoptimizeReason.kAllocationSiteTransitionChange => "dependent allocation site transition changed",
        LazyDeoptimizeReason.kContextCellChange => "dependent context cell state changed",
        LazyDeoptimizeReason.kDebugger => "JS debugger attached",
        LazyDeoptimizeReason.kEagerDeopt => "marked due to eager deopt",
        LazyDeoptimizeReason.kEmptyContextExtensionChange => "dependent empty context extension changed",
        LazyDeoptimizeReason.kExceptionCaught => "exception with omitted catch handler",
        LazyDeoptimizeReason.kFieldRepresentationChange => "dependent field representation changed",
        LazyDeoptimizeReason.kFieldTypeChange => "dependent field type changed",
        LazyDeoptimizeReason.kFieldTypeConstChange => "dependent field type constness changed",
        LazyDeoptimizeReason.kFrameValueMaterialized => "value in stack frame was materialized",
        LazyDeoptimizeReason.kInitialMapChange => "dependent initial map changed",
        LazyDeoptimizeReason.kMapDeprecated => "dependent map was deprecated",
        LazyDeoptimizeReason.kPrototypeChange => "dependent prototype chain changed",
        LazyDeoptimizeReason.kPropertyCellChange => "dependent property cell changed",
        LazyDeoptimizeReason.kTesting => "for testing",
        LazyDeoptimizeReason.kWeakObjects => "embedded weak objects cleared",
        _ => "(unknown)",
    };
}
