<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>V8Sharp.Parsing</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/V8Sharp.Base/V8Sharp.Base.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="V8Sharp.Parsing.Tests" />
  </ItemGroup>

</Project>
