# Generates dotnet/src/V8Sharp.Base/Ieee754.Tables.cs (run with python3): double-double tables
# for the table-driven kernels, computed with Python's decimal module at 80
# significant digits.
import os
import struct
from decimal import Decimal, getcontext
getcontext().prec = 80

def bits(f):
    return struct.unpack('<Q', struct.pack('<d', f))[0]

def dd(v):
    hi = float(v)
    lo = float(v - Decimal(hi))
    return hi, lo

def pi_value():
    def atan_inv(n, digits):
        one = 10 ** digits
        power = one // n; s = power; k = 1; n2 = n * n; sign = -1
        while power:
            power //= n2
            s += sign * (power // (2 * k + 1)); sign = -sign; k += 1
        return s
    D = 100
    return Decimal(16 * atan_inv(5, D) - 4 * atan_inv(239, D)) / Decimal(10) ** D

PI = pi_value()
LN2 = Decimal(2).ln()

def sin_cos(x):
    s = Decimal(0); c = Decimal(0)
    term = x; n = 1
    while term != 0 and abs(term) > Decimal(10) ** -90:
        s += term; term = -term * x * x / ((n + 1) * (n + 2)); n += 2
    term = Decimal(1); n = 0
    while abs(term) > Decimal(10) ** -90:
        c += term; term = -term * x * x / ((n + 1) * (n + 2)); n += 2
    return s, c

def atan(x):
    # x in [0, 1]
    h = 0
    while x > Decimal("0.05"):
        x = x / (1 + (1 + x * x).sqrt()); h += 1
    s = Decimal(0); term = x; k = 0; x2 = x * x
    while term != 0 and abs(term) > Decimal(10) ** -90:
        s += term / (2 * k + 1) * (-1 if k % 2 else 1); term *= x2; k += 1
    return s * (2 ** h)

out = []
def emit_dd_table(name, values, comment):
    out.append("    // " + comment)
    out.append("    static ReadOnlySpan<ulong> %s => [" % name)
    for v in values:
        hi, lo = dd(v)
        out.append("        0x%016X, 0x%016X, // %r" % (bits(hi), bits(lo), hi))
    out.append("    ];")
    out.append("")

# exp: 2^(j/128), j = 0..127.
emit_dd_table("ExpTable", [(LN2 * j / 128).exp() for j in range(128)], "2^(j/128) for j = 0..127, as (hi, lo).")

# log: for j = 0..127, f in [1 + j/128, 1 + (j+1)/128). invc ~ 1/center rounded
# to 21 bits; j = 0 uses 1 and j = 127 uses 0.5 so that arguments near 1 need
# no table term. For j >= 53 (centre above sqrt(2)) the entry is shifted by
# one binade: -log(2 invc), used with exponent e + 1.
inv = []
logs = []
import math
for j in range(128):
    center = 1 + (j + 0.5) / 128
    if j == 0:
        invc = 1.0
    elif j == 127:
        invc = 0.5
    else:
        m, e = math.frexp(1 / center)
        invc = math.ldexp(round(m * 2 ** 21), e - 21)
    inv.append(invc)
    if 1 + j / 128 >= 1.4140625 and j != 0:
        logs.append(-(Decimal(invc) * 2).ln() if j != 127 else Decimal(0))
    else:
        logs.append(-Decimal(invc).ln())
shift_from = next(j for j in range(128) if 1 + j / 128 >= 1.4140625)
out.append("    // log: first index whose entry is shifted by one binade.")
out.append("    const int kLogShiftIndex = %d;" % shift_from)
out.append("")
out.append("    // log: 1/c for f in [1 + j/128, 1 + (j+1)/128).")
out.append("    static ReadOnlySpan<ulong> LogInvC => [")
for v in inv:
    out.append("        0x%016X, // %r" % (bits(v), v))
out.append("    ];")
out.append("")
emit_dd_table("LogTable", logs, "log: -log(invc), or -log(2 invc) from kLogShiftIndex on, as (hi, lo).")

# sin/cos of j/64 for j = 0..51 (pi/4 < 51/64 + 1/128).
sc = [sin_cos(Decimal(j) / 64) for j in range(52)]
emit_dd_table("SinTable", [s for s, c in sc], "sin(j/64), j = 0..51, as (hi, lo).")
emit_dd_table("CosTable", [c for s, c in sc], "cos(j/64), j = 0..51, as (hi, lo).")

# atan(j/64) for j = 0..64.
emit_dd_table("AtanTable", [atan(Decimal(j) / 64) for j in range(65)], "atan(j/64), j = 0..64, as (hi, lo).")

consts = {
    "Ln2": LN2,
    "InvLn2": 1 / LN2,
    "InvLn10": 1 / Decimal(10).ln(),
    "Pi": PI,
    "HalfPi": PI / 2,
}
out.append("    // Constants as (hi, lo).")
for k, v in consts.items():
    hi, lo = dd(v)
    out.append("    const ulong k%sHi = 0x%016X, k%sLo = 0x%016X; // %r" % (k, bits(hi), k, bits(lo), hi))
out.append("")

# ln2/128 split: hi with 36 significant bits (n * hi exact for |n| < 2^17), lo.
v = LN2 / 128
m, e = math.frexp(float(v))
hi = math.ldexp(math.floor(m * 2 ** 36), e - 36)
lo = float(v - Decimal(hi))
lo2 = float(v - Decimal(hi) - Decimal(lo))
out.append("    // ln(2)/128 in three parts; the first has 36 significant bits.")
out.append("    const ulong kLn2Over128Hi = 0x%016X, kLn2Over128Mid = 0x%016X, kLn2Over128Lo = 0x%016X;" % (bits(hi), bits(lo), bits(lo2)))
out.append("")

header = '''// Tables for the table-driven kernels in Ieee754.Kernels.cs. Generated by a
// script from 80-digit decimal evaluations (independent of the multiprecision
// code in Ieee754.CorrectlyRounded.cs); do not edit by hand.

namespace V8Sharp.Base;

internal static partial class Ieee754Kernels
{
'''
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..", "src", "V8Sharp.Base", "Ieee754.Tables.cs"), "w").write(header + "\n".join(out).rstrip() + "\n}\n")
print("shift index", shift_from)
