# Generates dotnet/src/V8Sharp.Base/Numbers/ShortestDecimal.Table.cs (run
# with python3): g = floor(10^-k * 2^-r) + 1 with r = floor(-k log2(10)) - 125,
# so that 2^125 <= g < 2^126, for k in [-324, 292], split as (g >> 63,
# g & (2^63 - 1)). Also checks the integer approximations of the logarithms
# used by ShortestDecimal.cs over the whole range they are used in.
import os
from fractions import Fraction
import math

K_MIN, K_MAX = -324, 292

def flog10pow2(q): return (q * 661971961083) >> 41
def flog10three_quarters_pow2(q): return (q * 661971961083 - 274743187321) >> 41
def flog2pow10(e): return (e * 913124641741) >> 38

def exact_floor_log(num, base):
    # floor(log_base(num)) for a positive Fraction.
    k = math.floor(math.log(num.numerator, base) - math.log(num.denominator, base))
    while Fraction(base) ** (k + 1) <= num: k += 1
    while Fraction(base) ** k > num: k -= 1
    return k

for q in range(-1100, 1100):
    assert flog10pow2(q) == exact_floor_log(Fraction(2) ** q, 10), q
    assert flog10three_quarters_pow2(q) == exact_floor_log(Fraction(3, 4) * Fraction(2) ** q, 10), q
for e in range(-400, 400):
    assert flog2pow10(e) == exact_floor_log(Fraction(10) ** e, 2), e

lines = []
for k in range(K_MIN, K_MAX + 1):
    r = flog2pow10(-k) - 125
    g = math.floor(Fraction(10) ** (-k) / Fraction(2) ** r) + 1
    assert (1 << 125) <= g < (1 << 126), k
    lines.append("        0x%016X, 0x%016X, // %d" % (g >> 63, g & ((1 << 63) - 1), k))

src = """// The table of ShortestDecimal.cs. Generated by
// tests/V8Sharp.Base.Tests/Generators/gen_schubfach_table.py; do not edit by hand.

namespace V8Sharp.Base.Numbers;

internal static partial class ShortestDecimal
{
    const int kKMin = %d;
    const int kKMax = %d;

    // g1(k), g0(k) for k = kKMin .. kKMax.
    static ReadOnlySpan<ulong> G => [
%s
    ];
}
""" % (K_MIN, K_MAX, "\n".join(lines))
here = os.path.dirname(os.path.abspath(__file__))
open(os.path.join(here, "..", "..", "..", "src", "V8Sharp.Base", "Numbers", "ShortestDecimal.Table.cs"), "w").write(src)
print("ok")
