# Generates dotnet/src/V8Sharp.Base/Numbers/FastFloat.Table.cs (run with
# python3): 5^q for q in [-342, 308] as 128-bit values normalized to
# [2^127, 2^128), truncated for q >= 0 and taken from ceil(2^b / 5^-q) for
# q < 0, as fast_float's table is. Each entry is (high 64 bits, low 64 bits).
import os

lines = []
for q in range(-342, 309):
    if q >= 0:
        v = 5 ** q
        while v < (1 << 127):
            v <<= 1
        while v >= (1 << 128):
            v >>= 1
    else:
        p = 5 ** -q
        z = p.bit_length()
        b = z + 127 + 64
        v = (1 << b) // p + 1
        while v >= (1 << 128):
            v >>= 1
    lines.append("        0x%016X, 0x%016X, // 5^%d" % (v >> 64, v & ((1 << 64) - 1), q))

src = """// 128-bit approximations of the powers of five for the Eisel-Lemire
// algorithm in FastFloat.cs. Generated by
// tests/V8Sharp.Base.Tests/Generators/gen_power5_table.py; do not edit by hand.

namespace V8Sharp.Base.Numbers;

internal static partial class FastFloat
{
    const int kSmallestPowerOfFive = -342;
    const int kLargestPowerOfFive = 308;

    static ReadOnlySpan<ulong> PowersOfFive => [
%s
    ];
}
""" % "\n".join(lines)
here = os.path.dirname(os.path.abspath(__file__))
open(os.path.join(here, "..", "..", "..", "src", "V8Sharp.Base", "Numbers", "FastFloat.Table.cs"), "w").write(src)
