// Port of src/regexp/experimental/experimental-compiler.h and
// experimental-compiler.cc.

namespace V8Sharp.RegExp.Experimental;

public static class ExperimentalCompiler
{
    /// <summary>--experimental-regexp-engine-capture-group-opt (default false).</summary>
    public static bool s_experimentalRegExpEngineCaptureGroupOpt;

    // TODO(mbid, v8:10765): Currently the experimental engine doesn't support
    // UTF-16, but this shouldn't be too hard to implement.
    internal const int kMaxSupportedCodepoint = 0xFFFF;

    // Checks whether a given Tree can be compiled into an experimental
    // bytecode program.  This mostly amounts to the absence of back references,
    // but see the definition.
    // TODO(mbid,v8:10765): Currently more things are not handled, e.g. some
    // quantifiers and unicode.
    public static bool CanBeHandled(RegExpTree tree, RegExpFlags flags, int captureCount) =>
        CanBeHandledVisitor.Check(tree, flags, captureCount);

    // Compile regexp into a bytecode program.  The regexp must be handleable by
    // the experimental engine; see`CanBeHandled`.  The program is returned as a
    // list of instructions.
    public static List<Instruction> Compile(RegExpTree tree, RegExpFlags flags) =>
        CompileVisitor.Compile(tree, flags);

    sealed class CanBeHandledVisitor : IRegExpVisitor
    {
        // Visitor to implement `ExperimentalRegExp::CanBeHandled`.
        public static bool Check(RegExpTree tree, RegExpFlags flags, int captureCount)
        {
            if (!AreSuitableFlags(flags)) return false;
            var visitor = new CanBeHandledVisitor(flags);
            tree.Accept(visitor, null);
            return visitor._result;
        }

        readonly RegExpFlags _flags;
        // See comment in `VisitQuantifier`:
        int _replicationFactor = 1;
        bool _result = true;

        CanBeHandledVisitor(RegExpFlags flags) => _flags = flags;

        static bool AreSuitableFlags(RegExpFlags flags)
        {
            // TODO(mbid, v8:10765): We should be able to support all flags in the
            // future.
            const RegExpFlags kAllowedFlags = RegExpFlags.Global | RegExpFlags.Sticky | RegExpFlags.Multiline |
                                              RegExpFlags.DotAll | RegExpFlags.Linear;
            // We support Unicode iff kUnicode is among the supported flags.
            return (flags & ~kAllowedFlags) == 0;
        }

        public object? VisitDisjunction(RegExpDisjunction node, object? data)
        {
            foreach (RegExpTree alt in node.Alternatives)
            {
                alt.Accept(this, null);
                if (!_result) return null;
            }
            return null;
        }

        public object? VisitAlternative(RegExpAlternative node, object? data)
        {
            foreach (RegExpTree child in node.Nodes)
            {
                child.Accept(this, null);
                if (!_result) return null;
            }
            return null;
        }

        public object? VisitClassRanges(RegExpClassRanges node, object? data) => null;

        public object? VisitClassSetOperand(RegExpClassSetOperand node, object? data)
        {
            _result = !node.HasStrings;
            return null;
        }

        public object? VisitClassSetExpression(RegExpClassSetExpression node, object? data)
        {
            _result = false;
            return null;
        }

        public object? VisitAssertion(RegExpAssertion node, object? data) => null;

        public object? VisitAtom(RegExpAtom node, object? data) => null;

        public object? VisitText(RegExpText node, object? data)
        {
            foreach (TextElement el in node.Elements)
            {
                el.Tree.Accept(this, null);
                if (!_result) return null;
            }
            return null;
        }

        public object? VisitQuantifier(RegExpQuantifier node, object? data)
        {
            // Finite but large values of `min()` and `max()` are bad for the
            // breadth-first engine because finite (optional) repetition is dealt with
            // by replicating the bytecode of the body of the quantifier.  The number
            // of replications grows exponentially in how deeply quantifiers are nested.
            // `replication_factor_` keeps track of how often the current node will
            // have to be replicated in the generated bytecode, and we don't allow this
            // to exceed some small value.
            const int kMaxReplicationFactor = 16;

            // First we rule out values for min and max that are too big even before
            // taking into account the ambient replication_factor_.  This also guards
            // against overflows in `local_replication` or `replication_factor_`.
            if (node.Min > kMaxReplicationFactor ||
                (node.Max != RegExpTree.kInfinity && node.Max > kMaxReplicationFactor))
            {
                _result = false;
                return null;
            }

            // Save the current replication factor so that it can be restored if we
            // return with `result_ == true`.
            int beforeReplicationFactor = _replicationFactor;

            int localReplication;
            if (node.Max == RegExpTree.kInfinity)
            {
                if (node.Min > 0 && node.MinMatch > 0)
                {
                    // Quantifier can be reduced to a non nullable plus.
                    localReplication = Math.Max(node.Min, 1);
                }
                else
                {
                    localReplication = node.Min + 1;
                }
            }
            else
            {
                localReplication = node.Max;
            }

            _replicationFactor *= localReplication;
            if (_replicationFactor > kMaxReplicationFactor)
            {
                _result = false;
                return null;
            }

            switch (node.Type)
            {
                case RegExpQuantifier.QuantifierType.GREEDY:
                case RegExpQuantifier.QuantifierType.NON_GREEDY:
                    break;
                case RegExpQuantifier.QuantifierType.POSSESSIVE:
                    // TODO(mbid, v8:10765): It's not clear to me whether this can be
                    // supported in breadth-first mode. Re2 doesn't support it.
                    _result = false;
                    return null;
            }

            node.Body.Accept(this, null);
            _replicationFactor = beforeReplicationFactor;
            return null;
        }

        public object? VisitCapture(RegExpCapture node, object? data)
        {
            node.Body.Accept(this, null);
            return null;
        }

        public object? VisitGroup(RegExpGroup node, object? data)
        {
            if (_flags != node.Flags)
            {
                // Flags that aren't supported by the experimental engine at all, are not
                // supported via modifiers either.
                if (!AreSuitableFlags(node.Flags))
                {
                    _result = false;
                    return null;
                }
            }
            node.Body.Accept(this, null);
            return null;
        }

        public object? VisitLookaround(RegExpLookaround node, object? data)
        {
            if (_flags.IsGlobal() || _flags.IsSticky())
            {
                _result = false;
                return null;
            }

            // If `experimental_regexp_engine_capture_group_opt` is false, reject all
            // lookaheads or capturing lookbehinds.
            if (!s_experimentalRegExpEngineCaptureGroupOpt &&
                (node.LookaroundType == RegExpLookaround.Type.LOOKAHEAD || node.CaptureCount > 0))
            {
                _result = false;
                return null;
            }

            node.Body.Accept(this, null);
            return null;
        }

        public object? VisitBackReference(RegExpBackReference node, object? data)
        {
            // This can't be implemented without backtracking.
            _result = false;
            return null;
        }

        public object? VisitEmpty(RegExpEmpty node, object? data) => null;
    }

    // A label in bytecode which starts with no known address. The address *must*
    // be bound with `Bind` before the label goes out of scope.
    // Implemented as a linked list through the `payload.pc` of FORK and JMP
    // instructions.
    sealed class Label
    {
        public bool Bound;
        // UNBOUND implies unbound_patch_list_begin_; BOUND implies bound_index_.
        public int UnboundPatchListBegin = -1;
        public int BoundIndex;
    }

    sealed class BytecodeAssembler
    {
        readonly List<Instruction> _code = [];

        public List<Instruction> IntoCode() => _code;

        public void Accept() => _code.Add(Instruction.Accept());
        public void Assertion(RegExpAssertion.Type t) => _code.Add(Instruction.Assertion(t));
        public void ClearRegister(int registerIndex) => _code.Add(Instruction.ClearRegister(registerIndex));
        public void ConsumeRange(char from, char to) => _code.Add(Instruction.ConsumeRange(from, to));
        public void ConsumeAnyChar() => _code.Add(Instruction.ConsumeAnyChar());
        public void RangeCount(int numRanges) => _code.Add(Instruction.RangeCount(numRanges));
        public void Fork(Label target) => LabelledInstrImpl(Instruction.Opcode.FORK, target);
        public void Jmp(Label target) => LabelledInstrImpl(Instruction.Opcode.JMP, target);
        public void SetRegisterToCp(int registerIndex) => _code.Add(Instruction.SetRegisterToCp(registerIndex));
        public void BeginLoop() => _code.Add(Instruction.BeginLoop());
        public void EndLoop() => _code.Add(Instruction.EndLoop());

        public void StartLookaround(int lookaroundIndex, bool isPositive, RegExpLookaround.Type type) =>
            _code.Add(Instruction.StartLookaround(lookaroundIndex, isPositive, type));

        public void EndLookaround() => _code.Add(Instruction.EndLookaround());
        public void WriteLookaroundTable(int index) => _code.Add(Instruction.WriteLookTable(index));

        public void ReadLookaroundTable(int index, bool isPositive, RegExpLookaround.Type type) =>
            _code.Add(Instruction.ReadLookTable(index, isPositive, type));

        public void SetQuantifierToClock(int quantifierId) =>
            _code.Add(Instruction.SetQuantifierToClock(quantifierId));

        public void FilterQuantifier(int quantifierId) => _code.Add(Instruction.FilterQuantifier(quantifierId));
        public void FilterGroup(int groupId) => _code.Add(Instruction.FilterGroup(groupId));
        public void FilterLookaround(int lookaroundId) => _code.Add(Instruction.FilterLookaround(lookaroundId));
        public void FilterChild(Label target) => LabelledInstrImpl(Instruction.Opcode.FILTER_CHILD, target);

        public void Bind(Label target)
        {
            Debug.Assert(!target.Bound);

            int index = _code.Count;

            while (target.UnboundPatchListBegin != -1)
            {
                Instruction inst = _code[target.UnboundPatchListBegin];
                Debug.Assert(inst.opcode is Instruction.Opcode.FORK or Instruction.Opcode.JMP
                    or Instruction.Opcode.FILTER_CHILD);

                int at = target.UnboundPatchListBegin;
                target.UnboundPatchListBegin = inst.Pc;
                _code[at] = inst.WithPc(index);
            }

            target.Bound = true;
            target.BoundIndex = index;
        }

        public void Fail() => _code.Add(Instruction.Fail());

        void LabelledInstrImpl(Instruction.Opcode op, Label target)
        {
            int pc;
            if (target.Bound)
            {
                pc = target.BoundIndex;
            }
            else
            {
                int newListBegin = _code.Count;
                pc = target.UnboundPatchListBegin;
                target.UnboundPatchListBegin = newListBegin;
            }

            _code.Add(op switch
            {
                Instruction.Opcode.FORK => Instruction.Fork(pc),
                Instruction.Opcode.JMP => Instruction.Jmp(pc),
                _ => Instruction.FilterChild(pc),
            });
        }
    }

    sealed class FilterGroupsCompileVisitor : IRegExpVisitor
    {
        public static void CompileFilter(RegExpTree tree, BytecodeAssembler assembler,
            Dictionary<int, int> quantifierIdRemapping, Dictionary<int, int> lookaroundIdRemapping)
        {
            // To filter out groups that were not matched in the last iteration of a
            // quantifier, the regexp's AST is compiled using a special sets of
            // instructions: `FILTER_GROUP`, `FILTER_QUANTIFIER` and `FILTER_CHILD`.
            // They encode a simplified AST containing only the groups and quantifiers.
            // Each node is represented as either a `FILTER_GROUP` or a
            // `FILTER_QUANTIFIER` instruction, containing the index of the respective
            // group or quantifier, followed by a variable number of `FILTER_CHILD`
            // instructions each containing the index of their respective node in the
            // bytecode.
            //
            // The regexp's AST is traversed in breadth-first mode, compiling one node
            // at a time, while saving its children in a queue.
            var visitor = new FilterGroupsCompileVisitor(assembler, quantifierIdRemapping, lookaroundIdRemapping);

            tree.Accept(visitor, null);

            while (visitor._nodes.Count != 0)
            {
                BFEntry entry = visitor._nodes.First!.Value;

                visitor._assembler.Bind(entry.Label);
                visitor._canCompileNode = true;
                entry.Node.Accept(visitor, null);

                visitor._nodes.RemoveFirst();
            }
        }

        readonly BytecodeAssembler _assembler;
        readonly LinkedList<BFEntry> _nodes = new();
        // Whether we can compile a node or we should add it to `nodes_`. This is
        // set to true after popping an element from the queue, and false after
        // having compiled one.
        bool _canCompileNode;
        readonly Dictionary<int, int> _quantifierIdRemapping;
        // The lookarounds ids are remapped to be contiguous. This may not already be
        // the case, since parts of the AST may be optimized out during parsing.
        readonly Dictionary<int, int> _lookaroundIdRemapping;

        sealed class BFEntry(RegExpTree node)
        {
            public readonly Label Label = new();
            public readonly RegExpTree Node = node;
        }

        FilterGroupsCompileVisitor(BytecodeAssembler assembler, Dictionary<int, int> quantifierIdRemapping,
            Dictionary<int, int> lookaroundIdRemapping)
        {
            _assembler = assembler;
            _quantifierIdRemapping = quantifierIdRemapping;
            _lookaroundIdRemapping = lookaroundIdRemapping;
        }

        public object? VisitDisjunction(RegExpDisjunction node, object? data)
        {
            foreach (RegExpTree alt in node.Alternatives) alt.Accept(this, null);
            return null;
        }

        public object? VisitAlternative(RegExpAlternative node, object? data)
        {
            foreach (RegExpTree alt in node.Nodes) alt.Accept(this, null);
            return null;
        }

        public object? VisitClassRanges(RegExpClassRanges node, object? data) => null;
        public object? VisitClassSetOperand(RegExpClassSetOperand node, object? data) => null;
        public object? VisitClassSetExpression(RegExpClassSetExpression node, object? data) => null;
        public object? VisitAssertion(RegExpAssertion node, object? data) => null;
        public object? VisitAtom(RegExpAtom node, object? data) => null;
        public object? VisitText(RegExpText node, object? data) => null;

        public object? VisitQuantifier(RegExpQuantifier node, object? data)
        {
            if (node.Max == 0) return null;

            if (_canCompileNode)
            {
                _assembler.FilterQuantifier(_quantifierIdRemapping[node.Index]);
                _canCompileNode = false;
                node.Body.Accept(this, null);
            }
            else
            {
                // TODO(v8:10765): Handle stack overflow instead of passing unlimited max
                // depth here and below.
                if (node.CaptureRegisters(new StackLimiter(int.MaxValue)).IsEmpty) return null;

                _nodes.AddLast(new BFEntry(node));
                _assembler.FilterChild(_nodes.Last!.Value.Label);
            }

            return null;
        }

        public object? VisitCapture(RegExpCapture node, object? data)
        {
            if (_canCompileNode)
            {
                _assembler.FilterGroup(node.Index);
                _canCompileNode = false;
                node.Body.Accept(this, null);
            }
            else
            {
                _nodes.AddLast(new BFEntry(node));
                _assembler.FilterChild(_nodes.Last!.Value.Label);
            }

            return null;
        }

        public object? VisitGroup(RegExpGroup node, object? data)
        {
            node.Body.Accept(this, null);
            return null;
        }

        public object? VisitLookaround(RegExpLookaround node, object? data)
        {
            if (_canCompileNode)
            {
                _assembler.FilterLookaround(_lookaroundIdRemapping[node.Index]);
                _canCompileNode = false;
                node.Body.Accept(this, null);
            }
            else
            {
                if (node.CaptureRegisters(new StackLimiter(int.MaxValue)).IsEmpty) return null;

                _nodes.AddLast(new BFEntry(node));
                _assembler.FilterChild(_nodes.Last!.Value.Label);
            }

            return null;
        }

        public object? VisitBackReference(RegExpBackReference node, object? data) => null;
        public object? VisitEmpty(RegExpEmpty node, object? data) => null;
    }

    sealed class CompileVisitor : IRegExpVisitor
    {
        public static List<Instruction> Compile(RegExpTree tree, RegExpFlags flags)
        {
            var compiler = new CompileVisitor();

            if (!flags.IsSticky() && !tree.IsCertainlyAnchoredAtStart(RegExpNode.kRecursionBudget))
            {
                // The match is not anchored, i.e. may start at any input position, so we
                // emit a preamble corresponding to /.*?/.  This skips an arbitrary
                // prefix in the input non-greedily.
                compiler.CompileNonGreedyStar(static c => c._assembler.ConsumeAnyChar());
            }

            compiler._assembler.SetRegisterToCp(0);
            tree.Accept(compiler, null);
            compiler._assembler.SetRegisterToCp(1);
            compiler._assembler.Accept();

            // Each lookaround is compiled as two different bytecode sections: a
            // reverse, captureless automaton and a capturing one. The indexes are
            // remapped to avoid holes in the lookaround table, which would occur when
            // lookarounds are optimized out of the AST. The resulting indexes have the
            // following order: lookarounds can only depend on ones with a higher index.
            //
            // During the compilation of the main expression, lookarounds are not
            // immediately compiled, and are instead pushed at the back of a queue.
            // After compiling the filtering instructions, the queue is emptied and
            // each lookaround body is compiled into two sections:
            //
            // 1. A non-capturing automaton, which is reversed if it is a lookahead.
            // 2. A capturing automaton, reversed if it is a lookbehind. Since it is
            //    only used for capturing, it can be empty if the lookaround does
            //    not contain any captures.
            while (compiler._lookarounds.Count != 0)
            {
                RegExpLookaround node = compiler._lookarounds.First!.Value;
                compiler.CompileLookaround(node);
                compiler._lookarounds.RemoveFirst();
            }

            if (s_experimentalRegExpEngineCaptureGroupOpt)
            {
                FilterGroupsCompileVisitor.CompileFilter(tree, compiler._assembler,
                    compiler._quantifierIdRemapping!, compiler._lookaroundIdRemapping);
            }

            return compiler._assembler.IntoCode();
        }

        // Stores the AST of the lookbehinds encountered in a queue. They are compiled
        // after the main expression, in breadth-first order.
        readonly LinkedList<RegExpLookaround> _lookarounds = new();
        readonly Dictionary<int, int>? _quantifierIdRemapping;
        readonly Dictionary<int, int> _lookaroundIdRemapping = new();
        readonly BytecodeAssembler _assembler = new();
        bool _reverse;
        // Do not produce `SET_REGISTER_TO_CP` instructions. Used when compiling
        // the lookarounds' matching automata, since the capture results will be never
        // be used.
        bool _ignoreCaptures;
        // Indicates whether the encountered lookarounds should be pushed into the
        // queue. Set when compiling the lookarounds' capturing automata, as the
        // children lookarounds where already pushed while compiling the matching
        // automata.
        bool _ignoreLookarounds;

        CompileVisitor()
        {
            if (s_experimentalRegExpEngineCaptureGroupOpt) _quantifierIdRemapping = new Dictionary<int, int>();
        }

        // Generate all the instructions to match and capture a lookaround.
        void CompileLookaround(RegExpLookaround lookaround)
        {
            // Generate the first section, reversed in the case of a lookahead.
            _assembler.StartLookaround(RemapLookaround(lookaround.Index), lookaround.IsPositive,
                lookaround.LookaroundType);

            // If the lookaround is not anchored, we add a /.*?/ at its start, such
            // that the resulting automaton will run over the whole input.
            if ((lookaround.LookaroundType == RegExpLookaround.Type.LOOKAHEAD &&
                 !lookaround.Body.IsCertainlyAnchoredAtEnd(RegExpNode.kRecursionBudget)) ||
                (lookaround.LookaroundType == RegExpLookaround.Type.LOOKBEHIND &&
                 !lookaround.Body.IsCertainlyAnchoredAtStart(RegExpNode.kRecursionBudget)))
            {
                CompileNonGreedyStar(static c => c._assembler.ConsumeAnyChar());
            }

            _reverse = lookaround.LookaroundType == RegExpLookaround.Type.LOOKAHEAD;

            _ignoreCaptures = true;
            lookaround.Body.Accept(this, null);
            _ignoreCaptures = false;

            _assembler.WriteLookaroundTable(RemapLookaround(lookaround.Index));

            // Generate the second sections, reversed in the case of a lookbehind.
            if (lookaround.CaptureCount > 0 && lookaround.IsPositive)
            {
                _reverse = lookaround.LookaroundType == RegExpLookaround.Type.LOOKBEHIND;

                _ignoreLookarounds = true;
                lookaround.Body.Accept(this, null);
                _ignoreLookarounds = false;
            }

            _assembler.EndLookaround();
        }

        // Generate a disjunction of code fragments compiled by a function
        // `alt_gen`. `alt_gen` is called repeatedly with argument `int i = 0, 1,
        // ..., alt_num - 1` and should build code corresponding to the ith
        // alternative.
        void CompileDisjunction(List<RegExpTree> alts)
        {
            // An alternative a1 | ... | an is compiled into
            //
            //     FORK tail1
            //     <a1>
            //     JMP end
            //   tail1:
            //     FORK tail2
            //     <a2>
            //     JMP end
            //   tail2:
            //     ...
            //     ...
            //   tail{n -1}:
            //     <an>
            //   end:
            //
            // By the semantics of the FORK instruction (see above at definition and
            // semantics), a forked thread has lower priority than the thread that
            // spawned it.  This means that with the code we're generating here, the
            // thread matching the alternative a1 has indeed highest priority, followed
            // by the thread for a2 and so on.
            int altNum = alts.Count;
            if (altNum == 0)
            {
                // The empty disjunction.  This can never match.
                _assembler.Fail();
                return;
            }

            var end = new Label();

            for (int i = 0; i != altNum - 1; ++i)
            {
                var tail = new Label();
                _assembler.Fork(tail);
                alts[i].Accept(this, null);
                _assembler.Jmp(end);
                _assembler.Bind(tail);
            }

            alts[altNum - 1].Accept(this, null);

            _assembler.Bind(end);
        }

        public object? VisitDisjunction(RegExpDisjunction node, object? data)
        {
            CompileDisjunction(node.Alternatives);
            return null;
        }

        public object? VisitAlternative(RegExpAlternative node, object? data)
        {
            if (_reverse)
            {
                List<RegExpTree> children = node.Nodes;
                for (int i = children.Count - 1; i >= 0; --i) children[i].Accept(this, null);
            }
            else
            {
                foreach (RegExpTree child in node.Nodes) child.Accept(this, null);
            }
            return null;
        }

        public object? VisitAssertion(RegExpAssertion node, object? data)
        {
            _assembler.Assertion(node.AssertionType);
            return null;
        }

        void CompileCharacterRanges(List<CharacterRange> ranges, bool negated)
        {
            // A character class is compiled as disjoint character ranges.
            // A single range is represented by a single `CONSUME_RANGE` instruction.
            // Disjoint ranges are represented by a `RANGE_COUNT` instruction followed
            // by `CONSUME_RANGE` instructions.
            CharacterRange.Canonicalize(ranges);
            if (negated)
            {
                // The complement of a disjoint, non-adjacent (i.e. `Canonicalize`d)
                // union of k intervals is a union of at most k + 1 intervals.
                var negatedRanges = new List<CharacterRange>(ranges.Count + 1);
                CharacterRange.Negate(ranges, negatedRanges);
                Debug.Assert(negatedRanges.Count <= ranges.Count + 1);
                ranges = negatedRanges;
            }

            if (ranges.Count == 0)
            {
                _assembler.Fail();
                return;
            }

            if (ranges.Count > 1)
            {
                // In the case of a multiple ranges, we need a RANGE_COUNT instruction.
                _assembler.RangeCount(ranges.Count);
            }

            for (int i = 0; i < ranges.Count; ++i)
            {
                // We don't support utf16 for now, so only ranges that can be specified
                // by (complements of) ranges with base::uc16 bounds.
                int from = ranges[i].From;
                int to = ranges[i].To;

                // Special case for [^\x00-￿]: This will create a from value outside
                // the supported codepoint range even in non-unicode mode. Since we can't
                // match any character for this pattern in non-unicode mode, we fail.
                if (from > kMaxSupportedCodepoint && to > kMaxSupportedCodepoint)
                {
                    Debug.Assert(negated);
                    _assembler.Fail();
                    return;
                }

                Debug.Assert(from <= kMaxSupportedCodepoint);
                char fromUc16 = (char)from;
                char toUc16 = (char)Math.Min(to, kMaxSupportedCodepoint);

                _assembler.ConsumeRange(fromUc16, toUc16);
            }
        }

        public object? VisitClassRanges(RegExpClassRanges node, object? data)
        {
            CompileCharacterRanges(node.Ranges, node.IsNegated);
            return null;
        }

        public object? VisitClassSetOperand(RegExpClassSetOperand node, object? data)
        {
            // TODO(v8:11935): Support strings.
            Debug.Assert(!node.HasStrings);
            CompileCharacterRanges(node.Ranges, false);
            return null;
        }

        // TODO(v8:11935): Add support.
        public object? VisitClassSetExpression(RegExpClassSetExpression node, object? data) =>
            throw new InvalidOperationException("UNREACHABLE");

        public object? VisitAtom(RegExpAtom node, object? data)
        {
            string d = node.Data;
            if (_reverse)
            {
                for (int i = d.Length - 1; i >= 0; --i) _assembler.ConsumeRange(d[i], d[i]);
            }
            else
            {
                foreach (char c in d) _assembler.ConsumeRange(c, c);
            }
            return null;
        }

        void ClearRegisters(Interval indices)
        {
            if (indices.IsEmpty) return;
            Debug.Assert(indices.From % 2 == 0);
            Debug.Assert(indices.To % 2 == 1);
            for (int i = indices.From; i <= indices.To; i += 2)
            {
                // It suffices to clear the register containing the `begin` of a capture
                // because this indicates that the capture is undefined, regardless of
                // the value in the `end` register.
                _assembler.ClearRegister(i);
            }
        }

        // Emit bytecode corresponding to /<emit_body>*/.
        void CompileGreedyStar(Action<CompileVisitor> emitBody)
        {
            // This is compiled into
            //
            //   begin:
            //     FORK end
            //     BEGIN_LOOP
            //     <body>
            //     END_LOOP
            //     JMP begin
            //   end:
            //     ...
            //
            // This is greedy because a forked thread has lower priority than the
            // thread that spawned it.
            var begin = new Label();
            var end = new Label();

            _assembler.Bind(begin);
            _assembler.Fork(end);
            _assembler.BeginLoop();
            emitBody(this);
            _assembler.EndLoop();
            _assembler.Jmp(begin);

            _assembler.Bind(end);
        }

        // Emit bytecode corresponding to /<emit_body>*?/.
        void CompileNonGreedyStar(Action<CompileVisitor> emitBody)
        {
            // This is compiled into
            //
            //     FORK body
            //     JMP end
            //   body:
            //     BEGIN_LOOP
            //     <body>
            //     END_LOOP
            //     FORK body
            //   end:
            //     ...
            var body = new Label();
            var end = new Label();

            _assembler.Fork(body);
            _assembler.Jmp(end);

            _assembler.Bind(body);
            _assembler.BeginLoop();
            emitBody(this);
            _assembler.EndLoop();
            _assembler.Fork(body);

            _assembler.Bind(end);
        }

        // Emit bytecode corresponding to /<emit_body>{0, max_repetition_num}/.
        void CompileGreedyRepetition(Action<CompileVisitor> emitBody, int maxRepetitionNum)
        {
            // This is compiled into
            //
            //     FORK end
            //     BEGIN_LOOP
            //     <body>
            //     END_LOOP
            //     FORK end
            //     BEGIN_LOOP
            //     <body>
            //     END_LOOP
            //     ...
            //     ...
            //     FORK end
            //     <body>
            //   end:
            //     ...
            //
            // We add `BEGIN_LOOP` and `END_LOOP` instructions because these optional
            // repetitions of the body cannot match the empty string.
            var end = new Label();
            for (int i = 0; i != maxRepetitionNum; ++i)
            {
                _assembler.Fork(end);
                _assembler.BeginLoop();
                emitBody(this);
                _assembler.EndLoop();
            }
            _assembler.Bind(end);
        }

        // Emit bytecode corresponding to /<emit_body>{0, max_repetition_num}?/.
        void CompileNonGreedyRepetition(Action<CompileVisitor> emitBody, int maxRepetitionNum)
        {
            // This is compiled into
            //
            //     FORK body0
            //     JMP end
            //   body0:
            //     BEGIN_LOOP
            //     <body>
            //     END_LOOP
            //
            //     FORK body1
            //     JMP end
            //   body1:
            //     BEGIN_LOOP
            //     <body>
            //     END_LOOP
            //     ...
            //     ...
            //   body{max_repetition_num - 1}:
            //     BEGIN_LOOP
            //     <body>
            //     END_LOOP
            //   end:
            //     ...
            //
            // We add `BEGIN_LOOP` and `END_LOOP` instructions because these optional
            // repetitions of the body cannot match the empty string.
            var end = new Label();
            for (int i = 0; i != maxRepetitionNum; ++i)
            {
                var body = new Label();
                _assembler.Fork(body);
                _assembler.Jmp(end);

                _assembler.Bind(body);
                _assembler.BeginLoop();
                emitBody(this);
                _assembler.EndLoop();
            }
            _assembler.Bind(end);
        }

        // In the particular case where <body> cannot match the empty string, the
        // plus can be compiled without duplicating the bytecode of <body>, resulting
        // in a bytecode linear in the size of the regex in case of nested
        // non-nullable pluses.
        //
        // E.g. `/.+/` will compile `/./` once, while `/(?:.?)+/` will be compiled as
        // `/(?:.?)(?:.?)*/`, resulting in two repetitions of the body.

        // Emit bytecode corresponding to /<emit_body>+/, with <emit_body> not
        // nullable.
        void CompileNonNullableGreedyPlus(Action<CompileVisitor> emitBody)
        {
            // This is compiled into
            //
            //   begin:
            //     <body>
            //
            //     FORK end
            //     JMP begin
            //   end:
            //     ...
            var begin = new Label();
            var end = new Label();

            _assembler.Bind(begin);
            emitBody(this);

            _assembler.Fork(end);
            _assembler.Jmp(begin);
            _assembler.Bind(end);
        }

        // Emit bytecode corresponding to /<emit_body>+?/, with <emit_body> not
        // nullable.
        void CompileNonNullableNonGreedyPlus(Action<CompileVisitor> emitBody)
        {
            // This is compiled into
            //
            //   begin:
            //     <body>
            //
            //     FORK begin
            //     ...
            var begin = new Label();

            _assembler.Bind(begin);
            emitBody(this);

            _assembler.Fork(begin);
        }

        public object? VisitQuantifier(RegExpQuantifier node, object? data)
        {
            // If the quantifier must match nothing, we do not produce its body, but
            // still need the `SET_QUANTIFIER_TO_CLOCK` for the Nfa to be able to
            // correctly determine the number of quantifiers.
            if (s_experimentalRegExpEngineCaptureGroupOpt && node.Max == 0) return null;

            // Emit the body, but clear registers occurring in body first.
            //
            // TODO(mbid,v8:10765): It's not always necessary to a) capture registers
            // and b) clear them.
            Interval bodyRegisters = node.Body.CaptureRegisters(new StackLimiter(int.MaxValue));
            void EmitBody(CompileVisitor c)
            {
                if (s_experimentalRegExpEngineCaptureGroupOpt)
                {
                    c._assembler.SetQuantifierToClock(c.RemapQuantifier(node.Index));
                }
                else
                {
                    c.ClearRegisters(bodyRegisters);
                }

                node.Body.Accept(c, null);
            }

            bool canBeReducedToNonNullablePlus = node.Min > 0 && node.Max == RegExpTree.kInfinity && node.MinMatch > 0;

            if (canBeReducedToNonNullablePlus)
            {
                // Compile <body>+ with an optimization allowing linear sized bytecode in
                // the case of nested pluses. Repetitions with infinite upperbound like
                // <body>{n,}, with n != 0, are compiled into <body>{n-1}<body+>, avoiding
                // one repetition, compared to <body>{n}<body>*.

                // Compile the mandatory repetitions. We repeat `min() - 1` times, such
                // that the last repetition, compiled later, can be reused in a loop.
                for (int i = 0; i < node.Min - 1; ++i) EmitBody(this);

                // Compile the optional repetitions, using an optimized plus when
                // possible.
                switch (node.Type)
                {
                    case RegExpQuantifier.QuantifierType.POSSESSIVE:
                        throw new InvalidOperationException("UNREACHABLE");
                    case RegExpQuantifier.QuantifierType.GREEDY:
                        // Compile both last mandatory repetition and optional ones.
                        CompileNonNullableGreedyPlus(EmitBody);
                        break;
                    case RegExpQuantifier.QuantifierType.NON_GREEDY:
                        // Compile both last mandatory repetition and optional ones.
                        CompileNonNullableNonGreedyPlus(EmitBody);
                        break;
                }
            }
            else
            {
                // Compile <body>+ into <body><body>*, and <body>{n,}, with n != 0, into
                // <body>{n}<body>*.

                // Compile the first `min()` repetitions.
                for (int i = 0; i < node.Min; ++i) EmitBody(this);

                // Compile the optional repetitions, using stars or repetitions.
                switch (node.Type)
                {
                    case RegExpQuantifier.QuantifierType.POSSESSIVE:
                        throw new InvalidOperationException("UNREACHABLE");
                    case RegExpQuantifier.QuantifierType.GREEDY:
                        if (node.Max == RegExpTree.kInfinity)
                        {
                            CompileGreedyStar(EmitBody);
                        }
                        else
                        {
                            CompileGreedyRepetition(EmitBody, node.Max - node.Min);
                        }
                        break;
                    case RegExpQuantifier.QuantifierType.NON_GREEDY:
                        if (node.Max == RegExpTree.kInfinity)
                        {
                            CompileNonGreedyStar(EmitBody);
                        }
                        else
                        {
                            CompileNonGreedyRepetition(EmitBody, node.Max - node.Min);
                        }
                        break;
                }
            }

            return null;
        }

        public object? VisitCapture(RegExpCapture node, object? data)
        {
            if (_ignoreCaptures)
            {
                // Skips the `SET_REGISTER_TO_CP` instructions.
                node.Body.Accept(this, null);
            }
            else
            {
                int index = node.Index;
                int startRegister = RegExpCapture.StartRegister(index);
                int endRegister = RegExpCapture.EndRegister(index);

                _assembler.SetRegisterToCp(_reverse ? endRegister : startRegister);
                node.Body.Accept(this, null);
                _assembler.SetRegisterToCp(_reverse ? startRegister : endRegister);
            }

            return null;
        }

        public object? VisitGroup(RegExpGroup node, object? data)
        {
            node.Body.Accept(this, null);
            return null;
        }

        public object? VisitLookaround(RegExpLookaround node, object? data)
        {
            _assembler.ReadLookaroundTable(RemapLookaround(node.Index), node.IsPositive, node.LookaroundType);

            // Add the lookbehind to the queue of lookbehinds to be compiled.
            if (!_ignoreLookarounds) _lookarounds.AddLast(node);

            return null;
        }

        public object? VisitBackReference(RegExpBackReference node, object? data) =>
            throw new InvalidOperationException("UNREACHABLE");

        public object? VisitEmpty(RegExpEmpty node, object? data) => null;

        public object? VisitText(RegExpText node, object? data)
        {
            if (_reverse)
            {
                List<TextElement> elements = node.Elements;
                for (int i = elements.Count - 1; i >= 0; --i) elements[i].Tree.Accept(this, null);
            }
            else
            {
                foreach (TextElement textEl in node.Elements) textEl.Tree.Accept(this, null);
            }
            return null;
        }

        int RemapQuantifier(int id)
        {
            Debug.Assert(s_experimentalRegExpEngineCaptureGroupOpt);
            Dictionary<int, int> map = _quantifierIdRemapping!;
            if (!map.TryGetValue(id, out int value))
            {
                value = map.Count;
                map.Add(id, value);
            }
            return value;
        }

        int RemapLookaround(int id)
        {
            if (!_lookaroundIdRemapping.TryGetValue(id, out int value))
            {
                value = _lookaroundIdRemapping.Count;
                _lookaroundIdRemapping.Add(id, value);
            }
            return value;
        }
    }
}
