// Copyright 2012 the V8 project authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// The intrinsic table of src/runtime/runtime.h (Runtime::FunctionId,
// Runtime::Function, kIntrinsicFunctions), generated from FOR_EACH_INTRINSIC
// for V8 built without WebAssembly and without V8_INTL_SUPPORT, which is
// the configuration V8Sharp matches. The parser needs it for natives syntax
// (%Foo(...)) and for the runtime calls it creates itself; the engine binds
// the entries to its implementations by FunctionId. Regenerate rather than
// edit by hand when syncing V8.

namespace V8Sharp.Runtime;

public enum FunctionId
{
    DebugBreakOnBytecode,
    LoadLookupSlotForCall,
    ArrayIncludes_Slow,
    ArrayIndexOf,
    ArrayIsArray,
    ArraySpeciesConstructor,
    GrowArrayElements,
    IsArray,
    NewArray,
    NormalizeElements,
    TransitionElementsKind,
    TransitionElementsKindWithKind,
    AtomicsLoad64,
    AtomicsStore64,
    AtomicsAdd,
    AtomicsAnd,
    AtomicsCompareExchange,
    AtomicsExchange,
    AtomicsNumWaitersForTesting,
    AtomicsNumUnresolvedAsyncPromisesForTesting,
    AtomicsOr,
    AtomicsSub,
    AtomicsXor,
    SetAllowAtomicsWait,
    AtomicsLoadSharedStructOrArray,
    AtomicsStoreSharedStructOrArray,
    AtomicsExchangeSharedStructOrArray,
    AtomicsCompareExchangeSharedStructOrArray,
    AtomicsSynchronizationPrimitiveNumWaitersForTesting,
    BigIntCompareToNumber,
    BigIntCompareToString,
    BigIntEqualToBigInt,
    BigIntEqualToNumber,
    BigIntEqualToString,
    BigIntExponentiate,
    BigIntMaxBits,
    BigIntToNumber,
    BigIntUnaryOp,
    ToBigInt,
    ToBigIntConvertNumber,
    ThrowConstructorNonCallableError,
    ThrowNotSuperConstructor,
    ThrowStaticPrototypeError,
    ThrowSuperAlreadyCalledError,
    ThrowSuperNotCalled,
    ThrowUnsupportedSuperError,
    DefineClass,
    LoadFromSuper,
    LoadKeyedFromSuper,
    StoreKeyedToSuper,
    StoreToSuper,
    MapGrow,
    MapShrink,
    OrderedHashSetGrow,
    SetGrow,
    SetShrink,
    OrderedHashSetShrink,
    TheHole,
    WeakCollectionDelete,
    WeakCollectionSet,
    OrderedHashMapGrow,
    CompileOptimizedOSR,
    CompileOptimizedOSRFromMaglev,
    CompileOptimizedOSRFromMaglevInlined,
    LogOrTraceOptimizedOSREntry,
    CompileLazy,
    CompileBaseline,
    InstallBaselineCode,
    InstallSFICode,
    NotifyDeoptimized,
    ObserveNode,
    ResolvePossiblyDirectEval,
    VerifyType,
    CheckTurboshaftTypeOf,
    FunctionLogNextExecution,
    OptimizeMaglevEager,
    StartMaglevOptimizeJob,
    OptimizeTurbofanEager,
    StartTurbofanOptimizeJob,
    MarkLazyDeoptimizedOrFlushed,
    DateCurrentTime,
    ClearStepping,
    CollectGarbage,
    DebugAsyncFunctionSuspended,
    DebugBreakAtEntry,
    DebugCollectCoverage,
    DebugGetLoadedScriptIds,
    DebugOnFunctionCall,
    DebugPrepareStepInSuspendedGenerator,
    DebugPromiseThen,
    DebugToggleBlockCoverage,
    DebugTogglePreciseCoverage,
    FunctionGetInferredName,
    GetBreakLocations,
    GetGeneratorScopeCount,
    GetGeneratorScopeDetails,
    HandleDebuggerStatement,
    IsBreakOnException,
    IterableForEach,
    ProfileCreateSnapshotDataBlob,
    ScheduleBreak,
    ScriptLocationFromLine2,
    SetGeneratorScopeVariableValue,
    IncBlockCounter,
    ForInEnumerate,
    ForInHasProperty,
    Call,
    FunctionGetScriptSource,
    FunctionGetScriptId,
    FunctionGetScriptSourcePosition,
    FunctionGetSourceCode,
    FunctionIsAPIFunction,
    AsyncFunctionAwait,
    AsyncFunctionEnter,
    AsyncFunctionReject,
    AsyncFunctionResolve,
    AsyncGeneratorAwait,
    AsyncGeneratorReject,
    AsyncGeneratorResolve,
    AsyncGeneratorYieldWithAwait,
    CreateJSGeneratorObject,
    GeneratorClose,
    GeneratorGetFunction,
    GeneratorGetResumeMode,
    ElementsTransitionAndStoreIC_Miss,
    KeyedLoadIC_Miss,
    KeyedStoreIC_Miss,
    DefineKeyedOwnIC_Miss,
    StoreInArrayLiteralIC_Miss,
    DefineNamedOwnIC_Slow,
    KeyedStoreIC_Slow,
    DefineKeyedOwnIC_Slow,
    LoadElementWithInterceptor,
    LoadGlobalIC_Miss,
    LoadGlobalIC_Slow,
    LoadIC_Miss,
    LoadIC_Miss_FromBaseline,
    PatchLoadICUninitializedBaseline,
    GetStringLengthAndUpdateFeedback,
    LoadNoFeedbackIC_Miss,
    LoadWithReceiverIC_Miss,
    LoadWithReceiverNoFeedbackIC_Miss,
    LoadPropertyPastInterceptor,
    StoreCallbackProperty,
    StoreGlobalIC_Miss,
    StoreGlobalICNoFeedback_Miss,
    StoreGlobalIC_Slow,
    StoreIC_Miss,
    DefineNamedOwnIC_Miss,
    StoreInArrayLiteralIC_Slow,
    StorePropertyPastInterceptor,
    CloneObjectIC_Slow,
    CloneObjectIC_Miss,
    KeyedHasIC_Miss,
    HasElementWithInterceptor,
    ObjectAssignTryFastcase,
    Throw,
    ThrowTargetNonFunction,
    ThrowCalledNonCallable,
    ThrowConstructedNonConstructable,
    ThrowConstructorReturnedNonObject,
    ThrowInvalidStringLength,
    ThrowInvalidTypedArrayAlignment,
    ThrowIteratorError,
    ThrowSpreadArgError,
    ThrowIteratorResultNotAnObject,
    ThrowNoAccess,
    ThrowNotConstructor,
    ThrowPatternAssignmentNonCoercible,
    ThrowRangeError,
    ThrowReferenceError,
    ThrowAccessedUninitializedVariable,
    VarargStackOverflow,
    ThrowStackOverflow,
    ThrowSymbolAsyncIteratorInvalid,
    ThrowSymbolIteratorInvalid,
    ThrowThrowMethodMissing,
    ThrowTypeError,
    ThrowTypeErrorIfStrict,
    ReThrow,
    ReThrowWithMessage,
    AccessCheck,
    AllocateByteArray,
    AllocateInYoungGeneration,
    AllocateInOldGeneration,
    AllocateInSharedHeap,
    AllowDynamicFunction,
    CreateAsyncFromSyncIterator,
    CreateListFromArrayLike,
    DoubleToStringWithRadix,
    FatalProcessOutOfMemoryInAllocateRaw,
    FatalProcessOutOfMemoryInvalidArrayLength,
    FatalInvalidSize,
    GetAndResetRuntimeCallStats,
    GetAndResetTurboProfilingData,
    GetTemplateObject,
    IncrementUseCounter,
    InvalidateStringWrapperToPrimitiveProtector,
    BytecodeBudgetInterrupt_Ignition,
    BytecodeBudgetInterruptWithStackCheck_Ignition,
    BytecodeBudgetInterrupt_Sparkplug,
    BytecodeBudgetInterruptWithStackCheck_Sparkplug,
    BytecodeBudgetInterrupt_Maglev,
    BytecodeBudgetLoopInterrupt_Maglev,
    NotifyContextCellStateWillChange,
    NewError,
    NewReferenceError,
    NewTypeError,
    OrdinaryHasInstance,
    PropagateException,
    ReportMessageFromMicrotask,
    RunMicrotaskCallback,
    PerformMicrotaskCheckpoint,
    SharedValueBarrierSlow,
    StackGuard,
    HandleNoHeapWritesInterrupts,
    StackGuardWithGap,
    TerminateExecution,
    Typeof,
    UnwindAndFindExceptionHandler,
    AddLhsIsStringConstantInternalize,
    AddRhsIsStringConstantInternalize,
    CreateArrayLiteral,
    CreateObjectLiteral,
    SetPrototypeProperties,
    CreateRegExpLiteral,
    DynamicImportCall,
    GetImportMetaObject,
    GetModuleNamespace,
    GetModuleNamespaceExport,
    ArrayBufferMaxByteLength,
    IsSmi,
    MaxSmi,
    NumberToStringSlow,
    Float64ToStringSlow,
    StringParseFloat,
    StringParseInt,
    StringToNumber,
    AddAsyncDisposableValue,
    AddDictionaryProperty,
    AddDisposableValue,
    AddPrivateBrand,
    AllocateHeapNumber,
    CompleteInobjectSlackTrackingForMap,
    CopyDataProperties,
    CopyDataPropertiesWithExcludedPropertiesOnStack,
    CreateDataProperty,
    CreateIterResultObject,
    IterableToListWithInterceptor,
    CheckFastIterableToListPrototype,
    CreatePrivateAccessors,
    DefineAccessorPropertyUnchecked,
    DefineKeyedOwnPropertyInLiteral,
    DefineGetterPropertyUnchecked,
    DefineSetterPropertyUnchecked,
    DeleteProperty,
    DisposeDisposableStack,
    GeneratorYieldResult,
    GetDerivedMap,
    GetFunctionName,
    GetOwnPropertyDescriptorObject,
    GetOwnPropertyKeys,
    GetPrivateMember,
    GetProperty,
    HandleExceptionsInDisposeDisposableStack,
    HasFastPackedElements,
    HasInPrototypeChain,
    HasProperty,
    InitializeDisposableStack,
    InternalSetPrototype,
    IsJSReceiver,
    JSReceiverPreventExtensionsDontThrow,
    JSReceiverPreventExtensionsThrow,
    JSReceiverGetPrototypeOf,
    JSReceiverSetPrototypeOfDontThrow,
    JSReceiverSetPrototypeOfThrow,
    LoadPrivateGetter,
    LoadPrivateSetter,
    NewObject,
    ObjectCreate,
    ObjectEntries,
    ObjectEntriesSkipFastPath,
    ObjectGetOwnPropertyNames,
    ObjectGetOwnPropertyNamesTryFast,
    ObjectHasOwnProperty,
    HasOwnConstDataProperty,
    ObjectIsExtensible,
    ObjectKeys,
    ObjectValues,
    ObjectValuesSkipFastPath,
    OptimizeObjectForAddingMultipleProperties,
    SetDataProperties,
    SetFunctionName,
    SetKeyedProperty,
    DefineObjectOwnProperty,
    SetNamedProperty,
    SetOwnPropertyIgnoreAttributes,
    ShrinkNameDictionary,
    ShrinkSwissNameDictionary,
    ToFastProperties,
    ToLength,
    ToName,
    ToNumber,
    ToNumeric,
    ToObject,
    ToString,
    TryMigrateInstance,
    TryMigrateInstanceAndMarkMapAsMigrationTarget,
    SetPrivateMember,
    SwissTableAdd,
    SwissTableAllocate,
    SwissTableDelete,
    SwissTableDetailsAt,
    SwissTableElementsCount,
    SwissTableEquals,
    SwissTableFindEntry,
    SwissTableUpdate,
    SwissTableValueAt,
    SwissTableKeyAt,
    Add,
    Equal,
    GreaterThan,
    GreaterThanOrEqual,
    LessThan,
    LessThanOrEqual,
    NotEqual,
    StrictEqual,
    StrictNotEqual,
    ReferenceEqual,
    EnqueueMicrotask,
    PromiseHookAfter,
    PromiseHookBefore,
    PromiseHookInit,
    PromiseRejectEventFromStack,
    PromiseRevokeReject,
    RejectPromise,
    ResolvePromise,
    ConstructSuppressedError,
    ConstructAggregateErrorHelper,
    ConstructInternalAggregateErrorHelper,
    CheckProxyGetSetTrapResult,
    CheckProxyHasTrapResult,
    CheckProxyDeleteTrapResult,
    GetPropertyWithReceiver,
    IsJSProxy,
    JSProxyGetHandler,
    JSProxyGetTarget,
    SetPropertyWithReceiver,
    RegExpBuildIndices,
    RegExpGrowRegExpMatchInfo,
    RegExpExecMultiple,
    RegExpInitializeAndCompile,
    RegExpMatchGlobalAtom,
    RegExpReplaceRT,
    RegExpSplit,
    RegExpStringFromFlags,
    StringReplaceNonGlobalRegExpWithFunction,
    StringSplit,
    RegExpExec,
    RegExpExperimentalOneshotExec,
    ThrowConstAssignError,
    ThrowUsingAssignError,
    ThrowAwaitUsingAssignError,
    DeclareEvalFunction,
    DeclareEvalVar,
    DeclareGlobals,
    DeclareModuleExports,
    DeleteLookupSlot,
    LoadLookupSlot,
    LoadLookupSlotInsideTypeof,
    LoadLookupSlotForCall_Baseline,
    NewClosure,
    NewClosure_Tenured,
    NewFunctionContext,
    NewRestParameter,
    NewSloppyArguments,
    NewStrictArguments,
    PushBlockContext,
    PushCatchContext,
    PushWithContext,
    StoreGlobalNoHoleCheckForReplLetOrConst,
    StoreLookupSlot_Sloppy,
    StoreLookupSlot_SloppyHoisting,
    StoreLookupSlot_Strict,
    ShadowRealmWrappedFunctionCreate,
    ShadowRealmImportValue,
    ShadowRealmThrow,
    FlattenString,
    GetSubstitution,
    InternalizeString,
    StringAdd,
    StringAdd_LhsIsStringConstant_Internalize,
    StringAdd_RhsIsStringConstant_Internalize,
    StringBuilderConcat,
    StringCharCodeAt,
    StringCodePointAt,
    StringCompare,
    StringEqual,
    StringEscapeQuotes,
    StringGreaterThan,
    StringGreaterThanOrEqual,
    StringIsWellFormed,
    StringLastIndexOf,
    StringLessThan,
    StringLessThanOrEqual,
    StringMaxLength,
    StringReplaceOneCharWithString,
    StringSubstring,
    StringToArray,
    StringToWellFormed,
    CreatePrivateNameSymbol,
    CreatePrivateBrandSymbol,
    CreatePrivateSymbol,
    SymbolDescriptiveString,
    SymbolIsPrivate,
    Abort,
    AbortCSADcheck,
    AbortJS,
    ActiveTierIsIgnition,
    ActiveTierIsSparkplug,
    ActiveTierIsMaglev,
    ActiveTierIsTurbofan,
    AllocateHeapNumberWithValue,
    ArrayBufferDetachForceWasm,
    ArrayIteratorProtector,
    ArraySpeciesProtector,
    AssertNotPeeled,
    AssertPeeled,
    BaselineOsr,
    BenchMaglev,
    BenchTurbofan,
    BlockAt,
    VerifyGetJSBuiltinState,
    ClearFunctionFeedback,
    ClearMegamorphicStubCache,
    CompleteInobjectSlackTracking,
    ConstructConsString,
    ConstructDouble,
    ConstructInternalizedString,
    ConstructSlicedString,
    ConstructThinString,
    CurrentFrameIsTurbofan,
    DebugPrint,
    DebugPrintCppHeapPointerTable,
    DebugPrintCppHeapPointerTableFilterTag,
    DebugPrintExternalPointerTable,
    DebugPrintExternalPointerTableFilterTag,
    DebugPrintGeneric,
    DebugPrintFloat,
    DebugPrintPtr,
    DebugPrintWord,
    DebugTrace,
    DebugTraceMinimal,
    DeoptimizeFunction,
    DisableOptimizationFinalization,
    DisallowCodegenFromStrings,
    DisassembleFunction,
    EnableCodeLoggingForTesting,
    EnsureFeedbackVectorForFunction,
    FinalizeOptimization,
    ForceFlush,
    MajorGCForCompilerTesting,
    GetAbstractModuleSource,
    GetBytecode,
    ExhaustInterruptBudget,
    GetCallable,
    GetFeedback,
    GetFunctionForCurrentFrame,
    GetInitializerFunction,
    GetOptimizationStatus,
    GetUndetectable,
    GetWeakCollectionSize,
    GlobalPrint,
    HasCowElements,
    HasDictionaryElements,
    HasDoubleElements,
    HasElementsInALargeObjectSpace,
    HasFastElements,
    HasFastProperties,
    HasFixedBigInt64Elements,
    HasFixedBigUint64Elements,
    HasFixedFloat16Elements,
    HasFixedFloat32Elements,
    HasFixedFloat64Elements,
    HasFixedInt16Elements,
    HasFixedInt32Elements,
    HasFixedInt8Elements,
    HasFixedUint16Elements,
    HasFixedUint32Elements,
    HasFixedUint8ClampedElements,
    HasFixedUint8Elements,
    HasHoleyElements,
    HasObjectElements,
    HasPackedElements,
    HasSloppyArgumentsElements,
    HasSmiElements,
    HasSmiOrObjectElements,
    HaveSameMap,
    HeapObjectVerify,
    ICsAreEnabled,
    InLargeObjectSpace,
    InstallBytecode,
    InYoungGeneration,
    Is64Bit,
    IsAtomicsWaitAllowed,
    IsBeingInterpreted,
    IsConcatSpreadableProtector,
    IsConcurrentRecompilationSupported,
    IsDictPropertyConstTrackingEnabled,
    IsEfficiencyModeEnabled,
    IsInPlaceInternalizableString,
    IsInternalizedString,
    StringToCString,
    StringUtf8Value,
    IsUndefinedDoubleEnabled,
    IsMaglevEnabled,
    IsSameHeapObject,
    IsSharedString,
    IsInWritableSharedSpace,
    IsSparkplugEnabled,
    IsTurbofanEnabled,
    IsWasmTieringPredictable,
    MapIteratorProtector,
    NeverOptimizeFunction,
    NewRegExpWithBacktrackLimit,
    NoElementsProtector,
    NotifyContextDisposed,
    SetPriorityBestEffort,
    SetPriorityUserVisible,
    SetPriorityUserBlocking,
    OptimizeMaglevOnNextCall,
    OptimizeFunctionOnNextCall,
    OptimizeOsr,
    PrepareFunctionForOptimization,
    PretenureAllocationSite,
    PrintWithNameForAssert,
    PromiseSpeciesProtector,
    RegExpSpeciesProtector,
    RegexpHasBytecode,
    RegexpHasNativeCode,
    RegexpIsUnmodified,
    RegexpQuickCheckRejects,
    RegexpTypeTag,
    Resume,
    RunningInSimulator,
    RuntimeEvaluateREPL,
    ScheduleGCInStackCheck,
    SerializeDeserializeNow,
    SetAllocationTimeout,
    SetDispatchTableGCInterval,
    SetBatterySaverMode,
    SetForceSlowPath,
    SetIteratorProtector,
    SharedGC,
    ShareObject,
    SimulateNewspaceFull,
    StringIsFlat,
    StringIteratorProtector,
    StringWrapperToPrimitiveProtector,
    SystemBreak,
    TakeHeapSnapshot,
    TraceEnter,
    TraceExit,
    TurbofanStaticAssert,
    AssertEscapeAnalysisElided,
    TypedArraySpeciesProtector,
    WaitForBackgroundOptimization,
    WaitUntilBlocked,
    DeoptimizeNow,
    LeakHole,
    GetHoleNaNLower,
    GetHoleNaNUpper,
    GetHoleNaN,
    GetUndefinedNaN,
    ArrayBufferDetach,
    ArrayBufferSetDetachKey,
    GrowableSharedArrayBufferByteLength,
    TypedArrayCopyElements,
    TypedArrayGetBuffer,
    TypedArraySet,
    TypedArraySortFast,
    JSFinalizationRegistryRegisterWeakCellWithUnregisterToken,
    JSWeakRefAddToKeptObjects,
    InlineIncBlockCounter,
    InlineAsyncFunctionAwait,
    InlineAsyncFunctionEnter,
    InlineAsyncFunctionReject,
    InlineAsyncFunctionResolve,
    InlineAsyncGeneratorAwait,
    InlineAsyncGeneratorReject,
    InlineAsyncGeneratorResolve,
    InlineAsyncGeneratorYieldWithAwait,
    InlineCreateJSGeneratorObject,
    InlineGeneratorClose,
    InlineGeneratorGetResumeMode,
    InlineCreateAsyncFromSyncIterator,
    InlineAddLhsIsStringConstantInternalize,
    InlineAddRhsIsStringConstantInternalize,
    InlineGetImportMetaObject,
    InlineCopyDataProperties,
    InlineCopyDataPropertiesWithExcludedPropertiesOnStack,
    InlineCreateDataProperty,
    InlineCreateIterResultObject,
    InlineGeneratorYieldResult,
    InlineDeoptimizeNow,
    NumFunctions,
}

public enum IntrinsicType { RUNTIME, INLINE }

public sealed class RuntimeFunction(FunctionId functionId, IntrinsicType intrinsicType, string name, sbyte nargs, sbyte resultSize)
{
    public FunctionId function_id { get; } = functionId;
    public IntrinsicType intrinsic_type { get; } = intrinsicType;
    // The JS name of the function ("_Foo" for the inline variant).
    public string name { get; } = name;
    // The number of arguments expected. nargs is -1 if the function takes
    // a variable number of arguments.
    public sbyte nargs { get; } = nargs;
    public sbyte result_size { get; } = resultSize;
    public override string ToString() => name;
}

public static class Runtime
{
    private static readonly RuntimeFunction[] s_intrinsicFunctions =
    [
        new(FunctionId.DebugBreakOnBytecode, IntrinsicType.RUNTIME, "DebugBreakOnBytecode", 1, 2),
        new(FunctionId.LoadLookupSlotForCall, IntrinsicType.RUNTIME, "LoadLookupSlotForCall", 1, 2),
        new(FunctionId.ArrayIncludes_Slow, IntrinsicType.RUNTIME, "ArrayIncludes_Slow", 3, 1),
        new(FunctionId.ArrayIndexOf, IntrinsicType.RUNTIME, "ArrayIndexOf", 3, 1),
        new(FunctionId.ArrayIsArray, IntrinsicType.RUNTIME, "ArrayIsArray", 1, 1),
        new(FunctionId.ArraySpeciesConstructor, IntrinsicType.RUNTIME, "ArraySpeciesConstructor", 1, 1),
        new(FunctionId.GrowArrayElements, IntrinsicType.RUNTIME, "GrowArrayElements", 2, 1),
        new(FunctionId.IsArray, IntrinsicType.RUNTIME, "IsArray", 1, 1),
        new(FunctionId.NewArray, IntrinsicType.RUNTIME, "NewArray", -1, 1),
        new(FunctionId.NormalizeElements, IntrinsicType.RUNTIME, "NormalizeElements", 1, 1),
        new(FunctionId.TransitionElementsKind, IntrinsicType.RUNTIME, "TransitionElementsKind", 2, 1),
        new(FunctionId.TransitionElementsKindWithKind, IntrinsicType.RUNTIME, "TransitionElementsKindWithKind", 2, 1),
        new(FunctionId.AtomicsLoad64, IntrinsicType.RUNTIME, "AtomicsLoad64", 2, 1),
        new(FunctionId.AtomicsStore64, IntrinsicType.RUNTIME, "AtomicsStore64", 3, 1),
        new(FunctionId.AtomicsAdd, IntrinsicType.RUNTIME, "AtomicsAdd", 3, 1),
        new(FunctionId.AtomicsAnd, IntrinsicType.RUNTIME, "AtomicsAnd", 3, 1),
        new(FunctionId.AtomicsCompareExchange, IntrinsicType.RUNTIME, "AtomicsCompareExchange", 4, 1),
        new(FunctionId.AtomicsExchange, IntrinsicType.RUNTIME, "AtomicsExchange", 3, 1),
        new(FunctionId.AtomicsNumWaitersForTesting, IntrinsicType.RUNTIME, "AtomicsNumWaitersForTesting", 2, 1),
        new(FunctionId.AtomicsNumUnresolvedAsyncPromisesForTesting, IntrinsicType.RUNTIME, "AtomicsNumUnresolvedAsyncPromisesForTesting", 2, 1),
        new(FunctionId.AtomicsOr, IntrinsicType.RUNTIME, "AtomicsOr", 3, 1),
        new(FunctionId.AtomicsSub, IntrinsicType.RUNTIME, "AtomicsSub", 3, 1),
        new(FunctionId.AtomicsXor, IntrinsicType.RUNTIME, "AtomicsXor", 3, 1),
        new(FunctionId.SetAllowAtomicsWait, IntrinsicType.RUNTIME, "SetAllowAtomicsWait", 1, 1),
        new(FunctionId.AtomicsLoadSharedStructOrArray, IntrinsicType.RUNTIME, "AtomicsLoadSharedStructOrArray", 2, 1),
        new(FunctionId.AtomicsStoreSharedStructOrArray, IntrinsicType.RUNTIME, "AtomicsStoreSharedStructOrArray", 3, 1),
        new(FunctionId.AtomicsExchangeSharedStructOrArray, IntrinsicType.RUNTIME, "AtomicsExchangeSharedStructOrArray", 3, 1),
        new(FunctionId.AtomicsCompareExchangeSharedStructOrArray, IntrinsicType.RUNTIME, "AtomicsCompareExchangeSharedStructOrArray", 4, 1),
        new(FunctionId.AtomicsSynchronizationPrimitiveNumWaitersForTesting, IntrinsicType.RUNTIME, "AtomicsSynchronizationPrimitiveNumWaitersForTesting", 1, 1),
        new(FunctionId.BigIntCompareToNumber, IntrinsicType.RUNTIME, "BigIntCompareToNumber", 3, 1),
        new(FunctionId.BigIntCompareToString, IntrinsicType.RUNTIME, "BigIntCompareToString", 3, 1),
        new(FunctionId.BigIntEqualToBigInt, IntrinsicType.RUNTIME, "BigIntEqualToBigInt", 2, 1),
        new(FunctionId.BigIntEqualToNumber, IntrinsicType.RUNTIME, "BigIntEqualToNumber", 2, 1),
        new(FunctionId.BigIntEqualToString, IntrinsicType.RUNTIME, "BigIntEqualToString", 2, 1),
        new(FunctionId.BigIntExponentiate, IntrinsicType.RUNTIME, "BigIntExponentiate", 2, 1),
        new(FunctionId.BigIntMaxBits, IntrinsicType.RUNTIME, "BigIntMaxBits", 0, 1),
        new(FunctionId.BigIntToNumber, IntrinsicType.RUNTIME, "BigIntToNumber", 1, 1),
        new(FunctionId.BigIntUnaryOp, IntrinsicType.RUNTIME, "BigIntUnaryOp", 2, 1),
        new(FunctionId.ToBigInt, IntrinsicType.RUNTIME, "ToBigInt", 1, 1),
        new(FunctionId.ToBigIntConvertNumber, IntrinsicType.RUNTIME, "ToBigIntConvertNumber", 1, 1),
        new(FunctionId.ThrowConstructorNonCallableError, IntrinsicType.RUNTIME, "ThrowConstructorNonCallableError", 1, 1),
        new(FunctionId.ThrowNotSuperConstructor, IntrinsicType.RUNTIME, "ThrowNotSuperConstructor", 2, 1),
        new(FunctionId.ThrowStaticPrototypeError, IntrinsicType.RUNTIME, "ThrowStaticPrototypeError", 0, 1),
        new(FunctionId.ThrowSuperAlreadyCalledError, IntrinsicType.RUNTIME, "ThrowSuperAlreadyCalledError", 0, 1),
        new(FunctionId.ThrowSuperNotCalled, IntrinsicType.RUNTIME, "ThrowSuperNotCalled", 0, 1),
        new(FunctionId.ThrowUnsupportedSuperError, IntrinsicType.RUNTIME, "ThrowUnsupportedSuperError", 0, 1),
        new(FunctionId.DefineClass, IntrinsicType.RUNTIME, "DefineClass", -1, 1),
        new(FunctionId.LoadFromSuper, IntrinsicType.RUNTIME, "LoadFromSuper", 3, 1),
        new(FunctionId.LoadKeyedFromSuper, IntrinsicType.RUNTIME, "LoadKeyedFromSuper", 3, 1),
        new(FunctionId.StoreKeyedToSuper, IntrinsicType.RUNTIME, "StoreKeyedToSuper", 4, 1),
        new(FunctionId.StoreToSuper, IntrinsicType.RUNTIME, "StoreToSuper", 4, 1),
        new(FunctionId.MapGrow, IntrinsicType.RUNTIME, "MapGrow", 1, 1),
        new(FunctionId.MapShrink, IntrinsicType.RUNTIME, "MapShrink", 1, 1),
        new(FunctionId.OrderedHashSetGrow, IntrinsicType.RUNTIME, "OrderedHashSetGrow", 2, 1),
        new(FunctionId.SetGrow, IntrinsicType.RUNTIME, "SetGrow", 1, 1),
        new(FunctionId.SetShrink, IntrinsicType.RUNTIME, "SetShrink", 1, 1),
        new(FunctionId.OrderedHashSetShrink, IntrinsicType.RUNTIME, "OrderedHashSetShrink", 1, 1),
        new(FunctionId.TheHole, IntrinsicType.RUNTIME, "TheHole", 0, 1),
        new(FunctionId.WeakCollectionDelete, IntrinsicType.RUNTIME, "WeakCollectionDelete", 3, 1),
        new(FunctionId.WeakCollectionSet, IntrinsicType.RUNTIME, "WeakCollectionSet", 4, 1),
        new(FunctionId.OrderedHashMapGrow, IntrinsicType.RUNTIME, "OrderedHashMapGrow", 2, 1),
        new(FunctionId.CompileOptimizedOSR, IntrinsicType.RUNTIME, "CompileOptimizedOSR", 0, 1),
        new(FunctionId.CompileOptimizedOSRFromMaglev, IntrinsicType.RUNTIME, "CompileOptimizedOSRFromMaglev", 1, 1),
        new(FunctionId.CompileOptimizedOSRFromMaglevInlined, IntrinsicType.RUNTIME, "CompileOptimizedOSRFromMaglevInlined", 2, 1),
        new(FunctionId.LogOrTraceOptimizedOSREntry, IntrinsicType.RUNTIME, "LogOrTraceOptimizedOSREntry", 0, 1),
        new(FunctionId.CompileLazy, IntrinsicType.RUNTIME, "CompileLazy", 1, 1),
        new(FunctionId.CompileBaseline, IntrinsicType.RUNTIME, "CompileBaseline", 1, 1),
        new(FunctionId.InstallBaselineCode, IntrinsicType.RUNTIME, "InstallBaselineCode", 1, 1),
        new(FunctionId.InstallSFICode, IntrinsicType.RUNTIME, "InstallSFICode", 1, 1),
        new(FunctionId.NotifyDeoptimized, IntrinsicType.RUNTIME, "NotifyDeoptimized", 0, 1),
        new(FunctionId.ObserveNode, IntrinsicType.RUNTIME, "ObserveNode", 1, 1),
        new(FunctionId.ResolvePossiblyDirectEval, IntrinsicType.RUNTIME, "ResolvePossiblyDirectEval", 6, 1),
        new(FunctionId.VerifyType, IntrinsicType.RUNTIME, "VerifyType", 1, 1),
        new(FunctionId.CheckTurboshaftTypeOf, IntrinsicType.RUNTIME, "CheckTurboshaftTypeOf", 2, 1),
        new(FunctionId.FunctionLogNextExecution, IntrinsicType.RUNTIME, "FunctionLogNextExecution", 1, 1),
        new(FunctionId.OptimizeMaglevEager, IntrinsicType.RUNTIME, "OptimizeMaglevEager", 1, 1),
        new(FunctionId.StartMaglevOptimizeJob, IntrinsicType.RUNTIME, "StartMaglevOptimizeJob", 1, 1),
        new(FunctionId.OptimizeTurbofanEager, IntrinsicType.RUNTIME, "OptimizeTurbofanEager", 1, 1),
        new(FunctionId.StartTurbofanOptimizeJob, IntrinsicType.RUNTIME, "StartTurbofanOptimizeJob", 1, 1),
        new(FunctionId.MarkLazyDeoptimizedOrFlushed, IntrinsicType.RUNTIME, "MarkLazyDeoptimizedOrFlushed", 2, 1),
        new(FunctionId.DateCurrentTime, IntrinsicType.RUNTIME, "DateCurrentTime", 0, 1),
        new(FunctionId.ClearStepping, IntrinsicType.RUNTIME, "ClearStepping", 0, 1),
        new(FunctionId.CollectGarbage, IntrinsicType.RUNTIME, "CollectGarbage", 1, 1),
        new(FunctionId.DebugAsyncFunctionSuspended, IntrinsicType.RUNTIME, "DebugAsyncFunctionSuspended", 3, 1),
        new(FunctionId.DebugBreakAtEntry, IntrinsicType.RUNTIME, "DebugBreakAtEntry", 1, 1),
        new(FunctionId.DebugCollectCoverage, IntrinsicType.RUNTIME, "DebugCollectCoverage", 0, 1),
        new(FunctionId.DebugGetLoadedScriptIds, IntrinsicType.RUNTIME, "DebugGetLoadedScriptIds", 0, 1),
        new(FunctionId.DebugOnFunctionCall, IntrinsicType.RUNTIME, "DebugOnFunctionCall", 2, 1),
        new(FunctionId.DebugPrepareStepInSuspendedGenerator, IntrinsicType.RUNTIME, "DebugPrepareStepInSuspendedGenerator", 0, 1),
        new(FunctionId.DebugPromiseThen, IntrinsicType.RUNTIME, "DebugPromiseThen", 1, 1),
        new(FunctionId.DebugToggleBlockCoverage, IntrinsicType.RUNTIME, "DebugToggleBlockCoverage", 1, 1),
        new(FunctionId.DebugTogglePreciseCoverage, IntrinsicType.RUNTIME, "DebugTogglePreciseCoverage", 1, 1),
        new(FunctionId.FunctionGetInferredName, IntrinsicType.RUNTIME, "FunctionGetInferredName", 1, 1),
        new(FunctionId.GetBreakLocations, IntrinsicType.RUNTIME, "GetBreakLocations", 1, 1),
        new(FunctionId.GetGeneratorScopeCount, IntrinsicType.RUNTIME, "GetGeneratorScopeCount", 1, 1),
        new(FunctionId.GetGeneratorScopeDetails, IntrinsicType.RUNTIME, "GetGeneratorScopeDetails", 2, 1),
        new(FunctionId.HandleDebuggerStatement, IntrinsicType.RUNTIME, "HandleDebuggerStatement", 0, 1),
        new(FunctionId.IsBreakOnException, IntrinsicType.RUNTIME, "IsBreakOnException", 1, 1),
        new(FunctionId.IterableForEach, IntrinsicType.RUNTIME, "IterableForEach", 2, 1),
        new(FunctionId.ProfileCreateSnapshotDataBlob, IntrinsicType.RUNTIME, "ProfileCreateSnapshotDataBlob", 0, 1),
        new(FunctionId.ScheduleBreak, IntrinsicType.RUNTIME, "ScheduleBreak", 0, 1),
        new(FunctionId.ScriptLocationFromLine2, IntrinsicType.RUNTIME, "ScriptLocationFromLine2", 4, 1),
        new(FunctionId.SetGeneratorScopeVariableValue, IntrinsicType.RUNTIME, "SetGeneratorScopeVariableValue", 4, 1),
        new(FunctionId.IncBlockCounter, IntrinsicType.RUNTIME, "IncBlockCounter", 2, 1),
        new(FunctionId.ForInEnumerate, IntrinsicType.RUNTIME, "ForInEnumerate", 1, 1),
        new(FunctionId.ForInHasProperty, IntrinsicType.RUNTIME, "ForInHasProperty", 2, 1),
        new(FunctionId.Call, IntrinsicType.RUNTIME, "Call", -1, 1),
        new(FunctionId.FunctionGetScriptSource, IntrinsicType.RUNTIME, "FunctionGetScriptSource", 1, 1),
        new(FunctionId.FunctionGetScriptId, IntrinsicType.RUNTIME, "FunctionGetScriptId", 1, 1),
        new(FunctionId.FunctionGetScriptSourcePosition, IntrinsicType.RUNTIME, "FunctionGetScriptSourcePosition", 1, 1),
        new(FunctionId.FunctionGetSourceCode, IntrinsicType.RUNTIME, "FunctionGetSourceCode", 1, 1),
        new(FunctionId.FunctionIsAPIFunction, IntrinsicType.RUNTIME, "FunctionIsAPIFunction", 1, 1),
        new(FunctionId.AsyncFunctionAwait, IntrinsicType.RUNTIME, "AsyncFunctionAwait", 2, 1),
        new(FunctionId.AsyncFunctionEnter, IntrinsicType.RUNTIME, "AsyncFunctionEnter", 2, 1),
        new(FunctionId.AsyncFunctionReject, IntrinsicType.RUNTIME, "AsyncFunctionReject", 2, 1),
        new(FunctionId.AsyncFunctionResolve, IntrinsicType.RUNTIME, "AsyncFunctionResolve", 2, 1),
        new(FunctionId.AsyncGeneratorAwait, IntrinsicType.RUNTIME, "AsyncGeneratorAwait", 2, 1),
        new(FunctionId.AsyncGeneratorReject, IntrinsicType.RUNTIME, "AsyncGeneratorReject", 2, 1),
        new(FunctionId.AsyncGeneratorResolve, IntrinsicType.RUNTIME, "AsyncGeneratorResolve", 3, 1),
        new(FunctionId.AsyncGeneratorYieldWithAwait, IntrinsicType.RUNTIME, "AsyncGeneratorYieldWithAwait", 2, 1),
        new(FunctionId.CreateJSGeneratorObject, IntrinsicType.RUNTIME, "CreateJSGeneratorObject", 2, 1),
        new(FunctionId.GeneratorClose, IntrinsicType.RUNTIME, "GeneratorClose", 1, 1),
        new(FunctionId.GeneratorGetFunction, IntrinsicType.RUNTIME, "GeneratorGetFunction", 1, 1),
        new(FunctionId.GeneratorGetResumeMode, IntrinsicType.RUNTIME, "GeneratorGetResumeMode", 1, 1),
        new(FunctionId.ElementsTransitionAndStoreIC_Miss, IntrinsicType.RUNTIME, "ElementsTransitionAndStoreIC_Miss", 6, 1),
        new(FunctionId.KeyedLoadIC_Miss, IntrinsicType.RUNTIME, "KeyedLoadIC_Miss", 4, 1),
        new(FunctionId.KeyedStoreIC_Miss, IntrinsicType.RUNTIME, "KeyedStoreIC_Miss", 5, 1),
        new(FunctionId.DefineKeyedOwnIC_Miss, IntrinsicType.RUNTIME, "DefineKeyedOwnIC_Miss", 5, 1),
        new(FunctionId.StoreInArrayLiteralIC_Miss, IntrinsicType.RUNTIME, "StoreInArrayLiteralIC_Miss", 5, 1),
        new(FunctionId.DefineNamedOwnIC_Slow, IntrinsicType.RUNTIME, "DefineNamedOwnIC_Slow", 3, 1),
        new(FunctionId.KeyedStoreIC_Slow, IntrinsicType.RUNTIME, "KeyedStoreIC_Slow", 3, 1),
        new(FunctionId.DefineKeyedOwnIC_Slow, IntrinsicType.RUNTIME, "DefineKeyedOwnIC_Slow", 3, 1),
        new(FunctionId.LoadElementWithInterceptor, IntrinsicType.RUNTIME, "LoadElementWithInterceptor", 2, 1),
        new(FunctionId.LoadGlobalIC_Miss, IntrinsicType.RUNTIME, "LoadGlobalIC_Miss", 4, 1),
        new(FunctionId.LoadGlobalIC_Slow, IntrinsicType.RUNTIME, "LoadGlobalIC_Slow", 3, 1),
        new(FunctionId.LoadIC_Miss, IntrinsicType.RUNTIME, "LoadIC_Miss", 4, 1),
        new(FunctionId.LoadIC_Miss_FromBaseline, IntrinsicType.RUNTIME, "LoadIC_Miss_FromBaseline", 4, 1),
        new(FunctionId.PatchLoadICUninitializedBaseline, IntrinsicType.RUNTIME, "PatchLoadICUninitializedBaseline", 4, 1),
        new(FunctionId.GetStringLengthAndUpdateFeedback, IntrinsicType.RUNTIME, "GetStringLengthAndUpdateFeedback", 3, 1),
        new(FunctionId.LoadNoFeedbackIC_Miss, IntrinsicType.RUNTIME, "LoadNoFeedbackIC_Miss", 4, 1),
        new(FunctionId.LoadWithReceiverIC_Miss, IntrinsicType.RUNTIME, "LoadWithReceiverIC_Miss", 5, 1),
        new(FunctionId.LoadWithReceiverNoFeedbackIC_Miss, IntrinsicType.RUNTIME, "LoadWithReceiverNoFeedbackIC_Miss", 3, 1),
        new(FunctionId.LoadPropertyPastInterceptor, IntrinsicType.RUNTIME, "LoadPropertyPastInterceptor", 6, 1),
        new(FunctionId.StoreCallbackProperty, IntrinsicType.RUNTIME, "StoreCallbackProperty", 5, 1),
        new(FunctionId.StoreGlobalIC_Miss, IntrinsicType.RUNTIME, "StoreGlobalIC_Miss", 4, 1),
        new(FunctionId.StoreGlobalICNoFeedback_Miss, IntrinsicType.RUNTIME, "StoreGlobalICNoFeedback_Miss", 2, 1),
        new(FunctionId.StoreGlobalIC_Slow, IntrinsicType.RUNTIME, "StoreGlobalIC_Slow", 5, 1),
        new(FunctionId.StoreIC_Miss, IntrinsicType.RUNTIME, "StoreIC_Miss", 5, 1),
        new(FunctionId.DefineNamedOwnIC_Miss, IntrinsicType.RUNTIME, "DefineNamedOwnIC_Miss", 5, 1),
        new(FunctionId.StoreInArrayLiteralIC_Slow, IntrinsicType.RUNTIME, "StoreInArrayLiteralIC_Slow", 3, 1),
        new(FunctionId.StorePropertyPastInterceptor, IntrinsicType.RUNTIME, "StorePropertyPastInterceptor", 4, 1),
        new(FunctionId.CloneObjectIC_Slow, IntrinsicType.RUNTIME, "CloneObjectIC_Slow", 2, 1),
        new(FunctionId.CloneObjectIC_Miss, IntrinsicType.RUNTIME, "CloneObjectIC_Miss", 4, 1),
        new(FunctionId.KeyedHasIC_Miss, IntrinsicType.RUNTIME, "KeyedHasIC_Miss", 4, 1),
        new(FunctionId.HasElementWithInterceptor, IntrinsicType.RUNTIME, "HasElementWithInterceptor", 2, 1),
        new(FunctionId.ObjectAssignTryFastcase, IntrinsicType.RUNTIME, "ObjectAssignTryFastcase", 2, 1),
        new(FunctionId.Throw, IntrinsicType.RUNTIME, "Throw", 1, 1),
        new(FunctionId.ThrowTargetNonFunction, IntrinsicType.RUNTIME, "ThrowTargetNonFunction", 2, 1),
        new(FunctionId.ThrowCalledNonCallable, IntrinsicType.RUNTIME, "ThrowCalledNonCallable", 1, 1),
        new(FunctionId.ThrowConstructedNonConstructable, IntrinsicType.RUNTIME, "ThrowConstructedNonConstructable", 1, 1),
        new(FunctionId.ThrowConstructorReturnedNonObject, IntrinsicType.RUNTIME, "ThrowConstructorReturnedNonObject", 0, 1),
        new(FunctionId.ThrowInvalidStringLength, IntrinsicType.RUNTIME, "ThrowInvalidStringLength", 0, 1),
        new(FunctionId.ThrowInvalidTypedArrayAlignment, IntrinsicType.RUNTIME, "ThrowInvalidTypedArrayAlignment", 2, 1),
        new(FunctionId.ThrowIteratorError, IntrinsicType.RUNTIME, "ThrowIteratorError", 1, 1),
        new(FunctionId.ThrowSpreadArgError, IntrinsicType.RUNTIME, "ThrowSpreadArgError", 2, 1),
        new(FunctionId.ThrowIteratorResultNotAnObject, IntrinsicType.RUNTIME, "ThrowIteratorResultNotAnObject", 1, 1),
        new(FunctionId.ThrowNoAccess, IntrinsicType.RUNTIME, "ThrowNoAccess", 0, 1),
        new(FunctionId.ThrowNotConstructor, IntrinsicType.RUNTIME, "ThrowNotConstructor", 1, 1),
        new(FunctionId.ThrowPatternAssignmentNonCoercible, IntrinsicType.RUNTIME, "ThrowPatternAssignmentNonCoercible", 1, 1),
        new(FunctionId.ThrowRangeError, IntrinsicType.RUNTIME, "ThrowRangeError", -1, 1),
        new(FunctionId.ThrowReferenceError, IntrinsicType.RUNTIME, "ThrowReferenceError", 1, 1),
        new(FunctionId.ThrowAccessedUninitializedVariable, IntrinsicType.RUNTIME, "ThrowAccessedUninitializedVariable", 1, 1),
        new(FunctionId.VarargStackOverflow, IntrinsicType.RUNTIME, "VarargStackOverflow", -1, 1),
        new(FunctionId.ThrowStackOverflow, IntrinsicType.RUNTIME, "ThrowStackOverflow", 0, 1),
        new(FunctionId.ThrowSymbolAsyncIteratorInvalid, IntrinsicType.RUNTIME, "ThrowSymbolAsyncIteratorInvalid", 0, 1),
        new(FunctionId.ThrowSymbolIteratorInvalid, IntrinsicType.RUNTIME, "ThrowSymbolIteratorInvalid", 0, 1),
        new(FunctionId.ThrowThrowMethodMissing, IntrinsicType.RUNTIME, "ThrowThrowMethodMissing", 0, 1),
        new(FunctionId.ThrowTypeError, IntrinsicType.RUNTIME, "ThrowTypeError", -1, 1),
        new(FunctionId.ThrowTypeErrorIfStrict, IntrinsicType.RUNTIME, "ThrowTypeErrorIfStrict", -1, 1),
        new(FunctionId.ReThrow, IntrinsicType.RUNTIME, "ReThrow", 1, 1),
        new(FunctionId.ReThrowWithMessage, IntrinsicType.RUNTIME, "ReThrowWithMessage", 2, 1),
        new(FunctionId.AccessCheck, IntrinsicType.RUNTIME, "AccessCheck", 1, 1),
        new(FunctionId.AllocateByteArray, IntrinsicType.RUNTIME, "AllocateByteArray", 1, 1),
        new(FunctionId.AllocateInYoungGeneration, IntrinsicType.RUNTIME, "AllocateInYoungGeneration", 2, 1),
        new(FunctionId.AllocateInOldGeneration, IntrinsicType.RUNTIME, "AllocateInOldGeneration", 2, 1),
        new(FunctionId.AllocateInSharedHeap, IntrinsicType.RUNTIME, "AllocateInSharedHeap", 2, 1),
        new(FunctionId.AllowDynamicFunction, IntrinsicType.RUNTIME, "AllowDynamicFunction", 1, 1),
        new(FunctionId.CreateAsyncFromSyncIterator, IntrinsicType.RUNTIME, "CreateAsyncFromSyncIterator", 1, 1),
        new(FunctionId.CreateListFromArrayLike, IntrinsicType.RUNTIME, "CreateListFromArrayLike", 1, 1),
        new(FunctionId.DoubleToStringWithRadix, IntrinsicType.RUNTIME, "DoubleToStringWithRadix", 2, 1),
        new(FunctionId.FatalProcessOutOfMemoryInAllocateRaw, IntrinsicType.RUNTIME, "FatalProcessOutOfMemoryInAllocateRaw", 0, 1),
        new(FunctionId.FatalProcessOutOfMemoryInvalidArrayLength, IntrinsicType.RUNTIME, "FatalProcessOutOfMemoryInvalidArrayLength", 0, 1),
        new(FunctionId.FatalInvalidSize, IntrinsicType.RUNTIME, "FatalInvalidSize", 0, 1),
        new(FunctionId.GetAndResetRuntimeCallStats, IntrinsicType.RUNTIME, "GetAndResetRuntimeCallStats", -1, 1),
        new(FunctionId.GetAndResetTurboProfilingData, IntrinsicType.RUNTIME, "GetAndResetTurboProfilingData", 0, 1),
        new(FunctionId.GetTemplateObject, IntrinsicType.RUNTIME, "GetTemplateObject", 3, 1),
        new(FunctionId.IncrementUseCounter, IntrinsicType.RUNTIME, "IncrementUseCounter", 1, 1),
        new(FunctionId.InvalidateStringWrapperToPrimitiveProtector, IntrinsicType.RUNTIME, "InvalidateStringWrapperToPrimitiveProtector", 1, 1),
        new(FunctionId.BytecodeBudgetInterrupt_Ignition, IntrinsicType.RUNTIME, "BytecodeBudgetInterrupt_Ignition", 1, 1),
        new(FunctionId.BytecodeBudgetInterruptWithStackCheck_Ignition, IntrinsicType.RUNTIME, "BytecodeBudgetInterruptWithStackCheck_Ignition", 1, 1),
        new(FunctionId.BytecodeBudgetInterrupt_Sparkplug, IntrinsicType.RUNTIME, "BytecodeBudgetInterrupt_Sparkplug", 1, 1),
        new(FunctionId.BytecodeBudgetInterruptWithStackCheck_Sparkplug, IntrinsicType.RUNTIME, "BytecodeBudgetInterruptWithStackCheck_Sparkplug", 1, 1),
        new(FunctionId.BytecodeBudgetInterrupt_Maglev, IntrinsicType.RUNTIME, "BytecodeBudgetInterrupt_Maglev", 1, 1),
        new(FunctionId.BytecodeBudgetLoopInterrupt_Maglev, IntrinsicType.RUNTIME, "BytecodeBudgetLoopInterrupt_Maglev", 2, 1),
        new(FunctionId.NotifyContextCellStateWillChange, IntrinsicType.RUNTIME, "NotifyContextCellStateWillChange", 1, 1),
        new(FunctionId.NewError, IntrinsicType.RUNTIME, "NewError", 2, 1),
        new(FunctionId.NewReferenceError, IntrinsicType.RUNTIME, "NewReferenceError", 2, 1),
        new(FunctionId.NewTypeError, IntrinsicType.RUNTIME, "NewTypeError", -1, 1),
        new(FunctionId.OrdinaryHasInstance, IntrinsicType.RUNTIME, "OrdinaryHasInstance", 2, 1),
        new(FunctionId.PropagateException, IntrinsicType.RUNTIME, "PropagateException", 0, 1),
        new(FunctionId.ReportMessageFromMicrotask, IntrinsicType.RUNTIME, "ReportMessageFromMicrotask", 1, 1),
        new(FunctionId.RunMicrotaskCallback, IntrinsicType.RUNTIME, "RunMicrotaskCallback", 2, 1),
        new(FunctionId.PerformMicrotaskCheckpoint, IntrinsicType.RUNTIME, "PerformMicrotaskCheckpoint", 0, 1),
        new(FunctionId.SharedValueBarrierSlow, IntrinsicType.RUNTIME, "SharedValueBarrierSlow", 1, 1),
        new(FunctionId.StackGuard, IntrinsicType.RUNTIME, "StackGuard", 0, 1),
        new(FunctionId.HandleNoHeapWritesInterrupts, IntrinsicType.RUNTIME, "HandleNoHeapWritesInterrupts", 0, 1),
        new(FunctionId.StackGuardWithGap, IntrinsicType.RUNTIME, "StackGuardWithGap", 1, 1),
        new(FunctionId.TerminateExecution, IntrinsicType.RUNTIME, "TerminateExecution", 0, 1),
        new(FunctionId.Typeof, IntrinsicType.RUNTIME, "Typeof", 1, 1),
        new(FunctionId.UnwindAndFindExceptionHandler, IntrinsicType.RUNTIME, "UnwindAndFindExceptionHandler", 0, 1),
        new(FunctionId.AddLhsIsStringConstantInternalize, IntrinsicType.RUNTIME, "AddLhsIsStringConstantInternalize", 4, 1),
        new(FunctionId.AddRhsIsStringConstantInternalize, IntrinsicType.RUNTIME, "AddRhsIsStringConstantInternalize", 4, 1),
        new(FunctionId.CreateArrayLiteral, IntrinsicType.RUNTIME, "CreateArrayLiteral", 4, 1),
        new(FunctionId.CreateObjectLiteral, IntrinsicType.RUNTIME, "CreateObjectLiteral", 4, 1),
        new(FunctionId.SetPrototypeProperties, IntrinsicType.RUNTIME, "SetPrototypeProperties", 4, 1),
        new(FunctionId.CreateRegExpLiteral, IntrinsicType.RUNTIME, "CreateRegExpLiteral", 4, 1),
        new(FunctionId.DynamicImportCall, IntrinsicType.RUNTIME, "DynamicImportCall", -1, 1),
        new(FunctionId.GetImportMetaObject, IntrinsicType.RUNTIME, "GetImportMetaObject", 0, 1),
        new(FunctionId.GetModuleNamespace, IntrinsicType.RUNTIME, "GetModuleNamespace", 1, 1),
        new(FunctionId.GetModuleNamespaceExport, IntrinsicType.RUNTIME, "GetModuleNamespaceExport", 2, 1),
        new(FunctionId.ArrayBufferMaxByteLength, IntrinsicType.RUNTIME, "ArrayBufferMaxByteLength", 0, 1),
        new(FunctionId.IsSmi, IntrinsicType.RUNTIME, "IsSmi", 1, 1),
        new(FunctionId.MaxSmi, IntrinsicType.RUNTIME, "MaxSmi", 0, 1),
        new(FunctionId.NumberToStringSlow, IntrinsicType.RUNTIME, "NumberToStringSlow", 1, 1),
        new(FunctionId.Float64ToStringSlow, IntrinsicType.RUNTIME, "Float64ToStringSlow", 0, 1),
        new(FunctionId.StringParseFloat, IntrinsicType.RUNTIME, "StringParseFloat", 1, 1),
        new(FunctionId.StringParseInt, IntrinsicType.RUNTIME, "StringParseInt", 2, 1),
        new(FunctionId.StringToNumber, IntrinsicType.RUNTIME, "StringToNumber", 1, 1),
        new(FunctionId.AddAsyncDisposableValue, IntrinsicType.RUNTIME, "AddAsyncDisposableValue", 2, 1),
        new(FunctionId.AddDictionaryProperty, IntrinsicType.RUNTIME, "AddDictionaryProperty", 3, 1),
        new(FunctionId.AddDisposableValue, IntrinsicType.RUNTIME, "AddDisposableValue", 2, 1),
        new(FunctionId.AddPrivateBrand, IntrinsicType.RUNTIME, "AddPrivateBrand", 4, 1),
        new(FunctionId.AllocateHeapNumber, IntrinsicType.RUNTIME, "AllocateHeapNumber", 0, 1),
        new(FunctionId.CompleteInobjectSlackTrackingForMap, IntrinsicType.RUNTIME, "CompleteInobjectSlackTrackingForMap", 1, 1),
        new(FunctionId.CopyDataProperties, IntrinsicType.RUNTIME, "CopyDataProperties", 2, 1),
        new(FunctionId.CopyDataPropertiesWithExcludedPropertiesOnStack, IntrinsicType.RUNTIME, "CopyDataPropertiesWithExcludedPropertiesOnStack", -1, 1),
        new(FunctionId.CreateDataProperty, IntrinsicType.RUNTIME, "CreateDataProperty", 3, 1),
        new(FunctionId.CreateIterResultObject, IntrinsicType.RUNTIME, "CreateIterResultObject", 2, 1),
        new(FunctionId.IterableToListWithInterceptor, IntrinsicType.RUNTIME, "IterableToListWithInterceptor", 1, 1),
        new(FunctionId.CheckFastIterableToListPrototype, IntrinsicType.RUNTIME, "CheckFastIterableToListPrototype", 1, 1),
        new(FunctionId.CreatePrivateAccessors, IntrinsicType.RUNTIME, "CreatePrivateAccessors", 2, 1),
        new(FunctionId.DefineAccessorPropertyUnchecked, IntrinsicType.RUNTIME, "DefineAccessorPropertyUnchecked", 5, 1),
        new(FunctionId.DefineKeyedOwnPropertyInLiteral, IntrinsicType.RUNTIME, "DefineKeyedOwnPropertyInLiteral", 6, 1),
        new(FunctionId.DefineGetterPropertyUnchecked, IntrinsicType.RUNTIME, "DefineGetterPropertyUnchecked", 4, 1),
        new(FunctionId.DefineSetterPropertyUnchecked, IntrinsicType.RUNTIME, "DefineSetterPropertyUnchecked", 4, 1),
        new(FunctionId.DeleteProperty, IntrinsicType.RUNTIME, "DeleteProperty", 3, 1),
        new(FunctionId.DisposeDisposableStack, IntrinsicType.RUNTIME, "DisposeDisposableStack", 5, 1),
        new(FunctionId.GeneratorYieldResult, IntrinsicType.RUNTIME, "GeneratorYieldResult", 2, 1),
        new(FunctionId.GetDerivedMap, IntrinsicType.RUNTIME, "GetDerivedMap", 2, 1),
        new(FunctionId.GetFunctionName, IntrinsicType.RUNTIME, "GetFunctionName", 1, 1),
        new(FunctionId.GetOwnPropertyDescriptorObject, IntrinsicType.RUNTIME, "GetOwnPropertyDescriptorObject", 2, 1),
        new(FunctionId.GetOwnPropertyKeys, IntrinsicType.RUNTIME, "GetOwnPropertyKeys", 2, 1),
        new(FunctionId.GetPrivateMember, IntrinsicType.RUNTIME, "GetPrivateMember", 2, 1),
        new(FunctionId.GetProperty, IntrinsicType.RUNTIME, "GetProperty", -1, 1),
        new(FunctionId.HandleExceptionsInDisposeDisposableStack, IntrinsicType.RUNTIME, "HandleExceptionsInDisposeDisposableStack", 3, 1),
        new(FunctionId.HasFastPackedElements, IntrinsicType.RUNTIME, "HasFastPackedElements", 1, 1),
        new(FunctionId.HasInPrototypeChain, IntrinsicType.RUNTIME, "HasInPrototypeChain", 2, 1),
        new(FunctionId.HasProperty, IntrinsicType.RUNTIME, "HasProperty", 2, 1),
        new(FunctionId.InitializeDisposableStack, IntrinsicType.RUNTIME, "InitializeDisposableStack", 0, 1),
        new(FunctionId.InternalSetPrototype, IntrinsicType.RUNTIME, "InternalSetPrototype", 2, 1),
        new(FunctionId.IsJSReceiver, IntrinsicType.RUNTIME, "IsJSReceiver", 1, 1),
        new(FunctionId.JSReceiverPreventExtensionsDontThrow, IntrinsicType.RUNTIME, "JSReceiverPreventExtensionsDontThrow", 1, 1),
        new(FunctionId.JSReceiverPreventExtensionsThrow, IntrinsicType.RUNTIME, "JSReceiverPreventExtensionsThrow", 1, 1),
        new(FunctionId.JSReceiverGetPrototypeOf, IntrinsicType.RUNTIME, "JSReceiverGetPrototypeOf", 1, 1),
        new(FunctionId.JSReceiverSetPrototypeOfDontThrow, IntrinsicType.RUNTIME, "JSReceiverSetPrototypeOfDontThrow", 2, 1),
        new(FunctionId.JSReceiverSetPrototypeOfThrow, IntrinsicType.RUNTIME, "JSReceiverSetPrototypeOfThrow", 2, 1),
        new(FunctionId.LoadPrivateGetter, IntrinsicType.RUNTIME, "LoadPrivateGetter", 1, 1),
        new(FunctionId.LoadPrivateSetter, IntrinsicType.RUNTIME, "LoadPrivateSetter", 1, 1),
        new(FunctionId.NewObject, IntrinsicType.RUNTIME, "NewObject", 2, 1),
        new(FunctionId.ObjectCreate, IntrinsicType.RUNTIME, "ObjectCreate", 2, 1),
        new(FunctionId.ObjectEntries, IntrinsicType.RUNTIME, "ObjectEntries", 1, 1),
        new(FunctionId.ObjectEntriesSkipFastPath, IntrinsicType.RUNTIME, "ObjectEntriesSkipFastPath", 1, 1),
        new(FunctionId.ObjectGetOwnPropertyNames, IntrinsicType.RUNTIME, "ObjectGetOwnPropertyNames", 1, 1),
        new(FunctionId.ObjectGetOwnPropertyNamesTryFast, IntrinsicType.RUNTIME, "ObjectGetOwnPropertyNamesTryFast", 1, 1),
        new(FunctionId.ObjectHasOwnProperty, IntrinsicType.RUNTIME, "ObjectHasOwnProperty", 2, 1),
        new(FunctionId.HasOwnConstDataProperty, IntrinsicType.RUNTIME, "HasOwnConstDataProperty", 2, 1),
        new(FunctionId.ObjectIsExtensible, IntrinsicType.RUNTIME, "ObjectIsExtensible", 1, 1),
        new(FunctionId.ObjectKeys, IntrinsicType.RUNTIME, "ObjectKeys", 1, 1),
        new(FunctionId.ObjectValues, IntrinsicType.RUNTIME, "ObjectValues", 1, 1),
        new(FunctionId.ObjectValuesSkipFastPath, IntrinsicType.RUNTIME, "ObjectValuesSkipFastPath", 1, 1),
        new(FunctionId.OptimizeObjectForAddingMultipleProperties, IntrinsicType.RUNTIME, "OptimizeObjectForAddingMultipleProperties", 2, 1),
        new(FunctionId.SetDataProperties, IntrinsicType.RUNTIME, "SetDataProperties", 2, 1),
        new(FunctionId.SetFunctionName, IntrinsicType.RUNTIME, "SetFunctionName", 2, 1),
        new(FunctionId.SetKeyedProperty, IntrinsicType.RUNTIME, "SetKeyedProperty", 3, 1),
        new(FunctionId.DefineObjectOwnProperty, IntrinsicType.RUNTIME, "DefineObjectOwnProperty", 3, 1),
        new(FunctionId.SetNamedProperty, IntrinsicType.RUNTIME, "SetNamedProperty", 3, 1),
        new(FunctionId.SetOwnPropertyIgnoreAttributes, IntrinsicType.RUNTIME, "SetOwnPropertyIgnoreAttributes", 4, 1),
        new(FunctionId.ShrinkNameDictionary, IntrinsicType.RUNTIME, "ShrinkNameDictionary", 1, 1),
        new(FunctionId.ShrinkSwissNameDictionary, IntrinsicType.RUNTIME, "ShrinkSwissNameDictionary", 1, 1),
        new(FunctionId.ToFastProperties, IntrinsicType.RUNTIME, "ToFastProperties", 1, 1),
        new(FunctionId.ToLength, IntrinsicType.RUNTIME, "ToLength", 1, 1),
        new(FunctionId.ToName, IntrinsicType.RUNTIME, "ToName", 1, 1),
        new(FunctionId.ToNumber, IntrinsicType.RUNTIME, "ToNumber", 1, 1),
        new(FunctionId.ToNumeric, IntrinsicType.RUNTIME, "ToNumeric", 1, 1),
        new(FunctionId.ToObject, IntrinsicType.RUNTIME, "ToObject", 1, 1),
        new(FunctionId.ToString, IntrinsicType.RUNTIME, "ToString", 1, 1),
        new(FunctionId.TryMigrateInstance, IntrinsicType.RUNTIME, "TryMigrateInstance", 1, 1),
        new(FunctionId.TryMigrateInstanceAndMarkMapAsMigrationTarget, IntrinsicType.RUNTIME, "TryMigrateInstanceAndMarkMapAsMigrationTarget", 1, 1),
        new(FunctionId.SetPrivateMember, IntrinsicType.RUNTIME, "SetPrivateMember", 3, 1),
        new(FunctionId.SwissTableAdd, IntrinsicType.RUNTIME, "SwissTableAdd", 4, 1),
        new(FunctionId.SwissTableAllocate, IntrinsicType.RUNTIME, "SwissTableAllocate", 1, 1),
        new(FunctionId.SwissTableDelete, IntrinsicType.RUNTIME, "SwissTableDelete", 2, 1),
        new(FunctionId.SwissTableDetailsAt, IntrinsicType.RUNTIME, "SwissTableDetailsAt", 2, 1),
        new(FunctionId.SwissTableElementsCount, IntrinsicType.RUNTIME, "SwissTableElementsCount", 1, 1),
        new(FunctionId.SwissTableEquals, IntrinsicType.RUNTIME, "SwissTableEquals", 2, 1),
        new(FunctionId.SwissTableFindEntry, IntrinsicType.RUNTIME, "SwissTableFindEntry", 2, 1),
        new(FunctionId.SwissTableUpdate, IntrinsicType.RUNTIME, "SwissTableUpdate", 4, 1),
        new(FunctionId.SwissTableValueAt, IntrinsicType.RUNTIME, "SwissTableValueAt", 2, 1),
        new(FunctionId.SwissTableKeyAt, IntrinsicType.RUNTIME, "SwissTableKeyAt", 2, 1),
        new(FunctionId.Add, IntrinsicType.RUNTIME, "Add", 2, 1),
        new(FunctionId.Equal, IntrinsicType.RUNTIME, "Equal", 2, 1),
        new(FunctionId.GreaterThan, IntrinsicType.RUNTIME, "GreaterThan", 2, 1),
        new(FunctionId.GreaterThanOrEqual, IntrinsicType.RUNTIME, "GreaterThanOrEqual", 2, 1),
        new(FunctionId.LessThan, IntrinsicType.RUNTIME, "LessThan", 2, 1),
        new(FunctionId.LessThanOrEqual, IntrinsicType.RUNTIME, "LessThanOrEqual", 2, 1),
        new(FunctionId.NotEqual, IntrinsicType.RUNTIME, "NotEqual", 2, 1),
        new(FunctionId.StrictEqual, IntrinsicType.RUNTIME, "StrictEqual", 2, 1),
        new(FunctionId.StrictNotEqual, IntrinsicType.RUNTIME, "StrictNotEqual", 2, 1),
        new(FunctionId.ReferenceEqual, IntrinsicType.RUNTIME, "ReferenceEqual", 2, 1),
        new(FunctionId.EnqueueMicrotask, IntrinsicType.RUNTIME, "EnqueueMicrotask", 1, 1),
        new(FunctionId.PromiseHookAfter, IntrinsicType.RUNTIME, "PromiseHookAfter", 1, 1),
        new(FunctionId.PromiseHookBefore, IntrinsicType.RUNTIME, "PromiseHookBefore", 1, 1),
        new(FunctionId.PromiseHookInit, IntrinsicType.RUNTIME, "PromiseHookInit", 2, 1),
        new(FunctionId.PromiseRejectEventFromStack, IntrinsicType.RUNTIME, "PromiseRejectEventFromStack", 2, 1),
        new(FunctionId.PromiseRevokeReject, IntrinsicType.RUNTIME, "PromiseRevokeReject", 1, 1),
        new(FunctionId.RejectPromise, IntrinsicType.RUNTIME, "RejectPromise", 3, 1),
        new(FunctionId.ResolvePromise, IntrinsicType.RUNTIME, "ResolvePromise", 2, 1),
        new(FunctionId.ConstructSuppressedError, IntrinsicType.RUNTIME, "ConstructSuppressedError", 3, 1),
        new(FunctionId.ConstructAggregateErrorHelper, IntrinsicType.RUNTIME, "ConstructAggregateErrorHelper", 4, 1),
        new(FunctionId.ConstructInternalAggregateErrorHelper, IntrinsicType.RUNTIME, "ConstructInternalAggregateErrorHelper", -1, 1),
        new(FunctionId.CheckProxyGetSetTrapResult, IntrinsicType.RUNTIME, "CheckProxyGetSetTrapResult", 2, 1),
        new(FunctionId.CheckProxyHasTrapResult, IntrinsicType.RUNTIME, "CheckProxyHasTrapResult", 2, 1),
        new(FunctionId.CheckProxyDeleteTrapResult, IntrinsicType.RUNTIME, "CheckProxyDeleteTrapResult", 2, 1),
        new(FunctionId.GetPropertyWithReceiver, IntrinsicType.RUNTIME, "GetPropertyWithReceiver", 3, 1),
        new(FunctionId.IsJSProxy, IntrinsicType.RUNTIME, "IsJSProxy", 1, 1),
        new(FunctionId.JSProxyGetHandler, IntrinsicType.RUNTIME, "JSProxyGetHandler", 1, 1),
        new(FunctionId.JSProxyGetTarget, IntrinsicType.RUNTIME, "JSProxyGetTarget", 1, 1),
        new(FunctionId.SetPropertyWithReceiver, IntrinsicType.RUNTIME, "SetPropertyWithReceiver", 4, 1),
        new(FunctionId.RegExpBuildIndices, IntrinsicType.RUNTIME, "RegExpBuildIndices", 3, 1),
        new(FunctionId.RegExpGrowRegExpMatchInfo, IntrinsicType.RUNTIME, "RegExpGrowRegExpMatchInfo", 2, 1),
        new(FunctionId.RegExpExecMultiple, IntrinsicType.RUNTIME, "RegExpExecMultiple", 3, 1),
        new(FunctionId.RegExpInitializeAndCompile, IntrinsicType.RUNTIME, "RegExpInitializeAndCompile", 3, 1),
        new(FunctionId.RegExpMatchGlobalAtom, IntrinsicType.RUNTIME, "RegExpMatchGlobalAtom", 3, 1),
        new(FunctionId.RegExpReplaceRT, IntrinsicType.RUNTIME, "RegExpReplaceRT", 3, 1),
        new(FunctionId.RegExpSplit, IntrinsicType.RUNTIME, "RegExpSplit", 3, 1),
        new(FunctionId.RegExpStringFromFlags, IntrinsicType.RUNTIME, "RegExpStringFromFlags", 1, 1),
        new(FunctionId.StringReplaceNonGlobalRegExpWithFunction, IntrinsicType.RUNTIME, "StringReplaceNonGlobalRegExpWithFunction", 3, 1),
        new(FunctionId.StringSplit, IntrinsicType.RUNTIME, "StringSplit", 4, 1),
        new(FunctionId.RegExpExec, IntrinsicType.RUNTIME, "RegExpExec", 4, 1),
        new(FunctionId.RegExpExperimentalOneshotExec, IntrinsicType.RUNTIME, "RegExpExperimentalOneshotExec", 4, 1),
        new(FunctionId.ThrowConstAssignError, IntrinsicType.RUNTIME, "ThrowConstAssignError", 0, 1),
        new(FunctionId.ThrowUsingAssignError, IntrinsicType.RUNTIME, "ThrowUsingAssignError", 0, 1),
        new(FunctionId.ThrowAwaitUsingAssignError, IntrinsicType.RUNTIME, "ThrowAwaitUsingAssignError", 0, 1),
        new(FunctionId.DeclareEvalFunction, IntrinsicType.RUNTIME, "DeclareEvalFunction", 2, 1),
        new(FunctionId.DeclareEvalVar, IntrinsicType.RUNTIME, "DeclareEvalVar", 1, 1),
        new(FunctionId.DeclareGlobals, IntrinsicType.RUNTIME, "DeclareGlobals", 2, 1),
        new(FunctionId.DeclareModuleExports, IntrinsicType.RUNTIME, "DeclareModuleExports", 2, 1),
        new(FunctionId.DeleteLookupSlot, IntrinsicType.RUNTIME, "DeleteLookupSlot", 1, 1),
        new(FunctionId.LoadLookupSlot, IntrinsicType.RUNTIME, "LoadLookupSlot", 1, 1),
        new(FunctionId.LoadLookupSlotInsideTypeof, IntrinsicType.RUNTIME, "LoadLookupSlotInsideTypeof", 1, 1),
        new(FunctionId.LoadLookupSlotForCall_Baseline, IntrinsicType.RUNTIME, "LoadLookupSlotForCall_Baseline", 2, 1),
        new(FunctionId.NewClosure, IntrinsicType.RUNTIME, "NewClosure", 2, 1),
        new(FunctionId.NewClosure_Tenured, IntrinsicType.RUNTIME, "NewClosure_Tenured", 2, 1),
        new(FunctionId.NewFunctionContext, IntrinsicType.RUNTIME, "NewFunctionContext", 1, 1),
        new(FunctionId.NewRestParameter, IntrinsicType.RUNTIME, "NewRestParameter", 1, 1),
        new(FunctionId.NewSloppyArguments, IntrinsicType.RUNTIME, "NewSloppyArguments", 1, 1),
        new(FunctionId.NewStrictArguments, IntrinsicType.RUNTIME, "NewStrictArguments", 1, 1),
        new(FunctionId.PushBlockContext, IntrinsicType.RUNTIME, "PushBlockContext", 1, 1),
        new(FunctionId.PushCatchContext, IntrinsicType.RUNTIME, "PushCatchContext", 2, 1),
        new(FunctionId.PushWithContext, IntrinsicType.RUNTIME, "PushWithContext", 2, 1),
        new(FunctionId.StoreGlobalNoHoleCheckForReplLetOrConst, IntrinsicType.RUNTIME, "StoreGlobalNoHoleCheckForReplLetOrConst", 2, 1),
        new(FunctionId.StoreLookupSlot_Sloppy, IntrinsicType.RUNTIME, "StoreLookupSlot_Sloppy", 2, 1),
        new(FunctionId.StoreLookupSlot_SloppyHoisting, IntrinsicType.RUNTIME, "StoreLookupSlot_SloppyHoisting", 2, 1),
        new(FunctionId.StoreLookupSlot_Strict, IntrinsicType.RUNTIME, "StoreLookupSlot_Strict", 2, 1),
        new(FunctionId.ShadowRealmWrappedFunctionCreate, IntrinsicType.RUNTIME, "ShadowRealmWrappedFunctionCreate", 2, 1),
        new(FunctionId.ShadowRealmImportValue, IntrinsicType.RUNTIME, "ShadowRealmImportValue", 1, 1),
        new(FunctionId.ShadowRealmThrow, IntrinsicType.RUNTIME, "ShadowRealmThrow", 2, 1),
        new(FunctionId.FlattenString, IntrinsicType.RUNTIME, "FlattenString", 1, 1),
        new(FunctionId.GetSubstitution, IntrinsicType.RUNTIME, "GetSubstitution", 5, 1),
        new(FunctionId.InternalizeString, IntrinsicType.RUNTIME, "InternalizeString", 1, 1),
        new(FunctionId.StringAdd, IntrinsicType.RUNTIME, "StringAdd", 2, 1),
        new(FunctionId.StringAdd_LhsIsStringConstant_Internalize, IntrinsicType.RUNTIME, "StringAdd_LhsIsStringConstant_Internalize", 4, 1),
        new(FunctionId.StringAdd_RhsIsStringConstant_Internalize, IntrinsicType.RUNTIME, "StringAdd_RhsIsStringConstant_Internalize", 4, 1),
        new(FunctionId.StringBuilderConcat, IntrinsicType.RUNTIME, "StringBuilderConcat", 3, 1),
        new(FunctionId.StringCharCodeAt, IntrinsicType.RUNTIME, "StringCharCodeAt", 2, 1),
        new(FunctionId.StringCodePointAt, IntrinsicType.RUNTIME, "StringCodePointAt", 2, 1),
        new(FunctionId.StringCompare, IntrinsicType.RUNTIME, "StringCompare", 2, 1),
        new(FunctionId.StringEqual, IntrinsicType.RUNTIME, "StringEqual", 2, 1),
        new(FunctionId.StringEscapeQuotes, IntrinsicType.RUNTIME, "StringEscapeQuotes", 1, 1),
        new(FunctionId.StringGreaterThan, IntrinsicType.RUNTIME, "StringGreaterThan", 2, 1),
        new(FunctionId.StringGreaterThanOrEqual, IntrinsicType.RUNTIME, "StringGreaterThanOrEqual", 2, 1),
        new(FunctionId.StringIsWellFormed, IntrinsicType.RUNTIME, "StringIsWellFormed", 1, 1),
        new(FunctionId.StringLastIndexOf, IntrinsicType.RUNTIME, "StringLastIndexOf", 2, 1),
        new(FunctionId.StringLessThan, IntrinsicType.RUNTIME, "StringLessThan", 2, 1),
        new(FunctionId.StringLessThanOrEqual, IntrinsicType.RUNTIME, "StringLessThanOrEqual", 2, 1),
        new(FunctionId.StringMaxLength, IntrinsicType.RUNTIME, "StringMaxLength", 0, 1),
        new(FunctionId.StringReplaceOneCharWithString, IntrinsicType.RUNTIME, "StringReplaceOneCharWithString", 3, 1),
        new(FunctionId.StringSubstring, IntrinsicType.RUNTIME, "StringSubstring", 3, 1),
        new(FunctionId.StringToArray, IntrinsicType.RUNTIME, "StringToArray", 2, 1),
        new(FunctionId.StringToWellFormed, IntrinsicType.RUNTIME, "StringToWellFormed", 1, 1),
        new(FunctionId.CreatePrivateNameSymbol, IntrinsicType.RUNTIME, "CreatePrivateNameSymbol", 1, 1),
        new(FunctionId.CreatePrivateBrandSymbol, IntrinsicType.RUNTIME, "CreatePrivateBrandSymbol", 1, 1),
        new(FunctionId.CreatePrivateSymbol, IntrinsicType.RUNTIME, "CreatePrivateSymbol", -1, 1),
        new(FunctionId.SymbolDescriptiveString, IntrinsicType.RUNTIME, "SymbolDescriptiveString", 1, 1),
        new(FunctionId.SymbolIsPrivate, IntrinsicType.RUNTIME, "SymbolIsPrivate", 1, 1),
        new(FunctionId.Abort, IntrinsicType.RUNTIME, "Abort", 1, 1),
        new(FunctionId.AbortCSADcheck, IntrinsicType.RUNTIME, "AbortCSADcheck", 1, 1),
        new(FunctionId.AbortJS, IntrinsicType.RUNTIME, "AbortJS", 1, 1),
        new(FunctionId.ActiveTierIsIgnition, IntrinsicType.RUNTIME, "ActiveTierIsIgnition", 1, 1),
        new(FunctionId.ActiveTierIsSparkplug, IntrinsicType.RUNTIME, "ActiveTierIsSparkplug", 1, 1),
        new(FunctionId.ActiveTierIsMaglev, IntrinsicType.RUNTIME, "ActiveTierIsMaglev", 1, 1),
        new(FunctionId.ActiveTierIsTurbofan, IntrinsicType.RUNTIME, "ActiveTierIsTurbofan", 1, 1),
        new(FunctionId.AllocateHeapNumberWithValue, IntrinsicType.RUNTIME, "AllocateHeapNumberWithValue", 1, 1),
        new(FunctionId.ArrayBufferDetachForceWasm, IntrinsicType.RUNTIME, "ArrayBufferDetachForceWasm", 1, 1),
        new(FunctionId.ArrayIteratorProtector, IntrinsicType.RUNTIME, "ArrayIteratorProtector", 0, 1),
        new(FunctionId.ArraySpeciesProtector, IntrinsicType.RUNTIME, "ArraySpeciesProtector", 0, 1),
        new(FunctionId.AssertNotPeeled, IntrinsicType.RUNTIME, "AssertNotPeeled", 0, 1),
        new(FunctionId.AssertPeeled, IntrinsicType.RUNTIME, "AssertPeeled", 0, 1),
        new(FunctionId.BaselineOsr, IntrinsicType.RUNTIME, "BaselineOsr", -1, 1),
        new(FunctionId.BenchMaglev, IntrinsicType.RUNTIME, "BenchMaglev", 2, 1),
        new(FunctionId.BenchTurbofan, IntrinsicType.RUNTIME, "BenchTurbofan", 2, 1),
        new(FunctionId.BlockAt, IntrinsicType.RUNTIME, "BlockAt", 2, 1),
        new(FunctionId.VerifyGetJSBuiltinState, IntrinsicType.RUNTIME, "VerifyGetJSBuiltinState", 1, 1),
        new(FunctionId.ClearFunctionFeedback, IntrinsicType.RUNTIME, "ClearFunctionFeedback", 1, 1),
        new(FunctionId.ClearMegamorphicStubCache, IntrinsicType.RUNTIME, "ClearMegamorphicStubCache", 0, 1),
        new(FunctionId.CompleteInobjectSlackTracking, IntrinsicType.RUNTIME, "CompleteInobjectSlackTracking", 1, 1),
        new(FunctionId.ConstructConsString, IntrinsicType.RUNTIME, "ConstructConsString", 2, 1),
        new(FunctionId.ConstructDouble, IntrinsicType.RUNTIME, "ConstructDouble", 2, 1),
        new(FunctionId.ConstructInternalizedString, IntrinsicType.RUNTIME, "ConstructInternalizedString", 1, 1),
        new(FunctionId.ConstructSlicedString, IntrinsicType.RUNTIME, "ConstructSlicedString", 2, 1),
        new(FunctionId.ConstructThinString, IntrinsicType.RUNTIME, "ConstructThinString", 1, 1),
        new(FunctionId.CurrentFrameIsTurbofan, IntrinsicType.RUNTIME, "CurrentFrameIsTurbofan", 0, 1),
        new(FunctionId.DebugPrint, IntrinsicType.RUNTIME, "DebugPrint", -1, 1),
        new(FunctionId.DebugPrintCppHeapPointerTable, IntrinsicType.RUNTIME, "DebugPrintCppHeapPointerTable", -1, 1),
        new(FunctionId.DebugPrintCppHeapPointerTableFilterTag, IntrinsicType.RUNTIME, "DebugPrintCppHeapPointerTableFilterTag", -1, 1),
        new(FunctionId.DebugPrintExternalPointerTable, IntrinsicType.RUNTIME, "DebugPrintExternalPointerTable", -1, 1),
        new(FunctionId.DebugPrintExternalPointerTableFilterTag, IntrinsicType.RUNTIME, "DebugPrintExternalPointerTableFilterTag", -1, 1),
        new(FunctionId.DebugPrintGeneric, IntrinsicType.RUNTIME, "DebugPrintGeneric", -1, 1),
        new(FunctionId.DebugPrintFloat, IntrinsicType.RUNTIME, "DebugPrintFloat", 5, 1),
        new(FunctionId.DebugPrintPtr, IntrinsicType.RUNTIME, "DebugPrintPtr", 1, 1),
        new(FunctionId.DebugPrintWord, IntrinsicType.RUNTIME, "DebugPrintWord", 5, 1),
        new(FunctionId.DebugTrace, IntrinsicType.RUNTIME, "DebugTrace", 0, 1),
        new(FunctionId.DebugTraceMinimal, IntrinsicType.RUNTIME, "DebugTraceMinimal", 0, 1),
        new(FunctionId.DeoptimizeFunction, IntrinsicType.RUNTIME, "DeoptimizeFunction", 1, 1),
        new(FunctionId.DisableOptimizationFinalization, IntrinsicType.RUNTIME, "DisableOptimizationFinalization", 0, 1),
        new(FunctionId.DisallowCodegenFromStrings, IntrinsicType.RUNTIME, "DisallowCodegenFromStrings", 1, 1),
        new(FunctionId.DisassembleFunction, IntrinsicType.RUNTIME, "DisassembleFunction", 1, 1),
        new(FunctionId.EnableCodeLoggingForTesting, IntrinsicType.RUNTIME, "EnableCodeLoggingForTesting", 0, 1),
        new(FunctionId.EnsureFeedbackVectorForFunction, IntrinsicType.RUNTIME, "EnsureFeedbackVectorForFunction", 1, 1),
        new(FunctionId.FinalizeOptimization, IntrinsicType.RUNTIME, "FinalizeOptimization", 0, 1),
        new(FunctionId.ForceFlush, IntrinsicType.RUNTIME, "ForceFlush", 1, 1),
        new(FunctionId.MajorGCForCompilerTesting, IntrinsicType.RUNTIME, "MajorGCForCompilerTesting", 0, 1),
        new(FunctionId.GetAbstractModuleSource, IntrinsicType.RUNTIME, "GetAbstractModuleSource", 0, 1),
        new(FunctionId.GetBytecode, IntrinsicType.RUNTIME, "GetBytecode", 1, 1),
        new(FunctionId.ExhaustInterruptBudget, IntrinsicType.RUNTIME, "ExhaustInterruptBudget", 1, 1),
        new(FunctionId.GetCallable, IntrinsicType.RUNTIME, "GetCallable", 1, 1),
        new(FunctionId.GetFeedback, IntrinsicType.RUNTIME, "GetFeedback", 1, 1),
        new(FunctionId.GetFunctionForCurrentFrame, IntrinsicType.RUNTIME, "GetFunctionForCurrentFrame", 0, 1),
        new(FunctionId.GetInitializerFunction, IntrinsicType.RUNTIME, "GetInitializerFunction", 1, 1),
        new(FunctionId.GetOptimizationStatus, IntrinsicType.RUNTIME, "GetOptimizationStatus", 1, 1),
        new(FunctionId.GetUndetectable, IntrinsicType.RUNTIME, "GetUndetectable", 0, 1),
        new(FunctionId.GetWeakCollectionSize, IntrinsicType.RUNTIME, "GetWeakCollectionSize", 1, 1),
        new(FunctionId.GlobalPrint, IntrinsicType.RUNTIME, "GlobalPrint", -1, 1),
        new(FunctionId.HasCowElements, IntrinsicType.RUNTIME, "HasCowElements", 1, 1),
        new(FunctionId.HasDictionaryElements, IntrinsicType.RUNTIME, "HasDictionaryElements", 1, 1),
        new(FunctionId.HasDoubleElements, IntrinsicType.RUNTIME, "HasDoubleElements", 1, 1),
        new(FunctionId.HasElementsInALargeObjectSpace, IntrinsicType.RUNTIME, "HasElementsInALargeObjectSpace", 1, 1),
        new(FunctionId.HasFastElements, IntrinsicType.RUNTIME, "HasFastElements", 1, 1),
        new(FunctionId.HasFastProperties, IntrinsicType.RUNTIME, "HasFastProperties", 1, 1),
        new(FunctionId.HasFixedBigInt64Elements, IntrinsicType.RUNTIME, "HasFixedBigInt64Elements", 1, 1),
        new(FunctionId.HasFixedBigUint64Elements, IntrinsicType.RUNTIME, "HasFixedBigUint64Elements", 1, 1),
        new(FunctionId.HasFixedFloat16Elements, IntrinsicType.RUNTIME, "HasFixedFloat16Elements", 1, 1),
        new(FunctionId.HasFixedFloat32Elements, IntrinsicType.RUNTIME, "HasFixedFloat32Elements", 1, 1),
        new(FunctionId.HasFixedFloat64Elements, IntrinsicType.RUNTIME, "HasFixedFloat64Elements", 1, 1),
        new(FunctionId.HasFixedInt16Elements, IntrinsicType.RUNTIME, "HasFixedInt16Elements", 1, 1),
        new(FunctionId.HasFixedInt32Elements, IntrinsicType.RUNTIME, "HasFixedInt32Elements", 1, 1),
        new(FunctionId.HasFixedInt8Elements, IntrinsicType.RUNTIME, "HasFixedInt8Elements", 1, 1),
        new(FunctionId.HasFixedUint16Elements, IntrinsicType.RUNTIME, "HasFixedUint16Elements", 1, 1),
        new(FunctionId.HasFixedUint32Elements, IntrinsicType.RUNTIME, "HasFixedUint32Elements", 1, 1),
        new(FunctionId.HasFixedUint8ClampedElements, IntrinsicType.RUNTIME, "HasFixedUint8ClampedElements", 1, 1),
        new(FunctionId.HasFixedUint8Elements, IntrinsicType.RUNTIME, "HasFixedUint8Elements", 1, 1),
        new(FunctionId.HasHoleyElements, IntrinsicType.RUNTIME, "HasHoleyElements", 1, 1),
        new(FunctionId.HasObjectElements, IntrinsicType.RUNTIME, "HasObjectElements", 1, 1),
        new(FunctionId.HasPackedElements, IntrinsicType.RUNTIME, "HasPackedElements", 1, 1),
        new(FunctionId.HasSloppyArgumentsElements, IntrinsicType.RUNTIME, "HasSloppyArgumentsElements", 1, 1),
        new(FunctionId.HasSmiElements, IntrinsicType.RUNTIME, "HasSmiElements", 1, 1),
        new(FunctionId.HasSmiOrObjectElements, IntrinsicType.RUNTIME, "HasSmiOrObjectElements", 1, 1),
        new(FunctionId.HaveSameMap, IntrinsicType.RUNTIME, "HaveSameMap", 2, 1),
        new(FunctionId.HeapObjectVerify, IntrinsicType.RUNTIME, "HeapObjectVerify", 1, 1),
        new(FunctionId.ICsAreEnabled, IntrinsicType.RUNTIME, "ICsAreEnabled", 0, 1),
        new(FunctionId.InLargeObjectSpace, IntrinsicType.RUNTIME, "InLargeObjectSpace", 1, 1),
        new(FunctionId.InstallBytecode, IntrinsicType.RUNTIME, "InstallBytecode", 2, 1),
        new(FunctionId.InYoungGeneration, IntrinsicType.RUNTIME, "InYoungGeneration", 1, 1),
        new(FunctionId.Is64Bit, IntrinsicType.RUNTIME, "Is64Bit", 0, 1),
        new(FunctionId.IsAtomicsWaitAllowed, IntrinsicType.RUNTIME, "IsAtomicsWaitAllowed", 0, 1),
        new(FunctionId.IsBeingInterpreted, IntrinsicType.RUNTIME, "IsBeingInterpreted", 0, 1),
        new(FunctionId.IsConcatSpreadableProtector, IntrinsicType.RUNTIME, "IsConcatSpreadableProtector", 0, 1),
        new(FunctionId.IsConcurrentRecompilationSupported, IntrinsicType.RUNTIME, "IsConcurrentRecompilationSupported", 0, 1),
        new(FunctionId.IsDictPropertyConstTrackingEnabled, IntrinsicType.RUNTIME, "IsDictPropertyConstTrackingEnabled", 0, 1),
        new(FunctionId.IsEfficiencyModeEnabled, IntrinsicType.RUNTIME, "IsEfficiencyModeEnabled", 0, 1),
        new(FunctionId.IsInPlaceInternalizableString, IntrinsicType.RUNTIME, "IsInPlaceInternalizableString", 1, 1),
        new(FunctionId.IsInternalizedString, IntrinsicType.RUNTIME, "IsInternalizedString", 1, 1),
        new(FunctionId.StringToCString, IntrinsicType.RUNTIME, "StringToCString", 1, 1),
        new(FunctionId.StringUtf8Value, IntrinsicType.RUNTIME, "StringUtf8Value", 1, 1),
        new(FunctionId.IsUndefinedDoubleEnabled, IntrinsicType.RUNTIME, "IsUndefinedDoubleEnabled", 0, 1),
        new(FunctionId.IsMaglevEnabled, IntrinsicType.RUNTIME, "IsMaglevEnabled", 0, 1),
        new(FunctionId.IsSameHeapObject, IntrinsicType.RUNTIME, "IsSameHeapObject", 2, 1),
        new(FunctionId.IsSharedString, IntrinsicType.RUNTIME, "IsSharedString", 1, 1),
        new(FunctionId.IsInWritableSharedSpace, IntrinsicType.RUNTIME, "IsInWritableSharedSpace", 1, 1),
        new(FunctionId.IsSparkplugEnabled, IntrinsicType.RUNTIME, "IsSparkplugEnabled", 0, 1),
        new(FunctionId.IsTurbofanEnabled, IntrinsicType.RUNTIME, "IsTurbofanEnabled", 0, 1),
        new(FunctionId.IsWasmTieringPredictable, IntrinsicType.RUNTIME, "IsWasmTieringPredictable", 0, 1),
        new(FunctionId.MapIteratorProtector, IntrinsicType.RUNTIME, "MapIteratorProtector", 0, 1),
        new(FunctionId.NeverOptimizeFunction, IntrinsicType.RUNTIME, "NeverOptimizeFunction", 1, 1),
        new(FunctionId.NewRegExpWithBacktrackLimit, IntrinsicType.RUNTIME, "NewRegExpWithBacktrackLimit", 3, 1),
        new(FunctionId.NoElementsProtector, IntrinsicType.RUNTIME, "NoElementsProtector", 0, 1),
        new(FunctionId.NotifyContextDisposed, IntrinsicType.RUNTIME, "NotifyContextDisposed", 0, 1),
        new(FunctionId.SetPriorityBestEffort, IntrinsicType.RUNTIME, "SetPriorityBestEffort", 0, 1),
        new(FunctionId.SetPriorityUserVisible, IntrinsicType.RUNTIME, "SetPriorityUserVisible", 0, 1),
        new(FunctionId.SetPriorityUserBlocking, IntrinsicType.RUNTIME, "SetPriorityUserBlocking", 0, 1),
        new(FunctionId.OptimizeMaglevOnNextCall, IntrinsicType.RUNTIME, "OptimizeMaglevOnNextCall", -1, 1),
        new(FunctionId.OptimizeFunctionOnNextCall, IntrinsicType.RUNTIME, "OptimizeFunctionOnNextCall", -1, 1),
        new(FunctionId.OptimizeOsr, IntrinsicType.RUNTIME, "OptimizeOsr", -1, 1),
        new(FunctionId.PrepareFunctionForOptimization, IntrinsicType.RUNTIME, "PrepareFunctionForOptimization", -1, 1),
        new(FunctionId.PretenureAllocationSite, IntrinsicType.RUNTIME, "PretenureAllocationSite", 1, 1),
        new(FunctionId.PrintWithNameForAssert, IntrinsicType.RUNTIME, "PrintWithNameForAssert", 2, 1),
        new(FunctionId.PromiseSpeciesProtector, IntrinsicType.RUNTIME, "PromiseSpeciesProtector", 0, 1),
        new(FunctionId.RegExpSpeciesProtector, IntrinsicType.RUNTIME, "RegExpSpeciesProtector", 0, 1),
        new(FunctionId.RegexpHasBytecode, IntrinsicType.RUNTIME, "RegexpHasBytecode", 2, 1),
        new(FunctionId.RegexpHasNativeCode, IntrinsicType.RUNTIME, "RegexpHasNativeCode", 2, 1),
        new(FunctionId.RegexpIsUnmodified, IntrinsicType.RUNTIME, "RegexpIsUnmodified", 1, 1),
        new(FunctionId.RegexpQuickCheckRejects, IntrinsicType.RUNTIME, "RegexpQuickCheckRejects", 2, 1),
        new(FunctionId.RegexpTypeTag, IntrinsicType.RUNTIME, "RegexpTypeTag", 1, 1),
        new(FunctionId.Resume, IntrinsicType.RUNTIME, "Resume", 1, 1),
        new(FunctionId.RunningInSimulator, IntrinsicType.RUNTIME, "RunningInSimulator", 0, 1),
        new(FunctionId.RuntimeEvaluateREPL, IntrinsicType.RUNTIME, "RuntimeEvaluateREPL", 1, 1),
        new(FunctionId.ScheduleGCInStackCheck, IntrinsicType.RUNTIME, "ScheduleGCInStackCheck", 0, 1),
        new(FunctionId.SerializeDeserializeNow, IntrinsicType.RUNTIME, "SerializeDeserializeNow", 0, 1),
        new(FunctionId.SetAllocationTimeout, IntrinsicType.RUNTIME, "SetAllocationTimeout", -1, 1),
        new(FunctionId.SetDispatchTableGCInterval, IntrinsicType.RUNTIME, "SetDispatchTableGCInterval", 1, 1),
        new(FunctionId.SetBatterySaverMode, IntrinsicType.RUNTIME, "SetBatterySaverMode", 1, 1),
        new(FunctionId.SetForceSlowPath, IntrinsicType.RUNTIME, "SetForceSlowPath", 1, 1),
        new(FunctionId.SetIteratorProtector, IntrinsicType.RUNTIME, "SetIteratorProtector", 0, 1),
        new(FunctionId.SharedGC, IntrinsicType.RUNTIME, "SharedGC", 0, 1),
        new(FunctionId.ShareObject, IntrinsicType.RUNTIME, "ShareObject", 1, 1),
        new(FunctionId.SimulateNewspaceFull, IntrinsicType.RUNTIME, "SimulateNewspaceFull", 0, 1),
        new(FunctionId.StringIsFlat, IntrinsicType.RUNTIME, "StringIsFlat", 1, 1),
        new(FunctionId.StringIteratorProtector, IntrinsicType.RUNTIME, "StringIteratorProtector", 0, 1),
        new(FunctionId.StringWrapperToPrimitiveProtector, IntrinsicType.RUNTIME, "StringWrapperToPrimitiveProtector", 0, 1),
        new(FunctionId.SystemBreak, IntrinsicType.RUNTIME, "SystemBreak", 0, 1),
        new(FunctionId.TakeHeapSnapshot, IntrinsicType.RUNTIME, "TakeHeapSnapshot", -1, 1),
        new(FunctionId.TraceEnter, IntrinsicType.RUNTIME, "TraceEnter", 0, 1),
        new(FunctionId.TraceExit, IntrinsicType.RUNTIME, "TraceExit", 1, 1),
        new(FunctionId.TurbofanStaticAssert, IntrinsicType.RUNTIME, "TurbofanStaticAssert", 1, 1),
        new(FunctionId.AssertEscapeAnalysisElided, IntrinsicType.RUNTIME, "AssertEscapeAnalysisElided", 1, 1),
        new(FunctionId.TypedArraySpeciesProtector, IntrinsicType.RUNTIME, "TypedArraySpeciesProtector", 0, 1),
        new(FunctionId.WaitForBackgroundOptimization, IntrinsicType.RUNTIME, "WaitForBackgroundOptimization", 0, 1),
        new(FunctionId.WaitUntilBlocked, IntrinsicType.RUNTIME, "WaitUntilBlocked", 2, 1),
        new(FunctionId.DeoptimizeNow, IntrinsicType.RUNTIME, "DeoptimizeNow", 0, 1),
        new(FunctionId.LeakHole, IntrinsicType.RUNTIME, "LeakHole", 0, 1),
        new(FunctionId.GetHoleNaNLower, IntrinsicType.RUNTIME, "GetHoleNaNLower", 0, 1),
        new(FunctionId.GetHoleNaNUpper, IntrinsicType.RUNTIME, "GetHoleNaNUpper", 0, 1),
        new(FunctionId.GetHoleNaN, IntrinsicType.RUNTIME, "GetHoleNaN", 0, 1),
        new(FunctionId.GetUndefinedNaN, IntrinsicType.RUNTIME, "GetUndefinedNaN", 0, 1),
        new(FunctionId.ArrayBufferDetach, IntrinsicType.RUNTIME, "ArrayBufferDetach", -1, 1),
        new(FunctionId.ArrayBufferSetDetachKey, IntrinsicType.RUNTIME, "ArrayBufferSetDetachKey", 2, 1),
        new(FunctionId.GrowableSharedArrayBufferByteLength, IntrinsicType.RUNTIME, "GrowableSharedArrayBufferByteLength", 1, 1),
        new(FunctionId.TypedArrayCopyElements, IntrinsicType.RUNTIME, "TypedArrayCopyElements", 3, 1),
        new(FunctionId.TypedArrayGetBuffer, IntrinsicType.RUNTIME, "TypedArrayGetBuffer", 1, 1),
        new(FunctionId.TypedArraySet, IntrinsicType.RUNTIME, "TypedArraySet", 2, 1),
        new(FunctionId.TypedArraySortFast, IntrinsicType.RUNTIME, "TypedArraySortFast", 1, 1),
        new(FunctionId.JSFinalizationRegistryRegisterWeakCellWithUnregisterToken, IntrinsicType.RUNTIME, "JSFinalizationRegistryRegisterWeakCellWithUnregisterToken", 2, 1),
        new(FunctionId.JSWeakRefAddToKeptObjects, IntrinsicType.RUNTIME, "JSWeakRefAddToKeptObjects", 1, 1),
        new(FunctionId.InlineIncBlockCounter, IntrinsicType.INLINE, "_IncBlockCounter", 2, 1),
        new(FunctionId.InlineAsyncFunctionAwait, IntrinsicType.INLINE, "_AsyncFunctionAwait", 2, 1),
        new(FunctionId.InlineAsyncFunctionEnter, IntrinsicType.INLINE, "_AsyncFunctionEnter", 2, 1),
        new(FunctionId.InlineAsyncFunctionReject, IntrinsicType.INLINE, "_AsyncFunctionReject", 2, 1),
        new(FunctionId.InlineAsyncFunctionResolve, IntrinsicType.INLINE, "_AsyncFunctionResolve", 2, 1),
        new(FunctionId.InlineAsyncGeneratorAwait, IntrinsicType.INLINE, "_AsyncGeneratorAwait", 2, 1),
        new(FunctionId.InlineAsyncGeneratorReject, IntrinsicType.INLINE, "_AsyncGeneratorReject", 2, 1),
        new(FunctionId.InlineAsyncGeneratorResolve, IntrinsicType.INLINE, "_AsyncGeneratorResolve", 3, 1),
        new(FunctionId.InlineAsyncGeneratorYieldWithAwait, IntrinsicType.INLINE, "_AsyncGeneratorYieldWithAwait", 2, 1),
        new(FunctionId.InlineCreateJSGeneratorObject, IntrinsicType.INLINE, "_CreateJSGeneratorObject", 2, 1),
        new(FunctionId.InlineGeneratorClose, IntrinsicType.INLINE, "_GeneratorClose", 1, 1),
        new(FunctionId.InlineGeneratorGetResumeMode, IntrinsicType.INLINE, "_GeneratorGetResumeMode", 1, 1),
        new(FunctionId.InlineCreateAsyncFromSyncIterator, IntrinsicType.INLINE, "_CreateAsyncFromSyncIterator", 1, 1),
        new(FunctionId.InlineAddLhsIsStringConstantInternalize, IntrinsicType.INLINE, "_AddLhsIsStringConstantInternalize", 4, 1),
        new(FunctionId.InlineAddRhsIsStringConstantInternalize, IntrinsicType.INLINE, "_AddRhsIsStringConstantInternalize", 4, 1),
        new(FunctionId.InlineGetImportMetaObject, IntrinsicType.INLINE, "_GetImportMetaObject", 0, 1),
        new(FunctionId.InlineCopyDataProperties, IntrinsicType.INLINE, "_CopyDataProperties", 2, 1),
        new(FunctionId.InlineCopyDataPropertiesWithExcludedPropertiesOnStack, IntrinsicType.INLINE, "_CopyDataPropertiesWithExcludedPropertiesOnStack", -1, 1),
        new(FunctionId.InlineCreateDataProperty, IntrinsicType.INLINE, "_CreateDataProperty", 3, 1),
        new(FunctionId.InlineCreateIterResultObject, IntrinsicType.INLINE, "_CreateIterResultObject", 2, 1),
        new(FunctionId.InlineGeneratorYieldResult, IntrinsicType.INLINE, "_GeneratorYieldResult", 2, 1),
        new(FunctionId.InlineDeoptimizeNow, IntrinsicType.INLINE, "_DeoptimizeNow", 0, 1),
    ];

    private static readonly Dictionary<string, RuntimeFunction> s_byName = BuildNameMap();

    private static Dictionary<string, RuntimeFunction> BuildNameMap()
    {
        var map = new Dictionary<string, RuntimeFunction>(StringComparer.Ordinal);
        foreach (var f in s_intrinsicFunctions) map[f.name] = f;
        return map;
    }

    public const int kNumFunctions = (int)FunctionId.NumFunctions;

    // Get the intrinsic function with the given name.
    public static RuntimeFunction? FunctionForName(string name) => s_byName.GetValueOrDefault(name);

    public static RuntimeFunction? FunctionForName(ReadOnlySpan<char> name) =>
        s_byName.GetAlternateLookup<ReadOnlySpan<char>>().TryGetValue(name, out var f) ? f : null;

    // Get the intrinsic function with the given FunctionId.
    public static RuntimeFunction FunctionForId(FunctionId id) => s_intrinsicFunctions[(int)id];

    public static ReadOnlySpan<RuntimeFunction> AllFunctions => s_intrinsicFunctions;
}
