// <auto-generated> from BUILTIN_LIST in src/builtins/builtins-definitions.h by gen_builtins.py
// and the .tq files named in BUILD.gn torque_files (BUILTIN_LIST_FROM_TORQUE, non-generic
// builtins in file order). Build configuration: no i18n, no Temporal, no Wasm, no TSAN;
// the bytecode-handler builtins are not included.
#nullable enable
namespace V8Sharp.Builtins;

/// <summary>V8's Builtin ids, in V8's order. <see cref="NoBuiltinId"/> is V8's kNoBuiltinId.</summary>
public enum Builtin
{
    NoBuiltinId = -1,
    DeoptimizationEntry_Eager,  // ASM
    DeoptimizationEntry_Lazy,  // ASM
    DeoptimizationEntry_LazyAfterFastCall,  // ASM
    RecordWriteSaveFP,  // TFC
    RecordWriteIgnoreFP,  // TFC
    EphemeronKeyBarrierSaveFP,  // TFC
    EphemeronKeyBarrierIgnoreFP,  // TFC
    IndirectPointerBarrierSaveFP,  // TFC
    IndirectPointerBarrierIgnoreFP,  // TFC
    AdaptorWithBuiltinExitFrame0,  // TFC
    AdaptorWithBuiltinExitFrame1,  // TFC
    AdaptorWithBuiltinExitFrame2,  // TFC
    AdaptorWithBuiltinExitFrame3,  // TFC
    AdaptorWithBuiltinExitFrame4,  // TFC
    AdaptorWithBuiltinExitFrame5,  // TFC
    CallFunction_ReceiverIsNullOrUndefined,  // ASM
    CallFunction_ReceiverIsNotNullOrUndefined,  // ASM
    CallFunction_ReceiverIsAny,  // ASM
    CallBoundFunction,  // ASM
    CallWrappedFunction,  // TFC
    Call_ReceiverIsNullOrUndefined,  // ASM
    Call_ReceiverIsNotNullOrUndefined,  // ASM
    Call_ReceiverIsAny,  // ASM
    Call_ReceiverIsNullOrUndefined_Baseline_Compact,  // TFC
    Call_ReceiverIsNullOrUndefined_Baseline,  // TFC
    Call_ReceiverIsNotNullOrUndefined_Baseline_Compact,  // TFC
    Call_ReceiverIsNotNullOrUndefined_Baseline,  // TFC
    Call_ReceiverIsAny_Baseline_Compact,  // TFC
    Call_ReceiverIsAny_Baseline,  // TFC
    Call_ReceiverIsNullOrUndefined_WithFeedback,  // TFC
    Call_ReceiverIsNotNullOrUndefined_WithFeedback,  // TFC
    Call_ReceiverIsAny_WithFeedback,  // TFC
    CallProxy,  // TFC
    CallVarargs,  // ASM
    CallWithSpread,  // TFC
    CallWithSpread_Baseline,  // TFC
    CallWithSpread_WithFeedback,  // TFC
    CallWithArrayLike,  // TFC
    CallWithArrayLike_WithFeedback,  // TFC
    CallForwardVarargs,  // ASM
    CallFunctionForwardVarargs,  // ASM
    CallFunctionTemplate_Generic,  // TFC
    CallFunctionTemplate_CheckAccess,  // TFC
    CallFunctionTemplate_CheckCompatibleReceiver,  // TFC
    CallFunctionTemplate_CheckAccessAndCompatibleReceiver,  // TFC
    ConstructFunction,  // ASM
    ConstructBoundFunction,  // ASM
    ConstructedNonConstructable,  // ASM
    Construct,  // ASM
    ConstructVarargs,  // ASM
    ConstructWithSpread,  // TFC
    ConstructWithSpread_Baseline,  // TFC
    ConstructWithSpread_WithFeedback,  // TFC
    ConstructWithArrayLike,  // TFC
    ConstructForwardVarargs,  // ASM
    ConstructForwardAllArgs,  // ASM
    ConstructForwardAllArgs_Baseline,  // TFC
    ConstructForwardAllArgs_WithFeedback,  // TFC
    ConstructFunctionForwardVarargs,  // ASM
    Construct_Baseline,  // TFC
    Construct_WithFeedback,  // TFC
    JSConstructStubGeneric,  // ASM
    JSBuiltinsConstructStub,  // ASM
    FastNewObject,  // TFC
    FastNewClosure,  // TFS
    ConstructProxy,  // TFC
    JSEntry,  // ASM
    JSConstructEntry,  // ASM
    JSRunMicrotasksEntry,  // ASM
    JSEntryTrampoline,  // ASM
    JSConstructEntryTrampoline,  // ASM
    ResumeGeneratorTrampoline,  // ASM
    ResumeGeneratorTrampoline_WithCatch,  // TFC
    StringFromCodePointAt,  // TFC
    StringEqual,  // TFC
    StringGreaterThan,  // TFC
    StringGreaterThanOrEqual,  // TFC
    StringLessThan,  // TFC
    StringLessThanOrEqual,  // TFC
    StringCompare,  // TFC
    StringSubstring,  // TFC
    OrderedHashTableHealIndex,  // TFS
    InterpreterEntryTrampoline,  // ASM
    InterpreterEntryTrampolineForProfiling,  // ASM
    InterpreterForwardAllArgsThenConstruct,  // ASM
    InterpreterPushArgsThenCall,  // ASM
    InterpreterPushUndefinedAndArgsThenCall,  // ASM
    InterpreterPushArgsThenCallWithFinalSpread,  // ASM
    InterpreterPushArgsThenConstruct,  // ASM
    InterpreterPushArgsThenFastConstructFunction,  // ASM
    InterpreterPushArgsThenConstructArrayFunction,  // ASM
    InterpreterPushArgsThenConstructWithFinalSpread,  // ASM
    InterpreterEnterAtBytecode,  // ASM
    InterpreterEnterAtNextBytecode,  // ASM
    InterpreterOnStackReplacement,  // ASM
    BaselineOutOfLinePrologue,  // ASM
    BaselineOutOfLinePrologueDeopt,  // ASM
    BaselineOnStackReplacement,  // ASM
    BaselineLeaveFrame,  // ASM
    InterpreterOnStackReplacement_ToBaseline,  // ASM
    MaglevFunctionEntryStackCheck_WithoutNewTarget,  // ASM
    MaglevFunctionEntryStackCheck_WithNewTarget,  // ASM
    MaglevOptimizeCodeOrTailCallOptimizedCodeSlot,  // ASM
    CompileLazy,  // TFC
    NotifyDeoptimized,  // ASM
    StartMaglevOptimizeJob,  // TFC
    OptimizeMaglevEager,  // TFC
    StartTurbofanOptimizeJob,  // TFC
    OptimizeTurbofanEager,  // TFC
    FunctionLogNextExecution,  // TFC
    MarkReoptimizeLazyDeoptimized,  // TFC
    MarkLazyDeoptimized,  // TFC
    MarkFlushed,  // TFC
    ContinueToCodeStubBuiltin,  // ASM
    ContinueToCodeStubBuiltinWithResult,  // ASM
    ContinueToJavaScriptBuiltin,  // ASM
    ContinueToJavaScriptBuiltinWithResult,  // ASM
    CallApiCallbackGeneric,  // ASM
    CallApiCallbackOptimizedNoProfiling,  // ASM
    CallApiCallbackOptimized,  // ASM
    CallApiGetter,  // ASM
    CallNamedInterceptorGetter,  // ASM
    CallNamedInterceptorSetter,  // ASM
    HandleApiCallOrConstruct,  // TFC
    HandleApiConstruct,  // CPP
    HandleApiCallAsFunctionDelegate,  // CPP
    HandleApiCallAsConstructorDelegate,  // CPP
    AllocateInYoungGeneration,  // TFC
    AllocateInOldGeneration,  // TFC
    NewHeapNumber,  // TFC
    CopyFastSmiOrObjectElements,  // TFS
    GrowFastDoubleElements,  // TFC
    GrowFastSmiOrObjectElements,  // TFC
    DebugBreakTrampoline,  // TFJ
    RestartFrameTrampoline,  // ASM
    ToNumber,  // TFC
    ToBigInt,  // TFC
    ToNumber_Baseline,  // TFC
    ToNumeric_Baseline,  // TFC
    PlainPrimitiveToNumber,  // TFC
    ToNumberConvertBigInt,  // TFC
    ToBigIntConvertNumber,  // TFC
    Typeof,  // TFC
    Typeof_Baseline,  // TFC
    BigIntToI64,  // TFC
    BigIntToI32Pair,  // TFC
    I64ToBigInt,  // TFC
    I32PairToBigInt,  // TFC
    ToBooleanLazyDeoptContinuation,  // TFC
    MathCeilContinuation,  // TFC
    MathFloorContinuation,  // TFC
    MathRoundContinuation,  // TFC
    MathClz32Continuation,  // TFC
    KeyedLoadIC_PolymorphicName,  // TFH
    KeyedStoreIC_Megamorphic,  // TFH
    DefineKeyedOwnIC_Megamorphic,  // TFH
    LoadGlobalIC_NoFeedback,  // TFH
    LoadIC_FunctionPrototype,  // TFH
    LoadIC_StringLength,  // TFH
    LoadIC_StringWrapperLength,  // TFH
    LoadIC_NoFeedback,  // TFH
    StoreGlobalIC_Slow,  // TFH
    StoreIC_NoFeedback,  // TFH
    DefineNamedOwnIC_NoFeedback,  // TFH
    KeyedLoadIC_SloppyArguments,  // TFH
    LoadIndexedInterceptorIC,  // TFH
    KeyedStoreIC_SloppyArguments_InBounds,  // TFH
    KeyedStoreIC_SloppyArguments_NoTransitionGrowAndHandleCOW,  // TFH
    KeyedStoreIC_SloppyArguments_NoTransitionIgnoreTypedArrayOOB,  // TFH
    KeyedStoreIC_SloppyArguments_NoTransitionHandleCOW,  // TFH
    StoreFastElementIC_InBounds,  // TFH
    StoreFastElementIC_NoTransitionGrowAndHandleCOW,  // TFH
    StoreFastElementIC_NoTransitionIgnoreTypedArrayOOB,  // TFH
    StoreFastElementIC_NoTransitionHandleCOW,  // TFH
    ElementsTransitionAndStore_InBounds,  // TFH
    ElementsTransitionAndStore_NoTransitionGrowAndHandleCOW,  // TFH
    ElementsTransitionAndStore_NoTransitionIgnoreTypedArrayOOB,  // TFH
    ElementsTransitionAndStore_NoTransitionHandleCOW,  // TFH
    KeyedHasIC_PolymorphicName,  // TFH
    KeyedHasIC_SloppyArguments,  // TFH
    HasIndexedInterceptorIC,  // TFH
    EnqueueMicrotask,  // TFS
    GlobalQueueMicrotask,  // TFJ
    RunMicrotasksTrampoline,  // ASM
    RunMicrotasks,  // TFC
    HasProperty,  // TFS
    DeleteProperty,  // TFS
    CopyDataProperties,  // TFS
    SetDataProperties,  // TFS
    ProxyGetPropertyFastPath,  // TFS
    CopyDataPropertiesWithExcludedPropertiesOnStack,  // TFC
    CopyDataPropertiesWithExcludedProperties,  // TFC
    Abort,  // TFC
    AbortCSADcheck,  // TFC
    EmptyFunction,  // CPP
    EmptyFunction1,  // CPP
    Illegal,  // CPP
    IllegalInvocationThrower,  // CPP
    StrictPoisonPillThrower,  // CPP
    UnsupportedThrower,  // CPP
    ReturnReceiver,  // TFJ
    AbstractModuleSourceToStringTag,  // CPP
    ArrayConstructor,  // TFC
    ArrayConstructorImpl,  // TFC
    ArrayNoArgumentConstructor_PackedSmi_DontOverride,  // TFC
    ArrayNoArgumentConstructor_HoleySmi_DontOverride,  // TFC
    ArrayNoArgumentConstructor_PackedSmi_DisableAllocationSites,  // TFC
    ArrayNoArgumentConstructor_HoleySmi_DisableAllocationSites,  // TFC
    ArrayNoArgumentConstructor_Packed_DisableAllocationSites,  // TFC
    ArrayNoArgumentConstructor_Holey_DisableAllocationSites,  // TFC
    ArrayNoArgumentConstructor_PackedDouble_DisableAllocationSites,  // TFC
    ArrayNoArgumentConstructor_HoleyDouble_DisableAllocationSites,  // TFC
    ArraySingleArgumentConstructor_PackedSmi_DontOverride,  // TFC
    ArraySingleArgumentConstructor_HoleySmi_DontOverride,  // TFC
    ArraySingleArgumentConstructor_PackedSmi_DisableAllocationSites,  // TFC
    ArraySingleArgumentConstructor_HoleySmi_DisableAllocationSites,  // TFC
    ArraySingleArgumentConstructor_Packed_DisableAllocationSites,  // TFC
    ArraySingleArgumentConstructor_Holey_DisableAllocationSites,  // TFC
    ArraySingleArgumentConstructor_PackedDouble_DisableAllocationSites,  // TFC
    ArraySingleArgumentConstructor_HoleyDouble_DisableAllocationSites,  // TFC
    ArrayNArgumentsConstructor,  // TFC
    ArrayConcat,  // CPP
    ArrayPrototypeFill,  // CPP
    ArrayIncludesSmi,  // TFS
    ArrayIncludesSmiOrObject,  // TFS
    ArrayIncludesPackedDoubles,  // TFS
    ArrayIncludesHoleyDoubles,  // TFS
    ArrayIncludes,  // TFJ
    ArrayIndexOfSmi,  // TFS
    ArrayIndexOfSmiOrObject,  // TFS
    ArrayIndexOfPackedDoubles,  // TFS
    ArrayIndexOfHoleyDoubles,  // TFS
    ArrayIndexOf,  // TFJ
    ArrayPop,  // CPP
    ArrayPrototypePop,  // TFJ
    ArrayPush,  // CPP
    ArrayPrototypePush,  // TFJ
    ArrayShift,  // CPP
    ArrayUnshift,  // CPP
    CloneFastJSArray,  // TFS
    CloneFastJSArrayFillingHoles,  // TFS
    ExtractFastJSArray,  // TFS
    CreateArrayFromSlowBoilerplate,  // TFS
    CreateObjectFromSlowBoilerplate,  // TFS
    CreateArrayFromSlowBoilerplateHelper,  // TFC
    CreateObjectFromSlowBoilerplateHelper,  // TFC
    ArrayPrototypeEntries,  // TFJ
    ArrayPrototypeKeys,  // TFJ
    ArrayPrototypeValues,  // TFJ
    ArrayIteratorPrototypeNext,  // TFJ
    ArrayBufferConstructor,  // CPP
    ArrayBufferConstructor_DoNotInitialize,  // CPP
    ArrayBufferPrototypeSlice,  // CPP
    ArrayBufferPrototypeResize,  // CPP
    ArrayBufferPrototypeTransfer,  // CPP
    ArrayBufferPrototypeTransferToFixedLength,  // CPP
    ArrayBufferPrototypeTransferToImmutable,  // CPP
    ArrayBufferPrototypeSliceToImmutable,  // CPP
    AsyncFunctionEnter,  // TFS
    AsyncFunctionReject,  // TFS
    AsyncFunctionResolve,  // TFS
    AsyncFunctionLazyDeoptContinuation,  // TFC
    AsyncFunctionAwait,  // TFS
    AsyncFunctionAwaitRejectClosure,  // TFJ
    AsyncFunctionAwaitResolveClosure,  // TFJ
    BigIntConstructor,  // CPP
    BigIntAsUintN,  // CPP
    BigIntAsIntN,  // CPP
    BigIntPrototypeToLocaleString,  // CPP
    BigIntPrototypeToString,  // CPP
    BigIntPrototypeValueOf,  // CPP
    CallSitePrototypeGetColumnNumber,  // CPP
    CallSitePrototypeGetEnclosingColumnNumber,  // CPP
    CallSitePrototypeGetEnclosingLineNumber,  // CPP
    CallSitePrototypeGetEvalOrigin,  // CPP
    CallSitePrototypeGetFileName,  // CPP
    CallSitePrototypeGetFunction,  // CPP
    CallSitePrototypeGetFunctionName,  // CPP
    CallSitePrototypeGetLineNumber,  // CPP
    CallSitePrototypeGetMethodName,  // CPP
    CallSitePrototypeGetPosition,  // CPP
    CallSitePrototypeGetPromiseIndex,  // CPP
    CallSitePrototypeGetScriptHash,  // CPP
    CallSitePrototypeGetScriptNameOrSourceURL,  // CPP
    CallSitePrototypeGetThis,  // CPP
    CallSitePrototypeGetTypeName,  // CPP
    CallSitePrototypeIsAsync,  // CPP
    CallSitePrototypeIsConstructor,  // CPP
    CallSitePrototypeIsEval,  // CPP
    CallSitePrototypeIsNative,  // CPP
    CallSitePrototypeIsPromiseAll,  // CPP
    CallSitePrototypeIsToplevel,  // CPP
    CallSitePrototypeToString,  // CPP
    ConsoleDebug,  // CPP
    ConsoleError,  // CPP
    ConsoleInfo,  // CPP
    ConsoleLog,  // CPP
    ConsoleWarn,  // CPP
    ConsoleDir,  // CPP
    ConsoleDirXml,  // CPP
    ConsoleTable,  // CPP
    ConsoleTrace,  // CPP
    ConsoleGroup,  // CPP
    ConsoleGroupCollapsed,  // CPP
    ConsoleGroupEnd,  // CPP
    ConsoleClear,  // CPP
    ConsoleCount,  // CPP
    ConsoleCountReset,  // CPP
    ConsoleAssert,  // CPP
    ConsoleProfile,  // CPP
    ConsoleProfileEnd,  // CPP
    ConsoleTime,  // CPP
    ConsoleTimeLog,  // CPP
    ConsoleTimeEnd,  // CPP
    ConsoleTimeStamp,  // CPP
    ConsoleContext,  // CPP
    DataViewConstructor,  // CPP
    DateConstructor,  // CPP
    DatePrototypeGetDate,  // TFJ
    DatePrototypeGetDay,  // TFJ
    DatePrototypeGetFullYear,  // TFJ
    DatePrototypeGetHours,  // TFJ
    DatePrototypeGetMilliseconds,  // TFJ
    DatePrototypeGetMinutes,  // TFJ
    DatePrototypeGetMonth,  // TFJ
    DatePrototypeGetSeconds,  // TFJ
    DatePrototypeGetTime,  // TFJ
    DatePrototypeGetTimezoneOffset,  // TFJ
    DatePrototypeGetUTCDate,  // TFJ
    DatePrototypeGetUTCDay,  // TFJ
    DatePrototypeGetUTCFullYear,  // TFJ
    DatePrototypeGetUTCHours,  // TFJ
    DatePrototypeGetUTCMilliseconds,  // TFJ
    DatePrototypeGetUTCMinutes,  // TFJ
    DatePrototypeGetUTCMonth,  // TFJ
    DatePrototypeGetUTCSeconds,  // TFJ
    DatePrototypeValueOf,  // TFJ
    DatePrototypeToPrimitive,  // TFJ
    DatePrototypeGetYear,  // CPP
    DatePrototypeSetYear,  // CPP
    DateNow,  // CPP
    DateParse,  // CPP
    DatePrototypeSetDate,  // CPP
    DatePrototypeSetFullYear,  // CPP
    DatePrototypeSetHours,  // CPP
    DatePrototypeSetMilliseconds,  // CPP
    DatePrototypeSetMinutes,  // CPP
    DatePrototypeSetMonth,  // CPP
    DatePrototypeSetSeconds,  // CPP
    DatePrototypeSetTime,  // CPP
    DatePrototypeSetUTCDate,  // CPP
    DatePrototypeSetUTCFullYear,  // CPP
    DatePrototypeSetUTCHours,  // CPP
    DatePrototypeSetUTCMilliseconds,  // CPP
    DatePrototypeSetUTCMinutes,  // CPP
    DatePrototypeSetUTCMonth,  // CPP
    DatePrototypeSetUTCSeconds,  // CPP
    DatePrototypeToDateString,  // CPP
    DatePrototypeToISOString,  // CPP
    DatePrototypeToUTCString,  // CPP
    DatePrototypeToString,  // CPP
    DatePrototypeToTimeString,  // CPP
    DatePrototypeToJson,  // CPP
    DateUTC,  // CPP
    DisposableStackConstructor,  // CPP
    DisposableStackPrototypeUse,  // CPP
    DisposableStackPrototypeDispose,  // CPP
    DisposableStackPrototypeGetDisposed,  // CPP
    DisposableStackPrototypeAdopt,  // CPP
    DisposableStackPrototypeDefer,  // CPP
    DisposableStackPrototypeMove,  // CPP
    AsyncDisposableStackOnFulfilled,  // CPP
    AsyncDisposableStackOnRejected,  // CPP
    AsyncDisposeFromSyncDispose,  // CPP
    AsyncDisposableStackConstructor,  // CPP
    AsyncDisposableStackPrototypeUse,  // CPP
    AsyncDisposableStackPrototypeDisposeAsync,  // CPP
    AsyncDisposableStackPrototypeGetDisposed,  // CPP
    AsyncDisposableStackPrototypeAdopt,  // CPP
    AsyncDisposableStackPrototypeDefer,  // CPP
    AsyncDisposableStackPrototypeMove,  // CPP
    ErrorConstructor,  // CPP
    ErrorCaptureStackTrace,  // CPP
    ErrorPrototypeToString,  // CPP
    ErrorIsError,  // CPP
    FunctionConstructor,  // CPP
    FunctionPrototypeApply,  // ASM
    FunctionPrototypeBind,  // CPP
    FunctionPrototypeCall,  // ASM
    FunctionPrototypeToString,  // CPP
    FunctionPrototypeLegacyArgumentsGetter,  // CPP
    FunctionPrototypeLegacyArgumentsSetter,  // CPP
    FunctionPrototypeLegacyCallerGetter,  // CPP
    FunctionPrototypeLegacyCallerSetter,  // CPP
    CreateIterResultObject,  // TFS
    CreateGeneratorObject,  // TFS
    GeneratorFunctionConstructor,  // CPP
    GeneratorPrototypeNext,  // TFJ
    GeneratorPrototypeReturn,  // TFJ
    GeneratorPrototypeThrow,  // TFJ
    AsyncFunctionConstructor,  // CPP
    SuspendGeneratorBaseline,  // TFC
    ResumeGeneratorBaseline,  // TFC
    GetIteratorWithFeedbackLazyDeoptContinuation,  // TFC
    CallIteratorWithFeedbackLazyDeoptContinuation,  // TFC
    ForOfNextResultDeoptContinuation,  // TFC
    ForOfNextLoadDoneLazyDeoptContinuation,  // TFC
    ForOfNextLoadValueEagerDeoptContinuation,  // TFC
    ForOfNextLoadValueLazyDeoptContinuation,  // TFC
    GlobalDecodeURI,  // CPP
    GlobalDecodeURIComponent,  // CPP
    GlobalEncodeURI,  // CPP
    GlobalEncodeURIComponent,  // CPP
    GlobalEscape,  // CPP
    GlobalUnescape,  // CPP
    GlobalEval,  // CPP
    GlobalIsFinite,  // TFJ
    GlobalIsNaN,  // TFJ
    JsonParse,  // CPP
    JsonStringify,  // CPP
    JsonRawJson,  // CPP
    JsonIsRawJson,  // CPP
    LoadIC,  // TFH
    LoadIC_Megamorphic,  // TFH
    LoadIC_Noninlined,  // TFH
    LoadICTrampoline,  // TFH
    LoadICUninitializedBaseline,  // TFH
    LoadICInObjectNonDoubleFieldBaseline,  // TFH
    LoadICInObjectNonDoubleField0Baseline,  // TFH
    LoadICInObjectNonDoubleField1Baseline,  // TFH
    LoadICInObjectNonDoubleField2Baseline,  // TFH
    LoadICInObjectNonDoubleField3Baseline,  // TFH
    LoadICInObjectNonDoubleField4Baseline,  // TFH
    LoadICInObjectNonDoubleField5Baseline,  // TFH
    LoadICInObjectNonDoubleField6Baseline,  // TFH
    LoadICInObjectNonDoubleField7Baseline,  // TFH
    LoadICOutOfObjectNonDoubleFieldBaseline,  // TFH
    LoadICOutOfObjectNonDoubleField0Baseline,  // TFH
    LoadICOutOfObjectNonDoubleField1Baseline,  // TFH
    LoadICOutOfObjectNonDoubleField2Baseline,  // TFH
    LoadICOutOfObjectNonDoubleField3Baseline,  // TFH
    LoadICDoubleFieldBaseline,  // TFH
    LoadICConstantFromPrototypeBaseline,  // TFH
    LoadICConstantFromStringPrototypeBaseline,  // TFH
    LoadICStringLengthBaseline,  // TFH
    LoadICGenericBaseline,  // TFH
    LoadICTrampoline_Megamorphic,  // TFH
    LoadSuperIC,  // TFH
    LoadSuperICBaseline,  // TFH
    KeyedLoadIC,  // TFH
    EnumeratedKeyedLoadIC,  // TFH
    KeyedLoadIC_Megamorphic,  // TFH
    KeyedLoadICTrampoline,  // TFH
    KeyedLoadICBaseline,  // TFH
    EnumeratedKeyedLoadICBaseline,  // TFH
    KeyedLoadICTrampoline_Megamorphic,  // TFH
    StoreGlobalIC,  // TFH
    StoreGlobalICTrampoline,  // TFH
    StoreGlobalICBaseline,  // TFH
    StoreIC,  // TFH
    StoreIC_Megamorphic,  // TFH
    StoreICTrampoline,  // TFH
    StoreICTrampoline_Megamorphic,  // TFH
    StoreICBaseline,  // TFH
    DefineNamedOwnIC,  // TFH
    DefineNamedOwnICTrampoline,  // TFH
    DefineNamedOwnICBaseline,  // TFH
    KeyedStoreIC,  // TFH
    KeyedStoreICTrampoline,  // TFH
    KeyedStoreICTrampoline_Megamorphic,  // TFH
    KeyedStoreICBaseline,  // TFH
    DefineKeyedOwnIC,  // TFH
    DefineKeyedOwnICTrampoline,  // TFH
    DefineKeyedOwnICBaseline,  // TFH
    StoreInArrayLiteralIC,  // TFH
    StoreInArrayLiteralICBaseline,  // TFH
    LookupContextNoCellTrampoline,  // TFH
    LookupContextTrampoline,  // TFH
    LookupContextNoCellBaseline,  // TFH
    LookupScriptContextBaseline,  // TFH
    LookupContextNoCellInsideTypeofTrampoline,  // TFH
    LookupContextInsideTypeofTrampoline,  // TFH
    LookupContextNoCellInsideTypeofBaseline,  // TFH
    LookupContextInsideTypeofBaseline,  // TFH
    LoadGlobalIC,  // TFH
    LoadGlobalICInsideTypeof,  // TFH
    LoadGlobalICTrampoline,  // TFH
    LoadGlobalICBaseline,  // TFH
    LoadGlobalICInsideTypeofTrampoline,  // TFH
    LoadGlobalICInsideTypeofBaseline,  // TFH
    LookupGlobalIC,  // TFH
    LookupGlobalICTrampoline,  // TFH
    LookupGlobalICBaseline,  // TFH
    LookupGlobalICInsideTypeof,  // TFH
    LookupGlobalICInsideTypeofTrampoline,  // TFH
    LookupGlobalICInsideTypeofBaseline,  // TFH
    CloneObjectIC,  // TFH
    CloneObjectICBaseline,  // TFH
    CloneObjectIC_Slow,  // TFH
    KeyedHasIC,  // TFH
    KeyedHasICBaseline,  // TFH
    KeyedHasIC_Megamorphic,  // TFH
    AddLhsIsStringConstantInternalizeWithVector,  // TFH
    AddLhsIsStringConstantInternalizeTrampoline,  // TFH
    AddRhsIsStringConstantInternalizeWithVector,  // TFH
    AddRhsIsStringConstantInternalizeTrampoline,  // TFH
    IterableToList,  // TFS
    IterableToFixedArray,  // TFS
    IterableToListWithSymbolLookup,  // TFS
    IterableToFixedArrayWithSymbolLookupSlow,  // TFS
    IterableToListMayPreserveHoles,  // TFS
    IterableToListConvertHoles,  // TFS
    StringListFromIterable,  // TFS
    FindOrderedHashMapEntry,  // TFS
    MapConstructor,  // TFJ
    MapPrototypeSet,  // TFJ
    MapPrototypeDelete,  // TFJ
    MapPrototypeGet,  // TFJ
    MapPrototypeHas,  // TFJ
    MapPrototypeClear,  // CPP
    MapPrototypeGetOrInsert,  // TFJ
    MapPrototypeGetOrInsertComputed,  // TFJ
    MapPrototypeEntries,  // TFJ
    MapPrototypeGetSize,  // TFJ
    MapPrototypeForEach,  // TFJ
    MapPrototypeKeys,  // TFJ
    MapPrototypeValues,  // TFJ
    MapIteratorPrototypeNext,  // TFJ
    MapIteratorToList,  // TFS
    NumberPrototypeToExponential,  // CPP
    NumberPrototypeToFixed,  // CPP
    NumberPrototypeToLocaleString,  // CPP
    NumberPrototypeToPrecision,  // CPP
    MathSumPrecise,  // CPP
    SameValue,  // TFC
    SameValueNumbersOnly,  // TFC
    Add_Generic_Baseline,  // TFC
    Subtract_Generic_Baseline,  // TFC
    Multiply_Generic_Baseline,  // TFC
    Divide_Generic_Baseline,  // TFC
    Modulus_Generic_Baseline,  // TFC
    Exponentiate_Generic_Baseline,  // TFC
    BitwiseAnd_Generic_Baseline,  // TFC
    BitwiseOr_Generic_Baseline,  // TFC
    BitwiseXor_Generic_Baseline,  // TFC
    ShiftLeft_Generic_Baseline,  // TFC
    ShiftRight_Generic_Baseline,  // TFC
    ShiftRightLogical_Generic_Baseline,  // TFC
    AddSmi_Generic_Baseline,  // TFC
    SubtractSmi_Generic_Baseline,  // TFC
    MultiplySmi_Generic_Baseline,  // TFC
    DivideSmi_Generic_Baseline,  // TFC
    ModulusSmi_Generic_Baseline,  // TFC
    ExponentiateSmi_Generic_Baseline,  // TFC
    BitwiseAndSmi_Generic_Baseline,  // TFC
    BitwiseOrSmi_Generic_Baseline,  // TFC
    BitwiseXorSmi_Generic_Baseline,  // TFC
    ShiftLeftSmi_Generic_Baseline,  // TFC
    ShiftRightSmi_Generic_Baseline,  // TFC
    ShiftRightLogicalSmi_Generic_Baseline,  // TFC
    Add_WithFeedback,  // TFC
    Subtract_WithFeedback,  // TFC
    Multiply_WithFeedback,  // TFC
    Divide_WithFeedback,  // TFC
    Modulus_WithFeedback,  // TFC
    Exponentiate_WithFeedback,  // TFC
    BitwiseAnd_WithFeedback,  // TFC
    BitwiseOr_WithFeedback,  // TFC
    BitwiseXor_WithFeedback,  // TFC
    ShiftLeft_WithFeedback,  // TFC
    ShiftRight_WithFeedback,  // TFC
    ShiftRightLogical_WithFeedback,  // TFC
    Add_LhsIsStringConstant_Internalize_WithFeedback,  // TFC
    Add_LhsIsStringConstant_Internalize_Baseline,  // TFC
    Add_RhsIsStringConstant_Internalize_WithFeedback,  // TFC
    Add_RhsIsStringConstant_Internalize_Baseline,  // TFC
    Equal_Generic_Baseline,  // TFC
    StrictEqual_Generic_Baseline,  // TFC
    LessThan_Generic_Baseline,  // TFC
    GreaterThan_Generic_Baseline,  // TFC
    LessThanOrEqual_Generic_Baseline,  // TFC
    GreaterThanOrEqual_Generic_Baseline,  // TFC
    Equal_WithEmbeddedFeedback,  // TFC
    StrictEqual_WithEmbeddedFeedback,  // TFC
    LessThan_WithEmbeddedFeedback,  // TFC
    GreaterThan_WithEmbeddedFeedback,  // TFC
    LessThanOrEqual_WithEmbeddedFeedback,  // TFC
    GreaterThanOrEqual_WithEmbeddedFeedback,  // TFC
    BitwiseNot_Generic_Baseline,  // TFC
    Decrement_Generic_Baseline,  // TFC
    Increment_Generic_Baseline,  // TFC
    Negate_Generic_Baseline,  // TFC
    BitwiseNot_WithFeedback,  // TFC
    Decrement_WithFeedback,  // TFC
    Increment_WithFeedback,  // TFC
    Negate_WithFeedback,  // TFC
    ObjectAssign,  // TFJ
    ObjectCreate,  // TFJ
    ObjectDefineGetter,  // CPP
    ObjectDefineProperties,  // CPP
    ObjectDefineProperty,  // CPP
    ObjectDefineSetter,  // CPP
    ObjectEntries,  // TFJ
    ObjectFreeze,  // CPP
    ObjectGetOwnPropertyDescriptor,  // TFJ
    ObjectGetOwnPropertyDescriptors,  // CPP
    ObjectGetOwnPropertyNames,  // TFJ
    ObjectGetOwnPropertySymbols,  // CPP
    ObjectHasOwn,  // TFJ
    ObjectIs,  // TFJ
    ObjectIsFrozen,  // CPP
    ObjectIsSealed,  // CPP
    ObjectKeys,  // TFJ
    ObjectLookupGetter,  // CPP
    ObjectLookupSetter,  // CPP
    ObjectPrototypeHasOwnProperty,  // TFJ
    ObjectPrototypeIsPrototypeOf,  // TFJ
    ObjectPrototypePropertyIsEnumerable,  // CPP
    ObjectPrototypeGetProto,  // CPP
    ObjectPrototypeSetProto,  // CPP
    ObjectSeal,  // CPP
    ObjectToString,  // TFS
    ObjectValues,  // TFJ
    OrdinaryHasInstance,  // TFC
    InstanceOf,  // TFC
    InstanceOf_WithFeedback,  // TFC
    InstanceOf_Baseline,  // TFC
    ForInEnumerate,  // TFS
    ForInPrepare,  // TFC
    ForInFilter,  // TFS
    ReflectApply,  // ASM
    ReflectConstruct,  // ASM
    ReflectDefineProperty,  // CPP
    ReflectOwnKeys,  // CPP
    ReflectSet,  // CPP
    RegExpCapture1Getter,  // CPP
    RegExpCapture2Getter,  // CPP
    RegExpCapture3Getter,  // CPP
    RegExpCapture4Getter,  // CPP
    RegExpCapture5Getter,  // CPP
    RegExpCapture6Getter,  // CPP
    RegExpCapture7Getter,  // CPP
    RegExpCapture8Getter,  // CPP
    RegExpCapture9Getter,  // CPP
    RegExpConstructor,  // TFJ
    RegExpInputGetter,  // CPP
    RegExpInputSetter,  // CPP
    RegExpLastMatchGetter,  // CPP
    RegExpLastParenGetter,  // CPP
    RegExpLeftContextGetter,  // CPP
    RegExpPrototypeCompile,  // TFJ
    RegExpPrototypeToString,  // CPP
    RegExpRightContextGetter,  // CPP
    RegExpEscape,  // CPP
    RegExpExecAtom,  // TFS
    RegExpInterpreterTrampoline,  // ASM
    RegExpExperimentalTrampoline,  // ASM
    FindOrderedHashSetEntry,  // TFS
    SetConstructor,  // TFJ
    SetPrototypeHas,  // TFJ
    SetPrototypeAdd,  // TFJ
    SetPrototypeDelete,  // TFJ
    SetPrototypeClear,  // CPP
    SetPrototypeEntries,  // TFJ
    SetPrototypeGetSize,  // TFJ
    SetPrototypeForEach,  // TFJ
    SetPrototypeValues,  // TFJ
    SetIteratorPrototypeNext,  // TFJ
    SetOrSetIteratorToList,  // TFS
    ShadowRealmConstructor,  // CPP
    ShadowRealmGetWrappedValue,  // TFS
    ShadowRealmPrototypeEvaluate,  // CPP
    ShadowRealmPrototypeImportValue,  // TFJ
    ShadowRealmImportValueFulfilled,  // TFJ
    ShadowRealmImportValueRejected,  // TFJ
    SharedArrayBufferPrototypeGetByteLength,  // CPP
    SharedArrayBufferPrototypeSlice,  // CPP
    SharedArrayBufferPrototypeGrow,  // CPP
    AtomicsLoad,  // TFJ
    AtomicsStore,  // TFJ
    AtomicsExchange,  // TFJ
    AtomicsCompareExchange,  // TFJ
    AtomicsAdd,  // TFJ
    AtomicsSub,  // TFJ
    AtomicsAnd,  // TFJ
    AtomicsOr,  // TFJ
    AtomicsXor,  // TFJ
    AtomicsNotify,  // CPP
    AtomicsIsLockFree,  // CPP
    AtomicsWait,  // CPP
    AtomicsWaitAsync,  // CPP
    AtomicsPause,  // CPP
    StringFromCodePoint,  // CPP
    StringFromCharCode,  // TFJ
    StringPrototypeLastIndexOf,  // CPP
    StringPrototypeMatchAll,  // TFJ
    StringPrototypeReplace,  // TFJ
    StringPrototypeSplit,  // TFJ
    StringRaw,  // CPP
    SymbolConstructor,  // CPP
    SymbolFor,  // CPP
    SymbolKeyFor,  // CPP
    TypedArrayBaseConstructor,  // TFJ
    TypedArrayConstructor,  // TFJ
    TypedArrayPrototypeBuffer,  // CPP
    TypedArrayPrototypeByteLength,  // TFJ
    TypedArrayPrototypeByteOffset,  // TFJ
    TypedArrayPrototypeLength,  // TFJ
    TypedArrayPrototypeCopyWithin,  // CPP
    TypedArrayPrototypeFill,  // CPP
    TypedArrayPrototypeIncludes,  // CPP
    TypedArrayPrototypeIndexOf,  // CPP
    TypedArrayPrototypeLastIndexOf,  // CPP
    TypedArrayPrototypeReverse,  // CPP
    TypedArrayPrototypeToStringTag,  // TFJ
    TypedArrayPrototypeMap,  // TFJ
    Uint8ArrayFromBase64,  // CPP
    Uint8ArrayPrototypeSetFromBase64,  // CPP
    Uint8ArrayFromHex,  // CPP
    Uint8ArrayPrototypeSetFromHex,  // CPP
    Uint8ArrayPrototypeToBase64,  // CPP
    Uint8ArrayPrototypeToHex,  // CPP
    WeakMapConstructor,  // TFJ
    WeakMapLookupHashIndex,  // TFS
    WeakMapPrototypeGet,  // TFJ
    WeakMapPrototypeHas,  // TFJ
    WeakMapPrototypeSet,  // TFJ
    WeakMapPrototypeGetOrInsert,  // TFJ
    WeakMapPrototypeGetOrInsertComputed,  // TFJ
    WeakMapPrototypeDelete,  // TFJ
    WeakSetConstructor,  // TFJ
    WeakSetPrototypeHas,  // TFJ
    WeakSetPrototypeAdd,  // TFJ
    WeakSetPrototypeDelete,  // TFJ
    WeakCollectionDelete,  // TFS
    WeakCollectionSet,  // TFS
    SharedSpaceJSObjectHasInstance,  // CPP
    SharedStructTypeConstructor,  // CPP
    SharedStructTypeIsSharedStruct,  // CPP
    SharedStructConstructor,  // CPP
    SharedArrayConstructor,  // CPP
    SharedArrayIsSharedArray,  // CPP
    AtomicsMutexConstructor,  // CPP
    AtomicsMutexIsMutex,  // CPP
    AtomicsMutexLock,  // CPP
    AtomicsMutexLockWithTimeout,  // CPP
    AtomicsMutexTryLock,  // CPP
    AtomicsConditionConstructor,  // CPP
    AtomicsConditionIsCondition,  // CPP
    AtomicsConditionWait,  // CPP
    AtomicsConditionNotify,  // CPP
    AsyncGeneratorResolve,  // TFS
    AsyncGeneratorReject,  // TFS
    AsyncGeneratorYieldWithAwait,  // TFS
    AsyncGeneratorReturn,  // TFS
    AsyncGeneratorResumeNext,  // TFS
    AsyncGeneratorFunctionConstructor,  // CPP
    AsyncGeneratorPrototypeNext,  // TFJ
    AsyncGeneratorPrototypeReturn,  // TFJ
    AsyncGeneratorPrototypeThrow,  // TFJ
    AsyncGeneratorAwait,  // TFS
    AsyncGeneratorAwaitResolveClosure,  // TFJ
    AsyncGeneratorAwaitRejectClosure,  // TFJ
    AsyncGeneratorYieldWithAwaitResolveClosure,  // TFJ
    AsyncGeneratorReturnClosedResolveClosure,  // TFJ
    AsyncGeneratorReturnClosedRejectClosure,  // TFJ
    AsyncGeneratorReturnResolveClosure,  // TFJ
    AsyncFromSyncIteratorPrototypeNext,  // TFJ
    AsyncFromSyncIteratorPrototypeThrow,  // TFJ
    AsyncFromSyncIteratorPrototypeReturn,  // TFJ
    AsyncFromSyncIteratorCloseSyncAndRethrow,  // TFJ
    AsyncIteratorValueUnwrap,  // TFJ
    CEntry_Return1_ArgvInRegister_NoBuiltinExit,  // ASM
    CEntry_Return1_ArgvOnStack_BuiltinExit,  // ASM
    CEntry_Return1_ArgvOnStack_NoBuiltinExit,  // ASM
    CEntry_Return2_ArgvInRegister_NoBuiltinExit,  // ASM
    CEntry_Return2_ArgvOnStack_NoBuiltinExit,  // ASM
    WasmCEntry,  // ASM
    DirectCEntry,  // ASM
    StringAdd_NoMapCheck,  // TFS
    SubString,  // TFS
    DoubleToI,  // ASM
    GetProperty,  // TFC
    GetPropertyWithReceiver,  // TFS
    SetProperty,  // TFS
    CreateDataProperty,  // TFS
    GetOwnPropertyDescriptor,  // TFS
    FindNonDefaultConstructorOrConstruct,  // TFC
    OrdinaryGetOwnPropertyDescriptor,  // TFS
    CheckMaglevType,  // TFS
    IsTraceCategoryEnabled,  // CPP
    Trace,  // CPP
    FinalizationRegistryUnregister,  // CPP
    AsyncModuleEvaluate,  // TFJ
    CallAsyncModuleFulfilled,  // CPP
    CallAsyncModuleRejected,  // CPP
    AggregateErrorConstructor,  // TFJ
    ArrayPrototypeAt,  // TFJ
    ArrayPrototypeConcat,  // TFJ
    ArrayPrototypeCopyWithin,  // TFJ
    ArrayEveryLoopEagerDeoptContinuation,  // TFJ
    ArrayEveryLoopLazyDeoptContinuation,  // TFJ
    ArrayEveryLoopContinuation,  // TFS
    ArrayEvery,  // TFJ
    ArrayFilterLoopEagerDeoptContinuation,  // TFJ
    ArrayFilterLoopLazyDeoptContinuation,  // TFJ
    ArrayFilterLoopContinuation,  // TFS
    ArrayFilter,  // TFJ
    ArrayFindLoopEagerDeoptContinuation,  // TFJ
    ArrayFindLoopLazyDeoptContinuation,  // TFJ
    ArrayFindLoopAfterCallbackLazyDeoptContinuation,  // TFJ
    ArrayFindLoopContinuation,  // TFS
    ArrayPrototypeFind,  // TFJ
    ArrayFindIndexLoopEagerDeoptContinuation,  // TFJ
    ArrayFindIndexLoopLazyDeoptContinuation,  // TFJ
    ArrayFindIndexLoopAfterCallbackLazyDeoptContinuation,  // TFJ
    ArrayFindIndexLoopContinuation,  // TFS
    ArrayPrototypeFindIndex,  // TFJ
    ArrayFindLastLoopContinuation,  // TFS
    ArrayPrototypeFindLast,  // TFJ
    ArrayFindLastIndexLoopContinuation,  // TFS
    ArrayPrototypeFindLastIndex,  // TFJ
    FlattenIntoArrayWithoutMapFn,  // TFS
    FlattenIntoArrayWithMapFn,  // TFS
    ArrayPrototypeFlat,  // TFJ
    ArrayPrototypeFlatMap,  // TFJ
    ArrayForEachLoopEagerDeoptContinuation,  // TFJ
    ArrayForEachLoopLazyDeoptContinuation,  // TFJ
    ArrayForEachLoopContinuation,  // TFS
    ArrayForEach,  // TFJ
    ArrayFromAsyncIterableOnFulfilled,  // TFJ
    ArrayFromAsyncIterableOnRejected,  // TFJ
    ArrayFromAsyncArrayLikeOnFulfilled,  // TFJ
    ArrayFromAsyncArrayLikeOnRejected,  // TFJ
    ArrayFromAsync,  // TFJ
    ArrayFrom,  // TFJ
    ArrayIsArray,  // TFJ
    ConvertToLocaleString,  // TFS
    JoinStackPush,  // TFS
    JoinStackPop,  // TFS
    ArrayPrototypeJoin,  // TFJ
    ArrayPrototypeJoinImpl,  // TFS
    ArrayPrototypeToLocaleString,  // TFJ
    ArrayPrototypeToString,  // TFJ
    TypedArrayPrototypeJoin,  // TFJ
    TypedArrayPrototypeToLocaleString,  // TFJ
    ArrayPrototypeLastIndexOf,  // TFJ
    ArrayMapPreLoopLazyDeoptContinuation,  // TFJ
    ArrayMapLoopEagerDeoptContinuation,  // TFJ
    ArrayMapLoopLazyDeoptContinuation,  // TFJ
    ArrayMapLoopContinuation,  // TFS
    ArrayMap,  // TFJ
    ArrayOf,  // TFJ
    ArrayReduceRightPreLoopEagerDeoptContinuation,  // TFJ
    ArrayReduceRightLoopEagerDeoptContinuation,  // TFJ
    ArrayReduceRightLoopLazyDeoptContinuation,  // TFJ
    ArrayReduceRightLoopContinuation,  // TFS
    ArrayReduceRight,  // TFJ
    ArrayReducePreLoopEagerDeoptContinuation,  // TFJ
    ArrayReduceLoopEagerDeoptContinuation,  // TFJ
    ArrayReduceLoopLazyDeoptContinuation,  // TFJ
    ArrayReduceLoopContinuation,  // TFS
    ArrayReduce,  // TFJ
    ArrayPrototypeReverse,  // TFJ
    ArrayPrototypeShift,  // TFJ
    ArrayPrototypeSlice,  // TFJ
    ArraySomeLoopEagerDeoptContinuation,  // TFJ
    ArraySomeLoopLazyDeoptContinuation,  // TFJ
    ArraySomeLoopContinuation,  // TFS
    ArraySome,  // TFJ
    ArrayPrototypeSplice,  // TFJ
    GenericArrayToReversed,  // TFS
    ArrayPrototypeToReversed,  // TFJ
    ArrayPowerSortIntoCopy,  // TFS
    ArrayPrototypeToSorted,  // TFJ
    ArrayPrototypeToSpliced,  // TFJ
    ArrayPrototypeUnshift,  // TFJ
    GenericArrayWith,  // TFS
    ArrayPrototypeWith,  // TFJ
    ArraySortContinueFromSnapshotEagerDeoptContinuation,  // TFJ
    ArraySortContinueFromSnapshotLazyDeoptContinuation,  // TFJ
    ArrayBufferPrototypeGetByteLength,  // TFJ
    ArrayBufferPrototypeGetMaxByteLength,  // TFJ
    ArrayBufferPrototypeGetResizable,  // TFJ
    ArrayBufferPrototypeGetDetached,  // TFJ
    ArrayBufferPrototypeGetImmutable,  // TFJ
    SharedArrayBufferPrototypeGetMaxByteLength,  // TFJ
    SharedArrayBufferPrototypeGetGrowable,  // TFJ
    ArrayBufferIsView,  // TFJ
    ToInteger,  // TFS
    FastCreateDataProperty,  // TFS
    BooleanConstructor,  // TFJ
    BooleanPrototypeToString,  // TFJ
    BooleanPrototypeValueOf,  // TFJ
    BigIntAddNoThrow,  // TFS
    BigIntAdd,  // TFS
    BigIntSubtractNoThrow,  // TFS
    BigIntSubtract,  // TFS
    BigIntMultiplyNoThrow,  // TFS
    BigIntMultiply,  // TFS
    BigIntDivideNoThrow,  // TFS
    BigIntDivide,  // TFS
    BigIntModulusNoThrow,  // TFS
    BigIntModulus,  // TFS
    BigIntBitwiseAndNoThrow,  // TFS
    BigIntBitwiseAnd,  // TFS
    BigIntBitwiseOrNoThrow,  // TFS
    BigIntBitwiseOr,  // TFS
    BigIntBitwiseXorNoThrow,  // TFS
    BigIntBitwiseXor,  // TFS
    BigIntShiftLeftNoThrow,  // TFS
    BigIntShiftLeft,  // TFS
    BigIntShiftRightNoThrow,  // TFS
    BigIntShiftRight,  // TFS
    BigIntEqual,  // TFS
    BigIntLessThan,  // TFS
    BigIntGreaterThan,  // TFS
    BigIntLessThanOrEqual,  // TFS
    BigIntGreaterThanOrEqual,  // TFS
    BigIntUnaryMinus,  // TFS
    ToString,  // TFS
    ToStringConvertSymbol,  // TFS
    StringPrototypeToString,  // TFJ
    StringPrototypeValueOf,  // TFJ
    StringToList,  // TFS
    StringPrototypeCharAt,  // TFJ
    StringPrototypeCharCodeAt,  // TFJ
    StringPrototypeCodePointAt,  // TFJ
    StringPrototypeConcat,  // TFJ
    StringConstructor,  // TFJ
    StringCreateLazyDeoptContinuation,  // TFJ
    StringAddConvertLeft,  // TFS
    StringAddConvertRight,  // TFS
    StringCharAt,  // TFS
    FastNewClosureBaseline,  // TFS
    FastNewFunctionContextEval,  // TFS
    FastNewFunctionContextFunction,  // TFS
    FastNewFunctionContextFunctionWithCells,  // TFS
    CreateRegExpLiteral,  // TFS
    CreateShallowArrayLiteral,  // TFS
    CreateEmptyArrayLiteral,  // TFS
    CreateShallowObjectLiteral,  // TFS
    ObjectConstructor,  // TFJ
    CreateEmptyLiteralObject,  // TFS
    NumberConstructor,  // TFJ
    GenericLazyDeoptContinuation,  // TFJ
    StringToNumber,  // TFS
    NonNumberToNumber,  // TFS
    NonNumberToNumeric,  // TFS
    ToNumeric,  // TFS
    NumberToString,  // TFS
    SmiToString,  // TFS
    Int32ToString,  // TFS
    Float64ToString,  // TFS
    ToBoolean,  // TFS
    ToBooleanForBaselineJump,  // TFS
    ToLength,  // TFS
    ToName,  // TFS
    ToObject,  // TFS
    NonPrimitiveToPrimitive_Default,  // TFS
    NonPrimitiveToPrimitive_Number,  // TFS
    NonPrimitiveToPrimitive_String,  // TFS
    OrdinaryToPrimitive_Number,  // TFS
    OrdinaryToPrimitive_Number_Inline,  // TFS
    OrdinaryToPrimitive_String,  // TFS
    FastConsoleAssert,  // TFJ
    DataViewPrototypeGetBuffer,  // TFJ
    DataViewPrototypeGetByteLength,  // TFJ
    DataViewPrototypeGetByteOffset,  // TFJ
    DataViewPrototypeGetUint8,  // TFJ
    DataViewPrototypeGetInt8,  // TFJ
    DataViewPrototypeGetUint16,  // TFJ
    DataViewPrototypeGetInt16,  // TFJ
    DataViewPrototypeGetUint32,  // TFJ
    DataViewPrototypeGetInt32,  // TFJ
    DataViewPrototypeGetFloat16,  // TFJ
    DataViewPrototypeGetFloat32,  // TFJ
    DataViewPrototypeGetFloat64,  // TFJ
    DataViewPrototypeGetBigUint64,  // TFJ
    DataViewPrototypeGetBigInt64,  // TFJ
    DataViewPrototypeSetUint8,  // TFJ
    DataViewPrototypeSetInt8,  // TFJ
    DataViewPrototypeSetUint16,  // TFJ
    DataViewPrototypeSetInt16,  // TFJ
    DataViewPrototypeSetUint32,  // TFJ
    DataViewPrototypeSetInt32,  // TFJ
    DataViewPrototypeSetFloat16,  // TFJ
    DataViewPrototypeSetFloat32,  // TFJ
    DataViewPrototypeSetFloat64,  // TFJ
    DataViewPrototypeSetBigUint64,  // TFJ
    DataViewPrototypeSetBigInt64,  // TFJ
    FinalizationRegistryConstructor,  // TFJ
    FinalizationRegistryRegister,  // TFJ
    FunctionPrototypeHasInstance,  // TFJ
    FastFunctionPrototypeBind,  // TFJ
    GeneratorPrototypeNextLazyDeoptContinuation,  // TFJ
    IncBlockCounter,  // TFS
    GetTemplateObject,  // TFS
    ForInNext,  // TFS
    GetImportMetaObjectBaseline,  // TFS
    GetIteratorWithFeedback,  // TFS
    GetIteratorBaseline,  // TFS
    CreateAsyncFromSyncIteratorBaseline,  // TFS
    ForOfNext,  // TFS
    ForOfNextBaseline,  // TFS
    CallIteratorWithFeedback,  // TFS
    IteratorClose,  // TFS
    IteratorConstructor,  // TFJ
    IteratorPrototypeGetToStringTag,  // TFJ
    IteratorPrototypeSetToStringTag,  // TFJ
    IteratorPrototypeGetConstructor,  // TFJ
    IteratorPrototypeSetConstructor,  // TFJ
    IteratorPrototypeDispose,  // TFJ
    AsyncIteratorPrototypeAsyncDisposeResolveClosure,  // TFJ
    AsyncIteratorPrototypeAsyncDispose,  // TFJ
    ArrayDestructure,  // TFS
    ArrayDestructureLazyDeoptContinuation,  // TFS
    IteratorFrom,  // TFJ
    WrapForValidIteratorPrototypeNext,  // TFJ
    WrapForValidIteratorPrototypeReturn,  // TFJ
    IteratorHelperPrototypeNext,  // TFJ
    IteratorHelperPrototypeReturn,  // TFJ
    IteratorPrototypeMap,  // TFJ
    IteratorMapHelperNext,  // TFS
    IteratorPrototypeFilter,  // TFJ
    IteratorFilterHelperNext,  // TFS
    IteratorPrototypeTake,  // TFJ
    IteratorTakeHelperNext,  // TFS
    IteratorPrototypeDrop,  // TFJ
    IteratorDropHelperNext,  // TFS
    IteratorPrototypeFlatMap,  // TFJ
    IteratorFlatMapHelperNext,  // TFS
    IteratorPrototypeReduce,  // TFJ
    IteratorPrototypeToArray,  // TFJ
    IteratorPrototypeForEach,  // TFJ
    IteratorPrototypeSome,  // TFJ
    IteratorPrototypeEvery,  // TFJ
    IteratorPrototypeFind,  // TFJ
    IteratorConcat,  // TFJ
    IteratorConcatHelperNext,  // TFS
    IteratorPrototypeJoin,  // TFJ
    IteratorZip,  // TFJ
    IteratorZipHelperNext,  // TFS
    IteratorZipKeyed,  // TFJ
    IteratorZipKeyedHelperNext,  // TFS
    IteratorPrototypeIncludes,  // TFJ
    MapGroupBy,  // TFJ
    MathAbs,  // TFJ
    MathCeil,  // TFJ
    MathFloor,  // TFJ
    MathRound,  // TFJ
    MathTrunc,  // TFJ
    MathPow,  // TFJ
    MathMax,  // TFJ
    MathMin,  // TFJ
    MathAcos,  // TFJ
    MathAcosh,  // TFJ
    MathAsin,  // TFJ
    MathAsinh,  // TFJ
    MathAtan,  // TFJ
    MathAtan2,  // TFJ
    MathAtanh,  // TFJ
    MathCbrt,  // TFJ
    MathClz32,  // TFJ
    MathCos,  // TFJ
    MathCosh,  // TFJ
    MathExp,  // TFJ
    MathExpm1,  // TFJ
    MathFround,  // TFJ
    MathF16round,  // TFJ
    MathImul,  // TFJ
    MathLog,  // TFJ
    MathLog1p,  // TFJ
    MathLog10,  // TFJ
    MathLog2,  // TFJ
    MathSin,  // TFJ
    MathSign,  // TFJ
    MathSinh,  // TFJ
    MathSqrt,  // TFJ
    MathTan,  // TFJ
    MathTanh,  // TFJ
    MathHypot,  // TFJ
    MathRandom,  // TFJ
    NumberPrototypeToString,  // TFJ
    NumberIsFinite,  // TFJ
    NumberIsInteger,  // TFJ
    NumberIsNaN,  // TFJ
    NumberIsSafeInteger,  // TFJ
    NumberPrototypeValueOf,  // TFJ
    NumberParseFloat,  // TFJ
    ParseInt,  // TFS
    NumberParseInt,  // TFJ
    Add,  // TFS
    Subtract,  // TFS
    Multiply,  // TFS
    Divide,  // TFS
    Modulus,  // TFS
    Exponentiate,  // TFS
    Negate,  // TFS
    BitwiseNot,  // TFS
    Decrement,  // TFS
    Increment,  // TFS
    ShiftLeft,  // TFS
    ShiftRight,  // TFS
    ShiftRightLogical,  // TFS
    BitwiseAnd,  // TFS
    BitwiseOr,  // TFS
    BitwiseXor,  // TFS
    LessThan,  // TFS
    LessThanOrEqual,  // TFS
    GreaterThan,  // TFS
    GreaterThanOrEqual,  // TFS
    Equal,  // TFS
    StrictEqual,  // TFS
    ObjectFromEntries,  // TFJ
    GroupByGeneric,  // TFS
    ObjectGroupBy,  // TFJ
    CreateObjectWithoutProperties,  // TFS
    ObjectIsExtensible,  // TFJ
    ObjectPreventExtensions,  // TFJ
    ObjectGetPrototypeOf,  // TFJ
    ObjectSetPrototypeOf,  // TFJ
    ObjectPrototypeToString,  // TFJ
    ObjectPrototypeValueOf,  // TFJ
    ObjectPrototypeToLocaleString,  // TFJ
    FulfillPromise,  // TFS
    RejectPromise,  // TFS
    NewPromiseCapability,  // TFS
    PromiseCapabilityDefaultReject,  // TFJ
    PromiseCapabilityDefaultResolve,  // TFJ
    PerformPromiseThenFunction,  // TFJ
    PerformPromiseThen,  // TFS
    PromiseReject,  // TFJ
    PromiseGetCapabilitiesExecutor,  // TFJ
    PromiseConstructorLazyDeoptContinuation,  // TFJ
    PromiseAll,  // TFJ
    PromiseAllSettled,  // TFJ
    PromiseAllResolveElementClosure,  // TFJ
    PromiseAllSettledResolveElementClosure,  // TFJ
    PromiseAllSettledRejectElementClosure,  // TFJ
    PromiseAnyRejectElementClosure,  // TFJ
    PromiseAny,  // TFJ
    PromiseConstructor,  // TFJ
    PromisePrototypeCatch,  // TFJ
    PromiseValueThunkFinally,  // TFJ
    PromiseThrowerFinally,  // TFJ
    PromiseCatchFinally,  // TFJ
    PromiseThenFinally,  // TFJ
    PromisePrototypeFinally,  // TFJ
    PromiseResolveThenableJob,  // TFS
    GetContinuationPreservedEmbedderData,  // TFJ
    SetContinuationPreservedEmbedderData,  // TFJ
    AsyncAwaitNonThenableFastPath,  // TFS
    PromiseRace,  // TFJ
    PromiseFulfillReactionJob,  // TFS
    PromiseRejectReactionJob,  // TFS
    PromiseResolveTrampoline,  // TFJ
    PromiseResolve,  // TFS
    ResolvePromise,  // TFS
    PromisePrototypeThen,  // TFJ
    PromiseTry,  // TFJ
    PromiseWithResolvers,  // TFJ
    ProxyConstructor,  // TFJ
    ProxyDeleteProperty,  // TFS
    ProxyGetProperty,  // TFS
    ProxyGetPrototypeOf,  // TFS
    ProxyHasProperty,  // TFS
    ProxyIsExtensible,  // TFS
    ProxyPreventExtensions,  // TFS
    ProxyRevocable,  // TFJ
    ProxyRevoke,  // TFJ
    ProxySetProperty,  // TFS
    ProxySetPrototypeOf,  // TFS
    ReflectIsExtensible,  // TFJ
    ReflectPreventExtensions,  // TFJ
    ReflectGetPrototypeOf,  // TFJ
    ReflectSetPrototypeOf,  // TFJ
    ReflectGet,  // TFJ
    ReflectDeleteProperty,  // TFJ
    ReflectHas,  // TFJ
    ReflectGetOwnPropertyDescriptor,  // TFJ
    RegExpPrototypeExecSlow,  // TFS
    RegExpPrototypeExec,  // TFJ
    RegExpPrototypeMatchAll,  // TFJ
    RegExpStringIteratorPrototypeNext,  // TFJ
    RegExpMatchFast,  // TFS
    RegExpPrototypeMatch,  // TFJ
    RegExpReplace,  // TFS
    RegExpPrototypeReplace,  // TFJ
    RegExpSearchFast,  // TFS
    RegExpPrototypeSearch,  // TFJ
    RegExpPrototypeSourceGetter,  // TFJ
    RegExpSplit,  // TFS
    RegExpPrototypeSplit,  // TFJ
    RegExpPrototypeTest,  // TFJ
    RegExpPrototypeTestFast,  // TFS
    RegExpPrototypeGlobalGetter,  // TFJ
    RegExpPrototypeIgnoreCaseGetter,  // TFJ
    RegExpPrototypeMultilineGetter,  // TFJ
    RegExpPrototypeHasIndicesGetter,  // TFJ
    RegExpPrototypeLinearGetter,  // TFJ
    RegExpPrototypeDotAllGetter,  // TFJ
    RegExpPrototypeStickyGetter,  // TFJ
    RegExpPrototypeUnicodeGetter,  // TFJ
    RegExpPrototypeUnicodeSetsGetter,  // TFJ
    RegExpPrototypeFlagsGetter,  // TFJ
    SetPrototypeDifference,  // TFJ
    SetPrototypeIntersection,  // TFJ
    SetPrototypeIsDisjointFrom,  // TFJ
    SetPrototypeIsSubsetOf,  // TFJ
    SetPrototypeIsSupersetOf,  // TFJ
    SetPrototypeSymmetricDifference,  // TFJ
    SetPrototypeUnion,  // TFJ
    StringPrototypeAt,  // TFJ
    StringPrototypeEndsWith,  // TFJ
    CreateHTML,  // TFS
    StringPrototypeAnchor,  // TFJ
    StringPrototypeBig,  // TFJ
    StringPrototypeBlink,  // TFJ
    StringPrototypeBold,  // TFJ
    StringPrototypeFontcolor,  // TFJ
    StringPrototypeFontsize,  // TFJ
    StringPrototypeFixed,  // TFJ
    StringPrototypeItalics,  // TFJ
    StringPrototypeLink,  // TFJ
    StringPrototypeSmall,  // TFJ
    StringPrototypeStrike,  // TFJ
    StringPrototypeSub,  // TFJ
    StringPrototypeSup,  // TFJ
    StringPrototypeIncludes,  // TFJ
    StringPrototypeIndexOf,  // TFJ
    StringPrototypeIsWellFormed,  // TFJ
    StringPrototypeIterator,  // TFJ
    StringIteratorPrototypeNext,  // TFJ
    StringPrototypeMatch,  // TFJ
    StringPrototypeSearch,  // TFJ
    StringPrototypePadStart,  // TFJ
    StringPrototypePadEnd,  // TFJ
    StringRepeat,  // TFS
    StringPrototypeRepeat,  // TFJ
    StringPrototypeReplaceAll,  // TFJ
    StringPrototypeSlice,  // TFJ
    StringPrototypeStartsWith,  // TFJ
    StringPrototypeSubstr,  // TFJ
    StringPrototypeSubstring,  // TFJ
    StringPrototypeToWellFormed,  // TFJ
    StringPrototypeTrim,  // TFJ
    StringPrototypeTrimStart,  // TFJ
    StringPrototypeTrimEnd,  // TFJ
    SuppressedErrorConstructor,  // TFJ
    SymbolPrototypeDescriptionGetter,  // TFJ
    SymbolPrototypeToPrimitive,  // TFJ
    SymbolPrototypeToString,  // TFJ
    SymbolPrototypeValueOf,  // TFJ
    TypedArrayPrototypeAt,  // TFJ
    CreateTypedArray,  // TFS
    TypedArrayPrototypeEvery,  // TFJ
    TypedArrayPrototypeEntries,  // TFJ
    TypedArrayPrototypeFilter,  // TFJ
    TypedArrayPrototypeFind,  // TFJ
    TypedArrayPrototypeFindIndex,  // TFJ
    TypedArrayPrototypeFindLast,  // TFJ
    TypedArrayPrototypeFindLastIndex,  // TFJ
    TypedArrayPrototypeForEach,  // TFJ
    TypedArrayFrom,  // TFJ
    TypedArrayPrototypeKeys,  // TFJ
    TypedArrayOf,  // TFJ
    TypedArrayPrototypeReduce,  // TFJ
    TypedArrayPrototypeReduceRight,  // TFJ
    TypedArrayPrototypeSet,  // TFJ
    TypedArrayPrototypeSlice,  // TFJ
    TypedArrayPrototypeSome,  // TFJ
    TypedArrayMergeSort,  // TFS
    TypedArrayPrototypeSort,  // TFJ
    TypedArrayPrototypeSubArray,  // TFJ
    TypedArrayPrototypeToReversed,  // TFJ
    TypedArrayPrototypeToSorted,  // TFJ
    TypedArrayPrototypeValues,  // TFJ
    TypedArrayPrototypeWith,  // TFJ
    WeakRefConstructor,  // TFJ
    WeakRefDeref,  // TFJ
    NewSloppyArgumentsElements,  // TFS
    NewStrictArgumentsElements,  // TFS
    NewRestArgumentsElements,  // TFS
    FastNewSloppyArguments,  // TFS
    FastNewStrictArguments,  // TFS
    FastNewRestArguments,  // TFS
    LoadFromContextCell,  // TFS
    StoreCurrentContextElementBaseline,  // TFS
    StoreContextElementBaseline,  // TFS
    DetachContextCell,  // TFS
    StringSlowFlatten,  // TFS
    StringIndexOf,  // TFS
    TestTurbofanType,  // TFS
    CheckTurbofanType,  // TFS
    CheckTurboshaftWord32Type,  // TFS
    CheckTurboshaftWord64Type,  // TFS
    CheckTurboshaftFloat32Type,  // TFS
    CheckTurboshaftFloat64Type,  // TFS
    DebugPrintWord32,  // TFS
    DebugPrintWord64,  // TFS
    DebugPrintFloat32,  // TFS
    DebugPrintFloat64,  // TFS
    DebugPrintObject,  // TFS
    TestHelperPlus1,  // TFS
    TestHelperPlus2,  // TFS
    ReturnTwoValues,  // TFS
    ThrowAsBuiltin,  // TFS
    TestCallNever,  // TFS
    TestIncrementArraySpeciesModified,  // TFS
    SortCompareDefault,  // TFS
    SortCompareUserFn,  // TFS
    Copy,  // TFS
    MergeAt,  // TFS
    GallopLeft,  // TFS
    GallopRight,  // TFS
    ArrayPowerSort,  // TFS
    ArrayPrototypeSort,  // TFJ
    StringPrototypeLocaleCompare,  // CPP
    StringPrototypeNormalize,  // CPP
    StringPrototypeToLocaleLowerCase,  // CPP
    StringPrototypeToLocaleUpperCase,  // CPP
    StringPrototypeToLowerCase,  // CPP
    StringPrototypeToUpperCase,  // CPP
}

/// <summary>The kind of each builtin (CPP, TFJ, TFC, TFS, TFH, ASM), as in BUILTIN_LIST.</summary>
public enum BuiltinKind : byte { CPP, TFJ, TFC, TFS, TFH, ASM, BCH }

public static partial class BuiltinRegistry
{
    public const int kBuiltinCount = 1324;

    static readonly BuiltinKind[] s_kinds =
    [
        BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.ASM,
        BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.TFC, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.ASM, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.ASM,
        BuiltinKind.ASM, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM,
        BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.ASM, BuiltinKind.ASM,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.ASM, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.TFC,
        BuiltinKind.TFS, BuiltinKind.TFC, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFS, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM,
        BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM,
        BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.TFC,
        BuiltinKind.ASM, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM,
        BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.TFC, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFS, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFJ, BuiltinKind.ASM, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.ASM,
        BuiltinKind.TFC, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFC, BuiltinKind.TFS, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.ASM, BuiltinKind.CPP, BuiltinKind.ASM, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.CPP, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFH,
        BuiltinKind.TFH, BuiltinKind.TFH, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.CPP,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFS, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.CPP,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFC,
        BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFC, BuiltinKind.TFS, BuiltinKind.TFC, BuiltinKind.TFS, BuiltinKind.ASM, BuiltinKind.ASM,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFS, BuiltinKind.ASM,
        BuiltinKind.ASM, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.CPP, BuiltinKind.TFS, BuiltinKind.CPP,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM,
        BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.ASM, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.ASM, BuiltinKind.TFC, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFC, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS,
        BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS,
        BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFS,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ, BuiltinKind.TFJ,
        BuiltinKind.TFJ, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS,
        BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFS, BuiltinKind.TFJ, BuiltinKind.CPP, BuiltinKind.CPP,
        BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP, BuiltinKind.CPP,
    ];
}
