// <auto-generated>
// The chunk dispatch of the Is/Convert functions of src/strings/unicode.cc,
// converted mechanically by a script; do not edit by hand.
// </auto-generated>

namespace V8Sharp.Base.Unibrow;

static partial class UnicodeTables
{
    internal static bool Uppercase_Is(uint c)
    {
        switch (c >> 13)
        {
            case 0: return LookupPredicate(kUppercaseTable0, kUppercaseTable0Size, c);
            case 1: return LookupPredicate(kUppercaseTable1, kUppercaseTable1Size, c);
            case 5: return LookupPredicate(kUppercaseTable5, kUppercaseTable5Size, c);
            case 7: return LookupPredicate(kUppercaseTable7, kUppercaseTable7Size, c);
            default: return false;
        }
    }

    internal static bool Letter_Is(uint c)
    {
        switch (c >> 13)
        {
            case 0: return LookupPredicate(kLetterTable0, kLetterTable0Size, c);
            case 1: return LookupPredicate(kLetterTable1, kLetterTable1Size, c);
            case 2: return LookupPredicate(kLetterTable2, kLetterTable2Size, c);
            case 3: return LookupPredicate(kLetterTable3, kLetterTable3Size, c);
            case 4: return LookupPredicate(kLetterTable4, kLetterTable4Size, c);
            case 5: return LookupPredicate(kLetterTable5, kLetterTable5Size, c);
            case 6: return LookupPredicate(kLetterTable6, kLetterTable6Size, c);
            case 7: return LookupPredicate(kLetterTable7, kLetterTable7Size, c);
            default: return false;
        }
    }

    internal static bool ID_Start_Is(uint c)
    {
        switch (c >> 13)
        {
            case 0: return LookupPredicate(kID_StartTable0, kID_StartTable0Size, c);
            case 1: return LookupPredicate(kID_StartTable1, kID_StartTable1Size, c);
            case 2: return LookupPredicate(kID_StartTable2, kID_StartTable2Size, c);
            case 3: return LookupPredicate(kID_StartTable3, kID_StartTable3Size, c);
            case 4: return LookupPredicate(kID_StartTable4, kID_StartTable4Size, c);
            case 5: return LookupPredicate(kID_StartTable5, kID_StartTable5Size, c);
            case 6: return LookupPredicate(kID_StartTable6, kID_StartTable6Size, c);
            case 7: return LookupPredicate(kID_StartTable7, kID_StartTable7Size, c);
            default: return false;
        }
    }

    internal static bool ID_Continue_Is(uint c)
    {
        switch (c >> 13)
        {
            case 0: return LookupPredicate(kID_ContinueTable0, kID_ContinueTable0Size, c);
            case 1: return LookupPredicate(kID_ContinueTable1, kID_ContinueTable1Size, c);
            case 5: return LookupPredicate(kID_ContinueTable5, kID_ContinueTable5Size, c);
            case 7: return LookupPredicate(kID_ContinueTable7, kID_ContinueTable7Size, c);
            default: return false;
        }
    }

    internal static bool WhiteSpace_Is(uint c)
    {
        switch (c >> 13)
        {
            case 0: return LookupPredicate(kWhiteSpaceTable0, kWhiteSpaceTable0Size, c);
            case 1: return LookupPredicate(kWhiteSpaceTable1, kWhiteSpaceTable1Size, c);
            case 7: return LookupPredicate(kWhiteSpaceTable7, kWhiteSpaceTable7Size, c);
            default: return false;
        }
    }

    internal static int ToLowercase_Convert(uint c, uint n, Span<uint> result, ref bool allowCaching)
    {
        switch (c >> 13)
        {
            case 0: return LookupMapping(true, kToLowercaseTable0, kToLowercaseTable0Size, kToLowercaseMultiStrings0, kToLowercaseMultiStrings0Width, c, n, result, ref allowCaching);
            case 1: return LookupMapping(true, kToLowercaseTable1, kToLowercaseTable1Size, kToLowercaseMultiStrings1, kToLowercaseMultiStrings1Width, c, n, result, ref allowCaching);
            case 5: return LookupMapping(true, kToLowercaseTable5, kToLowercaseTable5Size, kToLowercaseMultiStrings5, kToLowercaseMultiStrings5Width, c, n, result, ref allowCaching);
            case 7: return LookupMapping(true, kToLowercaseTable7, kToLowercaseTable7Size, kToLowercaseMultiStrings7, kToLowercaseMultiStrings7Width, c, n, result, ref allowCaching);
            default: return 0;
        }
    }

    internal static int ToUppercase_Convert(uint c, uint n, Span<uint> result, ref bool allowCaching)
    {
        switch (c >> 13)
        {
            case 0: return LookupMapping(true, kToUppercaseTable0, kToUppercaseTable0Size, kToUppercaseMultiStrings0, kToUppercaseMultiStrings0Width, c, n, result, ref allowCaching);
            case 1: return LookupMapping(true, kToUppercaseTable1, kToUppercaseTable1Size, kToUppercaseMultiStrings1, kToUppercaseMultiStrings1Width, c, n, result, ref allowCaching);
            case 5: return LookupMapping(true, kToUppercaseTable5, kToUppercaseTable5Size, kToUppercaseMultiStrings5, kToUppercaseMultiStrings5Width, c, n, result, ref allowCaching);
            case 7: return LookupMapping(true, kToUppercaseTable7, kToUppercaseTable7Size, kToUppercaseMultiStrings7, kToUppercaseMultiStrings7Width, c, n, result, ref allowCaching);
            default: return 0;
        }
    }

    internal static int Ecma262Canonicalize_Convert(uint c, uint n, Span<uint> result, ref bool allowCaching)
    {
        switch (c >> 13)
        {
            case 0: return LookupMapping(true, kEcma262CanonicalizeTable0, kEcma262CanonicalizeTable0Size, kEcma262CanonicalizeMultiStrings0, kEcma262CanonicalizeMultiStrings0Width, c, n, result, ref allowCaching);
            case 1: return LookupMapping(true, kEcma262CanonicalizeTable1, kEcma262CanonicalizeTable1Size, kEcma262CanonicalizeMultiStrings1, kEcma262CanonicalizeMultiStrings1Width, c, n, result, ref allowCaching);
            case 5: return LookupMapping(true, kEcma262CanonicalizeTable5, kEcma262CanonicalizeTable5Size, kEcma262CanonicalizeMultiStrings5, kEcma262CanonicalizeMultiStrings5Width, c, n, result, ref allowCaching);
            case 7: return LookupMapping(true, kEcma262CanonicalizeTable7, kEcma262CanonicalizeTable7Size, kEcma262CanonicalizeMultiStrings7, kEcma262CanonicalizeMultiStrings7Width, c, n, result, ref allowCaching);
            default: return 0;
        }
    }

    internal static int Ecma262UnCanonicalize_Convert(uint c, uint n, Span<uint> result, ref bool allowCaching)
    {
        switch (c >> 13)
        {
            case 0: return LookupMapping(true, kEcma262UnCanonicalizeTable0, kEcma262UnCanonicalizeTable0Size, kEcma262UnCanonicalizeMultiStrings0, kEcma262UnCanonicalizeMultiStrings0Width, c, n, result, ref allowCaching);
            case 1: return LookupMapping(true, kEcma262UnCanonicalizeTable1, kEcma262UnCanonicalizeTable1Size, kEcma262UnCanonicalizeMultiStrings1, kEcma262UnCanonicalizeMultiStrings1Width, c, n, result, ref allowCaching);
            case 5: return LookupMapping(true, kEcma262UnCanonicalizeTable5, kEcma262UnCanonicalizeTable5Size, kEcma262UnCanonicalizeMultiStrings5, kEcma262UnCanonicalizeMultiStrings5Width, c, n, result, ref allowCaching);
            case 7: return LookupMapping(true, kEcma262UnCanonicalizeTable7, kEcma262UnCanonicalizeTable7Size, kEcma262UnCanonicalizeMultiStrings7, kEcma262UnCanonicalizeMultiStrings7Width, c, n, result, ref allowCaching);
            default: return 0;
        }
    }

    internal static int CanonicalizationRange_Convert(uint c, uint n, Span<uint> result, ref bool allowCaching)
    {
        switch (c >> 13)
        {
            case 0: return LookupMapping(false, kCanonicalizationRangeTable0, kCanonicalizationRangeTable0Size, kCanonicalizationRangeMultiStrings0, kCanonicalizationRangeMultiStrings0Width, c, n, result, ref allowCaching);
            case 1: return LookupMapping(false, kCanonicalizationRangeTable1, kCanonicalizationRangeTable1Size, kCanonicalizationRangeMultiStrings1, kCanonicalizationRangeMultiStrings1Width, c, n, result, ref allowCaching);
            case 7: return LookupMapping(false, kCanonicalizationRangeTable7, kCanonicalizationRangeTable7Size, kCanonicalizationRangeMultiStrings7, kCanonicalizationRangeMultiStrings7Width, c, n, result, ref allowCaching);
            default: return 0;
        }
    }

}
