// Port of src/regexp/regexp-bytecode-peephole.h and
// src/regexp/regexp-bytecode-peephole.cc.

using System.Buffers.Binary;

namespace V8Sharp.RegExp;

/// <summary>
/// Peephole optimization for regexp interpreter bytecode. Pre-defined
/// bytecode sequences occurring in the bytecode generated by the
/// RegExpBytecodeGenerator can be optimized into a single bytecode.
/// </summary>
public static class RegExpBytecodePeepholeOptimization
{
    /// <summary>
    /// Performs peephole optimization on the bytecode in the given src_writer
    /// and returns the optimized bytecode.
    /// </summary>
    public static byte[] OptimizeBytecode(RegExpBytecodeWriter srcWriter)
    {
        var dstWriter = new RegExpBytecodeWriter();
        bool didOptimize = RegExpBytecodePeephole.OptimizeBytecode(srcWriter, dstWriter);
        // The result is in dst_writer iff a peephole rule fired; otherwise the
        // unchanged input bytecode is still in src_writer.
        RegExpBytecodeWriter result = didOptimize ? dstWriter : srcWriter;
        return result.CopyBuffer();
    }
}

internal class BytecodeArgument(int offset, int length)
{
    public int Offset { get; } = offset;
    public int Length { get; } = length;
}

/// <summary>Describes a bytecode operand for use in a peephole sequence.</summary>
internal readonly record struct OpInfo(int Offset, BytecodeOperandType Type)
{
    public int Size => Bytecodes.Size(Type);

    public static OpInfo Get(Bytecode bc, string operand)
    {
        BytecodeInfo info = Bytecodes.Info(bc);
        return new OpInfo(info.Offset(operand), info.Type(operand));
    }
}

internal sealed class BytecodeArgumentMapping : BytecodeArgument
{
    public enum MappingType : byte { kDefault, kOffsetAfterSequence }

    readonly OpInfo _opInfo;

    public BytecodeArgumentMapping(int offset, int length, OpInfo opInfo) : base(offset, length)
    {
        Type = MappingType.kDefault;
        _opInfo = opInfo;
    }

    public BytecodeArgumentMapping(MappingType type, OpInfo opInfo) : base(-1, -1)
    {
        Debug.Assert(type != MappingType.kDefault);
        Type = type;
        _opInfo = opInfo;
    }

    public MappingType Type { get; }
    public int NewOffset => _opInfo.Offset;
    public BytecodeOperandType NewOperandType => _opInfo.Type;
    public int NewLength => _opInfo.Size;
}

internal sealed class BytecodeArgumentCheck : BytecodeArgument
{
    public enum CheckType { kCheckAddress = 0, kCheckValue }

    public CheckType Type { get; }
    public int CheckOffset { get; }
    public int CheckLength { get; }

    public BytecodeArgumentCheck(int offset, int length, int checkOffset) : base(offset, length)
    {
        Type = CheckType.kCheckAddress;
        CheckOffset = checkOffset;
    }

    public BytecodeArgumentCheck(int offset, int length, int checkOffset, int checkLength) : base(offset, length)
    {
        Type = CheckType.kCheckValue;
        CheckOffset = checkOffset;
        CheckLength = checkLength;
    }
}

/// <summary>Trie-Node for storing bytecode sequences we want to optimize.</summary>
internal sealed class BytecodeSequenceNode(Bytecode? bytecode)
{
    readonly Bytecode? _bytecode = bytecode;
    Bytecode? _bytecodeReplacement;
    int _indexInSequence;
    int _startOffset;
    BytecodeSequenceNode? _parent;
    readonly Dictionary<Bytecode, BytecodeSequenceNode> _children = [];
    readonly List<BytecodeArgumentMapping> _argumentMapping = [];
    readonly List<BytecodeArgumentCheck> _argumentCheck = [];
    readonly List<BytecodeArgument> _argumentIgnored = [];
    // True, iff the node has been fully created (including conditions). This
    // implies that it is invalid to add further conditions.
    bool _sealed;

    // Adds a new node as child of the current node if it isn't a child already.
    public BytecodeSequenceNode FollowedBy(Bytecode bytecode)
    {
        _sealed = true;
        if (!_children.TryGetValue(bytecode, out BytecodeSequenceNode? node))
        {
            node = new BytecodeSequenceNode(bytecode);
            // If node is not the first in the sequence, set offsets and parent.
            if (_bytecode.HasValue)
            {
                node._startOffset = _startOffset + Bytecodes.Size(_bytecode.Value);
                node._indexInSequence = _indexInSequence + 1;
                node._parent = this;
            }
            _children[bytecode] = node;
        }
        // If this fails, the node was previously created as part of another
        // sequence. We can reuse it, but only if there are no condition for both the
        // previous and the current use.
        Debug.Assert(node._argumentCheck.Count == 0);
        return node;
    }

    // Marks the end of a sequence and sets optimized bytecode to replace all
    // bytecodes of the sequence with.
    public BytecodeSequenceNode ReplaceWith(Bytecode bytecode)
    {
        Debug.Assert(!_bytecodeReplacement.HasValue);
        _bytecodeReplacement = bytecode;
        return this;
    }

    // Maps arguments of bytecodes in the sequence to the optimized bytecode.
    // Order of invocation determines order of arguments in the optimized
    // bytecode.
    public BytecodeSequenceNode MapArgument(OpInfo toOpInfo, int fromBytecodeSequenceIndex, OpInfo fromOpInfo)
    {
        int srcOffset = fromOpInfo.Offset;
        int srcSize = fromOpInfo.Size;

        Debug.Assert(fromBytecodeSequenceIndex <= _indexInSequence);
        Debug.Assert(BytecodeArgumentMappingCreatedInOrder(toOpInfo));

        BytecodeSequenceNode refNode = GetNodeByIndexInSequence(fromBytecodeSequenceIndex);
        Debug.Assert(srcOffset < Bytecodes.Size(refNode._bytecode!.Value));

        int offsetFromStartOfSequence = refNode._startOffset + srcOffset;
        _argumentMapping.Add(new BytecodeArgumentMapping(offsetFromStartOfSequence, srcSize, toOpInfo));
        return this;
    }

    // Emits the offset after the whole sequence.
    // This should be used for every sequence that doesn't end in an unconditional
    // jump. The offset isn't statically known, as bytecodes might be preserved
    // after the sequence if they were jump targets from bytecodes outside the
    // sequence. The emitted offset is after these potentially preserved
    // bytecodes.
    public BytecodeSequenceNode EmitOffsetAfterSequence(OpInfo opInfo)
    {
        Debug.Assert(BytecodeArgumentMappingCreatedInOrder(opInfo));
        _argumentMapping.Add(new BytecodeArgumentMapping(BytecodeArgumentMapping.MappingType.kOffsetAfterSequence, opInfo));
        return this;
    }

    // Verifies that we've created mappings in the order they are specified.
    bool BytecodeArgumentMappingCreatedInOrder(OpInfo opInfo)
    {
        Debug.Assert(IsSequence);
        if (_argumentMapping.Count == 0) return true;

        BytecodeArgumentMapping m = _argumentMapping[^1];
        int offsetAfterLast = m.NewOffset + m.NewLength;
        int dstSize = opInfo.Size;
        int alignment = Math.Min(dstSize, Bytecodes.kBytecodeAlignment);
        return (offsetAfterLast + alignment - 1) / alignment * alignment == opInfo.Offset;
    }

    // Adds a check to the sequence node making it only a valid sequence when the
    // argument of the current bytecode at the specified offset matches the offset
    // to check against.
    public BytecodeSequenceNode IfArgumentEqualsOffset(OpInfo opInfo, int checkByteOffset)
    {
        Debug.Assert(!_sealed);
        int size = opInfo.Size;
        int offset = opInfo.Offset;

        Debug.Assert(offset < Bytecodes.Size(_bytecode!.Value));
        Debug.Assert(size == 1 || size == 2 || size == 4);

        int offsetFromStartOfSequence = _startOffset + offset;

        _argumentCheck.Add(new BytecodeArgumentCheck(offsetFromStartOfSequence, size, checkByteOffset));
        return this;
    }

    // Adds a check to the sequence node making it only a valid sequence when the
    // argument of the current bytecode at the specified offset matches the
    // argument of another bytecode in the sequence.
    public BytecodeSequenceNode IfArgumentEqualsValueAtOffset(OpInfo thisOpInfo, int otherBytecodeIndexInSequence,
        OpInfo otherOpInfo)
    {
        Debug.Assert(!_sealed);
        int size1 = thisOpInfo.Size;
        int size2 = otherOpInfo.Size;

        Debug.Assert(thisOpInfo.Offset < Bytecodes.Size(_bytecode!.Value));
        Debug.Assert(otherBytecodeIndexInSequence <= _indexInSequence);
        Debug.Assert(size1 == size2);

        BytecodeSequenceNode refNode = GetNodeByIndexInSequence(otherBytecodeIndexInSequence);
        Debug.Assert(otherOpInfo.Offset < Bytecodes.Size(refNode._bytecode!.Value));

        int offsetFromStartOfSequence = _startOffset + thisOpInfo.Offset;
        int otherOffsetFromStartOfSequence = refNode._startOffset + otherOpInfo.Offset;

        _argumentCheck.Add(new BytecodeArgumentCheck(offsetFromStartOfSequence, size1,
            otherOffsetFromStartOfSequence, size2));
        return this;
    }

    // Marks an argument as unused.
    // All arguments that are not mapped explicitly have to be marked as unused.
    public BytecodeSequenceNode IgnoreArgument(int bytecodeIndexInSequence, OpInfo opInfo)
    {
        int size = opInfo.Size;
        int offset = opInfo.Offset;

        Debug.Assert(IsSequence);
        Debug.Assert(bytecodeIndexInSequence <= _indexInSequence);

        BytecodeSequenceNode refNode = GetNodeByIndexInSequence(bytecodeIndexInSequence);
        Debug.Assert(offset < Bytecodes.Size(refNode._bytecode!.Value));

        int offsetFromStartOfSequence = refNode._startOffset + offset;

        _argumentIgnored.Add(new BytecodeArgument(offsetFromStartOfSequence, size));
        return this;
    }

    // Checks if the current node is valid for the sequence. I.e. all conditions
    // set by IfArgumentEqualsOffset and IfArgumentEquals are fulfilled by this
    // node for the actual bytecode sequence.
    public bool CheckArguments(byte[] bytecode, int pc)
    {
        bool isValid = true;
        for (int k = 0; k < _argumentCheck.Count && isValid; k++)
        {
            BytecodeArgumentCheck check = _argumentCheck[k];
            int value = RegExpBytecodePeephole.GetArgumentValue(bytecode, pc + check.Offset, check.Length);
            if (check.Type == BytecodeArgumentCheck.CheckType.kCheckAddress)
            {
                isValid &= value == pc + check.CheckOffset;
            }
            else
            {
                int otherValue = RegExpBytecodePeephole.GetArgumentValue(bytecode, pc + check.CheckOffset,
                    check.CheckLength);
                isValid &= value == otherValue;
            }
        }
        return isValid;
    }

    // Returns whether this node marks the end of a valid sequence (i.e. can be
    // replaced with an optimized bytecode).
    public bool IsSequence => _bytecodeReplacement.HasValue;

    // Returns the length of the sequence in bytes.
    public int SequenceLength => _startOffset + Bytecodes.Size(_bytecode!.Value);

    // Returns the optimized bytecode for the node.
    public Bytecode OptimizedBytecode => _bytecodeReplacement!.Value;

    // Returns the child of the current node matching the given bytecode or
    // nullptr if no such child is found.
    public BytecodeSequenceNode? Find(Bytecode bytecode) =>
        _children.TryGetValue(bytecode, out BytecodeSequenceNode? node) ? node : null;

    public int ArgumentSize => _argumentMapping.Count;
    public BytecodeArgumentMapping ArgumentMapping(int index) => _argumentMapping[index];

    // Returns a node in the sequence specified by its index within the sequence.
    BytecodeSequenceNode GetNodeByIndexInSequence(int indexInSequence)
    {
        Debug.Assert(indexInSequence <= _indexInSequence);
        if (indexInSequence < _indexInSequence) return _parent!.GetNodeByIndexInSequence(indexInSequence);
        return this;
    }
}

internal sealed class BytecodePeepholeSequences
{
    readonly BytecodeSequenceNode _sequences = new(null);

    public BytecodePeepholeSequences() => DefineStandardSequences();

    public BytecodeSequenceNode Sequences => _sequences;

    BytecodeSequenceNode CreateSequence(Bytecode bytecode) => _sequences.FollowedBy(bytecode);

    static OpInfo I(Bytecode bc, string operand) => OpInfo.Get(bc, operand);

    void DefineStandardSequences()
    {
        // Commonly used sequences can be found by creating regexp bytecode traces
        // (--trace-regexp-bytecodes) and using v8/tools/regexp-sequences.py.
        {
            const Bytecode Target = Bytecode.kSkipUntilBitInTable;
            CreateSequence(Bytecode.kLoadCurrentCharacter)
                .FollowedBy(Bytecode.kCheckBitInTable)
                .FollowedBy(Bytecode.kAdvanceCpAndGoto)
                .IfArgumentEqualsOffset(I(Bytecode.kAdvanceCpAndGoto, "on_goto"), 0)
                .ReplaceWith(Target)
                .MapArgument(I(Target, "cp_offset"), 0, I(Bytecode.kLoadCurrentCharacter, "cp_offset"))
                .MapArgument(I(Target, "advance_by"), 2, I(Bytecode.kAdvanceCpAndGoto, "by"))
                .MapArgument(I(Target, "table"), 1, I(Bytecode.kCheckBitInTable, "table"))
                .MapArgument(I(Target, "bounds_check_offset"), 0, I(Bytecode.kLoadCurrentCharacter, "bounds_check_offset"))
                .MapArgument(I(Target, "on_match"), 1, I(Bytecode.kCheckBitInTable, "on_bit_set"))
                .MapArgument(I(Target, "on_no_match"), 0, I(Bytecode.kLoadCurrentCharacter, "on_failure"))
                .IgnoreArgument(2, I(Bytecode.kAdvanceCpAndGoto, "on_goto"));
        }

        {
            const Bytecode Target = Bytecode.kSkipUntilCharAnd;
            CreateSequence(Bytecode.kLoadCurrentCharacter)
                .FollowedBy(Bytecode.kCheckCharacterAfterAnd)
                .FollowedBy(Bytecode.kAdvanceCpAndGoto)
                .IfArgumentEqualsOffset(I(Bytecode.kAdvanceCpAndGoto, "on_goto"), 0)
                .ReplaceWith(Target)
                .MapArgument(I(Target, "cp_offset"), 0, I(Bytecode.kLoadCurrentCharacter, "cp_offset"))
                .MapArgument(I(Target, "advance_by"), 2, I(Bytecode.kAdvanceCpAndGoto, "by"))
                .MapArgument(I(Target, "character"), 1, I(Bytecode.kCheckCharacterAfterAnd, "character"))
                .MapArgument(I(Target, "mask"), 1, I(Bytecode.kCheckCharacterAfterAnd, "mask"))
                .MapArgument(I(Target, "bounds_check_offset"), 0, I(Bytecode.kLoadCurrentCharacter, "bounds_check_offset"))
                .MapArgument(I(Target, "on_match"), 1, I(Bytecode.kCheckCharacterAfterAnd, "on_equal"))
                .MapArgument(I(Target, "on_no_match"), 0, I(Bytecode.kLoadCurrentCharacter, "on_failure"))
                .IgnoreArgument(2, I(Bytecode.kAdvanceCpAndGoto, "on_goto"));
        }

        // TODO(pthier): It might make sense for short sequences like this one to only
        // optimize them if the resulting optimization is not longer than the current
        // one. This could be the case if there are jumps inside the sequence and we
        // have to replicate parts of the sequence. A method to mark such sequences
        // might be useful.
        {
            const Bytecode Target = Bytecode.kSkipUntilChar;
            CreateSequence(Bytecode.kLoadCurrentCharacter)
                .FollowedBy(Bytecode.kCheckCharacter)
                .FollowedBy(Bytecode.kAdvanceCpAndGoto)
                .IfArgumentEqualsOffset(I(Bytecode.kAdvanceCpAndGoto, "on_goto"), 0)
                .ReplaceWith(Target)
                .MapArgument(I(Target, "cp_offset"), 0, I(Bytecode.kLoadCurrentCharacter, "cp_offset"))
                .MapArgument(I(Target, "advance_by"), 2, I(Bytecode.kAdvanceCpAndGoto, "by"))
                .MapArgument(I(Target, "character"), 1, I(Bytecode.kCheckCharacter, "character"))
                .MapArgument(I(Target, "bounds_check_offset"), 0, I(Bytecode.kLoadCurrentCharacter, "bounds_check_offset"))
                .MapArgument(I(Target, "on_match"), 1, I(Bytecode.kCheckCharacter, "on_equal"))
                .MapArgument(I(Target, "on_no_match"), 0, I(Bytecode.kLoadCurrentCharacter, "on_failure"))
                .IgnoreArgument(2, I(Bytecode.kAdvanceCpAndGoto, "on_goto"));
        }

        {
            const Bytecode Target = Bytecode.kSkipUntilCharOrChar;
            CreateSequence(Bytecode.kLoadCurrentCharacter)
                .FollowedBy(Bytecode.kCheckCharacter)
                .FollowedBy(Bytecode.kCheckCharacter)
                .IfArgumentEqualsValueAtOffset(I(Bytecode.kCheckCharacter, "on_equal"), 1,
                    I(Bytecode.kCheckCharacter, "on_equal"))
                .FollowedBy(Bytecode.kAdvanceCpAndGoto)
                .IfArgumentEqualsOffset(I(Bytecode.kAdvanceCpAndGoto, "on_goto"), 0)
                .ReplaceWith(Target)
                .MapArgument(I(Target, "cp_offset"), 0, I(Bytecode.kLoadCurrentCharacter, "cp_offset"))
                .MapArgument(I(Target, "advance_by"), 3, I(Bytecode.kAdvanceCpAndGoto, "by"))
                .MapArgument(I(Target, "char1"), 1, I(Bytecode.kCheckCharacter, "character"))
                .MapArgument(I(Target, "char2"), 2, I(Bytecode.kCheckCharacter, "character"))
                .MapArgument(I(Target, "bounds_check_offset"), 0, I(Bytecode.kLoadCurrentCharacter, "bounds_check_offset"))
                .MapArgument(I(Target, "on_match"), 1, I(Bytecode.kCheckCharacter, "on_equal"))
                .MapArgument(I(Target, "on_no_match"), 0, I(Bytecode.kLoadCurrentCharacter, "on_failure"))
                .IgnoreArgument(2, I(Bytecode.kCheckCharacter, "on_equal"))
                .IgnoreArgument(3, I(Bytecode.kAdvanceCpAndGoto, "on_goto"));
        }

        {
            const Bytecode Target = Bytecode.kSkipUntilGtOrNotBitInTable;
            CreateSequence(Bytecode.kLoadCurrentCharacter)
                .FollowedBy(Bytecode.kCheckCharacterGT)
                // Sequence is only valid if the jump target of kCheckCharacterGT is the
                // first bytecode AFTER the whole sequence.
                .IfArgumentEqualsOffset(I(Bytecode.kCheckCharacterGT, "on_greater"), 60)
                .FollowedBy(Bytecode.kCheckBitInTable)
                // Sequence is only valid if the jump target of kCheckBitInTable is
                // the kAdvanceCpAndGoto bytecode at the end of the sequence.
                .IfArgumentEqualsOffset(I(Bytecode.kCheckBitInTable, "on_bit_set"), 52)
                .FollowedBy(Bytecode.kGoTo)
                // Sequence is only valid if the jump target of kGoTo is the same as the
                // jump target of kCheckCharacterGT (i.e. both jump to the first
                // bytecode AFTER the whole sequence.
                .IfArgumentEqualsValueAtOffset(I(Bytecode.kGoTo, "label"), 1, I(Bytecode.kCheckCharacterGT, "on_greater"))
                .FollowedBy(Bytecode.kAdvanceCpAndGoto)
                .IfArgumentEqualsOffset(I(Bytecode.kAdvanceCpAndGoto, "on_goto"), 0)
                .ReplaceWith(Target)
                .MapArgument(I(Target, "cp_offset"), 0, I(Bytecode.kLoadCurrentCharacter, "cp_offset"))
                .MapArgument(I(Target, "advance_by"), 4, I(Bytecode.kAdvanceCpAndGoto, "by"))
                .MapArgument(I(Target, "character"), 1, I(Bytecode.kCheckCharacterGT, "limit"))
                .MapArgument(I(Target, "table"), 2, I(Bytecode.kCheckBitInTable, "table"))
                .MapArgument(I(Target, "bounds_check_offset"), 0, I(Bytecode.kLoadCurrentCharacter, "bounds_check_offset"))
                .MapArgument(I(Target, "on_match"), 1, I(Bytecode.kCheckCharacterGT, "on_greater"))
                .MapArgument(I(Target, "on_no_match"), 0, I(Bytecode.kLoadCurrentCharacter, "on_failure"))
                .IgnoreArgument(2, I(Bytecode.kCheckBitInTable, "on_bit_set"))
                .IgnoreArgument(3, I(Bytecode.kGoTo, "label"))
                .IgnoreArgument(4, I(Bytecode.kAdvanceCpAndGoto, "on_goto"));
        }
        {
            const Bytecode Target = Bytecode.kSkipUntilOneOfMasked;
            CreateSequence(Bytecode.kLoad4CurrentChars)
                .FollowedBy(Bytecode.kAndCheck4Chars)
                // Jump target is the offset of the next AndCheck4Chars (right after
                // AdvanceCpAndGoto).
                .IfArgumentEqualsOffset(I(Bytecode.kAndCheck4Chars, "on_equal"), 0x24)
                .FollowedBy(Bytecode.kAdvanceCpAndGoto)
                .IfArgumentEqualsOffset(I(Bytecode.kAdvanceCpAndGoto, "on_goto"), 0)
                .FollowedBy(Bytecode.kAndCheck4Chars)
                .FollowedBy(Bytecode.kAndCheckNot4Chars)
                // Jump target is AdvanceCpAndGoto.
                .IfArgumentEqualsOffset(I(Bytecode.kAndCheckNot4Chars, "on_not_equal"), 0x1c)
                .ReplaceWith(Target)
                .MapArgument(I(Target, "cp_offset"), 0, I(Bytecode.kLoad4CurrentChars, "cp_offset"))
                .MapArgument(I(Target, "advance_by"), 2, I(Bytecode.kAdvanceCpAndGoto, "by"))
                .MapArgument(I(Target, "both_chars"), 1, I(Bytecode.kAndCheck4Chars, "characters"))
                .MapArgument(I(Target, "both_mask"), 1, I(Bytecode.kAndCheck4Chars, "mask"))
                .MapArgument(I(Target, "max_offset"), 0, I(Bytecode.kLoad4CurrentChars, "bounds_check_offset"))
                .MapArgument(I(Target, "chars1"), 3, I(Bytecode.kAndCheck4Chars, "characters"))
                .MapArgument(I(Target, "mask1"), 3, I(Bytecode.kAndCheck4Chars, "mask"))
                .MapArgument(I(Target, "chars2"), 4, I(Bytecode.kAndCheckNot4Chars, "characters"))
                .MapArgument(I(Target, "mask2"), 4, I(Bytecode.kAndCheckNot4Chars, "mask"))
                .MapArgument(I(Target, "on_match1"), 3, I(Bytecode.kAndCheck4Chars, "on_equal"))
                .EmitOffsetAfterSequence(I(Target, "on_match2"))
                .MapArgument(I(Target, "on_failure"), 0, I(Bytecode.kLoad4CurrentChars, "on_failure"))
                .IgnoreArgument(2, I(Bytecode.kAdvanceCpAndGoto, "on_goto"))
                .IgnoreArgument(1, I(Bytecode.kAndCheck4Chars, "on_equal"));
        }
        // The original bytecode sequence for kSkipUntilOneOfMasked3 is:
        //
        // sequence offset name
        // bc0   0  SkipUntilBitInTable
        // bc1  24  Load4CurrentChars
        // bc2  30  AndCheck4Chars
        // bc3  40  AdvanceCpAndGoto
        // bc4  48  Load4CurrentChars
        // bc5  54  AndCheck4Chars
        // bc6  64  AndCheck4Chars
        // bc7  74  AndCheckNot4Chars
        {
            const int kOffsetOfBc0SkipUntilBitInTable = 0x0;
            const int kOffsetOfBc1Load4CurrentChars = 0x24;
            const int kOffsetOfBc3AdvanceCpAndGoto = 0x40;
            const Bytecode Target = Bytecode.kSkipUntilOneOfMasked3;
            BytecodeSequenceNode s0 = CreateSequence(Bytecode.kSkipUntilBitInTable)
                .IfArgumentEqualsOffset(I(Bytecode.kSkipUntilBitInTable, "on_match"), kOffsetOfBc1Load4CurrentChars)
                .IfArgumentEqualsOffset(I(Bytecode.kSkipUntilBitInTable, "on_no_match"), kOffsetOfBc1Load4CurrentChars);

            Debug.Assert(s0.SequenceLength == kOffsetOfBc1Load4CurrentChars);
            const int kOffsetOfBc4Load4CurrentChars = 0x48;
            BytecodeSequenceNode s1 = s0.FollowedBy(Bytecode.kLoad4CurrentChars)
                .FollowedBy(Bytecode.kAndCheck4Chars)
                .IfArgumentEqualsOffset(I(Bytecode.kAndCheck4Chars, "on_equal"), kOffsetOfBc4Load4CurrentChars);

            Debug.Assert(s1.SequenceLength == kOffsetOfBc3AdvanceCpAndGoto);
            BytecodeSequenceNode s2 = s1.FollowedBy(Bytecode.kAdvanceCpAndGoto)
                .IfArgumentEqualsOffset(I(Bytecode.kAdvanceCpAndGoto, "on_goto"), kOffsetOfBc0SkipUntilBitInTable);

            Debug.Assert(s2.SequenceLength == kOffsetOfBc4Load4CurrentChars);
            BytecodeSequenceNode s3 = s2.FollowedBy(Bytecode.kLoad4CurrentChars)
                .IfArgumentEqualsOffset(I(Bytecode.kLoad4CurrentChars, "on_failure"), kOffsetOfBc3AdvanceCpAndGoto)
                .FollowedBy(Bytecode.kAndCheck4Chars)
                .FollowedBy(Bytecode.kAndCheck4Chars)
                .FollowedBy(Bytecode.kAndCheckNot4Chars)
                .IfArgumentEqualsOffset(I(Bytecode.kAndCheckNot4Chars, "on_not_equal"), kOffsetOfBc3AdvanceCpAndGoto);

            s3.ReplaceWith(Target)
                .MapArgument(I(Target, "bc0_cp_offset"), 0, I(Bytecode.kSkipUntilBitInTable, "cp_offset"))
                .MapArgument(I(Target, "bc0_advance_by"), 0, I(Bytecode.kSkipUntilBitInTable, "advance_by"))
                .MapArgument(I(Target, "bc0_table"), 0, I(Bytecode.kSkipUntilBitInTable, "table"))
                .IgnoreArgument(0, I(Bytecode.kSkipUntilBitInTable, "on_match"))
                .IgnoreArgument(0, I(Bytecode.kSkipUntilBitInTable, "on_no_match"))
                .IgnoreArgument(0, I(Bytecode.kSkipUntilBitInTable, "bounds_check_offset"))
                .MapArgument(I(Target, "bc1_bounds_check_offset"), 1, I(Bytecode.kLoad4CurrentChars, "bounds_check_offset"))
                .MapArgument(I(Target, "bc1_on_failure"), 1, I(Bytecode.kLoad4CurrentChars, "on_failure"))
                .MapArgument(I(Target, "bc1_cp_offset"), 1, I(Bytecode.kLoad4CurrentChars, "cp_offset"))
                .MapArgument(I(Target, "bc2_characters"), 2, I(Bytecode.kAndCheck4Chars, "characters"))
                .MapArgument(I(Target, "bc2_mask"), 2, I(Bytecode.kAndCheck4Chars, "mask"))
                .IgnoreArgument(2, I(Bytecode.kAndCheck4Chars, "on_equal"))
                .MapArgument(I(Target, "bc3_by"), 3, I(Bytecode.kAdvanceCpAndGoto, "by"))
                .IgnoreArgument(3, I(Bytecode.kAdvanceCpAndGoto, "on_goto"))
                .MapArgument(I(Target, "bc4_bounds_check_offset"), 4, I(Bytecode.kLoad4CurrentChars, "bounds_check_offset"))
                .MapArgument(I(Target, "bc4_cp_offset"), 4, I(Bytecode.kLoad4CurrentChars, "cp_offset"))
                .IgnoreArgument(4, I(Bytecode.kLoad4CurrentChars, "on_failure"))
                .MapArgument(I(Target, "bc5_characters"), 5, I(Bytecode.kAndCheck4Chars, "characters"))
                .MapArgument(I(Target, "bc5_mask"), 5, I(Bytecode.kAndCheck4Chars, "mask"))
                .MapArgument(I(Target, "bc5_on_equal"), 5, I(Bytecode.kAndCheck4Chars, "on_equal"))
                .MapArgument(I(Target, "bc6_characters"), 6, I(Bytecode.kAndCheck4Chars, "characters"))
                .MapArgument(I(Target, "bc6_mask"), 6, I(Bytecode.kAndCheck4Chars, "mask"))
                .MapArgument(I(Target, "bc6_on_equal"), 6, I(Bytecode.kAndCheck4Chars, "on_equal"))
                .MapArgument(I(Target, "bc7_characters"), 7, I(Bytecode.kAndCheckNot4Chars, "characters"))
                .MapArgument(I(Target, "bc7_mask"), 7, I(Bytecode.kAndCheckNot4Chars, "mask"))
                .IgnoreArgument(7, I(Bytecode.kAndCheckNot4Chars, "on_not_equal"))
                .EmitOffsetAfterSequence(I(Target, "fallthrough_jump_target"));
        }
    }
}

internal sealed class RegExpBytecodePeephole
{
    static BytecodePeepholeSequences? s_standardSequences;
    static BytecodePeepholeSequences GetStandardSequences() => s_standardSequences ??= new BytecodePeepholeSequences();

    readonly RegExpBytecodeWriter _dstWriter;
    readonly RegExpBytecodeWriter _srcWriter;

    // Number of times a jump destination is used within the bytecode.
    // Key: Jump destination (offset in old bytecode).
    // Value: Number of times jump destination is used.
    readonly JumpEdgeMap _jumpUsageCounts = new();
    // Maps offsets in old bytecode to fixups of destinations (delta to new
    // bytecode).
    // Key: Offset in old bytecode from where the fixup is valid.
    // Value: Delta to map jump destinations from old bytecode to new bytecode in
    // bytes.
    readonly JumpEdgeMap _jumpDestinationFixups = new();

    // Points at the first pc in src_writer that has not yet been emitted. Used
    // for batch copying unchanged regions of the incoming bytecodes.
    int _nextSrcPcToEmit;

    RegExpBytecodePeephole(RegExpBytecodeWriter srcWriter, RegExpBytecodeWriter dstWriter)
    {
        _dstWriter = dstWriter;
        _srcWriter = srcWriter;
        // Prepare jump usage counts.
        JumpEdgeMap edges = _srcWriter.JumpEdges;
        for (int i = 0; i < edges.Count; i++)
        {
            int jumpDestination = edges.ValueAt(i);
            _jumpUsageCounts.Increment(jumpDestination, 1);
        }
        // Sentinel fixups at beginning of bytecode (position -1) so we don't have to
        // check for end of iterator inside the fixup loop.
        // In general fixups are deltas of original offsets of jump
        // sources/destinations (in the old bytecode) to find them in the new
        // bytecode. All jump targets are fixed after the new bytecode is fully
        // emitted in the internal buffer.
        _jumpDestinationFixups.Emplace(-1, 0);
        // Sentinel fixups at end of (old) bytecode so we don't have to check for
        // end of iterator inside the fixup loop.
        _jumpDestinationFixups.Emplace(_srcWriter.Length, 0);
    }

    internal static int GetArgumentValue(byte[] bytecode, int offset, int length) => length switch
    {
        1 => bytecode[offset],
        2 => BinaryPrimitives.ReadInt16LittleEndian(bytecode.AsSpan(offset)),
        4 => BinaryPrimitives.ReadInt32LittleEndian(bytecode.AsSpan(offset)),
        _ => throw new InvalidOperationException("UNREACHABLE"),
    };

    // Parses bytecode and fills the internal buffer with the potentially
    // optimized bytecode. Returns true when optimizations were performed, false
    // otherwise.
    public static bool OptimizeBytecode(RegExpBytecodeWriter srcWriter, RegExpBytecodeWriter dstWriter)
    {
        var p = new RegExpBytecodePeephole(srcWriter, dstWriter);

        byte[] bytecode = srcWriter.Buffer;
        int length = srcWriter.Length;

        int oldPc = 0;
        bool didOptimize = false;

        while (oldPc < length)
        {
            int replacedLen = p.TryOptimizeSequence(bytecode, length, oldPc);
            if (replacedLen > 0)
            {
                oldPc += replacedLen;
                didOptimize = true;
            }
            else
            {
                int bcLen = Bytecodes.Size(bytecode[oldPc]);
                oldPc += bcLen;
            }
        }

        if (didOptimize)
        {
            // If we optimized anything, we must flush the remaining unoptimized bytes.
            // If we didn't optimize anything, we leave the dst_writer empty and the
            // caller will continue using src_writer (effectively a no-op pass).
            if (oldPc > p._nextSrcPcToEmit)
            {
                dstWriter.EmitRawBytecodeStream(srcWriter, p._nextSrcPcToEmit, oldPc - p._nextSrcPcToEmit);
            }
            p.FixJumps();
        }

        return didOptimize;
    }

    // Checks for optimization candidates at pc and emits optimized bytecode to
    // the internal buffer. Returns the length of replaced bytecodes in bytes.
    int TryOptimizeSequence(byte[] bytecode, int bytecodeLength, int startPc)
    {
        BytecodeSequenceNode? seqNode = GetStandardSequences().Sequences;
        BytecodeSequenceNode? validSeqEnd = null;

        int currentPc = startPc;

        // Check for the longest valid sequence matching any of the pre-defined
        // sequences in the Trie data structure.
        while (currentPc < bytecodeLength)
        {
            seqNode = seqNode.Find(Bytecodes.FromByte(bytecode[currentPc]));
            if (seqNode is null) break;
            if (!seqNode.CheckArguments(bytecode, startPc)) break;

            if (seqNode.IsSequence) validSeqEnd = seqNode;
            currentPc += Bytecodes.Size(bytecode[currentPc]);
        }

        if (validSeqEnd is not null)
        {
            EmitOptimization(startPc, bytecode, validSeqEnd);
            return validSeqEnd.SequenceLength;
        }

        return 0;
    }

    // Emits optimized bytecode to the internal buffer. start_pc points to the
    // start of the sequence in bytecode and last_node is the last
    // BytecodeSequenceNode of the matching sequence found.
    void EmitOptimization(int startPc, byte[] bytecode, BytecodeSequenceNode lastNode)
    {
        // Flush any sequence of bytecodes which we haven't emitted yet.
        if (startPc > _nextSrcPcToEmit)
        {
            _dstWriter.EmitRawBytecodeStream(_srcWriter, _nextSrcPcToEmit, startPc - _nextSrcPcToEmit);
        }
        int sequenceLength = lastNode.SequenceLength;
        _nextSrcPcToEmit = startPc + sequenceLength;

        // Update usage counts for all jumps originating in the sequence we are about
        // to replace. Counts for the target locations are decremented here. Emitting
        // kJumpTarget below will again increment for newly emitted destinations.
        JumpEdgeMap srcEdges = _srcWriter.JumpEdges;
        for (int e = srcEdges.LowerBound(startPc); e < srcEdges.Count && srcEdges.KeyAt(e) < startPc + sequenceLength; e++)
        {
            int target = srcEdges.ValueAt(e);
            Debug.Assert(_jumpUsageCounts.ContainsKey(target));
            _jumpUsageCounts.Increment(target, -1);
        }

        int optimizedStartPc = Pc;
        // List of offsets in the optimized sequence that need to be patched to the
        // offset value right after the optimized sequence.
        var afterSequenceOffsets = new List<int>();

        Bytecode bc = lastNode.OptimizedBytecode;
        _dstWriter.EmitBytecode(bc);

        for (int argIdx = 0; argIdx < lastNode.ArgumentSize; argIdx++)
        {
            BytecodeArgumentMapping argMap = lastNode.ArgumentMapping(argIdx);
            if (argMap.Type == BytecodeArgumentMapping.MappingType.kDefault)
            {
                if (argMap.NewOperandType == BytecodeOperandType.kJumpTarget)
                {
                    int target = GetArgumentValue(bytecode, startPc + argMap.Offset, argMap.Length);
                    _jumpUsageCounts.Increment(target, 1);
                }
                EmitArgument(startPc, bytecode, argMap);
            }
            else
            {
                Debug.Assert(argMap.Type == BytecodeArgumentMapping.MappingType.kOffsetAfterSequence);
                afterSequenceOffsets.Add(optimizedStartPc + argMap.NewOffset);
                // Reserve space to overwrite later with the pc after this sequence.
                _dstWriter.EmitRaw(0, 4, argMap.NewOffset);
            }
        }

        // Final alignment.
        _dstWriter.Finalize(bc);
        Debug.Assert(Pc == optimizedStartPc + Bytecodes.Size(bc));

        int fixupLength = Bytecodes.Size(bc) - sequenceLength;

        // Check if there are any jumps inside the old sequence.
        // If so we have to keep the bytecodes that are jumped to around.
        int candidate = _jumpUsageCounts.UpperBound(startPc);
        // Jump destinations only jumped to from inside the sequence will be ignored.
        while (candidate < _jumpUsageCounts.Count && _jumpUsageCounts.ValueAt(candidate) == 0)
        {
            ++candidate;
        }

        int preserveFrom = startPc + sequenceLength;
        if (candidate < _jumpUsageCounts.Count && _jumpUsageCounts.KeyAt(candidate) < startPc + sequenceLength)
        {
            preserveFrom = _jumpUsageCounts.KeyAt(candidate);
            // Check if any jump in the sequence we are preserving has a jump
            // destination inside the optimized sequence before the current position we
            // want to preserve. If so we have to preserve all bytecodes starting at
            // this jump destination.
            for (int j = srcEdges.LowerBound(preserveFrom);
                 j < srcEdges.Count && srcEdges.KeyAt(j) /* jump source */ < startPc + sequenceLength; ++j)
            {
                int jumpDestination = srcEdges.ValueAt(j);
                if (jumpDestination > startPc && jumpDestination < preserveFrom)
                {
                    preserveFrom = jumpDestination;
                }
            }

            // We preserve everything to the end of the sequence. This is conservative
            // since it would be enough to preserve all bytecodes up to an unconditional
            // jump.
            int preserveLength = startPc + sequenceLength - preserveFrom;
            fixupLength += preserveLength;
            // All jump targets after the start of the optimized sequence need to be
            // fixed relative to the length of the optimized sequence including
            // bytecodes we preserved.
            AddJumpDestinationFixup(fixupLength, startPc + 1);
            // Jumps to the sequence we preserved need absolute fixup as they could
            // occur before or after the sequence.
            SetJumpDestinationFixup(Pc - preserveFrom, preserveFrom);
            _dstWriter.EmitRawBytecodeStream(_srcWriter, preserveFrom, preserveLength);
        }
        else
        {
            AddJumpDestinationFixup(fixupLength, startPc + 1);
        }

        foreach (int offset in afterSequenceOffsets)
        {
            Debug.Assert(_dstWriter.Buffer[offset] == 0);
            _dstWriter.OverwriteValue((uint)Pc, offset);
            // Register the offset in jump_edges_ so that subsequent peephole passes
            // adjust it when bytecodes shift.
            _dstWriter.JumpEdges.Emplace(offset, startPc + sequenceLength);
        }
    }

    // Adds a relative jump destination fixup at pos.
    // Jump destination fixups are used to find offsets in the new bytecode that
    // can be jumped to.
    void AddJumpDestinationFixup(int fixup, int pos)
    {
        int previous = _jumpDestinationFixups.LowerBound(pos);
        Debug.Assert(previous < _jumpDestinationFixups.Count);
        Debug.Assert(previous > 0);
        int previousFixupValue = _jumpDestinationFixups.ValueAt(previous - 1);
        _jumpDestinationFixups.Set(pos, previousFixupValue + fixup);
    }

    // Sets an absolute jump destination fixup at pos.
    void SetJumpDestinationFixup(int fixup, int pos)
    {
        int previous = _jumpDestinationFixups.LowerBound(pos);
        Debug.Assert(previous < _jumpDestinationFixups.Count);
        Debug.Assert(previous > 0);
        int previousFixupValue = _jumpDestinationFixups.ValueAt(previous - 1);
        _jumpDestinationFixups.Emplace(pos, fixup);
        _jumpDestinationFixups.Emplace(pos + 1, previousFixupValue);
    }

    // Updates all jump targets in the new bytecode.
    void FixJumps()
    {
        JumpEdgeMap edges = _dstWriter.JumpEdges;
        // PatchJump only overwrites values of existing keys, so iterating by index
        // is safe.
        for (int i = 0; i < edges.Count; i++)
        {
            int jumpSource = edges.KeyAt(i);
            int jumpDestination = edges.ValueAt(i);
            int fixedJumpDestination = jumpDestination +
                _jumpDestinationFixups.ValueAt(_jumpDestinationFixups.UpperBound(jumpDestination) - 1);
            Debug.Assert(fixedJumpDestination < Pc);
            Debug.Assert(Bytecodes.IsValidJumpTarget(_dstWriter.Buffer[fixedJumpDestination]));

            if (jumpDestination != fixedJumpDestination)
            {
                _dstWriter.PatchJump(fixedJumpDestination, jumpSource);
            }
        }
    }

    void EmitArgument(int startPc, byte[] bytecode, BytecodeArgumentMapping arg)
    {
        BytecodeOperandType type = arg.NewOperandType;
        if (type == BytecodeOperandType.kBitTable)
        {
            Debug.Assert(arg.Length == 16);
            byte[] table = bytecode.AsSpan(startPc + arg.Offset, 16).ToArray();
            _dstWriter.EmitOperand(type, table, arg.NewOffset);
            return;
        }
        Debug.Assert(arg.Length <= 4);
        int value = GetArgumentValue(bytecode, startPc + arg.Offset, arg.Length);
        // static_cast<CType>: narrow to the destination operand's C type.
        long typed = type switch
        {
            BytecodeOperandType.kInt16 or BytecodeOperandType.kOffset => (short)value,
            BytecodeOperandType.kUint32 or BytecodeOperandType.kJumpTarget => (uint)value,
            BytecodeOperandType.kChar or BytecodeOperandType.kRegister => (ushort)value,
            BytecodeOperandType.kStackCheckFlag or BytecodeOperandType.kStandardCharacterSet => (byte)value,
            _ => value,
        };
        if (type == BytecodeOperandType.kJumpTarget)
        {
            _dstWriter.EmitOperand(type, (int)(uint)typed, arg.NewOffset);
        }
        else if (type == BytecodeOperandType.kUint32)
        {
            _dstWriter.EmitOperand(type, (uint)typed, arg.NewOffset);
        }
        else
        {
            _dstWriter.EmitOperand(type, (int)typed, arg.NewOffset);
        }
    }

    int Pc => _dstWriter.Pc;
}
